/**
 * V3.5 Universal Copy-Token Layer
 * 
 * Entry-point-specific terminology that allows Work Requests and Service Runs
 * UI/notifications to render wording based on business vertical.
 * 
 * IMPORTANT: 
 * - Never use "contractor" in generic context - use "provider" instead
 * - Never use "book/booking" - use "reserve/reservation" only
 */

export type EntryPointType = 
  | 'lodging'
  | 'parking'
  | 'marina'
  | 'restaurant'
  | 'equipment'
  | 'service'
  | 'activity'
  | 'generic';

export type CopyContext = {
  entryPoint: EntryPointType;
  surfaceKind?: string;
  portalTone?: 'community' | 'company';
  actorRole?: 'requester' | 'provider' | 'operator';
};

/**
 * Required token keys that every entry point must define
 */
export const REQUIRED_TOKEN_KEYS = [
  'label.noun.provider',
  'label.noun.requester',
  'label.noun.request',
  'label.noun.run',
  'label.noun.community',
  'label.noun.company',
  'label.noun.reservation',
  'state.market.TARGETED.label',
  'state.market.OPEN.label',
  'state.market.INVITE_ONLY.label',
  'state.visibility.PRIVATE.label',
  'state.request.UNASSIGNED.label',
  'ui.market.locked_notice',
  'ui.publish.ask_requester.title',
  'ui.publish.ask_requester.body',
  'ui.publish.just_publish.notice',
  'ui.ai.suggestion.route_zones.title',
  'ui.ai.suggestion.route_zones.body',
  'msg.invite.sent.subject',
  'msg.invite.sent.body',
  'msg.request.accepted.subject',
  'msg.request.accepted.body',
  'msg.proposal.created.subject',
  'msg.proposal.created.body',
  'msg.request.declined.subject',
  'msg.request.declined.body',
  'msg.request.unassigned.subject',
  'msg.request.unassigned.body',
  'cta.proposal.review',
  'cta.proposal.accept',
  'cta.proposal.reject',
  'cta.proposal.propose_change',
  'cta.proposal.submit',
  'cta.request.open_to_bids',
  'cta.request.invite_another_provider',
  'cta.request.send',
  'cta.request.accept',
  'cta.request.decline',
  'cta.request.withdraw',
  'cta.request.cancel',
  'cta.request.modify',
  'cta.publish',
  'cta.run.withdraw',
  'cta.run.close_signups',
  'cta.run.express_interest',
  'cta.run.mark_complete',
  'cta.admin.reassign',
  'cta.admin.cancel',
  'cta.admin.force_status',
] as const;

export type CopyTokenKey = typeof REQUIRED_TOKEN_KEYS[number];

/**
 * Copy token inventory by entry point type
 */
export const ENTRY_POINT_COPY: Record<EntryPointType, Record<string, string>> = {
  generic: {
    'label.noun.provider': 'provider',
    'label.noun.requester': 'requester',
    'label.noun.request': 'request',
    'label.noun.run': 'service run',
    'label.noun.community': 'community',
    'label.noun.company': 'organization',
    'label.noun.reservation': 'reservation',
    'state.market.TARGETED.label': 'Targeted',
    'state.market.OPEN.label': 'Open',
    'state.market.INVITE_ONLY.label': 'Invite Only',
    'state.visibility.PRIVATE.label': 'Private',
    'state.request.UNASSIGNED.label': 'Unassigned',
    'ui.market.locked_notice': 'Provider selected — not open for responses',
    'ui.publish.ask_requester.title': 'Submit for approval',
    'ui.publish.ask_requester.body': 'Your proposal will be sent to the requester for review.',
    'ui.publish.just_publish.notice': 'This will be published immediately.',
    'ui.ai.suggestion.route_zones.title': 'Suggested zones',
    'ui.ai.suggestion.route_zones.body': 'Based on your service area, these zones may be relevant.',
    'msg.invite.sent.subject': 'You have been invited to respond',
    'msg.invite.sent.body': 'You have received an invitation to submit a proposal for {requestTitle}.',
    'msg.request.accepted.subject': 'Your proposal was accepted',
    'msg.request.accepted.body': 'Great news! Your proposal for {requestTitle} has been accepted.',
    'msg.proposal.created.subject': 'New proposal received',
    'msg.proposal.created.body': 'A provider has submitted a proposal for {requestTitle}.',
    'msg.request.declined.subject': 'Proposal declined',
    'msg.request.declined.body': 'The proposal for {requestTitle} was not accepted.',
    'msg.request.unassigned.subject': 'Request is now unassigned',
    'msg.request.unassigned.body': 'The request {requestTitle} is now open for new proposals.',
    'cta.proposal.review': 'Review Proposal',
    'cta.proposal.accept': 'Accept Proposal',
    'cta.proposal.reject': 'Decline Proposal',
    'cta.proposal.propose_change': 'Propose Change',
    'cta.proposal.submit': 'Submit Response',
    'cta.request.open_to_bids': 'Open for Responses',
    'cta.request.invite_another_provider': 'Invite Another Provider',
    'cta.request.send': 'Send Request',
    'cta.request.accept': 'Accept Request',
    'cta.request.decline': 'Decline Request',
    'cta.request.withdraw': 'Withdraw',
    'cta.request.cancel': 'Cancel Request',
    'cta.request.modify': 'Modify Request',
    'cta.publish': 'Publish',
    'cta.run.withdraw': 'Withdraw',
    'cta.run.close_signups': 'Close Signups',
    'cta.run.express_interest': 'Express Interest',
    'cta.run.mark_complete': 'Mark Complete',
    'cta.admin.reassign': 'Reassign',
    'cta.admin.cancel': 'Cancel',
    'cta.admin.force_status': 'Force Status',
    // V3.5 Message Action Block copy tokens
    'error.auth.unauthenticated': 'Please sign in to continue',
    'error.request.invalid': 'Invalid request',
    'error.action_block.not_participant': 'You are not a participant in this conversation',
    'error.action_block.missing': 'No action available for this message',
    'error.action_block.invalid': 'This action is not available',
    'error.action_block.expired': 'This action has expired',
    'error.action_block.already_resolved': 'This action has already been completed',
    'error.action_block.action_not_allowed': 'This action is not allowed',
    'error.action_block.marketmode_blocked': 'This action is not available at this time',
    'message.action_block.accepted': 'Accepted successfully',
    'message.action_block.declined': 'Declined',
    'message.action_block.answered': 'Response submitted',
    'message.action_block.acknowledged': 'Acknowledged',
    'message.action_block.countered': 'Counter proposal submitted',
    // V3.5 Provider Run Publish tokens
    'provider.run.publish.cta': 'Publish to Portals',
    'provider.run.publish.modal_title': 'Publish Service Run',
    'provider.run.publish.visibility_label': 'Visibility — Where this run appears',
    'provider.run.publish.visibility_helper': 'Select which community portals will display this run.',
    'provider.run.publish.competition_label': 'Competition — Who can respond',
    'provider.run.publish.market_mode_open': 'Open for responses',
    'provider.run.publish.market_mode_open_helper': 'Anyone can attach requests to this run. Does not commit you to any requests.',
    'provider.run.publish.market_mode_invite_only': 'By invitation only',
    'provider.run.publish.market_mode_invite_only_helper': 'Only invited requesters can attach. Does not commit you to any requests.',
    'provider.run.publish.confirm': 'Publish Run',
    'provider.run.publish.success': 'Run published successfully',
    'provider.run.publish.no_portals': 'No community portals available',
    'error.run.publish.invalid_market_mode': 'Invalid market mode. TARGETED is not valid for runs.',
    
    // V3.5 STEP 6: Provider Run Attachments tokens
    'provider.run.attachments.title': 'Attached Service Requests',
    'provider.run.attachments.held': 'Held',
    'provider.run.attachments.committed': 'Committed',
    'provider.run.attachments.add_cta': 'Add Requests',
    'provider.run.attachments.hold_cta': 'Hold',
    'provider.run.attachments.commit_cta': 'Commit',
    'provider.run.attachments.release_cta': 'Release',
    'provider.run.attachments.hold_success': 'Request held successfully',
    'provider.run.attachments.commit_success': 'Request committed successfully',
    'provider.run.attachments.release_success': 'Request released',
    'provider.run.attachments.empty': 'No requests attached to this run',
    'provider.run.attachments.add_modal_title': 'Add Requests to Run',
    'provider.run.attachments.no_requests': 'No available requests to attach',
    'error.request.invalid_state': 'Request cannot be modified in its current state',
    'error.attachment.not_holdable': 'This request cannot be held',
    'error.attachment.not_committable': 'This attachment cannot be committed',
    'error.commitment.release_not_allowed': 'Committed requests cannot be released',
    
    'provider.run.start_address.title': 'Start Location',
    'provider.run.start_address.not_set': 'Not set',
    'provider.run.start_address.edit': 'Edit',
    'provider.run.start_address.clear': 'Clear',
    'provider.run.start_address.helper_private': 'Start address is private and helps improve future suggestions.',
    'provider.run.start_address.helper_changeable': 'You can change this anytime.',
    'provider.run.start_address.helper_no_assignment': 'This does not affect who is assigned to the run.',
    'provider.start_address.modal_title': 'Select Start Address',
    'provider.start_address.select_label': 'Choose from saved addresses',
    'provider.start_address.add_new_label': 'Add new address',
    'provider.start_address.none_option': 'None (clear start address)',
    'provider.start_address.form.label': 'Address Name',
    'provider.start_address.form.label_placeholder': 'e.g., John\'s House, South Yard',
    'provider.start_address.form.address1': 'Street Address',
    'provider.start_address.form.city': 'City',
    'provider.start_address.form.region': 'Province/Region',
    'provider.start_address.form.postal': 'Postal Code',
    'provider.start_address.form.notes': 'Notes (optional)',
    'provider.start_address.form.notes_placeholder': 'e.g., Gate code: 1234',
    'provider.start_address.form.is_default': 'Set as default address',
    'provider.start_address.save': 'Save',
    'provider.start_address.cancel': 'Cancel',
    'provider.start_address.create_success': 'Address saved',
    'provider.start_address.update_success': 'Start address updated',
    'error.start_address.not_found': 'Address not found',
    'error.start_address.label_exists': 'An address with this name already exists',
    'error.start_address.archived': 'This address has been archived',
    
    // V3.5 STEP 7: Publish Suggestions tokens
    'provider.publish.suggestions.title': 'Suggested additional areas',
    'provider.publish.suggestions.distance_format': '~{distance} away',
    'provider.publish.suggestions.distance_unknown': 'Distance unknown',
    'provider.publish.suggestions.no_origin': 'Set a start address for distance estimates',
    'provider.publish.suggestions.no_origin_coords': 'Add coordinates to enable distance estimates',
    'provider.publish.suggestions.empty': 'No additional areas to suggest',
    'provider.publish.suggestions.in_portal': 'In: {portalName}',
    
    // V3.5 STEP 8: Start Address Coordinates tokens
    'provider.start_address.latitude_label': 'Latitude (optional)',
    'provider.start_address.longitude_label': 'Longitude (optional)',
    'provider.start_address.coords_helper': 'Optional: add coordinates to enable distance estimates.',
    'provider.start_address.coords_error': 'Enter both latitude and longitude (or leave both blank).',
    'provider.publish.preflight.set_address': 'Set start address',
    'provider.publish.preflight.add_coords': 'Add coordinates',
    
    // V3.5 STEP 11A: Provider Visibility Preview tokens
    'provider.publish.preview.title': 'Also visible in',
    'provider.publish.preview.direct_badge': 'Direct',
    'provider.publish.preview.rollup_badge': 'Via rollup',
    'provider.publish.preview.via_format': 'via {name}',
    'provider.publish.preview.loading': 'Calculating visibility...',
    'provider.publish.preview.empty': 'No additional visibility',
    'provider.publish.preview.error': 'Could not calculate visibility',
    'provider.publish.preview.cta': 'Preview reach',
    
    // V3.5 STEP 11B-FIX: Portal grouping and rule block tokens
    'provider.publish.rule.title': 'Visible to you ≠ Published by you',
    'provider.publish.rule.body': 'Visibility shows where this run may appear through the network. Publishing controls where the public can see it.',
    'provider.publish.portals.tenant_owned.title': 'Your portals',
    'provider.publish.portals.tenant_owned.help': 'Portals owned by your tenant.',
    'provider.publish.portals.tenant_owned.empty': 'No tenant portals are available.',
    'provider.publish.portals.community.title': 'Community portals',
    'provider.publish.portals.community.help': 'Publishing here makes this run visible in a community feed.',
    'provider.publish.portals.community.empty': 'No community portals are available for publishing.',
    'provider.publish.badge.owned': 'Owned',
    'provider.publish.badge.community': 'Community',
    'provider.publish.suggestions.badge.tenant_zone': 'Nearby zone',
    'provider.publish.suggestions.badge.community_portal': 'Nearby community',
    'provider.publish.suggestions.add': 'Add',
    'provider.publish.suggestions.added': 'Added',
    
    // STEP 11C: Notify stakeholders copy tokens
    'provider.run.notify.button': 'Notify stakeholders',
    'provider.notify.modal.title': 'Notify stakeholders',
    'provider.notify.rule.title': 'Private ops notifications',
    'provider.notify.rule.body': 'Notify sends private invitations. Publishing controls what appears on public portals.',
    'provider.notify.invitees.label': 'Email addresses',
    'provider.notify.invitees.help': 'One per line or comma-separated.',
    'provider.notify.name.label': 'Name (optional)',
    'provider.notify.message.label': 'Message (optional)',
    'provider.notify.send': 'Create invitations',
    'provider.notify.created.title': 'Invitation links',
    'provider.notify.copy': 'Copy link',
    'provider.notify.copied': 'Copied',
    'provider.notify.list.title': 'Invitation tracking',
    'provider.notify.status.sent': 'Sent',
    'provider.notify.status.viewed': 'Viewed',
    'provider.notify.status.claimed': 'Claimed',
    'provider.notify.status.expired': 'Expired',
    'provider.notify.status.revoked': 'Revoked',
    'provider.notify.bulk.title': 'Add multiple stakeholders',
    'provider.notify.bulk.mode.paste': 'Paste list',
    'provider.notify.bulk.mode.csv': 'Upload CSV',
    'provider.notify.bulk.paste.placeholder': 'Paste emails separated by commas or new lines',
    'provider.notify.bulk.csv.button': 'Choose CSV file',
    'provider.notify.bulk.preview.title': 'Preview',
    'provider.notify.bulk.preview.help': "We'll remove duplicates and skip anyone already invited.",
    'provider.notify.bulk.badge.on_platform': 'On platform',
    'provider.notify.bulk.badge.ready': 'Ready',
    'provider.notify.bulk.badge.invalid': 'Invalid',
    'provider.notify.bulk.badge.duplicate': 'Duplicate',
    'provider.notify.bulk.badge.already_invited': 'Already invited',
    'provider.notify.bulk.badge.created': 'Created',
    'provider.notify.bulk.badge.rate_limited': 'Limit reached',
    'provider.notify.bulk.submit': 'Send invitations',
    'provider.notify.bulk.remove': 'Remove',
    'provider.notify.bulk.error.csv_parse': "Couldn't read that CSV. Check headers and try again.",
    'provider.notify.bulk.error.rate_limited': 'Invitation limit reached. Try again later or adjust tenant policy.',
    'provider.notify.delivery.in_app': 'In-app',
    'provider.notify.delivery.email': 'Email',
    'provider.notify.delivery.both': 'In-app + Email',
    'provider.notify.delivery.link': 'Link',
    'public.invite.title': "You've been invited to view a service run",
    'public.invite.read_only': 'Read-only',
    'public.invite.expired': 'This invitation link is invalid or expired.',
    
    // STEP 11C Phase 2C-1.1: Stakeholder Responses Panel
    'provider.run.responses.title': 'Stakeholder responses',
    'provider.run.responses.empty': 'No stakeholder responses yet.',
    'provider.run.responses.loading': 'Loading responses…',
    'provider.run.responses.badge.confirm': 'Confirmed',
    'provider.run.responses.badge.request_change': 'Request change',
    'provider.run.responses.badge.question': 'Question',
    'provider.run.responses.identity.fallback': 'Stakeholder',
    
    // STEP 11C Phase 2C-1.2: Reply to Stakeholder
    'provider.run.responses.reply': 'Reply',
    'provider.run.responses.reply.prefill.confirm': 'Thanks for confirming. If anything changes, reply here.',
    'provider.run.responses.reply.prefill.request_change': 'I saw your request to change the schedule. What timing works best?',
    'provider.run.responses.reply.prefill.question': 'Thanks for your question. Here\'s a quick reply:',
  },

  lodging: {
    'label.noun.provider': 'host',
    'label.noun.requester': 'guest',
    'label.noun.request': 'reservation request',
    'label.noun.run': 'stay',
    'label.noun.community': 'community',
    'label.noun.company': 'property',
    'label.noun.reservation': 'reservation',
    'state.market.TARGETED.label': 'Targeted',
    'state.market.OPEN.label': 'Open',
    'state.market.INVITE_ONLY.label': 'Invite Only',
    'state.visibility.PRIVATE.label': 'Private',
    'state.request.UNASSIGNED.label': 'Unassigned',
    'ui.market.locked_notice': 'Host selected — not open for responses',
    'ui.publish.ask_requester.title': 'Send to guest for approval',
    'ui.publish.ask_requester.body': 'Your offer will be sent to the guest for confirmation.',
    'ui.publish.just_publish.notice': 'This reservation will be confirmed immediately.',
    'ui.ai.suggestion.route_zones.title': 'Suggested areas',
    'ui.ai.suggestion.route_zones.body': 'Based on guest preferences, these areas may be suitable.',
    'msg.invite.sent.subject': 'You have been invited to host',
    'msg.invite.sent.body': 'You have received an invitation to offer accommodation for {requestTitle}.',
    'msg.request.accepted.subject': 'Your accommodation was accepted',
    'msg.request.accepted.body': 'Great news! The guest has confirmed the reservation for {requestTitle}.',
    'msg.proposal.created.subject': 'New accommodation offer',
    'msg.proposal.created.body': 'A host has submitted an offer for {requestTitle}.',
    'msg.request.declined.subject': 'Offer declined',
    'msg.request.declined.body': 'The accommodation offer for {requestTitle} was not accepted.',
    'msg.request.unassigned.subject': 'Reservation request reopened',
    'msg.request.unassigned.body': 'The reservation request {requestTitle} is now open for new offers.',
    'cta.proposal.review': 'Review Offer',
    'cta.proposal.accept': 'Accept Offer',
    'cta.proposal.reject': 'Decline Offer',
    'cta.proposal.propose_change': 'Propose Change',
    'cta.proposal.submit': 'Submit Offer',
    'cta.request.open_to_bids': 'Open for Offers',
    'cta.request.invite_another_provider': 'Invite Another Host',
    'cta.request.send': 'Send Request',
    'cta.request.accept': 'Accept',
    'cta.request.decline': 'Decline',
    'cta.request.withdraw': 'Withdraw',
    'cta.request.cancel': 'Cancel Request',
    'cta.request.modify': 'Modify Request',
    'cta.publish': 'Publish',
    'cta.run.withdraw': 'Withdraw',
    'cta.run.close_signups': 'Close Availability',
    'cta.run.express_interest': 'Express Interest',
    'cta.run.mark_complete': 'Mark Complete',
    'cta.admin.reassign': 'Reassign',
    'cta.admin.cancel': 'Cancel',
    'cta.admin.force_status': 'Force Status',
  },

  parking: {
    'label.noun.provider': 'lot operator',
    'label.noun.requester': 'driver',
    'label.noun.request': 'capacity request',
    'label.noun.run': 'parking session',
    'label.noun.community': 'community',
    'label.noun.company': 'parking facility',
    'label.noun.reservation': 'reservation',
    'state.market.TARGETED.label': 'Targeted',
    'state.market.OPEN.label': 'Open',
    'state.market.INVITE_ONLY.label': 'Invite Only',
    'state.visibility.PRIVATE.label': 'Private',
    'state.request.UNASSIGNED.label': 'Unassigned',
    'ui.market.locked_notice': 'Lot operator selected — not open for responses',
    'ui.publish.ask_requester.title': 'Send to driver for confirmation',
    'ui.publish.ask_requester.body': 'Your offer will be sent to the driver for confirmation.',
    'ui.publish.just_publish.notice': 'This reservation will be confirmed immediately.',
    'ui.ai.suggestion.route_zones.title': 'Suggested parking areas',
    'ui.ai.suggestion.route_zones.body': 'Based on capacity needs, these parking areas may be suitable.',
    'msg.invite.sent.subject': 'You have been invited to provide parking',
    'msg.invite.sent.body': 'You have received an invitation to offer parking for {requestTitle}.',
    'msg.request.accepted.subject': 'Your parking offer was accepted',
    'msg.request.accepted.body': 'Great news! The driver has confirmed parking for {requestTitle}.',
    'msg.proposal.created.subject': 'New parking offer',
    'msg.proposal.created.body': 'A lot operator has submitted an offer for {requestTitle}.',
    'msg.request.declined.subject': 'Parking offer declined',
    'msg.request.declined.body': 'The parking offer for {requestTitle} was not accepted.',
    'msg.request.unassigned.subject': 'Parking request reopened',
    'msg.request.unassigned.body': 'The parking request {requestTitle} is now open for new offers.',
    'cta.proposal.review': 'Review Offer',
    'cta.proposal.accept': 'Accept Offer',
    'cta.proposal.reject': 'Decline Offer',
    'cta.proposal.propose_change': 'Propose Change',
    'cta.proposal.submit': 'Submit Offer',
    'cta.request.open_to_bids': 'Open for Offers',
    'cta.request.invite_another_provider': 'Invite Another Operator',
    'cta.request.send': 'Send Request',
    'cta.request.accept': 'Accept',
    'cta.request.decline': 'Decline',
    'cta.request.withdraw': 'Withdraw',
    'cta.request.cancel': 'Cancel Request',
    'cta.request.modify': 'Modify Request',
    'cta.publish': 'Publish',
    'cta.run.withdraw': 'Withdraw',
    'cta.run.close_signups': 'Close Availability',
    'cta.run.express_interest': 'Express Interest',
    'cta.run.mark_complete': 'Mark Complete',
    'cta.admin.reassign': 'Reassign',
    'cta.admin.cancel': 'Cancel',
    'cta.admin.force_status': 'Force Status',
  },

  marina: {
    'label.noun.provider': 'marina',
    'label.noun.requester': 'boater',
    'label.noun.request': 'moorage request',
    'label.noun.run': 'moorage',
    'label.noun.community': 'marina community',
    'label.noun.company': 'marina',
    'label.noun.reservation': 'reservation',
    'state.market.TARGETED.label': 'Targeted',
    'state.market.OPEN.label': 'Open',
    'state.market.INVITE_ONLY.label': 'Invite Only',
    'state.visibility.PRIVATE.label': 'Private',
    'state.request.UNASSIGNED.label': 'Unassigned',
    'ui.market.locked_notice': 'Marina selected — not open for responses',
    'ui.publish.ask_requester.title': 'Send to boater for confirmation',
    'ui.publish.ask_requester.body': 'Your moorage offer will be sent to the boater for confirmation.',
    'ui.publish.just_publish.notice': 'This moorage reservation will be confirmed immediately.',
    'ui.ai.suggestion.route_zones.title': 'Suggested moorage areas',
    'ui.ai.suggestion.route_zones.body': 'Based on vessel size and needs, these slips may be suitable.',
    'msg.invite.sent.subject': 'You have been invited to provide moorage',
    'msg.invite.sent.body': 'You have received an invitation to offer moorage for {requestTitle}.',
    'msg.request.accepted.subject': 'Your moorage offer was accepted',
    'msg.request.accepted.body': 'Great news! The boater has confirmed moorage for {requestTitle}.',
    'msg.proposal.created.subject': 'New moorage offer',
    'msg.proposal.created.body': 'A marina has submitted a moorage offer for {requestTitle}.',
    'msg.request.declined.subject': 'Moorage offer declined',
    'msg.request.declined.body': 'The moorage offer for {requestTitle} was not accepted.',
    'msg.request.unassigned.subject': 'Moorage request reopened',
    'msg.request.unassigned.body': 'The moorage request {requestTitle} is now open for new offers.',
    'cta.proposal.review': 'Review Offer',
    'cta.proposal.accept': 'Accept Offer',
    'cta.proposal.reject': 'Decline Offer',
    'cta.proposal.propose_change': 'Propose Change',
    'cta.proposal.submit': 'Submit Offer',
    'cta.request.open_to_bids': 'Open for Offers',
    'cta.request.invite_another_provider': 'Invite Another Marina',
    'cta.request.send': 'Send Request',
    'cta.request.accept': 'Accept',
    'cta.request.decline': 'Decline',
    'cta.request.withdraw': 'Withdraw',
    'cta.request.cancel': 'Cancel Request',
    'cta.request.modify': 'Modify Request',
    'cta.publish': 'Publish',
    'cta.run.withdraw': 'Withdraw',
    'cta.run.close_signups': 'Close Availability',
    'cta.run.express_interest': 'Express Interest',
    'cta.run.mark_complete': 'Mark Complete',
    'cta.admin.reassign': 'Reassign',
    'cta.admin.cancel': 'Cancel',
    'cta.admin.force_status': 'Force Status',
  },

  restaurant: {
    'label.noun.provider': 'restaurant',
    'label.noun.requester': 'guest',
    'label.noun.request': 'reservation request',
    'label.noun.run': 'dining experience',
    'label.noun.community': 'dining community',
    'label.noun.company': 'restaurant',
    'label.noun.reservation': 'reservation',
    'state.market.TARGETED.label': 'Targeted',
    'state.market.OPEN.label': 'Open',
    'state.market.INVITE_ONLY.label': 'Invite Only',
    'state.visibility.PRIVATE.label': 'Private',
    'state.request.UNASSIGNED.label': 'Unassigned',
    'ui.market.locked_notice': 'Restaurant selected — not open for responses',
    'ui.publish.ask_requester.title': 'Send to guest for confirmation',
    'ui.publish.ask_requester.body': 'Your offer will be sent to the guest for confirmation.',
    'ui.publish.just_publish.notice': 'This reservation will be confirmed immediately.',
    'ui.ai.suggestion.route_zones.title': 'Suggested dining options',
    'ui.ai.suggestion.route_zones.body': 'Based on guest preferences, these restaurants may be suitable.',
    'msg.invite.sent.subject': 'You have been invited to host a dining reservation',
    'msg.invite.sent.body': 'You have received an invitation to offer dining for {requestTitle}.',
    'msg.request.accepted.subject': 'Your dining reservation was confirmed',
    'msg.request.accepted.body': 'Great news! The guest has confirmed the reservation for {requestTitle}.',
    'msg.proposal.created.subject': 'New dining offer',
    'msg.proposal.created.body': 'A restaurant has submitted an offer for {requestTitle}.',
    'msg.request.declined.subject': 'Dining offer declined',
    'msg.request.declined.body': 'The dining offer for {requestTitle} was not accepted.',
    'msg.request.unassigned.subject': 'Dining request reopened',
    'msg.request.unassigned.body': 'The dining request {requestTitle} is now open for new offers.',
    'cta.proposal.review': 'Review Offer',
    'cta.proposal.accept': 'Accept Offer',
    'cta.proposal.reject': 'Decline Offer',
    'cta.proposal.propose_change': 'Propose Change',
    'cta.proposal.submit': 'Submit Offer',
    'cta.request.open_to_bids': 'Open for Offers',
    'cta.request.invite_another_provider': 'Invite Another Restaurant',
    'cta.request.send': 'Send Request',
    'cta.request.accept': 'Accept',
    'cta.request.decline': 'Decline',
    'cta.request.withdraw': 'Withdraw',
    'cta.request.cancel': 'Cancel Request',
    'cta.request.modify': 'Modify Request',
    'cta.publish': 'Publish',
    'cta.run.withdraw': 'Withdraw',
    'cta.run.close_signups': 'Close Availability',
    'cta.run.express_interest': 'Express Interest',
    'cta.run.mark_complete': 'Mark Complete',
    'cta.admin.reassign': 'Reassign',
    'cta.admin.cancel': 'Cancel',
    'cta.admin.force_status': 'Force Status',
  },

  equipment: {
    'label.noun.provider': 'rental provider',
    'label.noun.requester': 'renter',
    'label.noun.request': 'rental request',
    'label.noun.run': 'rental period',
    'label.noun.community': 'community',
    'label.noun.company': 'rental company',
    'label.noun.reservation': 'reservation',
    'state.market.TARGETED.label': 'Targeted',
    'state.market.OPEN.label': 'Open',
    'state.market.INVITE_ONLY.label': 'Invite Only',
    'state.visibility.PRIVATE.label': 'Private',
    'state.request.UNASSIGNED.label': 'Unassigned',
    'ui.market.locked_notice': 'Rental provider selected — not open for responses',
    'ui.publish.ask_requester.title': 'Send to renter for confirmation',
    'ui.publish.ask_requester.body': 'Your rental offer will be sent to the renter for confirmation.',
    'ui.publish.just_publish.notice': 'This rental reservation will be confirmed immediately.',
    'ui.ai.suggestion.route_zones.title': 'Suggested rental options',
    'ui.ai.suggestion.route_zones.body': 'Based on equipment needs, these providers may be suitable.',
    'msg.invite.sent.subject': 'You have been invited to provide equipment',
    'msg.invite.sent.body': 'You have received an invitation to offer equipment for {requestTitle}.',
    'msg.request.accepted.subject': 'Your rental offer was accepted',
    'msg.request.accepted.body': 'Great news! The renter has confirmed the rental for {requestTitle}.',
    'msg.proposal.created.subject': 'New rental offer',
    'msg.proposal.created.body': 'A rental provider has submitted an offer for {requestTitle}.',
    'msg.request.declined.subject': 'Rental offer declined',
    'msg.request.declined.body': 'The rental offer for {requestTitle} was not accepted.',
    'msg.request.unassigned.subject': 'Rental request reopened',
    'msg.request.unassigned.body': 'The rental request {requestTitle} is now open for new offers.',
    'cta.proposal.review': 'Review Offer',
    'cta.proposal.accept': 'Accept Offer',
    'cta.proposal.reject': 'Decline Offer',
    'cta.proposal.propose_change': 'Propose Change',
    'cta.proposal.submit': 'Submit Offer',
    'cta.request.open_to_bids': 'Open for Offers',
    'cta.request.invite_another_provider': 'Invite Another Provider',
    'cta.request.send': 'Send Request',
    'cta.request.accept': 'Accept',
    'cta.request.decline': 'Decline',
    'cta.request.withdraw': 'Withdraw',
    'cta.request.cancel': 'Cancel Request',
    'cta.request.modify': 'Modify Request',
    'cta.publish': 'Publish',
    'cta.run.withdraw': 'Withdraw',
    'cta.run.close_signups': 'Close Availability',
    'cta.run.express_interest': 'Express Interest',
    'cta.run.mark_complete': 'Mark Complete',
    'cta.admin.reassign': 'Reassign',
    'cta.admin.cancel': 'Cancel',
    'cta.admin.force_status': 'Force Status',
  },

  service: {
    'label.noun.provider': 'service provider',
    'label.noun.requester': 'client',
    'label.noun.request': 'service request',
    'label.noun.run': 'service run',
    'label.noun.community': 'community',
    'label.noun.company': 'service company',
    'label.noun.reservation': 'reservation',
    'state.market.TARGETED.label': 'Targeted',
    'state.market.OPEN.label': 'Open',
    'state.market.INVITE_ONLY.label': 'Invite Only',
    'state.visibility.PRIVATE.label': 'Private',
    'state.request.UNASSIGNED.label': 'Unassigned',
    'ui.market.locked_notice': 'Provider selected — not open for responses',
    'ui.publish.ask_requester.title': 'Submit for approval',
    'ui.publish.ask_requester.body': 'Your proposal will be sent to the client for review.',
    'ui.publish.just_publish.notice': 'This will be scheduled immediately.',
    'ui.ai.suggestion.route_zones.title': 'Suggested service areas',
    'ui.ai.suggestion.route_zones.body': 'Based on your service area, these zones may be relevant.',
    'msg.invite.sent.subject': 'You have been invited to provide service',
    'msg.invite.sent.body': 'You have received an invitation to submit a proposal for {requestTitle}.',
    'msg.request.accepted.subject': 'Your proposal was accepted',
    'msg.request.accepted.body': 'Great news! Your proposal for {requestTitle} has been accepted.',
    'msg.proposal.created.subject': 'New service proposal received',
    'msg.proposal.created.body': 'A provider has submitted a proposal for {requestTitle}.',
    'msg.request.declined.subject': 'Proposal declined',
    'msg.request.declined.body': 'The proposal for {requestTitle} was not accepted.',
    'msg.request.unassigned.subject': 'Service request is now unassigned',
    'msg.request.unassigned.body': 'The service request {requestTitle} is now open for new proposals.',
    'cta.proposal.review': 'Review Proposal',
    'cta.proposal.accept': 'Accept Proposal',
    'cta.proposal.reject': 'Decline Proposal',
    'cta.proposal.propose_change': 'Propose Change',
    'cta.proposal.submit': 'Submit Proposal',
    'cta.request.open_to_bids': 'Open for Proposals',
    'cta.request.invite_another_provider': 'Invite Another Provider',
    'cta.request.send': 'Send Request',
    'cta.request.accept': 'Accept',
    'cta.request.decline': 'Decline',
    'cta.request.withdraw': 'Withdraw',
    'cta.request.cancel': 'Cancel Request',
    'cta.request.modify': 'Modify Request',
    'cta.publish': 'Publish',
    'cta.run.withdraw': 'Withdraw',
    'cta.run.close_signups': 'Close Signups',
    'cta.run.express_interest': 'Express Interest',
    'cta.run.mark_complete': 'Mark Complete',
    'cta.admin.reassign': 'Reassign',
    'cta.admin.cancel': 'Cancel',
    'cta.admin.force_status': 'Force Status',
    // Provider inbox UI tokens
    'ui.inbox.title': 'Inbox',
    'ui.inbox.subtitle': 'Incoming {request}s requiring your response',
    'ui.inbox.search_placeholder': 'Search {request}s...',
    'ui.inbox.tab.pending': 'Pending',
    'ui.inbox.tab.proposed': 'Proposed',
    'ui.inbox.tab.accepted': 'Accepted',
    'ui.inbox.tab.all': 'All',
    'ui.inbox.empty': 'No {request}s found',
    'ui.detail.description': 'Description',
    'ui.detail.notes': 'Additional Notes',
    'ui.detail.actions': 'Actions',
    'ui.detail.respond': 'Respond to this {request}',
    'ui.detail.from': 'From',
    'ui.detail.preferred_time': 'Preferred Time',
    'ui.detail.location': 'Location',
    'ui.modal.accept.title': 'Accept {request}',
    'ui.modal.accept.description': 'Confirm that you will handle this {request}.',
    'ui.modal.propose.title': 'Propose Alternative',
    'ui.modal.propose.description': 'Suggest a different date or time for this {request}.',
    'ui.modal.decline.title': 'Decline {request}',
    'ui.modal.decline.description': 'Provide an optional reason for declining.',
    'ui.modal.decline.reason': 'Reason (optional)',
    'ui.status.awaiting': 'Awaiting Response',
    'ui.status.proposed': 'Change Proposed',
    'ui.status.accepted': 'Accepted',
    'ui.status.declined': 'Declined',
    'ui.status.new': 'New',
    'ui.status.unassigned': 'Unassigned',
    'ui.loading': 'Loading...',
    'ui.not_found': '{request} not found',
    'ui.untitled': 'Untitled {request}',
    'ui.no_actions': 'No actions available for this {request}',
    'ui.received': 'Received',
    'ui.toast.accepted.title': 'Accepted',
    'ui.toast.proposal_sent.title': 'Proposal Sent',
    'ui.toast.declined.title': 'Declined',
    'ui.toast.error.title': 'Error',
    'ui.toast.error.accept': 'Failed to accept {request}',
    'ui.toast.error.propose': 'Failed to submit proposal',
    'ui.toast.error.decline': 'Failed to decline {request}',
    'ui.button.cancel': 'Cancel',
    'ui.button.confirm': 'Confirm',
    'ui.button.accepting': 'Accepting...',
    'ui.button.send_proposal': 'Send Proposal',
    'ui.button.sending': 'Sending...',
    'ui.button.declining': 'Declining...',
    'ui.label.proposed_date': 'Proposed Date',
    'ui.label.start_time': 'Start Time',
    'ui.label.end_time': 'End Time',
    'ui.label.message': 'Message (optional)',
    'ui.placeholder.propose_reason': 'Explain why you are proposing this change...',
    'ui.placeholder.decline_reason': 'Let them know why you cannot take this on...',
    // V3.5 Provider Run Publish tokens
    'provider.run.publish.cta': 'Publish to Portals',
    'provider.run.publish.modal_title': 'Publish Service Run',
    'provider.run.publish.visibility_label': 'Visibility — Where this run appears',
    'provider.run.publish.visibility_helper': 'Select which community portals will display this run.',
    'provider.run.publish.competition_label': 'Competition — Who can respond',
    'provider.run.publish.market_mode_open': 'Open for responses',
    'provider.run.publish.market_mode_open_helper': 'Anyone can attach requests to this run. Does not commit you to any requests.',
    'provider.run.publish.market_mode_invite_only': 'By invitation only',
    'provider.run.publish.market_mode_invite_only_helper': 'Only invited requesters can attach. Does not commit you to any requests.',
    'provider.run.publish.confirm': 'Publish Run',
    'provider.run.publish.success': 'Run published successfully',
    'provider.run.publish.no_portals': 'No community portals available',
    'error.run.publish.invalid_market_mode': 'Invalid market mode. TARGETED is not valid for runs.',
    
    // V3.5 STEP 6: Provider Run Attachments tokens
    'provider.run.attachments.title': 'Attached Service Requests',
    'provider.run.attachments.held': 'Held',
    'provider.run.attachments.committed': 'Committed',
    'provider.run.attachments.add_cta': 'Add Requests',
    'provider.run.attachments.hold_cta': 'Hold',
    'provider.run.attachments.commit_cta': 'Commit',
    'provider.run.attachments.release_cta': 'Release',
    'provider.run.attachments.hold_success': 'Request held successfully',
    'provider.run.attachments.commit_success': 'Request committed successfully',
    'provider.run.attachments.release_success': 'Request released',
    'provider.run.attachments.empty': 'No requests attached to this run',
    'provider.run.attachments.add_modal_title': 'Add Requests to Run',
    'provider.run.attachments.no_requests': 'No available requests to attach',
    'error.request.invalid_state': 'Request cannot be modified in its current state',
    'error.attachment.not_holdable': 'This request cannot be held',
    'error.attachment.not_committable': 'This attachment cannot be committed',
    'error.commitment.release_not_allowed': 'Committed requests cannot be released',
    
    // V3.5 STEP 6.5B: Start Address tokens
    'provider.run.start_address.title': 'Start Location',
    'provider.run.start_address.not_set': 'Not set',
    'provider.run.start_address.edit': 'Edit',
    'provider.run.start_address.clear': 'Clear',
    'provider.run.start_address.helper_private': 'Start address is private and helps improve future suggestions.',
    'provider.run.start_address.helper_changeable': 'You can change this anytime.',
    'provider.run.start_address.helper_no_assignment': 'This does not affect who is assigned to the run.',
    'provider.start_address.modal_title': 'Select Start Address',
    'provider.start_address.select_label': 'Choose from saved addresses',
    'provider.start_address.add_new_label': 'Add new address',
    'provider.start_address.none_option': 'None (clear start address)',
    'provider.start_address.form.label': 'Address Name',
    'provider.start_address.form.label_placeholder': 'e.g., John\'s House, South Yard',
    'provider.start_address.form.address1': 'Street Address',
    'provider.start_address.form.city': 'City',
    'provider.start_address.form.region': 'Province/Region',
    'provider.start_address.form.postal': 'Postal Code',
    'provider.start_address.form.notes': 'Notes (optional)',
    'provider.start_address.form.notes_placeholder': 'e.g., Gate code: 1234',
    'provider.start_address.form.is_default': 'Set as default address',
    'provider.start_address.save': 'Save',
    'provider.start_address.cancel': 'Cancel',
    'provider.start_address.create_success': 'Address saved',
    'provider.start_address.update_success': 'Start address updated',
    'error.start_address.not_found': 'Address not found',
    'error.start_address.label_exists': 'An address with this name already exists',
    'error.start_address.archived': 'This address has been archived',
    
    // V3.5 STEP 11C Phase 2C-1: Stakeholder Response tokens
    'stakeholder.response.title': 'Your Response',
    'stakeholder.response.help': 'Send a response to the service provider.',
    'stakeholder.response.type.label': 'Response type',
    'stakeholder.response.type.confirm': 'Confirm',
    'stakeholder.response.type.request_change': 'Request change',
    'stakeholder.response.type.question': 'Ask a question',
    'stakeholder.response.message.label': 'Message (optional)',
    'stakeholder.response.message.placeholder': 'Add details for the service provider…',
    'stakeholder.response.submit': 'Send Response',
    'stakeholder.response.history.title': 'Previous Responses',
    'stakeholder.response.success': 'Response sent.',
    'stakeholder.response.current': 'Your current response',
  },

  activity: {
    'label.noun.provider': 'operator',
    'label.noun.requester': 'participant',
    'label.noun.request': 'activity request',
    'label.noun.run': 'activity session',
    'label.noun.community': 'community',
    'label.noun.company': 'activity operator',
    'label.noun.reservation': 'reservation',
    'state.market.TARGETED.label': 'Targeted',
    'state.market.OPEN.label': 'Open',
    'state.market.INVITE_ONLY.label': 'Invite Only',
    'state.visibility.PRIVATE.label': 'Private',
    'state.request.UNASSIGNED.label': 'Unassigned',
    'ui.market.locked_notice': 'Operator selected — not open for responses',
    'ui.publish.ask_requester.title': 'Send to participant for confirmation',
    'ui.publish.ask_requester.body': 'Your activity offer will be sent to the participant for confirmation.',
    'ui.publish.just_publish.notice': 'This activity reservation will be confirmed immediately.',
    'ui.ai.suggestion.route_zones.title': 'Suggested activities',
    'ui.ai.suggestion.route_zones.body': 'Based on participant preferences, these activities may be suitable.',
    'msg.invite.sent.subject': 'You have been invited to provide an activity',
    'msg.invite.sent.body': 'You have received an invitation to offer an activity for {requestTitle}.',
    'msg.request.accepted.subject': 'Your activity offer was accepted',
    'msg.request.accepted.body': 'Great news! The participant has confirmed the activity for {requestTitle}.',
    'msg.proposal.created.subject': 'New activity offer',
    'msg.proposal.created.body': 'An operator has submitted an activity offer for {requestTitle}.',
    'msg.request.declined.subject': 'Activity offer declined',
    'msg.request.declined.body': 'The activity offer for {requestTitle} was not accepted.',
    'msg.request.unassigned.subject': 'Activity request reopened',
    'msg.request.unassigned.body': 'The activity request {requestTitle} is now open for new offers.',
    'cta.proposal.review': 'Review Offer',
    'cta.proposal.accept': 'Accept Offer',
    'cta.proposal.reject': 'Decline Offer',
    'cta.proposal.propose_change': 'Propose Change',
    'cta.proposal.submit': 'Submit Offer',
    'cta.request.open_to_bids': 'Open for Offers',
    'cta.request.invite_another_provider': 'Invite Another Operator',
    'cta.request.send': 'Send Request',
    'cta.request.accept': 'Accept',
    'cta.request.decline': 'Decline',
    'cta.request.withdraw': 'Withdraw',
    'cta.request.cancel': 'Cancel Request',
    'cta.request.modify': 'Modify Request',
    'cta.publish': 'Publish',
    'cta.run.withdraw': 'Withdraw',
    'cta.run.close_signups': 'Close Signups',
    'cta.run.express_interest': 'Express Interest',
    'cta.run.mark_complete': 'Mark Complete',
    'cta.admin.reassign': 'Reassign',
    'cta.admin.cancel': 'Cancel',
    'cta.admin.force_status': 'Force Status',
  },
};
