/**
 * QA Proof Writer
 * 
 * Helper to write proof artifacts (JSON + Markdown) for SCM certification.
 */

import fs from "fs";
import path from "path";

export interface StepResult {
  step: string;
  ok: boolean | string;
  [key: string]: unknown;
}

export interface Assertion {
  assert: string;
  pass: boolean;
}

export interface ProofData {
  startedAt: string;
  finishedAt?: string;
  baseUrl: string;
  steps: StepResult[];
  ids: Record<string, string>;
  assertions: Assertion[];
  monetization: unknown;
  audit: unknown;
}

export function writeProofArtifacts(artifactsDir: string, proof: ProofData): void {
  // Write JSON
  const jsonPath = path.join(artifactsDir, "p2-smoke-proof.json");
  fs.writeFileSync(jsonPath, JSON.stringify(proof, null, 2), "utf8");

  // Write Markdown
  const mdPath = path.join(artifactsDir, "p2-smoke-proof.md");
  const md = generateMarkdown(proof);
  fs.writeFileSync(mdPath, md, "utf8");
}

function generateMarkdown(proof: ProofData): string {
  const lines: string[] = [
    `# P2 Operator Smoke Proof`,
    ``,
    `- **Started**: ${proof.startedAt}`,
    `- **Finished**: ${proof.finishedAt || "N/A"}`,
    `- **Base URL**: ${proof.baseUrl}`,
    ``,
    `## IDs Created`,
    "```json",
    JSON.stringify(proof.ids, null, 2),
    "```",
    ``,
    `## Steps`,
    ``,
    `| Step | Status | Details |`,
    `|------|--------|---------|`,
  ];

  for (const s of proof.steps) {
    const status = getStatusIcon(s.ok);
    const details = getStepDetails(s);
    lines.push(`| ${s.step} | ${status} | ${details} |`);
  }

  lines.push(``);
  lines.push(`## Assertions`);
  lines.push(``);

  if (proof.assertions.length === 0) {
    lines.push(`_No explicit assertions recorded._`);
  } else {
    lines.push(`| Assertion | Pass |`);
    lines.push(`|-----------|------|`);
    for (const a of proof.assertions) {
      lines.push(`| ${a.assert} | ${a.pass ? "PASS" : "FAIL"} |`);
    }
  }

  lines.push(``);
  lines.push(`## Monetization Snapshot`);
  lines.push(``);

  if (proof.monetization && typeof proof.monetization === "object") {
    const m = proof.monetization as { period?: string; counts?: Array<{ eventType: string; count: number }> };
    if (m.period && m.counts) {
      lines.push(`**Period**: ${m.period}`);
      lines.push(``);
      lines.push(`| Event Type | Count |`);
      lines.push(`|------------|-------|`);
      for (const c of m.counts) {
        lines.push(`| ${c.eventType} | ${c.count} |`);
      }
    } else {
      lines.push("```json");
      lines.push(JSON.stringify(proof.monetization, null, 2));
      lines.push("```");
    }
  } else {
    lines.push(`_No monetization data captured._`);
  }

  lines.push(``);
  lines.push(`## Audit Events`);
  lines.push(``);

  if (proof.audit && typeof proof.audit === "object") {
    const a = proof.audit as { events?: unknown[] };
    if (Array.isArray(a.events)) {
      lines.push(`**Total Events**: ${a.events.length}`);
      lines.push(``);
      if (a.events.length > 0) {
        lines.push(`<details><summary>First 10 events</summary>`);
        lines.push(``);
        lines.push("```json");
        lines.push(JSON.stringify(a.events.slice(0, 10), null, 2));
        lines.push("```");
        lines.push(``);
        lines.push(`</details>`);
      }
    } else {
      lines.push("```json");
      lines.push(JSON.stringify(proof.audit, null, 2));
      lines.push("```");
    }
  } else {
    lines.push(`_No audit data captured._`);
  }

  lines.push(``);
  lines.push(`---`);
  lines.push(`_Generated by qa-operator-p2-smoke.ts_`);

  return lines.join("\n");
}

function getStatusIcon(ok: boolean | string): string {
  if (ok === true) return "PASS";
  if (ok === false) return "FAIL";
  if (ok === "failed") return "FAIL";
  if (typeof ok === "string" && ok.startsWith("skipped")) return "SKIP";
  return String(ok);
}

function getStepDetails(s: StepResult): string {
  const exclude = ["step", "ok"];
  const extras = Object.entries(s)
    .filter(([k]) => !exclude.includes(k))
    .map(([k, v]) => `${k}=${typeof v === "object" ? JSON.stringify(v) : v}`)
    .join(", ");
  return extras || "-";
}
