export type AirportType = 'large_airport' | 'medium_airport' | 'small_airport' | 'seaplane_base' | 'heliport' | 'closed';

export type AirportStatus = 'open' | 'closed' | 'seasonal';

export interface Airport {
  id: string;
  name: string;
  type: AirportType;
  status: AirportStatus;
  icao?: string;
  iata?: string;
  tc_lid?: string;
  latitude: number;
  longitude: number;
  elevation_ft?: number;
  municipality?: string;
  region_id?: string;
  has_metar: boolean;
  has_customs: boolean;
  runways?: string[];
  notes?: string;
}

export const BC_AIRPORTS: Airport[] = [
  // Major International Airports
  {
    id: "cyvr",
    name: "Vancouver International Airport",
    type: "large_airport",
    status: "open",
    icao: "CYVR",
    iata: "YVR",
    latitude: 49.1939,
    longitude: -123.1844,
    elevation_ft: 14,
    municipality: "Richmond",
    region_id: "metro-vancouver",
    has_metar: true,
    has_customs: true,
    runways: ["08L/26R", "08R/26L", "12/30"],
  },
  {
    id: "cyyj",
    name: "Victoria International Airport",
    type: "large_airport",
    status: "open",
    icao: "CYYJ",
    iata: "YYJ",
    latitude: 48.6469,
    longitude: -123.4258,
    elevation_ft: 63,
    municipality: "North Saanich",
    region_id: "capital",
    has_metar: true,
    has_customs: true,
    runways: ["09/27", "13/31"],
  },
  {
    id: "cylw",
    name: "Kelowna International Airport",
    type: "large_airport",
    status: "open",
    icao: "CYLW",
    iata: "YLW",
    latitude: 49.9561,
    longitude: -119.3778,
    elevation_ft: 1421,
    municipality: "Kelowna",
    region_id: "central-okanagan",
    has_metar: true,
    has_customs: true,
    runways: ["16/34"],
  },
  {
    id: "cyxx",
    name: "Abbotsford International Airport",
    type: "large_airport",
    status: "open",
    icao: "CYXX",
    iata: "YXX",
    latitude: 49.0253,
    longitude: -122.3608,
    elevation_ft: 195,
    municipality: "Abbotsford",
    region_id: "fraser-valley",
    has_metar: true,
    has_customs: true,
    runways: ["07/25", "01/19"],
  },
  
  // Regional Airports
  {
    id: "cyxs",
    name: "Prince George Airport",
    type: "medium_airport",
    status: "open",
    icao: "CYXS",
    iata: "YXS",
    latitude: 53.8894,
    longitude: -122.6789,
    elevation_ft: 2267,
    municipality: "Prince George",
    region_id: "fraser-fort-george",
    has_metar: true,
    has_customs: true,
    runways: ["15/33", "06/24"],
  },
  {
    id: "cyka",
    name: "Kamloops Airport",
    type: "medium_airport",
    status: "open",
    icao: "CYKA",
    iata: "YKA",
    latitude: 50.7022,
    longitude: -120.4444,
    elevation_ft: 1133,
    municipality: "Kamloops",
    region_id: "thompson-nicola",
    has_metar: true,
    has_customs: true,
    runways: ["08/26", "03/21"],
  },
  {
    id: "cyqq",
    name: "Comox Valley Airport",
    type: "medium_airport",
    status: "open",
    icao: "CYQQ",
    iata: "YQQ",
    latitude: 49.7108,
    longitude: -124.8867,
    elevation_ft: 84,
    municipality: "Comox",
    region_id: "comox-valley",
    has_metar: true,
    has_customs: true,
    runways: ["11/29", "18/36"],
    notes: "CFB Comox - joint military/civilian",
  },
  {
    id: "cycd",
    name: "Nanaimo Airport",
    type: "medium_airport",
    status: "open",
    icao: "CYCD",
    iata: "YCD",
    latitude: 49.0542,
    longitude: -123.8700,
    elevation_ft: 93,
    municipality: "Nanaimo",
    region_id: "nanaimo",
    has_metar: true,
    has_customs: true,
    runways: ["16/34"],
  },
  {
    id: "cyxc",
    name: "Cranbrook/Canadian Rockies International Airport",
    type: "medium_airport",
    status: "open",
    icao: "CYXC",
    iata: "YXC",
    latitude: 49.6108,
    longitude: -115.7819,
    elevation_ft: 3082,
    municipality: "Cranbrook",
    region_id: "east-kootenay",
    has_metar: true,
    has_customs: true,
    runways: ["16/34"],
  },
  {
    id: "cyxj",
    name: "Fort St. John Airport",
    type: "medium_airport",
    status: "open",
    icao: "CYXJ",
    iata: "YXJ",
    latitude: 56.2381,
    longitude: -120.7403,
    elevation_ft: 2280,
    municipality: "Fort St. John",
    region_id: "peace-river",
    has_metar: true,
    has_customs: true,
    runways: ["11/29", "02/20"],
  },
  {
    id: "cyyf",
    name: "Penticton Regional Airport",
    type: "medium_airport",
    status: "open",
    icao: "CYYF",
    iata: "YYF",
    latitude: 49.4631,
    longitude: -119.6019,
    elevation_ft: 1129,
    municipality: "Penticton",
    region_id: "okanagan-similkameen",
    has_metar: true,
    has_customs: true,
    runways: ["16/34"],
  },
  {
    id: "cypr",
    name: "Prince Rupert Airport (Digby Island)",
    type: "medium_airport",
    status: "open",
    icao: "CYPR",
    iata: "YPR",
    latitude: 54.2861,
    longitude: -130.4450,
    elevation_ft: 116,
    municipality: "Prince Rupert",
    region_id: "north-coast",
    has_metar: true,
    has_customs: true,
    runways: ["13/31"],
  },
  {
    id: "cyxt",
    name: "Northwest Regional Airport Terrace-Kitimat",
    type: "medium_airport",
    status: "open",
    icao: "CYXT",
    iata: "YXT",
    latitude: 54.4686,
    longitude: -128.5783,
    elevation_ft: 713,
    municipality: "Terrace",
    region_id: "kitimat-stikine",
    has_metar: true,
    has_customs: true,
    runways: ["15/33"],
  },
  {
    id: "cyyd",
    name: "Smithers Regional Airport",
    type: "medium_airport",
    status: "open",
    icao: "CYYD",
    iata: "YYD",
    latitude: 54.8247,
    longitude: -127.1828,
    elevation_ft: 1712,
    municipality: "Smithers",
    region_id: "bulkley-nechako",
    has_metar: true,
    has_customs: false,
    runways: ["15/33"],
  },
  {
    id: "cywl",
    name: "Williams Lake Airport",
    type: "medium_airport",
    status: "open",
    icao: "CYWL",
    iata: "YWL",
    latitude: 52.1831,
    longitude: -122.0539,
    elevation_ft: 3085,
    municipality: "Williams Lake",
    region_id: "cariboo",
    has_metar: true,
    has_customs: false,
    runways: ["11/29"],
  },
  {
    id: "cyqz",
    name: "Quesnel Airport",
    type: "medium_airport",
    status: "open",
    icao: "CYQZ",
    iata: "YQZ",
    latitude: 53.0261,
    longitude: -122.5100,
    elevation_ft: 1789,
    municipality: "Quesnel",
    region_id: "cariboo",
    has_metar: true,
    has_customs: false,
    runways: ["13/31"],
  },
  {
    id: "cycg",
    name: "Castlegar/West Kootenay Regional Airport",
    type: "medium_airport",
    status: "open",
    icao: "CYCG",
    iata: "YCG",
    latitude: 49.2964,
    longitude: -117.6325,
    elevation_ft: 1624,
    municipality: "Castlegar",
    region_id: "central-kootenay",
    has_metar: true,
    has_customs: false,
    runways: ["15/33"],
    notes: "Known for challenging approach through Columbia River valley",
  },
  {
    id: "cydq",
    name: "Dawson Creek Airport",
    type: "medium_airport",
    status: "open",
    icao: "CYDQ",
    iata: "YDQ",
    latitude: 55.7422,
    longitude: -120.1831,
    elevation_ft: 2148,
    municipality: "Dawson Creek",
    region_id: "peace-river",
    has_metar: true,
    has_customs: false,
    runways: ["06/24"],
  },
  {
    id: "cyye",
    name: "Fort Nelson Airport",
    type: "medium_airport",
    status: "open",
    icao: "CYYE",
    iata: "YYE",
    latitude: 58.8364,
    longitude: -122.5969,
    elevation_ft: 1253,
    municipality: "Fort Nelson",
    region_id: "northern-rockies",
    has_metar: true,
    has_customs: true,
    runways: ["03/21", "08/26"],
  },
  {
    id: "cybl",
    name: "Campbell River Airport",
    type: "small_airport",
    status: "open",
    icao: "CYBL",
    iata: "YBL",
    latitude: 49.9508,
    longitude: -125.2711,
    elevation_ft: 346,
    municipality: "Campbell River",
    region_id: "strathcona",
    has_metar: true,
    has_customs: false,
    runways: ["11/29"],
  },
  
  // Smaller Regional Airports
  {
    id: "cyzt",
    name: "Port Hardy Airport",
    type: "small_airport",
    status: "open",
    icao: "CYZT",
    iata: "YZT",
    latitude: 50.6806,
    longitude: -127.3667,
    elevation_ft: 72,
    municipality: "Port Hardy",
    region_id: "mount-waddington",
    has_metar: true,
    has_customs: true,
    runways: ["11/29"],
  },
  {
    id: "cypw",
    name: "Powell River Airport",
    type: "small_airport",
    status: "open",
    icao: "CYPW",
    iata: "YPW",
    latitude: 49.8342,
    longitude: -124.5000,
    elevation_ft: 425,
    municipality: "Powell River",
    region_id: "powell-river",
    has_metar: true,
    has_customs: false,
    runways: ["11/29"],
  },
  {
    id: "cyaz",
    name: "Tofino/Long Beach Airport",
    type: "small_airport",
    status: "open",
    icao: "CYAZ",
    iata: "YAZ",
    latitude: 49.0800,
    longitude: -125.7756,
    elevation_ft: 80,
    municipality: "Tofino",
    region_id: "alberni-clayoquot",
    has_metar: true,
    has_customs: false,
    runways: ["11/29"],
  },
  {
    id: "cyzp",
    name: "Sandspit Airport",
    type: "small_airport",
    status: "open",
    icao: "CYZP",
    iata: "YZP",
    latitude: 53.2542,
    longitude: -131.8139,
    elevation_ft: 21,
    municipality: "Sandspit",
    region_id: "north-coast",
    has_metar: true,
    has_customs: true,
    runways: ["14/32"],
    notes: "Haida Gwaii",
  },
  {
    id: "czmt",
    name: "Masset Airport",
    type: "small_airport",
    status: "open",
    icao: "CZMT",
    iata: "ZMT",
    latitude: 54.0275,
    longitude: -132.1250,
    elevation_ft: 25,
    municipality: "Masset",
    region_id: "north-coast",
    has_metar: true,
    has_customs: false,
    runways: ["11/29"],
    notes: "Haida Gwaii - Former CFB Masset",
  },
  {
    id: "cybd",
    name: "Bella Coola Airport",
    type: "small_airport",
    status: "open",
    icao: "CYBD",
    iata: "QBC",
    latitude: 52.3875,
    longitude: -126.5958,
    elevation_ft: 117,
    municipality: "Bella Coola",
    region_id: "central-coast",
    has_metar: true,
    has_customs: false,
    runways: ["04/22"],
    notes: "Famous for challenging approach through valley",
  },
  {
    id: "cybw",
    name: "Boundary Bay Airport",
    type: "small_airport",
    status: "open",
    icao: "CYBW",
    iata: "YDT",
    latitude: 49.0742,
    longitude: -123.0117,
    elevation_ft: 6,
    municipality: "Delta",
    region_id: "metro-vancouver",
    has_metar: true,
    has_customs: true,
    runways: ["07/25", "12/30"],
    notes: "Major flight training hub",
  },
  {
    id: "czbb",
    name: "Langley Regional Airport",
    type: "small_airport",
    status: "open",
    icao: "CZBB",
    iata: "YLY",
    latitude: 49.1008,
    longitude: -122.6306,
    elevation_ft: 34,
    municipality: "Langley",
    region_id: "metro-vancouver",
    has_metar: true,
    has_customs: false,
    runways: ["01/19", "07/25"],
  },
  {
    id: "cypk",
    name: "Pitt Meadows Airport",
    type: "small_airport",
    status: "open",
    icao: "CYPK",
    iata: "YPK",
    latitude: 49.2161,
    longitude: -122.7108,
    elevation_ft: 11,
    municipality: "Pitt Meadows",
    region_id: "metro-vancouver",
    has_metar: true,
    has_customs: false,
    runways: ["08/26", "18/36"],
  },
  {
    id: "cyge",
    name: "Golden Airport",
    type: "small_airport",
    status: "open",
    icao: "CYGE",
    iata: "YGE",
    latitude: 51.2992,
    longitude: -116.9814,
    elevation_ft: 2575,
    municipality: "Golden",
    region_id: "columbia-shuswap",
    has_metar: true,
    has_customs: false,
    runways: ["14/32"],
  },
  {
    id: "czry",
    name: "Revelstoke Airport",
    type: "small_airport",
    status: "open",
    icao: "CZRY",
    tc_lid: "CRY2",
    latitude: 50.9669,
    longitude: -118.1828,
    elevation_ft: 1459,
    municipality: "Revelstoke",
    region_id: "columbia-shuswap",
    has_metar: false,
    has_customs: false,
    runways: ["12/30"],
  },
  {
    id: "cyvk",
    name: "Vernon Regional Airport",
    type: "small_airport",
    status: "open",
    icao: "CYVK",
    latitude: 50.2478,
    longitude: -119.3306,
    elevation_ft: 1140,
    municipality: "Vernon",
    region_id: "north-okanagan",
    has_metar: true,
    has_customs: false,
    runways: ["05/23"],
  },
  {
    id: "cyzz",
    name: "Trail Regional Airport",
    type: "small_airport",
    status: "open",
    icao: "CYZZ",
    tc_lid: "CAD4",
    latitude: 49.0556,
    longitude: -117.6092,
    elevation_ft: 1427,
    municipality: "Trail",
    region_id: "kootenay-boundary",
    has_metar: true,
    has_customs: false,
    runways: ["03/21"],
  },
  {
    id: "cyps",
    name: "Port Alberni Airport",
    type: "small_airport",
    status: "open",
    icao: "CYPS",
    tc_lid: "CBS8",
    latitude: 49.3197,
    longitude: -124.9269,
    elevation_ft: 250,
    municipality: "Port Alberni",
    region_id: "alberni-clayoquot",
    has_metar: false,
    has_customs: false,
    runways: ["11/29"],
  },
  {
    id: "cad7",
    name: "Bamfield Airport",
    type: "small_airport",
    status: "closed",
    tc_lid: "CAD7",
    latitude: 48.8333,
    longitude: -125.1333,
    elevation_ft: 85,
    municipality: "Bamfield",
    region_id: "alberni-clayoquot",
    has_metar: false,
    has_customs: false,
    runways: ["06/24"],
    notes: "Closed - unserviced grass strip",
  },
  
  // Seaplane Bases
  {
    id: "cyhc",
    name: "Vancouver Harbour Flight Centre",
    type: "seaplane_base",
    status: "open",
    icao: "CYHC",
    iata: "CXH",
    latitude: 49.2944,
    longitude: -123.1114,
    municipality: "Vancouver",
    region_id: "metro-vancouver",
    has_metar: false,
    has_customs: true,
    notes: "Coal Harbour - Harbour Air hub",
  },
  {
    id: "cywh",
    name: "Victoria Harbour Airport",
    type: "seaplane_base",
    status: "open",
    icao: "CYWH",
    iata: "YWH",
    latitude: 48.4228,
    longitude: -123.3881,
    municipality: "Victoria",
    region_id: "capital",
    has_metar: false,
    has_customs: true,
    notes: "Inner Harbour seaplane terminal",
  },
  {
    id: "cyhe",
    name: "Nanaimo Harbour Water Airport",
    type: "seaplane_base",
    status: "open",
    icao: "CYHE",
    iata: "ZNA",
    latitude: 49.1833,
    longitude: -123.9500,
    municipality: "Nanaimo",
    region_id: "nanaimo",
    has_metar: false,
    has_customs: false,
    notes: "Downtown Nanaimo",
  },
  {
    id: "czsw",
    name: "Prince Rupert/Seal Cove Water Aerodrome",
    type: "seaplane_base",
    status: "open",
    icao: "CZSW",
    iata: "ZSW",
    latitude: 54.3333,
    longitude: -130.2833,
    municipality: "Prince Rupert",
    region_id: "north-coast",
    has_metar: false,
    has_customs: false,
  },
  {
    id: "cae5",
    name: "Whistler/Green Lake Water Aerodrome",
    type: "seaplane_base",
    status: "open",
    tc_lid: "CAE5",
    iata: "YWS",
    latitude: 50.1450,
    longitude: -122.9480,
    municipality: "Whistler",
    region_id: "squamish-lillooet",
    has_metar: false,
    has_customs: false,
  },
  {
    id: "cap5",
    name: "Victoria Airport/Pat Bay Water Aerodrome",
    type: "seaplane_base",
    status: "open",
    tc_lid: "CAP5",
    latitude: 48.6458,
    longitude: -123.4500,
    municipality: "North Saanich",
    region_id: "capital",
    has_metar: false,
    has_customs: false,
  },
  {
    id: "caq8",
    name: "Powell Lake Water Aerodrome",
    type: "seaplane_base",
    status: "open",
    tc_lid: "CAQ8",
    iata: "WPL",
    latitude: 49.8750,
    longitude: -124.5250,
    municipality: "Powell River",
    region_id: "powell-river",
    has_metar: false,
    has_customs: false,
  },
  {
    id: "tofino-seaplane",
    name: "Tofino Harbour Water Aerodrome",
    type: "seaplane_base",
    status: "open",
    latitude: 49.1530,
    longitude: -125.9070,
    municipality: "Tofino",
    region_id: "alberni-clayoquot",
    has_metar: false,
    has_customs: false,
  },
  {
    id: "port-alberni-seaplane",
    name: "Port Alberni Harbour Water Aerodrome",
    type: "seaplane_base",
    status: "open",
    latitude: 49.2350,
    longitude: -124.8050,
    municipality: "Port Alberni",
    region_id: "alberni-clayoquot",
    has_metar: false,
    has_customs: false,
    notes: "Clutesi Haven Marina",
  },
  {
    id: "bamfield-seaplane",
    name: "Bamfield Inlet Water Aerodrome",
    type: "seaplane_base",
    status: "open",
    latitude: 48.8333,
    longitude: -125.1350,
    municipality: "Bamfield",
    region_id: "alberni-clayoquot",
    has_metar: false,
    has_customs: false,
    notes: "Charter floatplane access only",
  },
];

export function getAirportsByMunicipality(municipality: string): Airport[] {
  return BC_AIRPORTS.filter(a => a.municipality === municipality);
}

export function getAirportsByRegion(regionId: string): Airport[] {
  return BC_AIRPORTS.filter(a => a.region_id === regionId);
}

export function getAirportsWithMETAR(): Airport[] {
  return BC_AIRPORTS.filter(a => a.has_metar);
}

export function getNearestAirports(lat: number, lon: number, limit: number = 5): Airport[] {
  const haversineDistance = (lat1: number, lon1: number, lat2: number, lon2: number): number => {
    const R = 6371;
    const dLat = (lat2 - lat1) * Math.PI / 180;
    const dLon = (lon2 - lon1) * Math.PI / 180;
    const a = Math.sin(dLat/2) * Math.sin(dLat/2) +
              Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) *
              Math.sin(dLon/2) * Math.sin(dLon/2);
    const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
    return R * c;
  };

  return BC_AIRPORTS
    .map(airport => ({
      airport,
      distance: haversineDistance(lat, lon, airport.latitude, airport.longitude)
    }))
    .sort((a, b) => a.distance - b.distance)
    .slice(0, limit)
    .map(item => item.airport);
}
