import { z } from 'zod';

export const BusinessCategorySchema = z.enum([
  'accommodation',
  'accounting',
  'agriculture',
  'arts-culture',
  'automotive',
  'aviation',
  'banking-finance',
  'cannabis',
  'charity-nonprofit',
  'childcare',
  'cleaning-janitorial',
  'construction',
  'consulting',
  'courier-delivery',
  'dental',
  'education',
  'electrical',
  'engineering',
  'entertainment',
  'environmental',
  'first-nations',
  'fishing-marine',
  'fitness-wellness',
  'food-beverage',
  'forestry-logging',
  'funeral',
  'government',
  'grocery',
  'hardware-supplies',
  'healthcare',
  'heating-cooling',
  'home-cc_services',
  'hospitality',
  'insurance',
  'it-technology',
  'landscaping',
  'legal',
  'manufacturing',
  'marketing-advertising',
  'cc_media',
  'medical',
  'mining',
  'optometry',
  'pets',
  'pharmacy',
  'photography',
  'plumbing',
  'printing',
  'property-management',
  'real-estate',
  'recreation',
  'religious',
  'restaurant',
  'retail',
  'roofing',
  'security',
  'seniors',
  'spa-beauty',
  'storage',
  'taxi-rideshare',
  'telecommunications',
  'towing',
  'transit',
  'trucking-freight',
  'utilities',
  'veterinary',
  'winery-brewery',
  'other',
]);

export type BusinessCategory = z.infer<typeof BusinessCategorySchema>;

export const CrossReferenceSchema = z.object({
  dataset: z.enum([
    'aviation',
    'marine',
    'emergency-cc_services',
    'ground-transport',
    'taxi-cc_services',
    'pharmacies',
    'community-facilities',
    'schools',
    'municipal-offices',
    'search-rescue',
    'weather-stations',
  ]),
  id: z.string(),
});

export const ChamberMemberSchema = z.object({
  id: z.string(),
  chamberId: z.string(),
  businessName: z.string().optional(),
  name: z.string().optional(),
  website: z.string().optional(),
  websiteNeedsCollection: z.boolean().optional(),
  phone: z.string().optional(),
  email: z.string().optional(),
  address: z.string().optional(),
  category: BusinessCategorySchema,
  subcategory: z.string().optional(),
  description: z.string().optional(),
  naicsCode: z.string().optional(),
  naicsSubsector: z.string().optional(),
  naicsSector: z.string().optional(),
  naicsTitle: z.string().optional(),
  naicsDescription: z.string().optional(),
  crossReference: CrossReferenceSchema.optional(),
  municipality: z.string().optional(),
  region: z.string().optional(),
  memberSince: z.number().optional(),
  featured: z.boolean().optional(),
  dateAdded: z.string().optional(),  // ISO date string (YYYY-MM-DD) when member was added to database
}).transform((data) => ({
  ...data,
  businessName: data.businessName || data.name || '',
}));

export type ChamberMember = z.infer<typeof ChamberMemberSchema>;

export const ChamberMemberArraySchema = z.array(ChamberMemberSchema);
