export type FacilityCategory = 
  | "community_center"
  | "sports_complex"
  | "arena"
  | "aquatic_center"
  | "curling_club"
  | "ice_rink"
  | "fieldhouse"
  | "recreation_park"
  | "playground"
  | "skate_park"
  | "stadium";

export type AmenityType =
  | "pool"
  | "hot_tub"
  | "sauna"
  | "steam_room"
  | "weight_room"
  | "fitness_studio"
  | "ice_sheet"
  | "curling_sheet"
  | "basketball_court"
  | "volleyball_court"
  | "tennis_court"
  | "squash_court"
  | "racquetball_court"
  | "badminton_court"
  | "pickleball_court"
  | "gymnasium"
  | "dance_studio"
  | "yoga_studio"
  | "martial_arts_studio"
  | "turf_field"
  | "grass_field"
  | "baseball_diamond"
  | "softball_diamond"
  | "soccer_field"
  | "lacrosse_box"
  | "running_track"
  | "walking_track"
  | "climbing_wall"
  | "bouldering_wall"
  | "playground_equipment"
  | "spray_park"
  | "wading_pool"
  | "skate_park"
  | "bmx_track"
  | "disc_golf"
  | "golf_course"
  | "driving_range"
  | "putting_green"
  | "lawn_bowling"
  | "bocce_court"
  | "horseshoe_pit"
  | "community_kitchen"
  | "meeting_room"
  | "banquet_hall"
  | "seniors_lounge"
  | "youth_center"
  | "childcare"
  | "preschool_program"
  | "library_kiosk"
  | "art_studio"
  | "pottery_studio"
  | "woodworking_shop"
  | "games_room"
  | "lounge"
  | "cafe"
  | "pro_shop"
  | "equipment_rental"
  | "changeroom"
  | "accessible_changeroom"
  | "family_changeroom"
  | "washroom"
  | "shower"
  | "locker"
  | "parking"
  | "bike_parking"
  | "observation_deck"
  | "bleachers"
  | "scoreboard";

export interface FacilityAmenity {
  type: AmenityType;
  name?: string;
  indoor?: boolean;
  count?: number;
  surface?: string;
  dimensions?: string;
  season?: "year_round" | "summer" | "winter" | "seasonal";
  access?: "public" | "membership" | "rental" | "drop_in" | "registered";
  notes?: string;
}

export interface CommunityFacility {
  id: string;
  name: string;
  category: FacilityCategory;
  municipality: string;
  region: string;
  address?: string;
  lat: number;
  lng: number;
  operator?: string;
  ownership?: "municipal" | "regional" | "provincial" | "private" | "non_profit";
  year_opened?: number;
  website?: string;
  phone?: string;
  amenities: FacilityAmenity[];
  notes?: string;
}

export const facilityCategoryLabels: Record<FacilityCategory, string> = {
  community_center: "Community Centre",
  sports_complex: "Sports Complex",
  arena: "Arena",
  aquatic_center: "Aquatic Centre",
  curling_club: "Curling Club",
  ice_rink: "Ice Rink",
  fieldhouse: "Fieldhouse",
  recreation_park: "Recreation Park",
  playground: "Playground",
  skate_park: "Skate Park",
  stadium: "Stadium",
};

export const amenityTypeLabels: Record<AmenityType, string> = {
  pool: "Pool",
  hot_tub: "Hot Tub",
  sauna: "Sauna",
  steam_room: "Steam Room",
  weight_room: "Weight Room",
  fitness_studio: "Fitness Studio",
  ice_sheet: "Ice Sheet",
  curling_sheet: "Curling Sheet",
  basketball_court: "Basketball Court",
  volleyball_court: "Volleyball Court",
  tennis_court: "Tennis Court",
  squash_court: "Squash Court",
  racquetball_court: "Racquetball Court",
  badminton_court: "Badminton Court",
  pickleball_court: "Pickleball Court",
  gymnasium: "Gymnasium",
  dance_studio: "Dance Studio",
  yoga_studio: "Yoga Studio",
  martial_arts_studio: "Martial Arts Studio",
  turf_field: "Turf Field",
  grass_field: "Grass Field",
  baseball_diamond: "Baseball Diamond",
  softball_diamond: "Softball Diamond",
  soccer_field: "Soccer Field",
  lacrosse_box: "Lacrosse Box",
  running_track: "Running Track",
  walking_track: "Walking Track",
  climbing_wall: "Climbing Wall",
  bouldering_wall: "Bouldering Wall",
  playground_equipment: "Playground",
  spray_park: "Spray Park",
  wading_pool: "Wading Pool",
  skate_park: "Skate Park",
  bmx_track: "BMX Track",
  disc_golf: "Disc Golf",
  golf_course: "Golf Course",
  driving_range: "Driving Range",
  putting_green: "Putting Green",
  lawn_bowling: "Lawn Bowling",
  bocce_court: "Bocce Court",
  horseshoe_pit: "Horseshoe Pit",
  community_kitchen: "Community Kitchen",
  meeting_room: "Meeting Room",
  banquet_hall: "Banquet Hall",
  seniors_lounge: "Seniors Lounge",
  youth_center: "Youth Centre",
  childcare: "Childcare",
  preschool_program: "Preschool Program",
  library_kiosk: "Library Kiosk",
  art_studio: "Art Studio",
  pottery_studio: "Pottery Studio",
  woodworking_shop: "Woodworking Shop",
  games_room: "Games Room",
  lounge: "Lounge",
  cafe: "Café",
  pro_shop: "Pro Shop",
  equipment_rental: "Equipment Rental",
  changeroom: "Changeroom",
  accessible_changeroom: "Accessible Changeroom",
  family_changeroom: "Family Changeroom",
  washroom: "Washroom",
  shower: "Shower",
  locker: "Locker",
  parking: "Parking",
  bike_parking: "Bike Parking",
  observation_deck: "Observation Deck",
  bleachers: "Bleachers",
  scoreboard: "Scoreboard",
};

export const BC_COMMUNITY_FACILITIES: CommunityFacility[] = [
  // ============================================
  // METRO VANCOUVER
  // ============================================

  // Vancouver
  {
    id: "van-hillcrest",
    name: "Hillcrest Community Centre",
    category: "community_center",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    address: "4575 Clancy Loranger Way",
    lat: 49.2346,
    lng: -123.1082,
    operator: "Vancouver Park Board",
    ownership: "municipal",
    year_opened: 2010,
    website: "https://vancouver.ca/parks-recreation-culture/hillcrest-community-centre.aspx",
    amenities: [
      { type: "pool", indoor: true, count: 1, name: "50m Olympic Pool" },
      { type: "pool", indoor: true, count: 1, name: "Leisure Pool" },
      { type: "hot_tub", indoor: true, count: 2 },
      { type: "sauna", indoor: true, count: 2 },
      { type: "steam_room", indoor: true, count: 2 },
      { type: "ice_sheet", indoor: true, count: 2 },
      { type: "curling_sheet", indoor: true, count: 8 },
      { type: "weight_room", indoor: true },
      { type: "fitness_studio", indoor: true, count: 2 },
      { type: "gymnasium", indoor: true },
      { type: "meeting_room", indoor: true, count: 4 },
      { type: "childcare", indoor: true },
      { type: "cafe", indoor: true },
    ],
  },
  {
    id: "van-killarney",
    name: "Killarney Community Centre",
    category: "community_center",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    address: "6260 Killarney Street",
    lat: 49.2275,
    lng: -123.0424,
    operator: "Vancouver Park Board",
    ownership: "municipal",
    website: "https://vancouver.ca/parks-recreation-culture/killarney-community-centre.aspx",
    amenities: [
      { type: "pool", indoor: true },
      { type: "ice_sheet", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "seniors_lounge", indoor: true },
      { type: "youth_center", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },
  {
    id: "van-trout-lake",
    name: "Trout Lake Community Centre",
    category: "community_center",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    address: "3360 Victoria Drive",
    lat: 49.2565,
    lng: -123.0651,
    operator: "Vancouver Park Board",
    ownership: "municipal",
    amenities: [
      { type: "ice_sheet", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "fitness_studio", indoor: true },
      { type: "meeting_room", indoor: true },
      { type: "childcare", indoor: true },
    ],
  },
  {
    id: "van-kerrisdale",
    name: "Kerrisdale Community Centre",
    category: "community_center",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    address: "5851 West Boulevard",
    lat: 49.2335,
    lng: -123.1571,
    operator: "Vancouver Park Board",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "ice_sheet", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "meeting_room", indoor: true },
      { type: "seniors_lounge", indoor: true },
    ],
  },
  {
    id: "van-britannia",
    name: "Britannia Community Services Centre",
    category: "community_center",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    address: "1661 Napier Street",
    lat: 49.2755,
    lng: -123.0706,
    operator: "Vancouver Park Board",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "ice_sheet", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "fitness_studio", indoor: true },
      { type: "library_kiosk", indoor: true },
      { type: "childcare", indoor: true },
      { type: "seniors_lounge", indoor: true },
      { type: "youth_center", indoor: true },
    ],
  },
  {
    id: "van-roundhouse",
    name: "Roundhouse Community Arts & Recreation Centre",
    category: "community_center",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    address: "181 Roundhouse Mews",
    lat: 49.2731,
    lng: -123.1216,
    operator: "Vancouver Park Board",
    ownership: "municipal",
    year_opened: 1997,
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "dance_studio", indoor: true },
      { type: "pottery_studio", indoor: true },
      { type: "woodworking_shop", indoor: true },
      { type: "meeting_room", indoor: true },
      { type: "banquet_hall", indoor: true },
    ],
  },
  {
    id: "van-kits-pool",
    name: "Kitsilano Pool",
    category: "aquatic_center",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    address: "2305 Cornwall Avenue",
    lat: 49.2735,
    lng: -123.1536,
    operator: "Vancouver Park Board",
    ownership: "municipal",
    year_opened: 1931,
    amenities: [
      { type: "pool", indoor: false, count: 1, name: "137m Saltwater Pool", season: "summer" },
      { type: "changeroom" },
    ],
  },
  {
    id: "van-ubc-aquatic",
    name: "UBC Aquatic Centre",
    category: "aquatic_center",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    address: "6121 University Boulevard",
    lat: 49.2680,
    lng: -123.2489,
    operator: "UBC Athletics",
    ownership: "provincial",
    amenities: [
      { type: "pool", indoor: true, count: 1, name: "50m Pool" },
      { type: "pool", indoor: true, count: 1, name: "Diving Tank" },
      { type: "hot_tub", indoor: true },
      { type: "sauna", indoor: true },
      { type: "steam_room", indoor: true },
      { type: "weight_room", indoor: true },
    ],
  },
  {
    id: "van-hastings",
    name: "Hastings Community Centre",
    category: "community_center",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    address: "3096 East Hastings Street",
    lat: 49.2812,
    lng: -123.0385,
    operator: "Vancouver Park Board",
    ownership: "municipal",
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "meeting_room", indoor: true },
      { type: "games_room", indoor: true },
      { type: "seniors_lounge", indoor: true },
    ],
  },
  {
    id: "van-dunbar",
    name: "Dunbar Community Centre",
    category: "community_center",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    address: "4747 Dunbar Street",
    lat: 49.2449,
    lng: -123.1855,
    operator: "Vancouver Park Board",
    ownership: "municipal",
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "fitness_studio", indoor: true },
      { type: "meeting_room", indoor: true },
      { type: "pottery_studio", indoor: true },
      { type: "childcare", indoor: true },
    ],
  },

  // Burnaby
  {
    id: "bby-bonsor",
    name: "Bonsor Recreation Complex",
    category: "sports_complex",
    municipality: "Burnaby",
    region: "Metro Vancouver",
    address: "6550 Bonsor Avenue",
    lat: 49.2272,
    lng: -122.9889,
    operator: "City of Burnaby",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "sauna", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "squash_court", indoor: true, count: 4 },
      { type: "meeting_room", indoor: true },
      { type: "seniors_lounge", indoor: true },
    ],
  },
  {
    id: "bby-edmonds",
    name: "Edmonds Community Centre",
    category: "community_center",
    municipality: "Burnaby",
    region: "Metro Vancouver",
    address: "7433 Edmonds Street",
    lat: 49.2116,
    lng: -122.9589,
    operator: "City of Burnaby",
    ownership: "municipal",
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "fitness_studio", indoor: true },
      { type: "meeting_room", indoor: true },
      { type: "childcare", indoor: true },
      { type: "seniors_lounge", indoor: true },
    ],
  },
  {
    id: "bby-bill-copeland",
    name: "Bill Copeland Sports Centre",
    category: "arena",
    municipality: "Burnaby",
    region: "Metro Vancouver",
    address: "3676 Kensington Avenue",
    lat: 49.2789,
    lng: -122.9931,
    operator: "City of Burnaby",
    ownership: "municipal",
    amenities: [
      { type: "ice_sheet", indoor: true, count: 2, name: "Twin Rinks" },
      { type: "pro_shop", indoor: true },
      { type: "cafe", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },
  {
    id: "bby-kensington",
    name: "Kensington Arena",
    category: "arena",
    municipality: "Burnaby",
    region: "Metro Vancouver",
    address: "6159 Curtis Street",
    lat: 49.2794,
    lng: -122.9875,
    operator: "City of Burnaby",
    ownership: "municipal",
    amenities: [
      { type: "ice_sheet", indoor: true },
    ],
  },
  {
    id: "bby-cg-brown",
    name: "C.G. Brown Memorial Pool",
    category: "aquatic_center",
    municipality: "Burnaby",
    region: "Metro Vancouver",
    address: "3702 Kensington Avenue",
    lat: 49.2787,
    lng: -122.9925,
    operator: "City of Burnaby",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "sauna", indoor: true },
    ],
  },

  // Surrey
  {
    id: "sur-newton",
    name: "Newton Recreation Centre",
    category: "community_center",
    municipality: "Surrey",
    region: "Metro Vancouver",
    address: "13730 72 Avenue",
    lat: 49.1287,
    lng: -122.8308,
    operator: "City of Surrey",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "ice_sheet", indoor: true, count: 2 },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "fitness_studio", indoor: true },
      { type: "meeting_room", indoor: true },
      { type: "childcare", indoor: true },
    ],
  },
  {
    id: "sur-guildford",
    name: "Guildford Recreation Centre",
    category: "community_center",
    municipality: "Surrey",
    region: "Metro Vancouver",
    address: "15105 105 Avenue",
    lat: 49.1902,
    lng: -122.8001,
    operator: "City of Surrey",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "squash_court", indoor: true },
      { type: "meeting_room", indoor: true },
      { type: "childcare", indoor: true },
    ],
  },
  {
    id: "sur-fleetwood",
    name: "Fleetwood Community Centre",
    category: "community_center",
    municipality: "Surrey",
    region: "Metro Vancouver",
    address: "15996 84 Avenue",
    lat: 49.1449,
    lng: -122.7772,
    operator: "City of Surrey",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "ice_sheet", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },
  {
    id: "sur-south-surrey",
    name: "South Surrey Recreation & Arts Centre",
    category: "community_center",
    municipality: "Surrey",
    region: "Metro Vancouver",
    address: "14601 20 Avenue",
    lat: 49.0454,
    lng: -122.8614,
    operator: "City of Surrey",
    ownership: "municipal",
    amenities: [
      { type: "ice_sheet", indoor: true, count: 2 },
      { type: "gymnasium", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "fitness_studio", indoor: true },
      { type: "art_studio", indoor: true },
      { type: "pottery_studio", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },
  {
    id: "sur-cloverdale",
    name: "Cloverdale Recreation Centre",
    category: "community_center",
    municipality: "Surrey",
    region: "Metro Vancouver",
    address: "6188 176 Street",
    lat: 49.1035,
    lng: -122.7273,
    operator: "City of Surrey",
    ownership: "municipal",
    amenities: [
      { type: "ice_sheet", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "meeting_room", indoor: true },
      { type: "seniors_lounge", indoor: true },
    ],
  },

  // Richmond
  {
    id: "ric-minoru",
    name: "Minoru Centre for Active Living",
    category: "community_center",
    municipality: "Richmond",
    region: "Metro Vancouver",
    address: "7191 Granville Avenue",
    lat: 49.1660,
    lng: -123.1371,
    operator: "City of Richmond",
    ownership: "municipal",
    year_opened: 2018,
    amenities: [
      { type: "pool", indoor: true, count: 2 },
      { type: "hot_tub", indoor: true, count: 2 },
      { type: "sauna", indoor: true },
      { type: "steam_room", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "fitness_studio", indoor: true, count: 3 },
      { type: "gymnasium", indoor: true },
      { type: "walking_track", indoor: true },
      { type: "seniors_lounge", indoor: true },
      { type: "cafe", indoor: true },
    ],
  },
  {
    id: "ric-oval",
    name: "Richmond Olympic Oval",
    category: "sports_complex",
    municipality: "Richmond",
    region: "Metro Vancouver",
    address: "6111 River Road",
    lat: 49.1743,
    lng: -123.1485,
    operator: "City of Richmond",
    ownership: "municipal",
    year_opened: 2008,
    website: "https://richmondoval.ca",
    amenities: [
      { type: "ice_sheet", indoor: true, count: 2 },
      { type: "basketball_court", indoor: true, count: 8 },
      { type: "volleyball_court", indoor: true },
      { type: "running_track", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "fitness_studio", indoor: true },
      { type: "climbing_wall", indoor: true },
      { type: "rowing_tank", indoor: true } as any,
      { type: "cafe", indoor: true },
      { type: "pro_shop", indoor: true },
    ],
  },
  {
    id: "ric-steveston",
    name: "Steveston Community Centre",
    category: "community_center",
    municipality: "Richmond",
    region: "Metro Vancouver",
    address: "4111 Moncton Street",
    lat: 49.1267,
    lng: -123.1823,
    operator: "City of Richmond",
    ownership: "municipal",
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "meeting_room", indoor: true },
      { type: "seniors_lounge", indoor: true },
      { type: "childcare", indoor: true },
    ],
  },

  // Coquitlam
  {
    id: "coq-poirier",
    name: "Poirier Sport & Leisure Complex",
    category: "sports_complex",
    municipality: "Coquitlam",
    region: "Metro Vancouver",
    address: "633 Poirier Street",
    lat: 49.2797,
    lng: -122.8018,
    operator: "City of Coquitlam",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "ice_sheet", indoor: true, count: 2 },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "meeting_room", indoor: true },
      { type: "childcare", indoor: true },
    ],
  },
  {
    id: "coq-city-centre",
    name: "City Centre Aquatic Complex",
    category: "aquatic_center",
    municipality: "Coquitlam",
    region: "Metro Vancouver",
    address: "1210 Pinetree Way",
    lat: 49.2825,
    lng: -122.7915,
    operator: "City of Coquitlam",
    ownership: "municipal",
    year_opened: 2009,
    amenities: [
      { type: "pool", indoor: true, name: "50m Competition Pool" },
      { type: "pool", indoor: true, name: "Leisure Pool" },
      { type: "hot_tub", indoor: true, count: 2 },
      { type: "sauna", indoor: true },
      { type: "steam_room", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "fitness_studio", indoor: true },
    ],
  },

  // North Vancouver (City)
  {
    id: "nvn-harry-jerome",
    name: "Harry Jerome Recreation Centre",
    category: "community_center",
    municipality: "North Vancouver",
    region: "Metro Vancouver",
    address: "123 East 23rd Street",
    lat: 49.3207,
    lng: -123.0685,
    operator: "City of North Vancouver",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "sauna", indoor: true },
      { type: "ice_sheet", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "squash_court", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },

  // West Vancouver
  {
    id: "wvan-aquatic",
    name: "West Vancouver Aquatic Centre",
    category: "aquatic_center",
    municipality: "West Vancouver",
    region: "Metro Vancouver",
    address: "2121 Marine Drive",
    lat: 49.3280,
    lng: -123.1645,
    operator: "District of West Vancouver",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true, name: "25m Lap Pool" },
      { type: "pool", indoor: true, name: "Leisure Pool" },
      { type: "hot_tub", indoor: true },
      { type: "sauna", indoor: true },
      { type: "steam_room", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "fitness_studio", indoor: true },
    ],
  },
  {
    id: "wvan-rec-centre",
    name: "West Vancouver Community Centre",
    category: "community_center",
    municipality: "West Vancouver",
    region: "Metro Vancouver",
    address: "2121 Marine Drive",
    lat: 49.3278,
    lng: -123.1648,
    operator: "District of West Vancouver",
    ownership: "municipal",
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "meeting_room", indoor: true },
      { type: "art_studio", indoor: true },
      { type: "pottery_studio", indoor: true },
      { type: "seniors_lounge", indoor: true },
      { type: "youth_center", indoor: true },
    ],
  },

  // New Westminster
  {
    id: "nwest-canada-games",
    name: "Canada Games Pool",
    category: "aquatic_center",
    municipality: "New Westminster",
    region: "Metro Vancouver",
    address: "65 East Sixth Avenue",
    lat: 49.2094,
    lng: -122.9128,
    operator: "City of New Westminster",
    ownership: "municipal",
    year_opened: 1973,
    amenities: [
      { type: "pool", indoor: true, name: "50m Competition Pool" },
      { type: "pool", indoor: true, name: "Leisure Pool" },
      { type: "hot_tub", indoor: true },
      { type: "sauna", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "fitness_studio", indoor: true },
    ],
  },
  {
    id: "nwest-queens-park",
    name: "Queens Park Arena",
    category: "arena",
    municipality: "New Westminster",
    region: "Metro Vancouver",
    address: "1st Street & 3rd Avenue",
    lat: 49.2156,
    lng: -122.9089,
    operator: "City of New Westminster",
    ownership: "municipal",
    amenities: [
      { type: "ice_sheet", indoor: true },
      { type: "bleachers", indoor: true },
    ],
  },

  // Delta
  {
    id: "delta-sdc",
    name: "Sungod Recreation Centre",
    category: "community_center",
    municipality: "Delta",
    region: "Metro Vancouver",
    address: "7815 112 Street",
    lat: 49.1287,
    lng: -122.9156,
    operator: "City of Delta",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "meeting_room", indoor: true },
      { type: "childcare", indoor: true },
    ],
  },
  {
    id: "delta-ladner",
    name: "Ladner Leisure Centre",
    category: "community_center",
    municipality: "Delta",
    region: "Metro Vancouver",
    address: "4600 Clarence Taylor Crescent",
    lat: 49.0859,
    lng: -123.0820,
    operator: "City of Delta",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "ice_sheet", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },

  // Langley
  {
    id: "lang-timms",
    name: "Timms Community Centre",
    category: "community_center",
    municipality: "Langley",
    region: "Metro Vancouver",
    address: "20399 Douglas Crescent",
    lat: 49.1004,
    lng: -122.6570,
    operator: "City of Langley",
    ownership: "municipal",
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "meeting_room", indoor: true },
      { type: "seniors_lounge", indoor: true },
    ],
  },
  {
    id: "lang-al-anderson",
    name: "Al Anderson Memorial Pool",
    category: "aquatic_center",
    municipality: "Langley",
    region: "Metro Vancouver",
    address: "20475 Douglas Crescent",
    lat: 49.0998,
    lng: -122.6575,
    operator: "City of Langley",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "sauna", indoor: true },
    ],
  },
  {
    id: "twp-lang-wc-blair",
    name: "W.C. Blair Recreation Centre",
    category: "community_center",
    municipality: "Township of Langley",
    region: "Metro Vancouver",
    address: "22200 Fraser Highway",
    lat: 49.0227,
    lng: -122.6749,
    operator: "Township of Langley",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "squash_court", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },
  {
    id: "twp-lang-walnut-grove",
    name: "Walnut Grove Community Centre",
    category: "community_center",
    municipality: "Township of Langley",
    region: "Metro Vancouver",
    address: "8889 Walnut Grove Drive",
    lat: 49.1646,
    lng: -122.6450,
    operator: "Township of Langley",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "ice_sheet", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },

  // Maple Ridge
  {
    id: "mr-leisure",
    name: "Maple Ridge Leisure Centre",
    category: "community_center",
    municipality: "Maple Ridge",
    region: "Metro Vancouver",
    address: "11925 Haney Place",
    lat: 49.2171,
    lng: -122.5974,
    operator: "City of Maple Ridge",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "walking_track", indoor: true },
      { type: "meeting_room", indoor: true },
      { type: "childcare", indoor: true },
    ],
  },
  {
    id: "mr-planet-ice",
    name: "Planet Ice Maple Ridge",
    category: "arena",
    municipality: "Maple Ridge",
    region: "Metro Vancouver",
    address: "23588 Jim Robson Way",
    lat: 49.2278,
    lng: -122.5707,
    operator: "Planet Ice",
    ownership: "private",
    amenities: [
      { type: "ice_sheet", indoor: true, count: 2 },
      { type: "pro_shop", indoor: true },
      { type: "cafe", indoor: true },
    ],
  },

  // Port Coquitlam
  {
    id: "poco-rec-complex",
    name: "Port Coquitlam Recreation Complex",
    category: "community_center",
    municipality: "Port Coquitlam",
    region: "Metro Vancouver",
    address: "2150 Wilson Avenue",
    lat: 49.2584,
    lng: -122.7647,
    operator: "City of Port Coquitlam",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "ice_sheet", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "meeting_room", indoor: true },
      { type: "childcare", indoor: true },
    ],
  },

  // Port Moody
  {
    id: "pm-rec-complex",
    name: "Port Moody Recreation Complex",
    category: "community_center",
    municipality: "Port Moody",
    region: "Metro Vancouver",
    address: "300 Ioco Road",
    lat: 49.2846,
    lng: -122.8319,
    operator: "City of Port Moody",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "ice_sheet", indoor: true, count: 2 },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },

  // White Rock
  {
    id: "wr-kent-street",
    name: "Kent Street Activity Centre",
    category: "community_center",
    municipality: "White Rock",
    region: "Metro Vancouver",
    address: "1475 Kent Street",
    lat: 49.0248,
    lng: -122.8026,
    operator: "City of White Rock",
    ownership: "municipal",
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "meeting_room", indoor: true },
      { type: "seniors_lounge", indoor: true },
      { type: "art_studio", indoor: true },
    ],
  },

  // Pitt Meadows
  {
    id: "pitm-family-rec",
    name: "Pitt Meadows Family Recreation Centre",
    category: "community_center",
    municipality: "Pitt Meadows",
    region: "Metro Vancouver",
    address: "12027 Harris Road",
    lat: 49.2213,
    lng: -122.6879,
    operator: "City of Pitt Meadows",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "ice_sheet", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },

  // ============================================
  // FRASER VALLEY
  // ============================================

  // Abbotsford
  {
    id: "abb-arc",
    name: "Abbotsford Recreation Centre",
    category: "sports_complex",
    municipality: "Abbotsford",
    region: "Fraser Valley",
    address: "2499 McMillan Road",
    lat: 49.0574,
    lng: -122.3013,
    operator: "City of Abbotsford",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "ice_sheet", indoor: true, count: 2 },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "fitness_studio", indoor: true },
      { type: "meeting_room", indoor: true },
      { type: "childcare", indoor: true },
    ],
  },
  {
    id: "abb-msa",
    name: "MSA Arena",
    category: "arena",
    municipality: "Abbotsford",
    region: "Fraser Valley",
    address: "32388 Veterans Way",
    lat: 49.0487,
    lng: -122.3116,
    operator: "City of Abbotsford",
    ownership: "municipal",
    amenities: [
      { type: "ice_sheet", indoor: true },
      { type: "bleachers", indoor: true },
    ],
  },
  {
    id: "abb-clearbrook",
    name: "W.C. Blair Recreation Centre (Clearbrook)",
    category: "community_center",
    municipality: "Abbotsford",
    region: "Fraser Valley",
    address: "2825 Clearbrook Road",
    lat: 49.0464,
    lng: -122.3378,
    operator: "City of Abbotsford",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },

  // Chilliwack
  {
    id: "chwk-landing",
    name: "Chilliwack Landing Leisure Centre",
    category: "sports_complex",
    municipality: "Chilliwack",
    region: "Fraser Valley",
    address: "45530 Spadina Avenue",
    lat: 49.1641,
    lng: -121.9597,
    operator: "City of Chilliwack",
    ownership: "municipal",
    year_opened: 2010,
    amenities: [
      { type: "pool", indoor: true },
      { type: "pool", indoor: false, name: "Outdoor Pool", season: "summer" },
      { type: "hot_tub", indoor: true },
      { type: "sauna", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "fitness_studio", indoor: true },
      { type: "meeting_room", indoor: true },
      { type: "childcare", indoor: true },
    ],
  },
  {
    id: "chwk-sardis",
    name: "Sardis Sports Complex",
    category: "sports_complex",
    municipality: "Chilliwack",
    region: "Fraser Valley",
    address: "5725 Tyson Road",
    lat: 49.0939,
    lng: -121.9774,
    operator: "City of Chilliwack",
    ownership: "municipal",
    amenities: [
      { type: "ice_sheet", indoor: true, count: 2 },
      { type: "turf_field", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },
  {
    id: "chwk-curling",
    name: "Chilliwack Curling Club",
    category: "curling_club",
    municipality: "Chilliwack",
    region: "Fraser Valley",
    address: "45950 Cheam Avenue",
    lat: 49.1669,
    lng: -121.9443,
    operator: "Chilliwack Curling Club",
    ownership: "non_profit",
    amenities: [
      { type: "curling_sheet", indoor: true, count: 6 },
      { type: "lounge", indoor: true },
      { type: "pro_shop", indoor: true },
    ],
  },

  // Mission
  {
    id: "miss-leisure",
    name: "Mission Leisure Centre",
    category: "community_center",
    municipality: "Mission",
    region: "Fraser Valley",
    address: "7650 Grand Street",
    lat: 49.1316,
    lng: -122.3130,
    operator: "District of Mission",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },

  // Hope
  {
    id: "hope-rec",
    name: "Hope Recreation Centre",
    category: "community_center",
    municipality: "Hope",
    region: "Fraser Valley",
    address: "1005 6th Avenue",
    lat: 49.3808,
    lng: -121.4418,
    operator: "District of Hope",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },

  // Agassiz
  {
    id: "agassiz-rec",
    name: "Agassiz Recreation Centre",
    category: "community_center",
    municipality: "Agassiz",
    region: "Fraser Valley",
    address: "7040 Cheam Avenue",
    lat: 49.2387,
    lng: -121.7594,
    operator: "District of Kent",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "ice_sheet", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },

  // ============================================
  // CAPITAL REGIONAL DISTRICT (VICTORIA AREA)
  // ============================================

  // Victoria
  {
    id: "vic-crystal-pool",
    name: "Crystal Pool & Fitness Centre",
    category: "aquatic_center",
    municipality: "Victoria",
    region: "Capital",
    address: "2275 Quadra Street",
    lat: 48.4326,
    lng: -123.3555,
    operator: "City of Victoria",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true, name: "25m Pool" },
      { type: "pool", indoor: true, name: "Dive Tank" },
      { type: "hot_tub", indoor: true },
      { type: "sauna", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "fitness_studio", indoor: true },
    ],
  },
  {
    id: "vic-save-on-arena",
    name: "Save-On-Foods Memorial Centre",
    category: "stadium",
    municipality: "Victoria",
    region: "Capital",
    address: "1925 Blanshard Street",
    lat: 48.4427,
    lng: -123.3651,
    operator: "RG Properties",
    ownership: "municipal",
    year_opened: 2005,
    amenities: [
      { type: "ice_sheet", indoor: true, name: "NHL-size Rink" },
      { type: "bleachers", indoor: true, count: 7006 },
      { type: "lounge", indoor: true },
      { type: "cafe", indoor: true },
    ],
  },

  // Saanich
  {
    id: "saan-commonwealth",
    name: "Commonwealth Place",
    category: "sports_complex",
    municipality: "Saanich",
    region: "Capital",
    address: "4636 Elk Lake Drive",
    lat: 48.4862,
    lng: -123.3859,
    operator: "District of Saanich",
    ownership: "municipal",
    year_opened: 1994,
    amenities: [
      { type: "pool", indoor: true, name: "50m Pool" },
      { type: "pool", indoor: true, name: "Dive Tank" },
      { type: "pool", indoor: true, name: "Leisure Pool" },
      { type: "hot_tub", indoor: true },
      { type: "sauna", indoor: true },
      { type: "steam_room", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "fitness_studio", indoor: true },
      { type: "squash_court", indoor: true },
    ],
  },
  {
    id: "saan-glanford",
    name: "G.R. Pearkes Recreation Centre",
    category: "community_center",
    municipality: "Saanich",
    region: "Capital",
    address: "3100 Tillicum Road",
    lat: 48.4601,
    lng: -123.3917,
    operator: "District of Saanich",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "ice_sheet", indoor: true, count: 2 },
      { type: "curling_sheet", indoor: true, count: 6 },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },
  {
    id: "saan-gordon-head",
    name: "Gordon Head Recreation Centre",
    category: "community_center",
    municipality: "Saanich",
    region: "Capital",
    address: "4100 Lambrick Way",
    lat: 48.4654,
    lng: -123.3076,
    operator: "District of Saanich",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "ice_sheet", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },

  // Oak Bay
  {
    id: "oak-rec-centre",
    name: "Oak Bay Recreation Centre",
    category: "community_center",
    municipality: "Oak Bay",
    region: "Capital",
    address: "1975 Bee Street",
    lat: 48.4454,
    lng: -123.3155,
    operator: "District of Oak Bay",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "squash_court", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },

  // Esquimalt
  {
    id: "esq-rec-centre",
    name: "Esquimalt Recreation Centre",
    category: "community_center",
    municipality: "Esquimalt",
    region: "Capital",
    address: "527 Fraser Street",
    lat: 48.4293,
    lng: -123.4065,
    operator: "Township of Esquimalt",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "ice_sheet", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },

  // Langford
  {
    id: "lang-westhills",
    name: "Westhills Stadium",
    category: "stadium",
    municipality: "Langford",
    region: "Capital",
    address: "1089 Langford Parkway",
    lat: 48.4498,
    lng: -123.4945,
    operator: "City of Langford",
    ownership: "municipal",
    amenities: [
      { type: "turf_field", indoor: false },
      { type: "running_track", indoor: false },
      { type: "bleachers", indoor: false },
    ],
  },

  // Sidney
  {
    id: "sid-panorama",
    name: "Panorama Recreation Centre",
    category: "community_center",
    municipality: "North Saanich",
    region: "Capital",
    address: "1885 Forest Park Drive",
    lat: 48.6516,
    lng: -123.4224,
    operator: "District of North Saanich",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "ice_sheet", indoor: true, count: 2 },
      { type: "curling_sheet", indoor: true, count: 6 },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "climbing_wall", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },

  // Sooke
  {
    id: "sooke-seaparc",
    name: "SEAPARC Leisure Complex",
    category: "community_center",
    municipality: "Sooke",
    region: "Capital",
    address: "2168 Phillips Road",
    lat: 48.3766,
    lng: -123.7145,
    operator: "Sooke Region",
    ownership: "regional",
    amenities: [
      { type: "pool", indoor: true },
      { type: "ice_sheet", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },

  // ============================================
  // OKANAGAN REGION
  // ============================================

  // Kelowna
  {
    id: "kel-parkinson",
    name: "Parkinson Recreation Centre",
    category: "community_center",
    municipality: "Kelowna",
    region: "Central Okanagan",
    address: "1800 Parkinson Way",
    lat: 49.8727,
    lng: -119.4970,
    operator: "City of Kelowna",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "ice_sheet", indoor: true, count: 2 },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "fitness_studio", indoor: true },
      { type: "meeting_room", indoor: true },
      { type: "childcare", indoor: true },
    ],
  },
  {
    id: "kel-hcp",
    name: "H2O Adventure + Fitness Centre",
    category: "aquatic_center",
    municipality: "Kelowna",
    region: "Central Okanagan",
    address: "4075 Gordon Drive",
    lat: 49.8461,
    lng: -119.4735,
    operator: "City of Kelowna",
    ownership: "municipal",
    year_opened: 2007,
    amenities: [
      { type: "pool", indoor: true, name: "Wave Pool" },
      { type: "pool", indoor: true, name: "Lazy River" },
      { type: "pool", indoor: true, name: "Lane Pool" },
      { type: "hot_tub", indoor: true },
      { type: "sauna", indoor: true },
      { type: "steam_room", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "fitness_studio", indoor: true },
      { type: "climbing_wall", indoor: true },
    ],
  },
  {
    id: "kel-prospera",
    name: "Prospera Place",
    category: "stadium",
    municipality: "Kelowna",
    region: "Central Okanagan",
    address: "1223 Water Street",
    lat: 49.8870,
    lng: -119.4867,
    operator: "City of Kelowna",
    ownership: "municipal",
    year_opened: 1999,
    amenities: [
      { type: "ice_sheet", indoor: true, name: "NHL-size Rink" },
      { type: "bleachers", indoor: true, count: 6886 },
      { type: "lounge", indoor: true },
      { type: "cafe", indoor: true },
    ],
  },
  {
    id: "kel-capital-news",
    name: "Capital News Centre",
    category: "sports_complex",
    municipality: "Kelowna",
    region: "Central Okanagan",
    address: "4105 Gordon Drive",
    lat: 49.8475,
    lng: -119.4728,
    operator: "City of Kelowna",
    ownership: "municipal",
    amenities: [
      { type: "ice_sheet", indoor: true, count: 4 },
      { type: "turf_field", indoor: true },
      { type: "pro_shop", indoor: true },
      { type: "cafe", indoor: true },
    ],
  },

  // Penticton
  {
    id: "pen-community",
    name: "Penticton Community Centre",
    category: "community_center",
    municipality: "Penticton",
    region: "Okanagan-Similkameen",
    address: "325 Power Street",
    lat: 49.4957,
    lng: -119.5888,
    operator: "City of Penticton",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },
  {
    id: "pen-memorial",
    name: "Memorial Arena",
    category: "arena",
    municipality: "Penticton",
    region: "Okanagan-Similkameen",
    address: "100 Main Street",
    lat: 49.4930,
    lng: -119.5857,
    operator: "City of Penticton",
    ownership: "municipal",
    amenities: [
      { type: "ice_sheet", indoor: true },
      { type: "bleachers", indoor: true },
    ],
  },
  {
    id: "pen-south-okanagan",
    name: "South Okanagan Events Centre",
    category: "stadium",
    municipality: "Penticton",
    region: "Okanagan-Similkameen",
    address: "853 Eckhardt Avenue West",
    lat: 49.4846,
    lng: -119.6002,
    operator: "City of Penticton",
    ownership: "municipal",
    year_opened: 2008,
    amenities: [
      { type: "ice_sheet", indoor: true },
      { type: "bleachers", indoor: true, count: 5000 },
      { type: "lounge", indoor: true },
    ],
  },

  // Vernon
  {
    id: "ver-rec-centre",
    name: "Vernon Recreation Complex",
    category: "community_center",
    municipality: "Vernon",
    region: "North Okanagan",
    address: "3310 37th Avenue",
    lat: 50.2595,
    lng: -119.2758,
    operator: "City of Vernon",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },
  {
    id: "ver-kal-tire",
    name: "Kal Tire Place",
    category: "arena",
    municipality: "Vernon",
    region: "North Okanagan",
    address: "3445 43rd Avenue",
    lat: 50.2667,
    lng: -119.2669,
    operator: "City of Vernon",
    ownership: "municipal",
    amenities: [
      { type: "ice_sheet", indoor: true, count: 2 },
      { type: "bleachers", indoor: true },
      { type: "pro_shop", indoor: true },
    ],
  },

  // West Kelowna
  {
    id: "wkel-johnson-bentley",
    name: "Johnson Bentley Memorial Aquatic Centre",
    category: "aquatic_center",
    municipality: "West Kelowna",
    region: "Central Okanagan",
    address: "3737 Old Okanagan Highway",
    lat: 49.8656,
    lng: -119.5892,
    operator: "City of West Kelowna",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "fitness_studio", indoor: true },
    ],
  },
  {
    id: "wkel-royal-lepage",
    name: "Royal LePage Place",
    category: "arena",
    municipality: "West Kelowna",
    region: "Central Okanagan",
    address: "3003 Main Street",
    lat: 49.8609,
    lng: -119.5809,
    operator: "City of West Kelowna",
    ownership: "municipal",
    amenities: [
      { type: "ice_sheet", indoor: true, count: 2 },
      { type: "gymnasium", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },

  // ============================================
  // KOOTENAY REGION
  // ============================================

  // Nelson
  {
    id: "nel-civic-arena",
    name: "Nelson Civic Arena",
    category: "arena",
    municipality: "Nelson",
    region: "Central Kootenay",
    address: "502 Vernon Street",
    lat: 49.4943,
    lng: -117.2907,
    operator: "City of Nelson",
    ownership: "municipal",
    amenities: [
      { type: "ice_sheet", indoor: true },
      { type: "bleachers", indoor: true },
    ],
  },
  {
    id: "nel-rec-centre",
    name: "Nelson & District Recreation Complex",
    category: "community_center",
    municipality: "Nelson",
    region: "Central Kootenay",
    address: "801 Lakeside Drive",
    lat: 49.4982,
    lng: -117.2987,
    operator: "City of Nelson",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },

  // Cranbrook
  {
    id: "cran-aquatic",
    name: "Cranbrook Aquatic Centre",
    category: "aquatic_center",
    municipality: "Cranbrook",
    region: "East Kootenay",
    address: "1777 2nd Street North",
    lat: 49.5155,
    lng: -115.7682,
    operator: "City of Cranbrook",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "sauna", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "fitness_studio", indoor: true },
    ],
  },
  {
    id: "cran-rec-plex",
    name: "Cranbrook RecPlex",
    category: "arena",
    municipality: "Cranbrook",
    region: "East Kootenay",
    address: "1777 2nd Street North",
    lat: 49.5150,
    lng: -115.7688,
    operator: "City of Cranbrook",
    ownership: "municipal",
    amenities: [
      { type: "ice_sheet", indoor: true, count: 2 },
      { type: "gymnasium", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },

  // Castlegar
  {
    id: "cast-complex",
    name: "Castlegar & District Recreation Complex",
    category: "community_center",
    municipality: "Castlegar",
    region: "Central Kootenay",
    address: "2101 6th Avenue",
    lat: 49.3268,
    lng: -117.6666,
    operator: "City of Castlegar",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "ice_sheet", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },

  // Trail
  {
    id: "trail-leisure",
    name: "Trail Memorial Centre",
    category: "community_center",
    municipality: "Trail",
    region: "Kootenay Boundary",
    address: "1051 Victoria Street",
    lat: 49.0979,
    lng: -117.7073,
    operator: "City of Trail",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "ice_sheet", indoor: true, count: 2 },
      { type: "curling_sheet", indoor: true, count: 6 },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
    ],
  },

  // Fernie
  {
    id: "fern-aquatic",
    name: "Fernie Aquatic Centre",
    category: "aquatic_center",
    municipality: "Fernie",
    region: "East Kootenay",
    address: "101 1st Avenue",
    lat: 49.5046,
    lng: -115.0632,
    operator: "City of Fernie",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "weight_room", indoor: true },
    ],
  },
  {
    id: "fern-arena",
    name: "Fernie Memorial Arena",
    category: "arena",
    municipality: "Fernie",
    region: "East Kootenay",
    address: "431 4th Avenue",
    lat: 49.5049,
    lng: -115.0678,
    operator: "City of Fernie",
    ownership: "municipal",
    amenities: [
      { type: "ice_sheet", indoor: true },
      { type: "bleachers", indoor: true },
    ],
  },

  // Golden
  {
    id: "gold-rec-centre",
    name: "Golden & District Recreation Centre",
    category: "community_center",
    municipality: "Golden",
    region: "Columbia-Shuswap",
    address: "1310 11th Avenue South",
    lat: 51.2962,
    lng: -116.9614,
    operator: "Town of Golden",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "ice_sheet", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },

  // ============================================
  // THOMPSON-OKANAGAN
  // ============================================

  // Kamloops
  {
    id: "kam-tournament",
    name: "Tournament Capital Centre",
    category: "sports_complex",
    municipality: "Kamloops",
    region: "Thompson-Nicola",
    address: "910 McGill Road",
    lat: 50.6706,
    lng: -120.3474,
    operator: "City of Kamloops",
    ownership: "municipal",
    year_opened: 1993,
    amenities: [
      { type: "pool", indoor: true, name: "50m Pool" },
      { type: "pool", indoor: true, name: "Leisure Pool" },
      { type: "hot_tub", indoor: true },
      { type: "sauna", indoor: true },
      { type: "ice_sheet", indoor: true, count: 2 },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "fitness_studio", indoor: true },
      { type: "running_track", indoor: true },
      { type: "turf_field", indoor: true },
      { type: "climbing_wall", indoor: true },
    ],
  },
  {
    id: "kam-sandman",
    name: "Sandman Centre",
    category: "stadium",
    municipality: "Kamloops",
    region: "Thompson-Nicola",
    address: "300 Lorne Street",
    lat: 50.6767,
    lng: -120.3280,
    operator: "City of Kamloops",
    ownership: "municipal",
    year_opened: 1966,
    amenities: [
      { type: "ice_sheet", indoor: true },
      { type: "bleachers", indoor: true, count: 5464 },
      { type: "lounge", indoor: true },
    ],
  },
  {
    id: "kam-mcarthur",
    name: "McArthur Island Sports & Events Centre",
    category: "sports_complex",
    municipality: "Kamloops",
    region: "Thompson-Nicola",
    address: "1655 Island Parkway",
    lat: 50.6738,
    lng: -120.3572,
    operator: "City of Kamloops",
    ownership: "municipal",
    amenities: [
      { type: "ice_sheet", indoor: true, count: 2 },
      { type: "curling_sheet", indoor: true, count: 8 },
      { type: "turf_field", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },

  // Salmon Arm
  {
    id: "sal-rec",
    name: "Salmon Arm Recreation Centre",
    category: "community_center",
    municipality: "Salmon Arm",
    region: "Columbia-Shuswap",
    address: "2800 12th Street NE",
    lat: 50.7017,
    lng: -119.2594,
    operator: "City of Salmon Arm",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "ice_sheet", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },

  // Revelstoke
  {
    id: "rev-aquatic",
    name: "Revelstoke Aquatic Centre",
    category: "aquatic_center",
    municipality: "Revelstoke",
    region: "Columbia-Shuswap",
    address: "600 Campbell Avenue",
    lat: 50.9996,
    lng: -118.1984,
    operator: "City of Revelstoke",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "sauna", indoor: true },
      { type: "weight_room", indoor: true },
    ],
  },
  {
    id: "rev-forum",
    name: "Revelstoke Forum",
    category: "arena",
    municipality: "Revelstoke",
    region: "Columbia-Shuswap",
    address: "600 Campbell Avenue",
    lat: 50.9993,
    lng: -118.1979,
    operator: "City of Revelstoke",
    ownership: "municipal",
    amenities: [
      { type: "ice_sheet", indoor: true },
      { type: "curling_sheet", indoor: true, count: 4 },
      { type: "bleachers", indoor: true },
    ],
  },

  // Merritt
  {
    id: "mer-aquatic",
    name: "Merritt Aquatic & Fitness Centre",
    category: "aquatic_center",
    municipality: "Merritt",
    region: "Thompson-Nicola",
    address: "1250 Voght Street",
    lat: 50.1127,
    lng: -120.7888,
    operator: "City of Merritt",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "weight_room", indoor: true },
    ],
  },
  {
    id: "mer-civic",
    name: "Merritt Civic Centre",
    category: "arena",
    municipality: "Merritt",
    region: "Thompson-Nicola",
    address: "1950 Mamette Avenue",
    lat: 50.1102,
    lng: -120.7918,
    operator: "City of Merritt",
    ownership: "municipal",
    amenities: [
      { type: "ice_sheet", indoor: true },
      { type: "curling_sheet", indoor: true, count: 4 },
    ],
  },

  // ============================================
  // NORTH COAST / PRINCE RUPERT
  // ============================================

  // Prince Rupert
  {
    id: "pr-civic",
    name: "Prince Rupert Civic Centre",
    category: "community_center",
    municipality: "Prince Rupert",
    region: "North Coast",
    address: "1000 McBride Street",
    lat: 54.3145,
    lng: -130.3215,
    operator: "City of Prince Rupert",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "ice_sheet", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },

  // Terrace
  {
    id: "ter-aquatic",
    name: "Terrace Aquatic Centre",
    category: "aquatic_center",
    municipality: "Terrace",
    region: "Kitimat-Stikine",
    address: "3320 Kalum Street",
    lat: 54.5165,
    lng: -128.6031,
    operator: "City of Terrace",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "sauna", indoor: true },
      { type: "weight_room", indoor: true },
    ],
  },
  {
    id: "ter-arena",
    name: "Terrace Arena",
    category: "arena",
    municipality: "Terrace",
    region: "Kitimat-Stikine",
    address: "3320 Kalum Street",
    lat: 54.5162,
    lng: -128.6027,
    operator: "City of Terrace",
    ownership: "municipal",
    amenities: [
      { type: "ice_sheet", indoor: true },
      { type: "bleachers", indoor: true },
    ],
  },

  // Kitimat
  {
    id: "kit-aquatic",
    name: "Kitimat Aquatic Centre",
    category: "aquatic_center",
    municipality: "Kitimat",
    region: "Kitimat-Stikine",
    address: "424 City Centre",
    lat: 54.0524,
    lng: -128.6537,
    operator: "District of Kitimat",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "weight_room", indoor: true },
    ],
  },
  {
    id: "kit-tamitik",
    name: "Tamitik Arena",
    category: "arena",
    municipality: "Kitimat",
    region: "Kitimat-Stikine",
    address: "545 Mountainview Square",
    lat: 54.0532,
    lng: -128.6524,
    operator: "District of Kitimat",
    ownership: "municipal",
    amenities: [
      { type: "ice_sheet", indoor: true },
      { type: "curling_sheet", indoor: true, count: 6 },
      { type: "bleachers", indoor: true },
    ],
  },

  // ============================================
  // PRINCE GEORGE / NORTHERN BC
  // ============================================

  // Prince George
  {
    id: "pg-four-seasons",
    name: "Four Seasons Leisure Pool",
    category: "aquatic_center",
    municipality: "Prince George",
    region: "Fraser-Fort George",
    address: "700 Dominion Street",
    lat: 53.9125,
    lng: -122.7495,
    operator: "City of Prince George",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "pool", indoor: true, name: "Leisure Pool" },
      { type: "hot_tub", indoor: true },
      { type: "sauna", indoor: true },
      { type: "steam_room", indoor: true },
    ],
  },
  {
    id: "pg-cn-centre",
    name: "CN Centre",
    category: "stadium",
    municipality: "Prince George",
    region: "Fraser-Fort George",
    address: "2187 Ospika Boulevard",
    lat: 53.9271,
    lng: -122.8053,
    operator: "City of Prince George",
    ownership: "municipal",
    year_opened: 1995,
    amenities: [
      { type: "ice_sheet", indoor: true },
      { type: "bleachers", indoor: true, count: 5995 },
      { type: "lounge", indoor: true },
    ],
  },
  {
    id: "pg-kin-centres",
    name: "Kin Centres",
    category: "sports_complex",
    municipality: "Prince George",
    region: "Fraser-Fort George",
    address: "1555 5th Avenue",
    lat: 53.9088,
    lng: -122.7681,
    operator: "City of Prince George",
    ownership: "municipal",
    amenities: [
      { type: "ice_sheet", indoor: true, count: 3 },
      { type: "curling_sheet", indoor: true, count: 8 },
      { type: "gymnasium", indoor: true },
    ],
  },
  {
    id: "pg-aquatic",
    name: "Prince George Aquatic Centre",
    category: "aquatic_center",
    municipality: "Prince George",
    region: "Fraser-Fort George",
    address: "1770 George Paul Lane",
    lat: 53.9257,
    lng: -122.8029,
    operator: "City of Prince George",
    ownership: "municipal",
    year_opened: 2017,
    amenities: [
      { type: "pool", indoor: true, name: "50m Competition Pool" },
      { type: "pool", indoor: true, name: "Leisure Pool" },
      { type: "hot_tub", indoor: true },
      { type: "sauna", indoor: true },
      { type: "steam_room", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "fitness_studio", indoor: true },
    ],
  },

  // Fort St. John
  {
    id: "fsj-pomeroy",
    name: "Pomeroy Sport Centre",
    category: "sports_complex",
    municipality: "Fort St. John",
    region: "Peace River",
    address: "9324 96th Street",
    lat: 56.2445,
    lng: -120.8485,
    operator: "City of Fort St. John",
    ownership: "municipal",
    year_opened: 2013,
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "ice_sheet", indoor: true, count: 2 },
      { type: "curling_sheet", indoor: true, count: 8 },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "running_track", indoor: true },
      { type: "climbing_wall", indoor: true },
    ],
  },
  {
    id: "fsj-encana",
    name: "Encana Events Centre",
    category: "stadium",
    municipality: "Fort St. John",
    region: "Peace River",
    address: "9303 100th Street",
    lat: 56.2448,
    lng: -120.8432,
    operator: "City of Fort St. John",
    ownership: "municipal",
    year_opened: 2008,
    amenities: [
      { type: "ice_sheet", indoor: true },
      { type: "bleachers", indoor: true, count: 5500 },
      { type: "lounge", indoor: true },
    ],
  },

  // Dawson Creek
  {
    id: "dc-memorial",
    name: "Memorial Arena",
    category: "arena",
    municipality: "Dawson Creek",
    region: "Peace River",
    address: "10105 12A Street",
    lat: 55.7598,
    lng: -120.2377,
    operator: "City of Dawson Creek",
    ownership: "municipal",
    amenities: [
      { type: "ice_sheet", indoor: true },
      { type: "curling_sheet", indoor: true, count: 4 },
      { type: "bleachers", indoor: true },
    ],
  },
  {
    id: "dc-kenn-borek",
    name: "Kenn Borek Aquatic Centre",
    category: "aquatic_center",
    municipality: "Dawson Creek",
    region: "Peace River",
    address: "10012 13th Street",
    lat: 55.7615,
    lng: -120.2385,
    operator: "City of Dawson Creek",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "weight_room", indoor: true },
    ],
  },

  // Fort Nelson
  {
    id: "fn-rec",
    name: "Fort Nelson Recreation Centre",
    category: "community_center",
    municipality: "Fort Nelson",
    region: "Northern Rockies",
    address: "5500 Mountainview Drive",
    lat: 58.8059,
    lng: -122.6978,
    operator: "Northern Rockies Regional Municipality",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "ice_sheet", indoor: true },
      { type: "curling_sheet", indoor: true, count: 4 },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
    ],
  },

  // Quesnel
  {
    id: "ques-rec",
    name: "Quesnel & District Recreation Centre",
    category: "community_center",
    municipality: "Quesnel",
    region: "Cariboo",
    address: "500 North Star Road",
    lat: 52.9783,
    lng: -122.4974,
    operator: "City of Quesnel",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "ice_sheet", indoor: true, count: 2 },
      { type: "curling_sheet", indoor: true, count: 6 },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
    ],
  },

  // Williams Lake
  {
    id: "wl-rec",
    name: "Williams Lake Recreation Complex",
    category: "community_center",
    municipality: "Williams Lake",
    region: "Cariboo",
    address: "777 Proctor Street",
    lat: 52.1293,
    lng: -122.1461,
    operator: "City of Williams Lake",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },
  {
    id: "wl-cariboo",
    name: "Cariboo Memorial Recreation Complex",
    category: "arena",
    municipality: "Williams Lake",
    region: "Cariboo",
    address: "470 Proctor Street",
    lat: 52.1288,
    lng: -122.1454,
    operator: "City of Williams Lake",
    ownership: "municipal",
    amenities: [
      { type: "ice_sheet", indoor: true },
      { type: "curling_sheet", indoor: true, count: 6 },
      { type: "bleachers", indoor: true },
    ],
  },

  // ============================================
  // VANCOUVER ISLAND (BEYOND CAPITAL)
  // ============================================

  // Nanaimo
  {
    id: "nan-nic",
    name: "Nanaimo Ice Centre",
    category: "arena",
    municipality: "Nanaimo",
    region: "Nanaimo",
    address: "2300 Bowen Road",
    lat: 49.1601,
    lng: -123.9626,
    operator: "City of Nanaimo",
    ownership: "municipal",
    amenities: [
      { type: "ice_sheet", indoor: true, count: 2 },
      { type: "pro_shop", indoor: true },
    ],
  },
  {
    id: "nan-beban",
    name: "Beban Park Recreation Centre",
    category: "community_center",
    municipality: "Nanaimo",
    region: "Nanaimo",
    address: "2300 Bowen Road",
    lat: 49.1604,
    lng: -123.9620,
    operator: "City of Nanaimo",
    ownership: "municipal",
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "fitness_studio", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },
  {
    id: "nan-nanaimo-aquatic",
    name: "Nanaimo Aquatic Centre",
    category: "aquatic_center",
    municipality: "Nanaimo",
    region: "Nanaimo",
    address: "741 Third Street",
    lat: 49.1671,
    lng: -123.9380,
    operator: "City of Nanaimo",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "sauna", indoor: true },
      { type: "steam_room", indoor: true },
      { type: "weight_room", indoor: true },
    ],
  },

  // Courtenay/Comox Valley
  {
    id: "cour-lewis",
    name: "Lewis Centre",
    category: "community_center",
    municipality: "Courtenay",
    region: "Comox Valley",
    address: "3300 Courtenay Street",
    lat: 49.6900,
    lng: -124.9954,
    operator: "City of Courtenay",
    ownership: "municipal",
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "fitness_studio", indoor: true },
      { type: "meeting_room", indoor: true },
      { type: "seniors_lounge", indoor: true },
    ],
  },
  {
    id: "cour-sports-centre",
    name: "Comox Valley Sports Centre",
    category: "sports_complex",
    municipality: "Courtenay",
    region: "Comox Valley",
    address: "3001 Vanier Drive",
    lat: 49.6885,
    lng: -124.9987,
    operator: "Comox Valley Regional District",
    ownership: "regional",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "ice_sheet", indoor: true, count: 2 },
      { type: "curling_sheet", indoor: true, count: 6 },
      { type: "gymnasium", indoor: true },
      { type: "weight_room", indoor: true },
    ],
  },

  // Campbell River
  {
    id: "cr-sportsplex",
    name: "Sportsplex",
    category: "sports_complex",
    municipality: "Campbell River",
    region: "Strathcona",
    address: "1800 South Alder Street",
    lat: 50.0113,
    lng: -125.2499,
    operator: "City of Campbell River",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "ice_sheet", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },

  // Port Alberni
  {
    id: "pa-echo",
    name: "Echo Aquatic & Fitness Centre",
    category: "aquatic_center",
    municipality: "Port Alberni",
    region: "Alberni-Clayoquot",
    address: "4255 Wallace Street",
    lat: 49.2413,
    lng: -124.8104,
    operator: "City of Port Alberni",
    ownership: "municipal",
    year_opened: 2016,
    amenities: [
      { type: "pool", indoor: true },
      { type: "pool", indoor: true, name: "Leisure Pool" },
      { type: "hot_tub", indoor: true },
      { type: "sauna", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "fitness_studio", indoor: true },
    ],
  },
  {
    id: "pa-multiplex",
    name: "Alberni Valley Multiplex",
    category: "arena",
    municipality: "Port Alberni",
    region: "Alberni-Clayoquot",
    address: "3737 Roger Street",
    lat: 49.2465,
    lng: -124.8043,
    operator: "City of Port Alberni",
    ownership: "municipal",
    amenities: [
      { type: "ice_sheet", indoor: true, count: 2 },
      { type: "curling_sheet", indoor: true, count: 6 },
      { type: "meeting_room", indoor: true },
    ],
  },

  // Parksville/Qualicum
  {
    id: "parks-ravensong",
    name: "Ravensong Aquatic Centre",
    category: "aquatic_center",
    municipality: "Qualicum Beach",
    region: "Nanaimo",
    address: "421 Primrose Street",
    lat: 49.3466,
    lng: -124.4366,
    operator: "Town of Qualicum Beach",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "fitness_studio", indoor: true },
    ],
  },

  // Duncan
  {
    id: "dun-aquatic",
    name: "Cowichan Aquatic Centre",
    category: "aquatic_center",
    municipality: "Duncan",
    region: "Cowichan Valley",
    address: "2760 James Street",
    lat: 48.7771,
    lng: -123.7128,
    operator: "CVRD",
    ownership: "regional",
    amenities: [
      { type: "pool", indoor: true },
      { type: "pool", indoor: true, name: "25m Lap Pool" },
      { type: "hot_tub", indoor: true },
      { type: "sauna", indoor: true },
      { type: "weight_room", indoor: true },
    ],
  },
  {
    id: "dun-cowichan",
    name: "Cowichan Community Centre",
    category: "arena",
    municipality: "Duncan",
    region: "Cowichan Valley",
    address: "2687 James Street",
    lat: 48.7763,
    lng: -123.7125,
    operator: "CVRD",
    ownership: "regional",
    amenities: [
      { type: "ice_sheet", indoor: true },
      { type: "curling_sheet", indoor: true, count: 6 },
      { type: "gymnasium", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },

  // ============================================
  // SUNSHINE COAST / SEA-TO-SKY
  // ============================================

  // Squamish
  {
    id: "sq-brennan",
    name: "Brennan Park Recreation Centre",
    category: "community_center",
    municipality: "Squamish",
    region: "Squamish-Lillooet",
    address: "1009 Centennial Way",
    lat: 49.7066,
    lng: -123.1525,
    operator: "District of Squamish",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "ice_sheet", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },

  // Whistler
  {
    id: "whis-meadow",
    name: "Meadow Park Sports Centre",
    category: "sports_complex",
    municipality: "Whistler",
    region: "Squamish-Lillooet",
    address: "8107 Camino Drive",
    lat: 50.1312,
    lng: -122.9632,
    operator: "Resort Municipality of Whistler",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "sauna", indoor: true },
      { type: "ice_sheet", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "squash_court", indoor: true },
      { type: "tennis_court", indoor: true },
    ],
  },

  // Pemberton
  {
    id: "pem-cc",
    name: "Pemberton Community Centre",
    category: "community_center",
    municipality: "Pemberton",
    region: "Squamish-Lillooet",
    address: "7390 Cottonwood Street",
    lat: 50.3168,
    lng: -122.7973,
    operator: "Village of Pemberton",
    ownership: "municipal",
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "meeting_room", indoor: true },
      { type: "childcare", indoor: true },
    ],
  },

  // Sechelt
  {
    id: "sec-aquatic",
    name: "Sechelt Aquatic Centre",
    category: "aquatic_center",
    municipality: "Sechelt",
    region: "Sunshine Coast",
    address: "5500 Shorncliffe Avenue",
    lat: 49.4716,
    lng: -123.7549,
    operator: "District of Sechelt",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "fitness_studio", indoor: true },
    ],
  },
  {
    id: "sec-arena",
    name: "Sechelt Arena",
    category: "arena",
    municipality: "Sechelt",
    region: "Sunshine Coast",
    address: "5700 Cowrie Street",
    lat: 49.4758,
    lng: -123.7569,
    operator: "District of Sechelt",
    ownership: "municipal",
    amenities: [
      { type: "ice_sheet", indoor: true },
      { type: "bleachers", indoor: true },
    ],
  },

  // Gibsons
  {
    id: "gib-rec",
    name: "Gibsons & District Recreation Centre",
    category: "community_center",
    municipality: "Gibsons",
    region: "Sunshine Coast",
    address: "700 Park Road",
    lat: 49.4040,
    lng: -123.5049,
    operator: "Town of Gibsons",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
  },

  // Powell River
  {
    id: "pow-rec",
    name: "Powell River Recreation Complex",
    category: "community_center",
    municipality: "Powell River",
    region: "Powell River",
    address: "5001 Joyce Avenue",
    lat: 49.8356,
    lng: -124.5240,
    operator: "City of Powell River",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: true },
      { type: "hot_tub", indoor: true },
      { type: "ice_sheet", indoor: true },
      { type: "curling_sheet", indoor: true, count: 4 },
      { type: "weight_room", indoor: true },
      { type: "gymnasium", indoor: true },
    ],
  },

  // ============================================
  // SELECTED PLAYGROUNDS / SKATE PARKS (MAJOR)
  // ============================================

  {
    id: "van-andy-livingstone",
    name: "Andy Livingstone Park Playground",
    category: "playground",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    address: "89 Expo Boulevard",
    lat: 49.2787,
    lng: -123.1028,
    operator: "Vancouver Park Board",
    ownership: "municipal",
    amenities: [
      { type: "playground_equipment", indoor: false },
      { type: "spray_park", indoor: false, season: "summer" },
      { type: "washroom", indoor: true },
    ],
  },
  {
    id: "van-coopers",
    name: "Coopers' Park Playground",
    category: "playground",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    address: "1020 Marinaside Crescent",
    lat: 49.2719,
    lng: -123.1215,
    operator: "Vancouver Park Board",
    ownership: "municipal",
    amenities: [
      { type: "playground_equipment", indoor: false },
      { type: "washroom", indoor: true },
    ],
  },
  {
    id: "van-china-creek",
    name: "China Creek Skatepark",
    category: "skate_park",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    address: "1001 East Broadway",
    lat: 49.2630,
    lng: -123.0840,
    operator: "Vancouver Park Board",
    ownership: "municipal",
    amenities: [
      { type: "skate_park", indoor: false },
    ],
  },
  {
    id: "sur-bear-creek",
    name: "Bear Creek Park",
    category: "recreation_park",
    municipality: "Surrey",
    region: "Metro Vancouver",
    address: "13750 88 Avenue",
    lat: 49.1644,
    lng: -122.8519,
    operator: "City of Surrey",
    ownership: "municipal",
    amenities: [
      { type: "pool", indoor: false, season: "summer" },
      { type: "playground_equipment", indoor: false },
      { type: "spray_park", indoor: false, season: "summer" },
      { type: "baseball_diamond", indoor: false },
      { type: "soccer_field", indoor: false },
      { type: "tennis_court", indoor: false },
    ],
  },
  {
    id: "bby-swangard",
    name: "Swangard Stadium",
    category: "stadium",
    municipality: "Burnaby",
    region: "Metro Vancouver",
    address: "3883 Imperial Street",
    lat: 49.2253,
    lng: -122.9889,
    operator: "City of Burnaby",
    ownership: "municipal",
    year_opened: 1969,
    amenities: [
      { type: "turf_field", indoor: false },
      { type: "running_track", indoor: false },
      { type: "bleachers", indoor: false, count: 5288 },
    ],
  },
  {
    id: "kel-prospera-skate",
    name: "Kelowna Skateboard Park",
    category: "skate_park",
    municipality: "Kelowna",
    region: "Central Okanagan",
    address: "1801 Water Street",
    lat: 49.8868,
    lng: -119.4965,
    operator: "City of Kelowna",
    ownership: "municipal",
    amenities: [
      { type: "skate_park", indoor: false },
    ],
  },
  {
    id: "vic-topaz-skate",
    name: "Topaz Skatepark",
    category: "skate_park",
    municipality: "Victoria",
    region: "Capital",
    address: "610 Finlayson Street",
    lat: 48.4421,
    lng: -123.3720,
    operator: "City of Victoria",
    ownership: "municipal",
    amenities: [
      { type: "skate_park", indoor: false },
    ],
  },

  // ============================================
  // FIRST NATIONS COMMUNITY FACILITIES
  // ============================================
  {
    id: "huuayaht-gym",
    name: "Huu-ay-aht First Nation Gymnasium",
    category: "sports_complex",
    municipality: "Bamfield",
    region: "Alberni-Clayoquot",
    address: "Anacla Reserve",
    lat: 48.8417,
    lng: -125.1531,
    operator: "Huu-ay-aht First Nations",
    ownership: "non_profit",
    amenities: [
      { type: "gymnasium", indoor: true, notes: "Full-size basketball court" },
      { type: "basketball_court", indoor: true },
      { type: "volleyball_court", indoor: true },
      { type: "meeting_room", indoor: true, notes: "Community cc_events space" },
      { type: "community_kitchen", indoor: true },
    ],
    notes: "Primary community gathering space for Huu-ay-aht First Nations and Bamfield area",
  },
  {
    id: "tseshaht-rec",
    name: "Tseshaht First Nation Recreation Centre",
    category: "community_center",
    municipality: "Port Alberni",
    region: "Alberni-Clayoquot",
    address: "5091 Tsuma-as Drive",
    lat: 49.2258,
    lng: -124.8075,
    operator: "Tseshaht First Nation",
    ownership: "non_profit",
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "basketball_court", indoor: true },
      { type: "meeting_room", indoor: true },
      { type: "community_kitchen", indoor: true },
    ],
    notes: "Tseshaht First Nation community facility",
  },
  {
    id: "ahousaht-gym",
    name: "Ahousaht Community Gymnasium",
    category: "sports_complex",
    municipality: "Ahousaht",
    region: "Alberni-Clayoquot",
    lat: 49.2842,
    lng: -126.0650,
    operator: "Ahousaht First Nation",
    ownership: "non_profit",
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "basketball_court", indoor: true },
      { type: "volleyball_court", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
    notes: "Remote community - accessible by boat or floatplane only",
  },
  {
    id: "toquaht-gym",
    name: "Toquaht Nation Community Hall",
    category: "community_center",
    municipality: "Ucluelet",
    region: "Alberni-Clayoquot",
    address: "Macoah Reserve",
    lat: 48.9456,
    lng: -125.4908,
    operator: "Toquaht Nation",
    ownership: "non_profit",
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "meeting_room", indoor: true },
      { type: "community_kitchen", indoor: true },
    ],
    notes: "Toquaht Nation community facility",
  },
  {
    id: "uchucklesaht-hall",
    name: "Uchucklesaht Community Hall",
    category: "community_center",
    municipality: "Port Alberni",
    region: "Alberni-Clayoquot",
    lat: 49.0667,
    lng: -125.0000,
    operator: "Uchucklesaht Tribe",
    ownership: "non_profit",
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
    notes: "Kildonan area - Uchucklesaht Tribe community facility",
  },
  {
    id: "heiltsuk-gym",
    name: "Heiltsuk Athletic Centre",
    category: "sports_complex",
    municipality: "Bella Bella",
    region: "Central Coast",
    lat: 52.1619,
    lng: -128.1442,
    operator: "Heiltsuk Nation",
    ownership: "non_profit",
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "basketball_court", indoor: true },
      { type: "volleyball_court", indoor: true },
      { type: "weight_room", indoor: true },
    ],
    notes: "Primary recreation facility for Bella Bella community",
  },
  {
    id: "kitasoo-gym",
    name: "Kitasoo/Xai'xais Community Recreation",
    category: "sports_complex",
    municipality: "Klemtu",
    region: "Central Coast",
    lat: 52.5917,
    lng: -128.5194,
    operator: "Kitasoo/Xai'xais Nation",
    ownership: "non_profit",
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "basketball_court", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
    notes: "Remote community - accessible by boat or floatplane only",
  },
  {
    id: "nuxalk-gym",
    name: "Nuxalk Nation Community Gymnasium",
    category: "sports_complex",
    municipality: "Bella Coola",
    region: "Central Coast",
    address: "Four Mile Reserve",
    lat: 52.3708,
    lng: -126.7556,
    operator: "Nuxalk Nation",
    ownership: "non_profit",
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "basketball_court", indoor: true },
      { type: "volleyball_court", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
    notes: "Nuxalk Nation community facility",
  },
  {
    id: "namgis-big-house",
    name: "'Namgis Big House & Recreation",
    category: "community_center",
    municipality: "Alert Bay",
    region: "Mount Waddington",
    address: "Cormorant Island",
    lat: 50.5861,
    lng: -126.9306,
    operator: "'Namgis First Nation",
    ownership: "non_profit",
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "meeting_room", indoor: true },
      { type: "banquet_hall", indoor: true, notes: "Cultural cc_events and potlatches" },
    ],
    notes: "Traditional Big House and community recreation facility",
  },
  {
    id: "kwakiutl-rec",
    name: "Kwakiutl First Nation Recreation Centre",
    category: "community_center",
    municipality: "Port Hardy",
    region: "Mount Waddington",
    address: "Fort Rupert Reserve",
    lat: 50.6889,
    lng: -127.4167,
    operator: "Kwakiutl First Nation",
    ownership: "non_profit",
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "basketball_court", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
    notes: "Kwakiutl First Nation community facility",
  },
  {
    id: "musqueam-community-centre",
    name: "Musqueam Community Centre",
    category: "community_center",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    address: "6735 Salish Drive",
    lat: 49.2217,
    lng: -123.2008,
    operator: "Musqueam Indian Band",
    ownership: "non_profit",
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "basketball_court", indoor: true },
      { type: "fitness_studio", indoor: true },
      { type: "meeting_room", indoor: true },
      { type: "community_kitchen", indoor: true },
      { type: "youth_center", indoor: true },
    ],
    notes: "Musqueam First Nation community recreation and cultural facility",
  },
  {
    id: "squamish-rec",
    name: "Squamish Nation Recreation Centre",
    category: "sports_complex",
    municipality: "North Vancouver",
    region: "Metro Vancouver",
    address: "100 Capilano Road",
    lat: 49.3219,
    lng: -123.0914,
    operator: "Squamish Nation",
    ownership: "non_profit",
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "basketball_court", indoor: true },
      { type: "volleyball_court", indoor: true },
      { type: "fitness_studio", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "youth_center", indoor: true },
    ],
    notes: "Squamish Nation community facility - Capilano Reserve",
  },
  {
    id: "tsleil-waututh-rec",
    name: "Tsleil-Waututh Recreation Centre",
    category: "community_center",
    municipality: "North Vancouver",
    region: "Metro Vancouver",
    address: "3075 Takaya Drive",
    lat: 49.3047,
    lng: -122.9506,
    operator: "Tsleil-Waututh Nation",
    ownership: "non_profit",
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "basketball_court", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
    notes: "Tsleil-Waututh (Burrard Inlet) Nation community facility",
  },
  {
    id: "sto-lo-rec",
    name: "Stó:lō Recreation Centre",
    category: "sports_complex",
    municipality: "Chilliwack",
    region: "Fraser Valley",
    address: "7201 Vedder Road",
    lat: 49.1011,
    lng: -121.9333,
    operator: "Stó:lō Nation",
    ownership: "non_profit",
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "basketball_court", indoor: true },
      { type: "volleyball_court", indoor: true },
      { type: "meeting_room", indoor: true },
      { type: "baseball_diamond", indoor: false },
      { type: "soccer_field", indoor: false },
    ],
    notes: "Stó:lō Nation multi-use recreation facility",
  },
  {
    id: "osoyoos-band-rec",
    name: "Osoyoos Indian Band Recreation Centre",
    category: "community_center",
    municipality: "Oliver",
    region: "Okanagan-Similkameen",
    address: "1000 Senkulmen Way",
    lat: 49.1311,
    lng: -119.5489,
    operator: "Osoyoos Indian Band",
    ownership: "non_profit",
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "basketball_court", indoor: true },
      { type: "meeting_room", indoor: true },
      { type: "community_kitchen", indoor: true },
    ],
    notes: "Osoyoos Indian Band community facility - Nk'Mip",
  },
  {
    id: "westbank-rec",
    name: "Westbank First Nation Recreation Centre",
    category: "sports_complex",
    municipality: "West Kelowna",
    region: "Central Okanagan",
    address: "515 Highway 97 S",
    lat: 49.8528,
    lng: -119.5922,
    operator: "Westbank First Nation",
    ownership: "non_profit",
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "basketball_court", indoor: true },
      { type: "volleyball_court", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
    notes: "Westbank First Nation community recreation facility",
  },
  {
    id: "shuswap-band-rec",
    name: "Shuswap Band Recreation Centre",
    category: "community_center",
    municipality: "Invermere",
    region: "East Kootenay",
    address: "Shuswap Reserve",
    lat: 50.5069,
    lng: -116.0278,
    operator: "Shuswap Indian Band",
    ownership: "non_profit",
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "basketball_court", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
    notes: "Ktunaxa Nation - Shuswap Band community facility",
  },
  {
    id: "kamloops-indian-band-rec",
    name: "Tk'emlúps te Secwépemc Recreation Centre",
    category: "sports_complex",
    municipality: "Kamloops",
    region: "Thompson-Nicola",
    address: "200 Chief Alex Thomas Way",
    lat: 50.6844,
    lng: -120.3628,
    operator: "Tk'emlúps te Secwépemc",
    ownership: "non_profit",
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "basketball_court", indoor: true },
      { type: "volleyball_court", indoor: true },
      { type: "fitness_studio", indoor: true },
      { type: "weight_room", indoor: true },
      { type: "meeting_room", indoor: true },
      { type: "baseball_diamond", indoor: false },
    ],
    notes: "Tk'emlúps te Secwépemc (Kamloops Indian Band) community facility",
  },
  {
    id: "lheidli-tenneh-rec",
    name: "Lheidli T'enneh Recreation Centre",
    category: "community_center",
    municipality: "Prince George",
    region: "Fraser-Fort George",
    address: "1041 Whenun Road",
    lat: 53.8444,
    lng: -122.7322,
    operator: "Lheidli T'enneh First Nation",
    ownership: "non_profit",
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "basketball_court", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
    notes: "Lheidli T'enneh First Nation community facility",
  },
  {
    id: "gitxsan-rec",
    name: "Gitxsan Recreation Complex",
    category: "sports_complex",
    municipality: "Hazelton",
    region: "Kitimat-Stikine",
    lat: 55.2519,
    lng: -127.6608,
    operator: "Gitxsan Nation",
    ownership: "non_profit",
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "basketball_court", indoor: true },
      { type: "volleyball_court", indoor: true },
      { type: "ice_sheet", indoor: true },
    ],
    notes: "Gitxsan Nation multi-use recreation facility",
  },
  {
    id: "nisga-rec",
    name: "Nisga'a Recreation Centre",
    category: "sports_complex",
    municipality: "New Aiyansh",
    region: "Kitimat-Stikine",
    lat: 55.2500,
    lng: -129.1000,
    operator: "Nisga'a Lisims Government",
    ownership: "non_profit",
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "basketball_court", indoor: true },
      { type: "ice_sheet", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
    notes: "Nisga'a Nation community recreation facility",
  },
  {
    id: "haisla-rec",
    name: "Haisla Recreation Centre",
    category: "sports_complex",
    municipality: "Kitamaat Village",
    region: "Kitimat-Stikine",
    lat: 53.9833,
    lng: -128.6333,
    operator: "Haisla Nation",
    ownership: "non_profit",
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "basketball_court", indoor: true },
      { type: "volleyball_court", indoor: true },
      { type: "weight_room", indoor: true },
    ],
    notes: "Haisla Nation community facility",
  },
  {
    id: "tahltan-rec",
    name: "Tahltan Recreation Centre",
    category: "community_center",
    municipality: "Telegraph Creek",
    region: "Stikine",
    lat: 57.9047,
    lng: -131.1553,
    operator: "Tahltan Nation",
    ownership: "non_profit",
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "basketball_court", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
    notes: "Tahltan Nation community facility",
  },
  {
    id: "kaska-dena-rec",
    name: "Kaska Dena Recreation Centre",
    category: "community_center",
    municipality: "Lower Post",
    region: "Northern Rockies",
    lat: 59.9500,
    lng: -128.9000,
    operator: "Kaska Dena Council",
    ownership: "non_profit",
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "basketball_court", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
    notes: "Kaska Dena Nation community facility - Lower Post",
  },
  {
    id: "doig-river-rec",
    name: "Doig River First Nation Recreation",
    category: "community_center",
    municipality: "Rose Prairie",
    region: "Peace River",
    lat: 56.5361,
    lng: -121.1333,
    operator: "Doig River First Nation",
    ownership: "non_profit",
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "basketball_court", indoor: true },
      { type: "meeting_room", indoor: true },
    ],
    notes: "Doig River First Nation community facility",
  },
  {
    id: "blueberry-river-rec",
    name: "Blueberry River First Nations Recreation",
    category: "community_center",
    municipality: "Buick",
    region: "Peace River",
    lat: 57.0689,
    lng: -122.0350,
    operator: "Blueberry River First Nations",
    ownership: "non_profit",
    amenities: [
      { type: "gymnasium", indoor: true },
      { type: "basketball_court", indoor: true },
      { type: "meeting_room", indoor: true },
      { type: "baseball_diamond", indoor: false },
    ],
    notes: "Blueberry River First Nations community facility",
  },
];
