export interface MunicipalOffice {
  id: string;
  name: string;
  type: "city_hall" | "town_office" | "district_office" | "village_office" | "regional_district" | "first_nation_band_office" | "treaty_nation_office";
  municipality: string;
  region: string;
  address?: string;
  lat: number;
  lng: number;
  phone?: string;
  website?: string;
  notes?: string;
}

export const municipalOffices: MunicipalOffice[] = [
  // ============================================
  // METRO VANCOUVER - CITIES
  // ============================================
  {
    id: "vancouver-city-hall",
    name: "Vancouver City Hall",
    type: "city_hall",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    address: "453 West 12th Avenue",
    lat: 49.2606,
    lng: -123.1139,
    phone: "604-873-7000",
    website: "https://vancouver.ca",
    notes: "Courts at 222 Main St (Provincial) and 800 Smithe St (Supreme) - separate locations",
  },
  {
    id: "burnaby-city-hall",
    name: "Burnaby City Hall",
    type: "city_hall",
    municipality: "Burnaby",
    region: "Metro Vancouver",
    address: "4949 Canada Way",
    lat: 49.2488,
    lng: -123.0016,
    phone: "604-294-7944",
    website: "https://www.burnaby.ca",
  },
  {
    id: "surrey-city-hall",
    name: "Surrey City Hall",
    type: "city_hall",
    municipality: "Surrey",
    region: "Metro Vancouver",
    address: "13450 104 Avenue",
    lat: 49.1913,
    lng: -122.8490,
    phone: "604-591-4011",
    website: "https://www.surrey.ca",
    notes: "Courts at 14340 57 Avenue",
  },
  {
    id: "richmond-city-hall",
    name: "Richmond City Hall",
    type: "city_hall",
    municipality: "Richmond",
    region: "Metro Vancouver",
    address: "6911 No. 3 Road",
    lat: 49.1681,
    lng: -123.1364,
    phone: "604-276-4000",
    website: "https://www.richmond.ca",
    notes: "Courts at 7577 Elmbridge Way",
  },
  {
    id: "coquitlam-city-hall",
    name: "Coquitlam City Hall",
    type: "city_hall",
    municipality: "Coquitlam",
    region: "Metro Vancouver",
    address: "3000 Guildford Way",
    lat: 49.2838,
    lng: -122.7932,
    phone: "604-927-3000",
    website: "https://www.coquitlam.ca",
  },
  {
    id: "new-westminster-city-hall",
    name: "New Westminster City Hall",
    type: "city_hall",
    municipality: "New Westminster",
    region: "Metro Vancouver",
    address: "511 Royal Avenue",
    lat: 49.2057,
    lng: -122.9110,
    phone: "604-521-3711",
    website: "https://www.newwestcity.ca",
    notes: "Court nearby at 651 Carnarvon Street - separate building",
  },
  {
    id: "delta-municipal-hall",
    name: "Delta Municipal Hall",
    type: "district_office",
    municipality: "Delta",
    region: "Metro Vancouver",
    address: "4500 Clarence Taylor Crescent",
    lat: 49.0847,
    lng: -123.0589,
    phone: "604-946-4141",
    website: "https://www.delta.ca",
  },
  {
    id: "north-vancouver-city-hall",
    name: "North Vancouver City Hall",
    type: "city_hall",
    municipality: "North Vancouver",
    region: "Metro Vancouver",
    address: "141 West 14th Street",
    lat: 49.3194,
    lng: -123.0750,
    phone: "604-985-7761",
    website: "https://www.cnv.org",
    notes: "Court nearby at 200 East 23rd Street - separate building",
  },
  {
    id: "north-vancouver-district",
    name: "District of North Vancouver Municipal Hall",
    type: "district_office",
    municipality: "North Vancouver",
    region: "Metro Vancouver",
    address: "355 West Queens Road",
    lat: 49.3353,
    lng: -123.0703,
    phone: "604-990-2311",
    website: "https://www.dnv.org",
  },
  {
    id: "west-vancouver-municipal-hall",
    name: "West Vancouver Municipal Hall",
    type: "district_office",
    municipality: "West Vancouver",
    region: "Metro Vancouver",
    address: "750 17th Street",
    lat: 49.3272,
    lng: -123.1661,
    phone: "604-925-7000",
    website: "https://www.westvancouver.ca",
  },
  {
    id: "port-coquitlam-city-hall",
    name: "Port Coquitlam City Hall",
    type: "city_hall",
    municipality: "Port Coquitlam",
    region: "Metro Vancouver",
    address: "2580 Shaughnessy Street",
    lat: 49.2625,
    lng: -122.7814,
    phone: "604-927-5411",
    website: "https://www.portcoquitlam.ca",
    notes: "Provincial Court at separate location",
  },
  {
    id: "port-moody-city-hall",
    name: "Port Moody City Hall",
    type: "city_hall",
    municipality: "Port Moody",
    region: "Metro Vancouver",
    address: "100 Newport Drive",
    lat: 49.2847,
    lng: -122.8317,
    phone: "604-469-4500",
    website: "https://www.portmoody.ca",
  },
  {
    id: "langley-city-hall",
    name: "Langley City Hall",
    type: "city_hall",
    municipality: "Langley",
    region: "Metro Vancouver",
    address: "20399 Douglas Crescent",
    lat: 49.1042,
    lng: -122.6603,
    phone: "604-514-2800",
    website: "https://www.langleycity.ca",
  },
  {
    id: "langley-township-hall",
    name: "Township of Langley Civic Facility",
    type: "district_office",
    municipality: "Langley",
    region: "Metro Vancouver",
    address: "20338 65 Avenue",
    lat: 49.1025,
    lng: -122.6589,
    phone: "604-534-3211",
    website: "https://www.tol.ca",
  },
  {
    id: "maple-ridge-city-hall",
    name: "Maple Ridge City Hall",
    type: "city_hall",
    municipality: "Maple Ridge",
    region: "Metro Vancouver",
    address: "11995 Haney Place",
    lat: 49.2194,
    lng: -122.5981,
    phone: "604-463-5221",
    website: "https://www.mapleridge.ca",
  },
  {
    id: "pitt-meadows-city-hall",
    name: "Pitt Meadows City Hall",
    type: "city_hall",
    municipality: "Pitt Meadows",
    region: "Metro Vancouver",
    address: "12007 Harris Road",
    lat: 49.2214,
    lng: -122.6869,
    phone: "604-465-5454",
    website: "https://www.pittmeadows.ca",
  },
  {
    id: "white-rock-city-hall",
    name: "White Rock City Hall",
    type: "city_hall",
    municipality: "White Rock",
    region: "Metro Vancouver",
    address: "15322 Buena Vista Avenue",
    lat: 49.0253,
    lng: -122.8028,
    phone: "604-541-2100",
    website: "https://www.whiterockcity.ca",
  },
  {
    id: "bowen-island-municipal-hall",
    name: "Bowen Island Municipal Hall",
    type: "village_office",
    municipality: "Bowen Island",
    region: "Metro Vancouver",
    address: "981 Artisan Lane",
    lat: 49.3847,
    lng: -123.3361,
    phone: "604-947-4255",
    website: "https://www.bowenislandmunicipality.ca",
  },
  {
    id: "lions-bay-village-office",
    name: "Lions Bay Village Office",
    type: "village_office",
    municipality: "Lions Bay",
    region: "Metro Vancouver",
    address: "400 Centre Road",
    lat: 49.4561,
    lng: -123.2369,
    phone: "604-921-9333",
    website: "https://www.lionsbay.ca",
  },
  {
    id: "anmore-village-hall",
    name: "Anmore Village Hall",
    type: "village_office",
    municipality: "Anmore",
    region: "Metro Vancouver",
    address: "2697 Sunnyside Road",
    lat: 49.3136,
    lng: -122.8494,
    phone: "604-469-9877",
    website: "https://www.anmore.com",
  },
  {
    id: "belcarra-village-hall",
    name: "Belcarra Village Hall",
    type: "village_office",
    municipality: "Belcarra",
    region: "Metro Vancouver",
    address: "4084 Bedwell Bay Road",
    lat: 49.3114,
    lng: -122.9178,
    phone: "604-937-4100",
    website: "https://www.belcarra.ca",
  },

  // ============================================
  // FRASER VALLEY
  // ============================================
  {
    id: "abbotsford-city-hall",
    name: "Abbotsford City Hall",
    type: "city_hall",
    municipality: "Abbotsford",
    region: "Fraser Valley",
    address: "32315 South Fraser Way",
    lat: 49.0504,
    lng: -122.3045,
    phone: "604-853-2281",
    website: "https://www.abbotsford.ca",
    notes: "Courts nearby at 32203 South Fraser Way - separate building",
  },
  {
    id: "chilliwack-city-hall",
    name: "Chilliwack City Hall",
    type: "city_hall",
    municipality: "Chilliwack",
    region: "Fraser Valley",
    address: "8550 Young Road",
    lat: 49.1577,
    lng: -121.9509,
    phone: "604-792-9311",
    website: "https://www.chilliwack.com",
    notes: "Courts nearby at 46085 Yale Road - separate building",
  },
  {
    id: "mission-district-hall",
    name: "Mission District Municipal Hall",
    type: "district_office",
    municipality: "Mission",
    region: "Fraser Valley",
    address: "8645 Stave Lake Street",
    lat: 49.1336,
    lng: -122.3094,
    phone: "604-820-3700",
    website: "https://www.mission.ca",
  },
  {
    id: "hope-district-office",
    name: "District of Hope Municipal Hall",
    type: "district_office",
    municipality: "Hope",
    region: "Fraser Valley",
    address: "325 Wallace Street",
    lat: 49.3836,
    lng: -121.4436,
    phone: "604-869-5671",
    website: "https://www.hope.ca",
  },
  {
    id: "harrison-hot-springs-village",
    name: "Village of Harrison Hot Springs",
    type: "village_office",
    municipality: "Harrison Hot Springs",
    region: "Fraser Valley",
    address: "495 Hot Springs Road",
    lat: 49.3044,
    lng: -121.7853,
    phone: "604-796-2171",
    website: "https://www.harrisonhotsprings.ca",
  },
  {
    id: "kent-district-office",
    name: "District of Kent Municipal Hall",
    type: "district_office",
    municipality: "Agassiz",
    region: "Fraser Valley",
    address: "7170 Cheam Avenue",
    lat: 49.2386,
    lng: -121.7614,
    phone: "604-796-2235",
    website: "https://www.kentbc.ca",
  },

  // ============================================
  // CAPITAL REGIONAL DISTRICT (GREATER VICTORIA)
  // ============================================
  {
    id: "victoria-city-hall",
    name: "Victoria City Hall",
    type: "city_hall",
    municipality: "Victoria",
    region: "Capital",
    address: "1 Centennial Square",
    lat: 48.4284,
    lng: -123.3656,
    phone: "250-385-5711",
    website: "https://www.victoria.ca",
    notes: "Courts nearby at 850 Burdett Avenue - separate building",
  },
  {
    id: "saanich-municipal-hall",
    name: "Saanich Municipal Hall",
    type: "district_office",
    municipality: "Saanich",
    region: "Capital",
    address: "770 Vernon Avenue",
    lat: 48.4622,
    lng: -123.3842,
    phone: "250-475-1775",
    website: "https://www.saanich.ca",
  },
  {
    id: "oak-bay-municipal-hall",
    name: "Oak Bay Municipal Hall",
    type: "district_office",
    municipality: "Oak Bay",
    region: "Capital",
    address: "2167 Oak Bay Avenue",
    lat: 48.4269,
    lng: -123.3156,
    phone: "250-598-3311",
    website: "https://www.oakbay.ca",
  },
  {
    id: "esquimalt-municipal-hall",
    name: "Esquimalt Municipal Hall",
    type: "district_office",
    municipality: "Esquimalt",
    region: "Capital",
    address: "1229 Esquimalt Road",
    lat: 48.4328,
    lng: -123.4139,
    phone: "250-414-7100",
    website: "https://www.esquimalt.ca",
  },
  {
    id: "langford-city-hall",
    name: "Langford City Hall",
    type: "city_hall",
    municipality: "Langford",
    region: "Capital",
    address: "877 Goldstream Avenue",
    lat: 48.4494,
    lng: -123.4947,
    phone: "250-478-7882",
    website: "https://www.langford.ca",
    notes: "Provincial Court serves Western Communities - separate building",
  },
  {
    id: "colwood-city-hall",
    name: "Colwood City Hall",
    type: "city_hall",
    municipality: "Colwood",
    region: "Capital",
    address: "3300 Wishart Road",
    lat: 48.4236,
    lng: -123.4958,
    phone: "250-478-5999",
    website: "https://www.colwood.ca",
  },
  {
    id: "view-royal-town-hall",
    name: "View Royal Town Hall",
    type: "town_office",
    municipality: "View Royal",
    region: "Capital",
    address: "45 View Royal Avenue",
    lat: 48.4514,
    lng: -123.4339,
    phone: "250-479-6800",
    website: "https://www.viewroyal.ca",
  },
  {
    id: "metchosin-municipal-hall",
    name: "Metchosin Municipal Hall",
    type: "district_office",
    municipality: "Metchosin",
    region: "Capital",
    address: "4450 Happy Valley Road",
    lat: 48.3831,
    lng: -123.5361,
    phone: "250-474-3167",
    website: "https://www.metchosin.ca",
  },
  {
    id: "sooke-district-office",
    name: "District of Sooke Municipal Hall",
    type: "district_office",
    municipality: "Sooke",
    region: "Capital",
    address: "2205 Otter Point Road",
    lat: 48.3742,
    lng: -123.7253,
    phone: "250-642-1634",
    website: "https://www.sooke.ca",
  },
  {
    id: "highlands-municipal-hall",
    name: "District of Highlands Municipal Hall",
    type: "district_office",
    municipality: "Highlands",
    region: "Capital",
    address: "1980 Millstream Road",
    lat: 48.4869,
    lng: -123.5028,
    phone: "250-474-1773",
    website: "https://www.highlands.ca",
  },
  {
    id: "sidney-town-hall",
    name: "Sidney Town Hall",
    type: "town_office",
    municipality: "Sidney",
    region: "Capital",
    address: "2440 Sidney Avenue",
    lat: 48.6503,
    lng: -123.3983,
    phone: "250-656-1184",
    website: "https://www.sidney.ca",
    notes: "Provincial Court at separate location",
  },
  {
    id: "north-saanich-municipal-hall",
    name: "North Saanich Municipal Hall",
    type: "district_office",
    municipality: "North Saanich",
    region: "Capital",
    address: "1620 Mills Road",
    lat: 48.6153,
    lng: -123.4214,
    phone: "250-656-0781",
    website: "https://www.northsaanich.ca",
  },
  {
    id: "central-saanich-municipal-hall",
    name: "Central Saanich Municipal Hall",
    type: "district_office",
    municipality: "Central Saanich",
    region: "Capital",
    address: "1903 Mount Newton Cross Road",
    lat: 48.5539,
    lng: -123.3819,
    phone: "250-652-4444",
    website: "https://www.centralsaanich.ca",
  },
  {
    id: "salt-spring-island-admin",
    name: "Salt Spring Island CRD Office",
    type: "district_office",
    municipality: "Salt Spring Island",
    region: "Capital",
    address: "108-121 McPhillips Avenue",
    lat: 48.8544,
    lng: -123.5058,
    phone: "250-537-4448",
    website: "https://www.crd.bc.ca",
    notes: "Provincial Court (circuit) serves Salt Spring Island",
  },

  // ============================================
  // VANCOUVER ISLAND - CENTRAL
  // ============================================
  {
    id: "nanaimo-city-hall",
    name: "Nanaimo City Hall",
    type: "city_hall",
    municipality: "Nanaimo",
    region: "Nanaimo",
    address: "455 Wallace Street",
    lat: 49.1659,
    lng: -123.9364,
    phone: "250-754-4251",
    website: "https://www.nanaimo.ca",
    notes: "Courts nearby at 35 Front Street - separate building",
  },
  {
    id: "parksville-city-hall",
    name: "Parksville City Hall",
    type: "city_hall",
    municipality: "Parksville",
    region: "Nanaimo",
    address: "100 Jensen Avenue East",
    lat: 49.3150,
    lng: -124.3128,
    phone: "250-248-6144",
    website: "https://www.parksville.ca",
  },
  {
    id: "qualicum-beach-town-hall",
    name: "Qualicum Beach Town Hall",
    type: "town_office",
    municipality: "Qualicum Beach",
    region: "Nanaimo",
    address: "201 2nd Avenue",
    lat: 49.3494,
    lng: -124.4367,
    phone: "250-752-6921",
    website: "https://www.qualicumbeach.com",
  },
  {
    id: "ladysmith-town-hall",
    name: "Ladysmith Town Hall",
    type: "town_office",
    municipality: "Ladysmith",
    region: "Nanaimo",
    address: "410 Esplanade",
    lat: 48.9958,
    lng: -123.8178,
    phone: "250-245-6400",
    website: "https://www.ladysmith.ca",
  },
  {
    id: "lantzville-village-hall",
    name: "Lantzville District Hall",
    type: "district_office",
    municipality: "Lantzville",
    region: "Nanaimo",
    address: "7192 Lantzville Road",
    lat: 49.2492,
    lng: -124.0628,
    phone: "250-390-4006",
    website: "https://www.lantzville.ca",
  },

  // ============================================
  // VANCOUVER ISLAND - COWICHAN VALLEY
  // ============================================
  {
    id: "duncan-city-hall",
    name: "Duncan City Hall",
    type: "city_hall",
    municipality: "Duncan",
    region: "Cowichan Valley",
    address: "200 Craig Street",
    lat: 48.7839,
    lng: -123.7067,
    phone: "250-746-6126",
    website: "https://www.duncan.ca",
    notes: "Courts nearby at 238 Government Street - separate building",
  },
  {
    id: "north-cowichan-municipal-hall",
    name: "North Cowichan Municipal Hall",
    type: "district_office",
    municipality: "North Cowichan",
    region: "Cowichan Valley",
    address: "7030 Trans-Canada Highway",
    lat: 48.8069,
    lng: -123.7189,
    phone: "250-746-3100",
    website: "https://www.northcowichan.ca",
  },
  {
    id: "lake-cowichan-town-hall",
    name: "Lake Cowichan Town Hall",
    type: "town_office",
    municipality: "Lake Cowichan",
    region: "Cowichan Valley",
    address: "39 South Shore Road",
    lat: 48.8247,
    lng: -124.0536,
    phone: "250-749-6681",
    website: "https://www.lakecowichan.ca",
  },

  // ============================================
  // VANCOUVER ISLAND - ALBERNI-CLAYOQUOT
  // ============================================
  {
    id: "port-alberni-city-hall",
    name: "Port Alberni City Hall",
    type: "city_hall",
    municipality: "Port Alberni",
    region: "Alberni-Clayoquot",
    address: "4850 Argyle Street",
    lat: 49.2339,
    lng: -124.8053,
    phone: "250-723-2146",
    website: "https://www.portalberni.ca",
    notes: "Courts nearby at 2999 4th Avenue - separate building",
  },
  {
    id: "tofino-district-office",
    name: "District of Tofino Municipal Hall",
    type: "district_office",
    municipality: "Tofino",
    region: "Alberni-Clayoquot",
    address: "121 3rd Street",
    lat: 49.1530,
    lng: -125.9063,
    phone: "250-725-3229",
    website: "https://www.tofino.ca",
  },
  {
    id: "ucluelet-district-office",
    name: "District of Ucluelet Municipal Hall",
    type: "district_office",
    municipality: "Ucluelet",
    region: "Alberni-Clayoquot",
    address: "200 Main Street",
    lat: 48.9421,
    lng: -125.5461,
    phone: "250-726-7744",
    website: "https://www.ucluelet.ca",
  },

  // ============================================
  // VANCOUVER ISLAND - COMOX VALLEY
  // ============================================
  {
    id: "courtenay-city-hall",
    name: "Courtenay City Hall",
    type: "city_hall",
    municipality: "Courtenay",
    region: "Comox Valley",
    address: "830 Cliffe Avenue",
    lat: 49.6878,
    lng: -124.9942,
    phone: "250-334-4441",
    website: "https://www.courtenay.ca",
    notes: "Courts nearby at 420 Cumberland Road - separate building",
  },
  {
    id: "comox-town-hall",
    name: "Comox Town Hall",
    type: "town_office",
    municipality: "Comox",
    region: "Comox Valley",
    address: "1809 Beaufort Avenue",
    lat: 49.6736,
    lng: -124.9328,
    phone: "250-339-2202",
    website: "https://www.comox.ca",
  },
  {
    id: "cumberland-village-office",
    name: "Village of Cumberland",
    type: "village_office",
    municipality: "Cumberland",
    region: "Comox Valley",
    address: "2673 Dunsmuir Avenue",
    lat: 49.6194,
    lng: -125.0278,
    phone: "250-336-2291",
    website: "https://www.cumberland.ca",
  },

  // ============================================
  // VANCOUVER ISLAND - STRATHCONA / CAMPBELL RIVER
  // ============================================
  {
    id: "campbell-river-city-hall",
    name: "Campbell River City Hall",
    type: "city_hall",
    municipality: "Campbell River",
    region: "Strathcona",
    address: "301 St. Ann's Road",
    lat: 50.0189,
    lng: -125.2472,
    phone: "250-286-5700",
    website: "https://www.campbellriver.ca",
    notes: "Courts nearby at 500 13th Avenue - separate building",
  },
  {
    id: "gold-river-village-office",
    name: "Village of Gold River",
    type: "village_office",
    municipality: "Gold River",
    region: "Strathcona",
    address: "499 Muchalet Drive",
    lat: 49.7794,
    lng: -126.0478,
    phone: "250-283-2202",
    website: "https://www.goldriver.ca",
  },
  {
    id: "tahsis-village-office",
    name: "Village of Tahsis",
    type: "village_office",
    municipality: "Tahsis",
    region: "Strathcona",
    address: "977 South Maquinna Drive",
    lat: 49.9167,
    lng: -126.6667,
    phone: "250-934-6344",
    website: "https://www.villageoftahsis.com",
  },
  {
    id: "zeballos-village-office",
    name: "Village of Zeballos",
    type: "village_office",
    municipality: "Zeballos",
    region: "Strathcona",
    address: "157 Maquinna Avenue",
    lat: 49.9833,
    lng: -126.8500,
    phone: "250-761-4229",
    website: "https://www.zeballos.com",
  },
  {
    id: "sayward-village-office",
    name: "Village of Sayward",
    type: "village_office",
    municipality: "Sayward",
    region: "Strathcona",
    address: "601 Kelsey Way",
    lat: 50.3872,
    lng: -125.9592,
    phone: "250-282-5512",
    website: "https://www.sayward.ca",
  },

  // ============================================
  // VANCOUVER ISLAND - NORTH (MOUNT WADDINGTON)
  // ============================================
  {
    id: "port-hardy-district-office",
    name: "District of Port Hardy",
    type: "district_office",
    municipality: "Port Hardy",
    region: "Mount Waddington",
    address: "7360 Columbia Street",
    lat: 50.7186,
    lng: -127.4927,
    phone: "250-949-6665",
    website: "https://www.porthardy.ca",
    notes: "Provincial Court at separate location",
  },
  {
    id: "port-mcneill-town-hall",
    name: "Town of Port McNeill",
    type: "town_office",
    municipality: "Port McNeill",
    region: "Mount Waddington",
    address: "2035 McNeill Road",
    lat: 50.5869,
    lng: -127.0856,
    phone: "250-956-3111",
    website: "https://www.portmcneill.net",
  },
  {
    id: "port-alice-village-office",
    name: "Village of Port Alice",
    type: "village_office",
    municipality: "Port Alice",
    region: "Mount Waddington",
    address: "1061 Marine Drive",
    lat: 50.3908,
    lng: -127.4564,
    phone: "250-284-3391",
    website: "https://www.portalice.ca",
  },
  {
    id: "alert-bay-village-office",
    name: "Village of Alert Bay",
    type: "village_office",
    municipality: "Alert Bay",
    region: "Mount Waddington",
    address: "118 Fir Street",
    lat: 50.5864,
    lng: -126.9297,
    phone: "250-974-5213",
    website: "https://www.alertbay.ca",
  },

  // ============================================
  // SUNSHINE COAST / POWELL RIVER
  // ============================================
  {
    id: "sechelt-district-office",
    name: "District of Sechelt",
    type: "district_office",
    municipality: "Sechelt",
    region: "Sunshine Coast",
    address: "5797 Cowrie Street",
    lat: 49.4739,
    lng: -123.7553,
    phone: "604-885-1986",
    website: "https://www.sechelt.ca",
    notes: "Provincial Court at separate location",
  },
  {
    id: "gibsons-town-hall",
    name: "Town of Gibsons",
    type: "town_office",
    municipality: "Gibsons",
    region: "Sunshine Coast",
    address: "474 South Fletcher Road",
    lat: 49.3961,
    lng: -123.5044,
    phone: "604-886-2274",
    website: "https://www.gibsons.ca",
  },
  {
    id: "powell-river-city-hall",
    name: "Powell River City Hall",
    type: "city_hall",
    municipality: "Powell River",
    region: "Powell River",
    address: "6910 Duncan Street",
    lat: 49.8356,
    lng: -124.5253,
    phone: "604-485-6291",
    website: "https://www.powellriver.ca",
    notes: "Courts nearby at 6953 Alberni Street - separate building",
  },

  // ============================================
  // SQUAMISH-LILLOOET / SEA-TO-SKY
  // ============================================
  {
    id: "squamish-district-office",
    name: "District of Squamish Municipal Hall",
    type: "district_office",
    municipality: "Squamish",
    region: "Squamish-Lillooet",
    address: "37955 Second Avenue",
    lat: 49.7014,
    lng: -123.1564,
    phone: "604-892-5217",
    website: "https://www.squamish.ca",
    notes: "Provincial Court at separate location",
  },
  {
    id: "whistler-municipal-hall",
    name: "Resort Municipality of Whistler",
    type: "district_office",
    municipality: "Whistler",
    region: "Squamish-Lillooet",
    address: "4325 Blackcomb Way",
    lat: 50.1175,
    lng: -122.9544,
    phone: "604-932-5535",
    website: "https://www.whistler.ca",
  },
  {
    id: "pemberton-village-office",
    name: "Village of Pemberton",
    type: "village_office",
    municipality: "Pemberton",
    region: "Squamish-Lillooet",
    address: "7400 Prospect Street",
    lat: 50.3194,
    lng: -122.8039,
    phone: "604-894-6135",
    website: "https://www.pemberton.ca",
  },
  {
    id: "lillooet-district-office",
    name: "District of Lillooet",
    type: "district_office",
    municipality: "Lillooet",
    region: "Squamish-Lillooet",
    address: "615 Main Street",
    lat: 50.6872,
    lng: -121.9414,
    phone: "250-256-4289",
    website: "https://www.lillooetbc.ca",
    notes: "Provincial Court at separate location",
  },

  // ============================================
  // OKANAGAN - CENTRAL
  // ============================================
  {
    id: "kelowna-city-hall",
    name: "Kelowna City Hall",
    type: "city_hall",
    municipality: "Kelowna",
    region: "Central Okanagan",
    address: "1435 Water Street",
    lat: 49.8850,
    lng: -119.4958,
    phone: "250-469-8500",
    website: "https://www.kelowna.ca",
    notes: "Courts nearby at 1355 Water Street - separate building",
  },
  {
    id: "west-kelowna-city-hall",
    name: "West Kelowna City Hall",
    type: "city_hall",
    municipality: "West Kelowna",
    region: "Central Okanagan",
    address: "2760 Cameron Road",
    lat: 49.8661,
    lng: -119.5761,
    phone: "778-797-1000",
    website: "https://www.westkelownacity.ca",
  },
  {
    id: "peachland-district-office",
    name: "District of Peachland",
    type: "district_office",
    municipality: "Peachland",
    region: "Central Okanagan",
    address: "5806 Beach Avenue",
    lat: 49.7744,
    lng: -119.7358,
    phone: "250-767-2647",
    website: "https://www.peachland.ca",
  },
  {
    id: "lake-country-district-office",
    name: "District of Lake Country",
    type: "district_office",
    municipality: "Lake Country",
    region: "Central Okanagan",
    address: "10150 Bottom Wood Lake Road",
    lat: 50.0261,
    lng: -119.4128,
    phone: "250-766-5650",
    website: "https://www.lakecountry.bc.ca",
  },

  // ============================================
  // OKANAGAN - NORTH
  // ============================================
  {
    id: "vernon-city-hall",
    name: "Vernon City Hall",
    type: "city_hall",
    municipality: "Vernon",
    region: "North Okanagan",
    address: "3400 30th Street",
    lat: 50.2669,
    lng: -119.2722,
    phone: "250-545-1361",
    website: "https://www.vernon.ca",
    notes: "Courts nearby at 3001 27th Street - separate building",
  },
  {
    id: "coldstream-district-office",
    name: "District of Coldstream",
    type: "district_office",
    municipality: "Coldstream",
    region: "North Okanagan",
    address: "9901 Kalamalka Road",
    lat: 50.2228,
    lng: -119.1886,
    phone: "250-545-5304",
    website: "https://www.coldstream.ca",
  },
  {
    id: "armstrong-city-hall",
    name: "Armstrong City Hall",
    type: "city_hall",
    municipality: "Armstrong",
    region: "North Okanagan",
    address: "3570 Bridge Street",
    lat: 50.4478,
    lng: -119.1972,
    phone: "250-546-3023",
    website: "https://www.cityofarmstrong.bc.ca",
  },
  {
    id: "spallumcheen-township-hall",
    name: "Township of Spallumcheen",
    type: "district_office",
    municipality: "Spallumcheen",
    region: "North Okanagan",
    address: "4144 Spallumcheen Way",
    lat: 50.4478,
    lng: -119.1939,
    phone: "250-546-3013",
    website: "https://www.spallumcheentwp.bc.ca",
  },
  {
    id: "enderby-city-hall",
    name: "Enderby City Hall",
    type: "city_hall",
    municipality: "Enderby",
    region: "North Okanagan",
    address: "619 Cliff Avenue",
    lat: 50.5503,
    lng: -119.1394,
    phone: "250-838-7230",
    website: "https://www.cityofenderby.com",
  },

  // ============================================
  // OKANAGAN - SOUTH / SIMILKAMEEN
  // ============================================
  {
    id: "penticton-city-hall",
    name: "Penticton City Hall",
    type: "city_hall",
    municipality: "Penticton",
    region: "Okanagan-Similkameen",
    address: "171 Main Street",
    lat: 49.4904,
    lng: -119.5906,
    phone: "250-490-2400",
    website: "https://www.penticton.ca",
    notes: "Courts nearby at 100 Main Street - separate building",
  },
  {
    id: "summerland-district-office",
    name: "District of Summerland",
    type: "district_office",
    municipality: "Summerland",
    region: "Okanagan-Similkameen",
    address: "13211 Henry Avenue",
    lat: 49.6006,
    lng: -119.6719,
    phone: "250-494-6451",
    website: "https://www.summerland.ca",
  },
  {
    id: "oliver-town-hall",
    name: "Town of Oliver",
    type: "town_office",
    municipality: "Oliver",
    region: "Okanagan-Similkameen",
    address: "6150 Main Street",
    lat: 49.1828,
    lng: -119.5494,
    phone: "250-498-4881",
    website: "https://www.oliver.ca",
  },
  {
    id: "osoyoos-town-hall",
    name: "Town of Osoyoos",
    type: "town_office",
    municipality: "Osoyoos",
    region: "Okanagan-Similkameen",
    address: "8707 Main Street",
    lat: 49.0306,
    lng: -119.4639,
    phone: "250-495-6515",
    website: "https://www.osoyoos.ca",
  },
  {
    id: "keremeos-village-office",
    name: "Village of Keremeos",
    type: "village_office",
    municipality: "Keremeos",
    region: "Okanagan-Similkameen",
    address: "702 4th Street",
    lat: 49.2028,
    lng: -119.8289,
    phone: "250-499-2711",
    website: "https://www.keremeos.ca",
  },
  {
    id: "princeton-town-hall",
    name: "Town of Princeton",
    type: "town_office",
    municipality: "Princeton",
    region: "Okanagan-Similkameen",
    address: "151 Vermilion Avenue",
    lat: 49.4589,
    lng: -120.5067,
    phone: "250-295-3135",
    website: "https://www.princeton.ca",
    notes: "Provincial Court (circuit) serves Princeton",
  },

  // ============================================
  // COLUMBIA-SHUSWAP
  // ============================================
  {
    id: "salmon-arm-city-hall",
    name: "Salmon Arm City Hall",
    type: "city_hall",
    municipality: "Salmon Arm",
    region: "Columbia-Shuswap",
    address: "500 2nd Avenue NE",
    lat: 50.7006,
    lng: -119.2722,
    phone: "250-803-4000",
    website: "https://www.salmonarm.ca",
    notes: "Courts nearby at 550 2nd Avenue NE - separate building",
  },
  {
    id: "sicamous-district-office",
    name: "District of Sicamous",
    type: "district_office",
    municipality: "Sicamous",
    region: "Columbia-Shuswap",
    address: "446 Main Street",
    lat: 50.8372,
    lng: -118.9753,
    phone: "250-836-2477",
    website: "https://www.sicamous.ca",
  },
  {
    id: "revelstoke-city-hall",
    name: "Revelstoke City Hall",
    type: "city_hall",
    municipality: "Revelstoke",
    region: "Columbia-Shuswap",
    address: "216 Mackenzie Avenue",
    lat: 50.9994,
    lng: -118.1953,
    phone: "250-837-2911",
    website: "https://www.revelstoke.ca",
    notes: "Provincial Court at separate location",
  },
  {
    id: "golden-town-hall",
    name: "Town of Golden",
    type: "town_office",
    municipality: "Golden",
    region: "Columbia-Shuswap",
    address: "810 9th Avenue S",
    lat: 51.2956,
    lng: -116.9644,
    phone: "250-344-2271",
    website: "https://www.golden.ca",
    notes: "Provincial Court at separate location",
  },

  // ============================================
  // EAST KOOTENAY
  // ============================================
  {
    id: "cranbrook-city-hall",
    name: "Cranbrook City Hall",
    type: "city_hall",
    municipality: "Cranbrook",
    region: "East Kootenay",
    address: "40 10th Avenue S",
    lat: 49.5097,
    lng: -115.7689,
    phone: "250-426-4211",
    website: "https://www.cranbrook.ca",
    notes: "Courts nearby at 102 11th Avenue S - separate building",
  },
  {
    id: "kimberley-city-hall",
    name: "Kimberley City Hall",
    type: "city_hall",
    municipality: "Kimberley",
    region: "East Kootenay",
    address: "340 Spokane Street",
    lat: 49.6697,
    lng: -115.9778,
    phone: "250-427-5311",
    website: "https://www.kimberley.ca",
  },
  {
    id: "fernie-city-hall",
    name: "Fernie City Hall",
    type: "city_hall",
    municipality: "Fernie",
    region: "East Kootenay",
    address: "501 3rd Avenue",
    lat: 49.5044,
    lng: -115.0628,
    phone: "250-423-6817",
    website: "https://www.fernie.ca",
    notes: "Provincial Court at separate location",
  },
  {
    id: "sparwood-district-office",
    name: "District of Sparwood",
    type: "district_office",
    municipality: "Sparwood",
    region: "East Kootenay",
    address: "136 Spruce Avenue",
    lat: 49.7344,
    lng: -114.8853,
    phone: "250-425-2423",
    website: "https://www.sparwood.ca",
  },
  {
    id: "elkford-district-office",
    name: "District of Elkford",
    type: "district_office",
    municipality: "Elkford",
    region: "East Kootenay",
    address: "816 Michel Road",
    lat: 50.0228,
    lng: -114.9214,
    phone: "250-865-4000",
    website: "https://www.elkford.ca",
  },
  {
    id: "invermere-district-office",
    name: "District of Invermere",
    type: "district_office",
    municipality: "Invermere",
    region: "East Kootenay",
    address: "914 8th Avenue",
    lat: 50.5078,
    lng: -116.0319,
    phone: "250-342-9281",
    website: "https://www.invermere.net",
    notes: "Provincial Court at separate location",
  },
  {
    id: "radium-hot-springs-village",
    name: "Village of Radium Hot Springs",
    type: "village_office",
    municipality: "Radium Hot Springs",
    region: "East Kootenay",
    address: "4996 Forester Street",
    lat: 50.6178,
    lng: -116.0678,
    phone: "250-347-6455",
    website: "https://www.radiumhotsprings.ca",
  },
  {
    id: "canal-flats-village",
    name: "Village of Canal Flats",
    type: "village_office",
    municipality: "Canal Flats",
    region: "East Kootenay",
    address: "8694 Grainger Road",
    lat: 50.1500,
    lng: -115.8167,
    phone: "250-349-5462",
    website: "https://www.canalflats.ca",
  },

  // ============================================
  // CENTRAL KOOTENAY
  // ============================================
  {
    id: "nelson-city-hall",
    name: "Nelson City Hall",
    type: "city_hall",
    municipality: "Nelson",
    region: "Central Kootenay",
    address: "310 Ward Street",
    lat: 49.4961,
    lng: -117.2897,
    phone: "250-352-5511",
    website: "https://www.nelson.ca",
    notes: "Courts adjacent at 320 Ward Street - separate building",
  },
  {
    id: "castlegar-city-hall",
    name: "Castlegar City Hall",
    type: "city_hall",
    municipality: "Castlegar",
    region: "Central Kootenay",
    address: "460 Columbia Avenue",
    lat: 49.3256,
    lng: -117.6656,
    phone: "250-365-7227",
    website: "https://www.castlegar.ca",
    notes: "Provincial Court at separate location",
  },
  {
    id: "creston-town-hall",
    name: "Town of Creston",
    type: "town_office",
    municipality: "Creston",
    region: "Central Kootenay",
    address: "238 10th Avenue N",
    lat: 49.0956,
    lng: -116.5131,
    phone: "250-428-2214",
    website: "https://www.creston.ca",
    notes: "Provincial Court at separate location",
  },
  {
    id: "salmo-village-office",
    name: "Village of Salmo",
    type: "village_office",
    municipality: "Salmo",
    region: "Central Kootenay",
    address: "423 Davies Avenue",
    lat: 49.1939,
    lng: -117.2744,
    phone: "250-357-9433",
    website: "https://www.salmo.ca",
  },
  {
    id: "nakusp-village-office",
    name: "Village of Nakusp",
    type: "village_office",
    municipality: "Nakusp",
    region: "Central Kootenay",
    address: "91 1st Street NW",
    lat: 50.2389,
    lng: -117.8019,
    phone: "250-265-3689",
    website: "https://www.nakusp.com",
    notes: "Provincial Court (circuit) serves Nakusp",
  },
  {
    id: "new-denver-village",
    name: "Village of New Denver",
    type: "village_office",
    municipality: "New Denver",
    region: "Central Kootenay",
    address: "115 Slocan Avenue",
    lat: 49.9931,
    lng: -117.3739,
    phone: "250-358-2316",
    website: "https://www.newdenver.ca",
  },
  {
    id: "silverton-village",
    name: "Village of Silverton",
    type: "village_office",
    municipality: "Silverton",
    region: "Central Kootenay",
    address: "421 Lake Avenue",
    lat: 49.9556,
    lng: -117.3903,
    phone: "250-358-2472",
    website: "https://www.silverton.ca",
  },
  {
    id: "slocan-village",
    name: "Village of Slocan",
    type: "village_office",
    municipality: "Slocan",
    region: "Central Kootenay",
    address: "503 Slocan Street",
    lat: 49.7642,
    lng: -117.4711,
    phone: "250-355-2277",
    website: "https://www.villageofslocan.ca",
  },
  {
    id: "kaslo-village",
    name: "Village of Kaslo",
    type: "village_office",
    municipality: "Kaslo",
    region: "Central Kootenay",
    address: "312 4th Street",
    lat: 49.9142,
    lng: -116.9131,
    phone: "250-353-2311",
    website: "https://www.kaslo.ca",
  },

  // ============================================
  // KOOTENAY BOUNDARY
  // ============================================
  {
    id: "trail-city-hall",
    name: "Trail City Hall",
    type: "city_hall",
    municipality: "Trail",
    region: "Kootenay Boundary",
    address: "1394 Pine Avenue",
    lat: 49.0950,
    lng: -117.7053,
    phone: "250-364-1262",
    website: "https://www.trail.ca",
    notes: "Provincial Court at separate location",
  },
  {
    id: "rossland-city-hall",
    name: "Rossland City Hall",
    type: "city_hall",
    municipality: "Rossland",
    region: "Kootenay Boundary",
    address: "1899 Columbia Avenue",
    lat: 49.0786,
    lng: -117.8019,
    phone: "250-362-7396",
    website: "https://www.rossland.ca",
  },
  {
    id: "grand-forks-city-hall",
    name: "Grand Forks City Hall",
    type: "city_hall",
    municipality: "Grand Forks",
    region: "Kootenay Boundary",
    address: "7217 4th Street",
    lat: 49.0283,
    lng: -118.4411,
    phone: "250-442-8266",
    website: "https://www.grandforks.ca",
    notes: "Provincial Court at separate location",
  },
  {
    id: "greenwood-city-hall",
    name: "Greenwood City Hall",
    type: "city_hall",
    municipality: "Greenwood",
    region: "Kootenay Boundary",
    address: "202 Government Avenue",
    lat: 49.0900,
    lng: -118.6778,
    phone: "250-445-6644",
    website: "https://www.greenwoodcity.com",
    notes: "Canada's smallest city",
  },
  {
    id: "fruitvale-village",
    name: "Village of Fruitvale",
    type: "village_office",
    municipality: "Fruitvale",
    region: "Kootenay Boundary",
    address: "1947 Beaver Street",
    lat: 49.1142,
    lng: -117.5489,
    phone: "250-367-7551",
    website: "https://www.village.fruitvale.bc.ca",
  },
  {
    id: "montrose-village",
    name: "Village of Montrose",
    type: "village_office",
    municipality: "Montrose",
    region: "Kootenay Boundary",
    address: "724 10th Avenue",
    lat: 49.1028,
    lng: -117.6336,
    phone: "250-367-7234",
    website: "https://www.montrose.ca",
  },
  {
    id: "warfield-village",
    name: "Village of Warfield",
    type: "village_office",
    municipality: "Warfield",
    region: "Kootenay Boundary",
    address: "585 Schofield Highway",
    lat: 49.0928,
    lng: -117.7331,
    phone: "250-368-8202",
    website: "https://www.warfield.ca",
  },
  {
    id: "midway-village",
    name: "Village of Midway",
    type: "village_office",
    municipality: "Midway",
    region: "Kootenay Boundary",
    address: "649 8th Avenue",
    lat: 49.0014,
    lng: -118.7678,
    phone: "250-449-2222",
    website: "https://www.midwaybc.ca",
  },

  // ============================================
  // THOMPSON-NICOLA
  // ============================================
  {
    id: "kamloops-city-hall",
    name: "Kamloops City Hall",
    type: "city_hall",
    municipality: "Kamloops",
    region: "Thompson-Nicola",
    address: "7 Victoria Street W",
    lat: 50.6744,
    lng: -120.3272,
    phone: "250-828-3311",
    website: "https://www.kamloops.ca",
    notes: "Courts nearby at 455 Columbia Street - separate building",
  },
  {
    id: "merritt-city-hall",
    name: "Merritt City Hall",
    type: "city_hall",
    municipality: "Merritt",
    region: "Thompson-Nicola",
    address: "2185 Voght Street",
    lat: 50.1083,
    lng: -120.7842,
    phone: "250-378-4224",
    website: "https://www.merritt.ca",
    notes: "Provincial Court at separate location",
  },
  {
    id: "clearwater-district-office",
    name: "District of Clearwater",
    type: "district_office",
    municipality: "Clearwater",
    region: "Thompson-Nicola",
    address: "209 Dutch Lake Road",
    lat: 51.6494,
    lng: -120.0369,
    phone: "250-674-2257",
    website: "https://www.districtofclearwater.com",
    notes: "Provincial Court at separate location",
  },
  {
    id: "barriere-district-office",
    name: "District of Barriere",
    type: "district_office",
    municipality: "Barriere",
    region: "Thompson-Nicola",
    address: "4936 Barriere Town Road",
    lat: 51.1831,
    lng: -120.1233,
    phone: "250-672-9751",
    website: "https://www.barriere.ca",
  },
  {
    id: "sun-peaks-mountain-resort",
    name: "Sun Peaks Mountain Resort Municipality",
    type: "district_office",
    municipality: "Sun Peaks",
    region: "Thompson-Nicola",
    address: "1280 Alpine Road",
    lat: 50.8833,
    lng: -119.9000,
    phone: "250-578-2020",
    website: "https://www.sunpeaksmunicipality.ca",
  },
  {
    id: "logan-lake-district",
    name: "District of Logan Lake",
    type: "district_office",
    municipality: "Logan Lake",
    region: "Thompson-Nicola",
    address: "1 Opal Drive",
    lat: 50.4922,
    lng: -120.8061,
    phone: "250-523-6225",
    website: "https://www.loganlake.ca",
  },
  {
    id: "ashcroft-village",
    name: "Village of Ashcroft",
    type: "village_office",
    municipality: "Ashcroft",
    region: "Thompson-Nicola",
    address: "601 Bancroft Street",
    lat: 50.7214,
    lng: -121.2831,
    phone: "250-453-9161",
    website: "https://www.ashcroftbc.ca",
  },
  {
    id: "cache-creek-village",
    name: "Village of Cache Creek",
    type: "village_office",
    municipality: "Cache Creek",
    region: "Thompson-Nicola",
    address: "1389 Quartz Road",
    lat: 50.8100,
    lng: -121.3253,
    phone: "250-457-6237",
    website: "https://www.cachecreek.ca",
  },
  {
    id: "chase-village",
    name: "Village of Chase",
    type: "village_office",
    municipality: "Chase",
    region: "Thompson-Nicola",
    address: "826 Okanagan Avenue",
    lat: 50.8181,
    lng: -119.6864,
    phone: "250-679-3238",
    website: "https://www.chasebc.ca",
  },
  {
    id: "clinton-village",
    name: "Village of Clinton",
    type: "village_office",
    municipality: "Clinton",
    region: "Thompson-Nicola",
    address: "423 Cariboo Highway",
    lat: 51.0903,
    lng: -121.5853,
    phone: "250-459-2261",
    website: "https://www.village.clinton.bc.ca",
  },
  {
    id: "lytton-village",
    name: "Village of Lytton",
    type: "village_office",
    municipality: "Lytton",
    region: "Thompson-Nicola",
    address: "380 Main Street",
    lat: 50.2289,
    lng: -121.5822,
    phone: "250-455-2355",
    website: "https://www.lytton.ca",
    notes: "Community rebuilding after 2021 wildfire",
  },

  // ============================================
  // CARIBOO
  // ============================================
  {
    id: "williams-lake-city-hall",
    name: "Williams Lake City Hall",
    type: "city_hall",
    municipality: "Williams Lake",
    region: "Cariboo",
    address: "450 Mart Street",
    lat: 52.1286,
    lng: -122.1511,
    phone: "250-392-2311",
    website: "https://www.williamslake.ca",
    notes: "Courts nearby at 540 Borland Street - separate building",
  },
  {
    id: "quesnel-city-hall",
    name: "Quesnel City Hall",
    type: "city_hall",
    municipality: "Quesnel",
    region: "Cariboo",
    address: "410 Kinchant Street",
    lat: 52.9783,
    lng: -122.4939,
    phone: "250-992-2111",
    website: "https://www.quesnel.ca",
    notes: "Courts nearby at 350 Barlow Avenue - separate building",
  },
  {
    id: "100-mile-house-district",
    name: "District of 100 Mile House",
    type: "district_office",
    municipality: "100 Mile House",
    region: "Cariboo",
    address: "385 Birch Avenue S",
    lat: 51.6397,
    lng: -121.2878,
    phone: "250-395-2434",
    website: "https://www.100milehouse.com",
    notes: "Provincial Court at separate location",
  },
  {
    id: "wells-district",
    name: "District of Wells",
    type: "district_office",
    municipality: "Wells",
    region: "Cariboo",
    address: "4243 Sanders Avenue",
    lat: 53.1178,
    lng: -121.5572,
    phone: "250-994-3330",
    website: "https://www.wells.ca",
    notes: "Historic Barkerville area",
  },

  // ============================================
  // PRINCE GEORGE / FRASER-FORT GEORGE
  // ============================================
  {
    id: "prince-george-city-hall",
    name: "Prince George City Hall",
    type: "city_hall",
    municipality: "Prince George",
    region: "Fraser-Fort George",
    address: "1100 Patricia Boulevard",
    lat: 53.9128,
    lng: -122.7556,
    phone: "250-561-7600",
    website: "https://www.princegeorge.ca",
    notes: "Courts nearby at 250 George Street - separate building",
  },
  {
    id: "mackenzie-district",
    name: "District of Mackenzie",
    type: "district_office",
    municipality: "Mackenzie",
    region: "Fraser-Fort George",
    address: "1 Mackenzie Boulevard",
    lat: 55.3397,
    lng: -123.0933,
    phone: "250-997-3221",
    website: "https://www.districtofmackenzie.ca",
  },
  {
    id: "mcbride-village",
    name: "Village of McBride",
    type: "village_office",
    municipality: "McBride",
    region: "Fraser-Fort George",
    address: "100 Dominion Street",
    lat: 53.3061,
    lng: -120.1653,
    phone: "250-569-2229",
    website: "https://www.mcbride.ca",
    notes: "Provincial Court (circuit) serves McBride",
  },
  {
    id: "valemount-village",
    name: "Village of Valemount",
    type: "village_office",
    municipality: "Valemount",
    region: "Fraser-Fort George",
    address: "735 Cranberry Lake Road",
    lat: 52.8306,
    lng: -119.2639,
    phone: "250-566-4435",
    website: "https://www.valemount.ca",
  },

  // ============================================
  // BULKLEY-NECHAKO
  // ============================================
  {
    id: "vanderhoof-district",
    name: "District of Vanderhoof",
    type: "district_office",
    municipality: "Vanderhoof",
    region: "Bulkley-Nechako",
    address: "160 Connaught Street",
    lat: 54.0172,
    lng: -124.0047,
    phone: "250-567-4711",
    website: "https://www.vanderhoof.ca",
    notes: "Provincial Court at separate location",
  },
  {
    id: "fort-st-james-district",
    name: "District of Fort St. James",
    type: "district_office",
    municipality: "Fort St. James",
    region: "Bulkley-Nechako",
    address: "477 Stuart Drive W",
    lat: 54.4433,
    lng: -124.2536,
    phone: "250-996-8233",
    website: "https://www.fortstjames.ca",
    notes: "Provincial Court (circuit) serves Fort St. James",
  },
  {
    id: "burns-lake-village",
    name: "Village of Burns Lake",
    type: "village_office",
    municipality: "Burns Lake",
    region: "Bulkley-Nechako",
    address: "15 3rd Avenue",
    lat: 54.2306,
    lng: -125.7583,
    phone: "250-692-7587",
    website: "https://www.burnslake.ca",
    notes: "Provincial Court at separate location",
  },
  {
    id: "houston-district",
    name: "District of Houston",
    type: "district_office",
    municipality: "Houston",
    region: "Bulkley-Nechako",
    address: "3367 12th Street",
    lat: 54.3972,
    lng: -126.6483,
    phone: "250-845-2238",
    website: "https://www.houston.ca",
  },
  {
    id: "smithers-town-hall",
    name: "Town of Smithers",
    type: "town_office",
    municipality: "Smithers",
    region: "Bulkley-Nechako",
    address: "1027 Aldous Street",
    lat: 54.3825,
    lng: -126.8311,
    phone: "250-847-1600",
    website: "https://www.smithers.ca",
    notes: "Courts nearby at 3793 Alfred Avenue - separate building",
  },
  {
    id: "fraser-lake-village",
    name: "Village of Fraser Lake",
    type: "village_office",
    municipality: "Fraser Lake",
    region: "Bulkley-Nechako",
    address: "210 Carrier Crescent",
    lat: 54.0506,
    lng: -124.8494,
    phone: "250-699-6257",
    website: "https://www.fraserlake.ca",
  },
  {
    id: "granisle-village",
    name: "Village of Granisle",
    type: "village_office",
    municipality: "Granisle",
    region: "Bulkley-Nechako",
    address: "1 MacDonald Avenue",
    lat: 54.9811,
    lng: -126.0983,
    phone: "250-697-2248",
    website: "https://www.granisle.ca",
  },

  // ============================================
  // KITIMAT-STIKINE
  // ============================================
  {
    id: "terrace-city-hall",
    name: "Terrace City Hall",
    type: "city_hall",
    municipality: "Terrace",
    region: "Kitimat-Stikine",
    address: "3215 Eby Street",
    lat: 54.5161,
    lng: -128.5978,
    phone: "250-635-6311",
    website: "https://www.terrace.ca",
    notes: "Courts nearby at 3408 Kalum Street - separate building",
  },
  {
    id: "kitimat-district",
    name: "District of Kitimat",
    type: "district_office",
    municipality: "Kitimat",
    region: "Kitimat-Stikine",
    address: "270 City Centre",
    lat: 54.0500,
    lng: -128.6536,
    phone: "250-632-8900",
    website: "https://www.kitimat.ca",
    notes: "Provincial Court at separate location",
  },
  {
    id: "hazelton-village",
    name: "Village of Hazelton",
    type: "village_office",
    municipality: "Hazelton",
    region: "Kitimat-Stikine",
    address: "4450 Government Street",
    lat: 55.2519,
    lng: -127.6678,
    phone: "250-842-5991",
    website: "https://www.hazelton.ca",
  },
  {
    id: "new-hazelton-district",
    name: "District of New Hazelton",
    type: "district_office",
    municipality: "New Hazelton",
    region: "Kitimat-Stikine",
    address: "3626 Bowser Street",
    lat: 55.2475,
    lng: -127.5894,
    phone: "250-842-6571",
    website: "https://www.newhazelton.ca",
  },
  {
    id: "stewart-district",
    name: "District of Stewart",
    type: "district_office",
    municipality: "Stewart",
    region: "Kitimat-Stikine",
    address: "706 Brightwell Street",
    lat: 55.9361,
    lng: -130.0039,
    phone: "250-636-2251",
    website: "https://www.districtofstewart.com",
    notes: "Provincial Court (circuit) serves Stewart",
  },

  // ============================================
  // NORTH COAST / PRINCE RUPERT
  // ============================================
  {
    id: "prince-rupert-city-hall",
    name: "Prince Rupert City Hall",
    type: "city_hall",
    municipality: "Prince Rupert",
    region: "North Coast",
    address: "424 3rd Avenue W",
    lat: 54.3131,
    lng: -130.3217,
    phone: "250-627-0934",
    website: "https://www.princerupert.ca",
    notes: "Courts nearby at 100 Market Place - separate building",
  },
  {
    id: "port-edward-district",
    name: "District of Port Edward",
    type: "district_office",
    municipality: "Port Edward",
    region: "North Coast",
    address: "770 Pacific Avenue",
    lat: 54.2258,
    lng: -130.2878,
    phone: "250-628-3667",
    website: "https://www.portedward.ca",
  },
  {
    id: "masset-village",
    name: "Village of Masset",
    type: "village_office",
    municipality: "Masset",
    region: "North Coast",
    address: "1567 Main Street",
    lat: 54.0111,
    lng: -132.1417,
    phone: "250-626-3995",
    website: "https://www.masset.ca",
    notes: "Provincial Court (circuit) serves Masset",
  },
  {
    id: "port-clements-village",
    name: "Village of Port Clements",
    type: "village_office",
    municipality: "Port Clements",
    region: "North Coast",
    address: "47 Oceanview Drive",
    lat: 53.6775,
    lng: -132.1703,
    phone: "250-557-4295",
    website: "https://www.portclements.ca",
  },
  {
    id: "queen-charlotte-village",
    name: "Village of Queen Charlotte",
    type: "village_office",
    municipality: "Queen Charlotte",
    region: "North Coast",
    address: "118 3rd Avenue",
    lat: 53.2519,
    lng: -132.0756,
    phone: "250-559-4765",
    website: "https://www.queencharlotte.ca",
    notes: "Provincial Court (circuit) serves Queen Charlotte",
  },

  // ============================================
  // CENTRAL COAST
  // ============================================
  {
    id: "bella-coola-regional",
    name: "Central Coast Regional District Office",
    type: "regional_district",
    municipality: "Bella Coola",
    region: "Central Coast",
    address: "626 Cliff Street",
    lat: 52.3697,
    lng: -126.7542,
    phone: "250-799-5291",
    website: "https://www.ccrd.ca",
    notes: "Provincial Court (circuit) serves Bella Coola",
  },

  // ============================================
  // PEACE RIVER
  // ============================================
  {
    id: "dawson-creek-city-hall",
    name: "Dawson Creek City Hall",
    type: "city_hall",
    municipality: "Dawson Creek",
    region: "Peace River",
    address: "10105 12A Street",
    lat: 55.7597,
    lng: -120.2378,
    phone: "250-784-3600",
    website: "https://www.dawsoncreek.ca",
    notes: "Courts nearby at 1201 103rd Avenue - separate building",
  },
  {
    id: "fort-st-john-city-hall",
    name: "Fort St. John City Hall",
    type: "city_hall",
    municipality: "Fort St. John",
    region: "Peace River",
    address: "10631 100th Street",
    lat: 56.2458,
    lng: -120.8506,
    phone: "250-787-8150",
    website: "https://www.fortstjohn.ca",
    notes: "Courts nearby at 10600 100th Street - separate building",
  },
  {
    id: "chetwynd-district",
    name: "District of Chetwynd",
    type: "district_office",
    municipality: "Chetwynd",
    region: "Peace River",
    address: "5217 North Access Road",
    lat: 55.6989,
    lng: -121.6319,
    phone: "250-401-4100",
    website: "https://www.gochetwynd.com",
    notes: "Provincial Court at separate location",
  },
  {
    id: "tumbler-ridge-district",
    name: "District of Tumbler Ridge",
    type: "district_office",
    municipality: "Tumbler Ridge",
    region: "Peace River",
    address: "305 Founders Street",
    lat: 55.1269,
    lng: -120.9936,
    phone: "250-242-4242",
    website: "https://www.tumblerridge.ca",
  },
  {
    id: "hudson-hope-district",
    name: "District of Hudson's Hope",
    type: "district_office",
    municipality: "Hudson's Hope",
    region: "Peace River",
    address: "9904 Dudley Drive",
    lat: 56.0314,
    lng: -121.9081,
    phone: "250-783-9901",
    website: "https://www.hudsonshope.ca",
  },
  {
    id: "taylor-district",
    name: "District of Taylor",
    type: "district_office",
    municipality: "Taylor",
    region: "Peace River",
    address: "10007 100A Street",
    lat: 56.1533,
    lng: -120.6833,
    phone: "250-789-3392",
    website: "https://www.districtoftaylor.com",
  },
  {
    id: "pouce-coupe-village",
    name: "Village of Pouce Coupe",
    type: "village_office",
    municipality: "Pouce Coupe",
    region: "Peace River",
    address: "5011 49th Avenue",
    lat: 55.7164,
    lng: -120.1311,
    phone: "250-786-5794",
    website: "https://www.poucecoupe.ca",
  },

  // ============================================
  // NORTHERN ROCKIES
  // ============================================
  {
    id: "fort-nelson-town-hall",
    name: "Northern Rockies Regional Municipality",
    type: "district_office",
    municipality: "Fort Nelson",
    region: "Northern Rockies",
    address: "5319 50th Avenue S",
    lat: 58.8039,
    lng: -122.6892,
    phone: "250-774-2541",
    website: "https://www.northernrockies.ca",
    notes: "Courts nearby at 4803 50th Avenue N - separate building",
  },

  // ============================================
  // STIKINE REGION
  // ============================================
  {
    id: "dease-lake-regional",
    name: "Regional District of Kitimat-Stikine (Dease Lake Office)",
    type: "regional_district",
    municipality: "Dease Lake",
    region: "Stikine",
    address: "Boulder Avenue",
    lat: 58.4289,
    lng: -130.0308,
    phone: "250-771-3141",
    website: "https://www.rdks.bc.ca",
    notes: "Provincial Court (circuit) serves Dease Lake",
  },

  // ============================================
  // FIRST NATIONS BAND OFFICES - VANCOUVER ISLAND
  // ============================================
  {
    id: "huuayaht-first-nation-office",
    name: "Huu-ay-aht First Nations Administration",
    type: "first_nation_band_office",
    municipality: "Bamfield",
    region: "Alberni-Clayoquot",
    address: "170 Nookemus Road, Anacla",
    lat: 48.8417,
    lng: -125.1531,
    phone: "250-728-3414",
    website: "https://www.huuayaht.org",
    notes: "Maa-nulth Treaty Nation - self-governing",
  },
  {
    id: "tseshaht-first-nation-office",
    name: "Tseshaht First Nation Administration",
    type: "first_nation_band_office",
    municipality: "Port Alberni",
    region: "Alberni-Clayoquot",
    address: "5091 Tsuma-as Drive",
    lat: 49.2258,
    lng: -124.8075,
    phone: "250-724-1225",
    website: "https://www.tseshaht.com",
    notes: "Nuu-chah-nulth member nation",
  },
  {
    id: "ahousaht-first-nation-office",
    name: "Ahousaht First Nation Administration",
    type: "first_nation_band_office",
    municipality: "Ahousaht",
    region: "Alberni-Clayoquot",
    lat: 49.2833,
    lng: -126.0667,
    phone: "250-670-9531",
    website: "https://www.ahousaht.ca",
    notes: "Nuu-chah-nulth member nation - boat/floatplane access only",
  },
  {
    id: "toquaht-nation-office",
    name: "Toquaht Nation Administration",
    type: "treaty_nation_office",
    municipality: "Ucluelet",
    region: "Alberni-Clayoquot",
    address: "1971 Peninsula Road",
    lat: 48.9444,
    lng: -125.5489,
    phone: "250-726-4230",
    website: "https://www.toquaht.ca",
    notes: "Maa-nulth Treaty Nation - self-governing",
  },
  {
    id: "ucluelet-first-nation-office",
    name: "Yuułuʔiłʔatḥ (Ucluelet First Nation) Administration",
    type: "treaty_nation_office",
    municipality: "Ucluelet",
    region: "Alberni-Clayoquot",
    address: "700 Wya Road",
    lat: 48.9456,
    lng: -125.5567,
    phone: "250-726-7342",
    website: "https://www.ufn.ca",
    notes: "Maa-nulth Treaty Nation - self-governing",
  },
  {
    id: "hesquiaht-first-nation-office",
    name: "Hesquiaht First Nation Administration",
    type: "first_nation_band_office",
    municipality: "Hot Springs Cove",
    region: "Alberni-Clayoquot",
    lat: 49.3494,
    lng: -126.2639,
    phone: "250-670-1100",
    website: "https://www.hesquiaht.org",
    notes: "Nuu-chah-nulth member nation - boat/floatplane access only",
  },
  {
    id: "tla-o-qui-aht-office",
    name: "Tla-o-qui-aht First Nations Administration",
    type: "first_nation_band_office",
    municipality: "Tofino",
    region: "Alberni-Clayoquot",
    address: "1119 Pacific Rim Highway",
    lat: 49.1092,
    lng: -125.8769,
    phone: "250-725-3350",
    website: "https://www.tla-o-qui-aht.org",
    notes: "Nuu-chah-nulth member nation",
  },
  {
    id: "namgis-first-nation-office",
    name: "'Namgis First Nation Administration",
    type: "first_nation_band_office",
    municipality: "Alert Bay",
    region: "Mount Waddington",
    address: "100 Namgis Crescent",
    lat: 50.5864,
    lng: -126.9297,
    phone: "250-974-5556",
    website: "https://www.namgis.bc.ca",
    notes: "Kwakwaka'wakw nation",
  },
  {
    id: "kwakiutl-first-nation-office",
    name: "Kwakiutl First Nation Administration",
    type: "first_nation_band_office",
    municipality: "Port Hardy",
    region: "Mount Waddington",
    address: "Fort Rupert Reserve",
    lat: 50.6889,
    lng: -127.4167,
    phone: "250-949-6012",
    website: "https://www.kwakiutl.bc.ca",
    notes: "Kwakwaka'wakw nation",
  },
  {
    id: "cowichan-tribes-office",
    name: "Cowichan Tribes Administration",
    type: "first_nation_band_office",
    municipality: "Duncan",
    region: "Cowichan Valley",
    address: "5760 Allenby Road",
    lat: 48.8044,
    lng: -123.7106,
    phone: "250-748-3196",
    website: "https://www.cowichantribes.com",
    notes: "Largest First Nation band in BC",
  },
  {
    id: "snuneymuxw-first-nation-office",
    name: "Snuneymuxw First Nation Administration",
    type: "first_nation_band_office",
    municipality: "Nanaimo",
    region: "Nanaimo",
    address: "668 Centre Street",
    lat: 49.1508,
    lng: -123.9339,
    phone: "250-740-2300",
    website: "https://www.snuneymuxw.ca",
    notes: "Coast Salish nation",
  },
  {
    id: "songhees-first-nation-office",
    name: "Songhees Nation Administration",
    type: "first_nation_band_office",
    municipality: "Victoria",
    region: "Capital",
    address: "1100 Admirals Road",
    lat: 48.4411,
    lng: -123.4142,
    phone: "250-386-1043",
    website: "https://www.songheesnation.ca",
    notes: "Coast Salish nation - Lekwungen peoples",
  },
  {
    id: "esquimalt-nation-office",
    name: "Esquimalt Nation Administration",
    type: "first_nation_band_office",
    municipality: "Esquimalt",
    region: "Capital",
    address: "1189A Kosapsum Crescent",
    lat: 48.4297,
    lng: -123.4083,
    phone: "250-381-7861",
    website: "https://www.esquimaltnation.ca",
    notes: "Coast Salish nation - Lekwungen peoples",
  },
  {
    id: "malahat-nation-office",
    name: "Malahat Nation Administration",
    type: "first_nation_band_office",
    municipality: "Mill Bay",
    region: "Cowichan Valley",
    address: "110 Thunder Road",
    lat: 48.6222,
    lng: -123.5492,
    phone: "250-743-3231",
    website: "https://www.malahatnation.com",
    notes: "Coast Salish nation",
  },

  // ============================================
  // FIRST NATIONS BAND OFFICES - METRO VANCOUVER
  // ============================================
  {
    id: "musqueam-indian-band-office",
    name: "Musqueam Indian Band Administration",
    type: "first_nation_band_office",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    address: "6735 Salish Drive",
    lat: 49.2208,
    lng: -123.2011,
    phone: "604-263-3261",
    website: "https://www.musqueam.bc.ca",
    notes: "Coast Salish nation - xʷməθkʷəy̓əm",
  },
  {
    id: "squamish-nation-office",
    name: "Squamish Nation Administration",
    type: "first_nation_band_office",
    municipality: "North Vancouver",
    region: "Metro Vancouver",
    address: "320 Seymour Boulevard",
    lat: 49.3006,
    lng: -123.0292,
    phone: "604-980-4553",
    website: "https://www.squamish.net",
    notes: "Skwxwú7mesh Úxwumixw",
  },
  {
    id: "tsleil-waututh-nation-office",
    name: "Tsleil-Waututh Nation Administration",
    type: "first_nation_band_office",
    municipality: "North Vancouver",
    region: "Metro Vancouver",
    address: "3178 Alder Court",
    lat: 49.3047,
    lng: -122.9506,
    phone: "604-929-3454",
    website: "https://www.twnation.ca",
    notes: "People of the Inlet",
  },
  {
    id: "tsawwassen-first-nation-office",
    name: "Tsawwassen First Nation Administration",
    type: "treaty_nation_office",
    municipality: "Delta",
    region: "Metro Vancouver",
    address: "1926 Tsawwassen Drive",
    lat: 49.0089,
    lng: -123.0831,
    phone: "604-943-2112",
    website: "https://www.tsawwassenfirstnation.com",
    notes: "Treaty First Nation - self-governing since 2009",
  },
  {
    id: "katzie-first-nation-office",
    name: "Katzie First Nation Administration",
    type: "first_nation_band_office",
    municipality: "Pitt Meadows",
    region: "Metro Vancouver",
    address: "10946 Katzie Road",
    lat: 49.2106,
    lng: -122.6614,
    phone: "604-465-8961",
    website: "https://www.katzie.ca",
    notes: "Coast Salish nation",
  },
  {
    id: "kwantlen-first-nation-office",
    name: "Kwantlen First Nation Administration",
    type: "first_nation_band_office",
    municipality: "Langley",
    region: "Metro Vancouver",
    address: "23286 Gabriel Lane",
    lat: 49.1639,
    lng: -122.5778,
    phone: "604-534-2905",
    website: "https://www.kwantlenfn.ca",
    notes: "Coast Salish nation",
  },
  {
    id: "semiahmoo-first-nation-office",
    name: "Semiahmoo First Nation Administration",
    type: "first_nation_band_office",
    municipality: "Surrey",
    region: "Metro Vancouver",
    address: "16049 Beach Road",
    lat: 49.0089,
    lng: -122.7628,
    phone: "604-536-3101",
    website: "https://www.semiahmoofirstnation.ca",
    notes: "Coast Salish nation",
  },

  // ============================================
  // FIRST NATIONS BAND OFFICES - FRASER VALLEY
  // ============================================
  {
    id: "sto-lo-nation-office",
    name: "Stó:lō Nation Administration",
    type: "first_nation_band_office",
    municipality: "Chilliwack",
    region: "Fraser Valley",
    address: "7201 Vedder Road",
    lat: 49.1011,
    lng: -121.9333,
    phone: "604-858-3366",
    website: "https://www.stolonation.bc.ca",
    notes: "Tribal Council representing 11 member bands",
  },
  {
    id: "seabird-island-band-office",
    name: "Seabird Island Band Administration",
    type: "first_nation_band_office",
    municipality: "Agassiz",
    region: "Fraser Valley",
    address: "2895 Chowat Road",
    lat: 49.2272,
    lng: -121.7567,
    phone: "604-796-2177",
    website: "https://www.seabirdisland.ca",
    notes: "Stó:lō member band",
  },
  {
    id: "chehalis-first-nation-office",
    name: "Sts'ailes (Chehalis) Administration",
    type: "first_nation_band_office",
    municipality: "Harrison Mills",
    region: "Fraser Valley",
    address: "4690 Salish Way",
    lat: 49.2339,
    lng: -121.9508,
    phone: "604-796-9401",
    website: "https://www.stsailes.com",
    notes: "People of the River",
  },

  // ============================================
  // FIRST NATIONS BAND OFFICES - INTERIOR
  // ============================================
  {
    id: "westbank-first-nation-office",
    name: "Westbank First Nation Administration",
    type: "treaty_nation_office",
    municipality: "West Kelowna",
    region: "Central Okanagan",
    address: "515 Highway 97 S",
    lat: 49.8528,
    lng: -119.5922,
    phone: "250-769-4999",
    website: "https://www.wfn.ca",
    notes: "Self-governing First Nation since 2005",
  },
  {
    id: "osoyoos-indian-band-office",
    name: "Osoyoos Indian Band Administration",
    type: "first_nation_band_office",
    municipality: "Oliver",
    region: "Okanagan-Similkameen",
    address: "9912 325 Avenue",
    lat: 49.1311,
    lng: -119.5489,
    phone: "250-498-3444",
    website: "https://www.oib.ca",
    notes: "Syilx (Okanagan) Nation",
  },
  {
    id: "tk-emlups-te-secwepemc-office",
    name: "Tk'emlúps te Secwépemc Administration",
    type: "first_nation_band_office",
    municipality: "Kamloops",
    region: "Thompson-Nicola",
    address: "200 Chief Alex Thomas Way",
    lat: 50.6844,
    lng: -120.3628,
    phone: "250-828-9700",
    website: "https://www.tkemlups.ca",
    notes: "Secwépemc (Shuswap) nation",
  },
  {
    id: "shuswap-indian-band-office",
    name: "Shuswap Indian Band Administration",
    type: "first_nation_band_office",
    municipality: "Invermere",
    region: "East Kootenay",
    address: "7470 Shuswap Road",
    lat: 50.5069,
    lng: -116.0278,
    phone: "250-342-6394",
    website: "https://www.shuswapindianband.com",
    notes: "Ktunaxa Nation member",
  },

  // ============================================
  // FIRST NATIONS BAND OFFICES - NORTH COAST
  // ============================================
  {
    id: "heiltsuk-nation-office",
    name: "Heiltsuk Nation Administration",
    type: "first_nation_band_office",
    municipality: "Bella Bella",
    region: "Central Coast",
    address: "99 Walbran Crescent",
    lat: 52.1606,
    lng: -128.1456,
    phone: "250-957-2381",
    website: "https://www.heiltsuk.ca",
    notes: "Boat/floatplane access only",
  },
  {
    id: "nuxalk-nation-office",
    name: "Nuxalk Nation Administration",
    type: "first_nation_band_office",
    municipality: "Bella Coola",
    region: "Central Coast",
    address: "626 Cliff Street",
    lat: 52.3697,
    lng: -126.7542,
    phone: "250-799-5613",
    website: "https://www.nuxalknation.ca",
    notes: "Bella Coola Valley",
  },
  {
    id: "kitasoo-xaixais-office",
    name: "Kitasoo/Xai'xais Nation Administration",
    type: "first_nation_band_office",
    municipality: "Klemtu",
    region: "Central Coast",
    lat: 52.5917,
    lng: -128.5183,
    phone: "250-839-1255",
    website: "https://www.kitasoo-xaixais.com",
    notes: "Boat/floatplane access only - Spirit Bear Conservancy",
  },
  {
    id: "gitxaala-nation-office",
    name: "Gitxaała Nation Administration",
    type: "first_nation_band_office",
    municipality: "Kitkatla",
    region: "North Coast",
    lat: 53.7917,
    lng: -130.4317,
    phone: "250-848-2214",
    website: "https://www.gitxaalanation.com",
    notes: "Boat/floatplane access only",
  },
  {
    id: "lax-kwalaams-band-office",
    name: "Lax Kw'alaams Band Administration",
    type: "first_nation_band_office",
    municipality: "Lax Kw'alaams",
    region: "North Coast",
    lat: 54.5597,
    lng: -130.4333,
    phone: "250-625-3293",
    website: "https://www.laxkwalaams.ca",
    notes: "Coast Tsimshian nation",
  },
  {
    id: "metlakatla-first-nation-office",
    name: "Metlakatla First Nation Administration",
    type: "first_nation_band_office",
    municipality: "Prince Rupert",
    region: "North Coast",
    address: "201-364 3rd Avenue W",
    lat: 54.3131,
    lng: -130.3178,
    phone: "250-628-3234",
    website: "https://www.metlakatla.ca",
    notes: "Coast Tsimshian nation",
  },
  {
    id: "skidegate-band-office",
    name: "Skidegate Band Council Administration",
    type: "first_nation_band_office",
    municipality: "Skidegate",
    region: "North Coast",
    lat: 53.2519,
    lng: -131.9989,
    phone: "250-559-4496",
    website: "https://www.skidegate.ca",
    notes: "Haida Nation",
  },
  {
    id: "old-massett-village-council",
    name: "Old Massett Village Council Administration",
    type: "first_nation_band_office",
    municipality: "Old Massett",
    region: "North Coast",
    lat: 54.0111,
    lng: -132.1417,
    phone: "250-626-3337",
    website: "https://www.omvc.ca",
    notes: "Haida Nation",
  },

  // ============================================
  // FIRST NATIONS BAND OFFICES - NORTHWEST
  // ============================================
  {
    id: "nisga-lisims-government-office",
    name: "Nisga'a Lisims Government Administration",
    type: "treaty_nation_office",
    municipality: "New Aiyansh",
    region: "Kitimat-Stikine",
    address: "2000 Lisims Drive",
    lat: 55.2500,
    lng: -129.1000,
    phone: "250-633-3000",
    website: "https://www.nisgaanation.ca",
    notes: "Treaty Nation - self-governing since 2000",
  },
  {
    id: "gitanyow-band-office",
    name: "Gitanyow Hereditary Chiefs Office",
    type: "first_nation_band_office",
    municipality: "Kitwanga",
    region: "Kitimat-Stikine",
    lat: 55.1028,
    lng: -128.0233,
    phone: "250-849-5222",
    website: "https://www.gitanyow.com",
    notes: "Gitxsan Nation",
  },
  {
    id: "gitxsan-hereditary-chiefs-office",
    name: "Gitxsan Hereditary Chiefs Office",
    type: "first_nation_band_office",
    municipality: "Hazelton",
    region: "Kitimat-Stikine",
    address: "4485 River Road",
    lat: 55.2519,
    lng: -127.6608,
    phone: "250-842-6780",
    website: "https://www.gitxsan.com",
    notes: "Gitxsan Nation governance",
  },
  {
    id: "haisla-nation-office",
    name: "Haisla Nation Administration",
    type: "first_nation_band_office",
    municipality: "Kitamaat Village",
    region: "Kitimat-Stikine",
    lat: 53.9833,
    lng: -128.6333,
    phone: "250-639-9361",
    website: "https://www.haisla.ca",
    notes: "Northern Wakashan nation",
  },
  {
    id: "kitsumkalum-first-nation-office",
    name: "Kitsumkalum First Nation Administration",
    type: "first_nation_band_office",
    municipality: "Terrace",
    region: "Kitimat-Stikine",
    address: "4562 Queensway Drive",
    lat: 54.5433,
    lng: -128.5953,
    phone: "250-635-6177",
    website: "https://www.kitsumkalum.com",
    notes: "Tsimshian nation",
  },
  {
    id: "kitselas-first-nation-office",
    name: "Kitselas First Nation Administration",
    type: "first_nation_band_office",
    municipality: "Terrace",
    region: "Kitimat-Stikine",
    address: "4562 Queensway Drive",
    lat: 54.5403,
    lng: -128.5889,
    phone: "250-635-5084",
    website: "https://www.kitselas.com",
    notes: "Tsimshian nation",
  },

  // ============================================
  // FIRST NATIONS BAND OFFICES - BULKLEY-NECHAKO
  // ============================================
  {
    id: "wetsuweten-first-nation-office",
    name: "Wet'suwet'en First Nation Administration",
    type: "first_nation_band_office",
    municipality: "Burns Lake",
    region: "Bulkley-Nechako",
    address: "3873 Centre Road",
    lat: 54.2300,
    lng: -125.7567,
    phone: "250-698-7309",
    website: "https://www.wetsuweten.com",
    notes: "Wet'suwet'en nation",
  },
  {
    id: "stellaten-first-nation-office",
    name: "Stellat'en First Nation Administration",
    type: "first_nation_band_office",
    municipality: "Fraser Lake",
    region: "Bulkley-Nechako",
    lat: 54.0417,
    lng: -124.8917,
    phone: "250-699-8747",
    website: "https://www.stellaten.ca",
    notes: "Carrier (Dakelh) nation",
  },
  {
    id: "nadleh-whuten-band-office",
    name: "Nadleh Whut'en Band Administration",
    type: "first_nation_band_office",
    municipality: "Fort Fraser",
    region: "Bulkley-Nechako",
    lat: 54.0517,
    lng: -124.4917,
    phone: "250-690-7211",
    website: "https://www.nadleh.ca",
    notes: "Carrier (Dakelh) nation",
  },
  {
    id: "lheidli-tenneh-band-office",
    name: "Lheidli T'enneh First Nation Administration",
    type: "first_nation_band_office",
    municipality: "Prince George",
    region: "Fraser-Fort George",
    address: "1041 Whenun Road",
    lat: 53.8444,
    lng: -122.7322,
    phone: "250-963-8451",
    website: "https://www.lheidli.ca",
    notes: "Carrier (Dakelh) nation",
  },

  // ============================================
  // FIRST NATIONS BAND OFFICES - PEACE RIVER
  // ============================================
  {
    id: "doig-river-first-nation-office",
    name: "Doig River First Nation Administration",
    type: "first_nation_band_office",
    municipality: "Rose Prairie",
    region: "Peace River",
    lat: 56.5333,
    lng: -121.1333,
    phone: "250-827-3776",
    website: "https://www.doigriverfn.com",
    notes: "Dane-zaa (Beaver) nation",
  },
  {
    id: "blueberry-river-first-nation-office",
    name: "Blueberry River First Nations Administration",
    type: "first_nation_band_office",
    municipality: "Buick",
    region: "Peace River",
    lat: 57.0667,
    lng: -122.0333,
    phone: "250-630-2584",
    website: "https://www.blueberryfn.ca",
    notes: "Dane-zaa (Beaver) nation",
  },
  {
    id: "halfway-river-first-nation-office",
    name: "Halfway River First Nation Administration",
    type: "first_nation_band_office",
    municipality: "Wonowon",
    region: "Peace River",
    lat: 56.7500,
    lng: -121.8333,
    phone: "250-772-5072",
    website: "https://www.halfwayriverfn.com",
    notes: "Dane-zaa (Beaver) nation",
  },
  {
    id: "west-moberly-first-nation-office",
    name: "West Moberly First Nations Administration",
    type: "first_nation_band_office",
    municipality: "Moberly Lake",
    region: "Peace River",
    lat: 55.8167,
    lng: -121.8833,
    phone: "250-788-3663",
    website: "https://www.westmoberly.ca",
    notes: "Dane-zaa (Beaver) nation",
  },
  {
    id: "saulteau-first-nations-office",
    name: "Saulteau First Nations Administration",
    type: "first_nation_band_office",
    municipality: "Moberly Lake",
    region: "Peace River",
    lat: 55.8233,
    lng: -121.8778,
    phone: "250-788-7280",
    website: "https://www.saulteau.com",
    notes: "Cree nation",
  },
  {
    id: "prophet-river-first-nation-office",
    name: "Prophet River First Nation Administration",
    type: "first_nation_band_office",
    municipality: "Prophet River",
    region: "Northern Rockies",
    lat: 58.7333,
    lng: -122.8167,
    phone: "250-773-6555",
    website: "https://www.prophetriverfirstnation.com",
    notes: "Dane-zaa (Beaver) nation",
  },

  // ============================================
  // FIRST NATIONS BAND OFFICES - STIKINE
  // ============================================
  {
    id: "tahltan-central-government-office",
    name: "Tahltan Central Government Administration",
    type: "first_nation_band_office",
    municipality: "Dease Lake",
    region: "Stikine",
    lat: 58.4289,
    lng: -130.0308,
    phone: "250-771-3274",
    website: "https://www.tahltan.org",
    notes: "Tahltan Nation central governance",
  },
  {
    id: "iskut-first-nation-office",
    name: "Iskut First Nation Administration",
    type: "first_nation_band_office",
    municipality: "Iskut",
    region: "Stikine",
    lat: 57.8442,
    lng: -129.9836,
    phone: "250-234-3331",
    website: "https://www.iskut.ca",
    notes: "Tahltan Nation member",
  },
  {
    id: "dease-river-first-nation-office",
    name: "Dease River First Nation Administration",
    type: "first_nation_band_office",
    municipality: "Good Hope Lake",
    region: "Stikine",
    lat: 59.2333,
    lng: -129.0833,
    phone: "250-239-3000",
    notes: "Kaska Dena nation",
  },
  {
    id: "kwadacha-nation-office",
    name: "Kwadacha Nation Administration",
    type: "first_nation_band_office",
    municipality: "Fort Ware",
    region: "Fraser-Fort George",
    lat: 57.4167,
    lng: -125.6333,
    phone: "250-996-7200",
    website: "https://www.kwadacha.com",
    notes: "Sekani nation - remote community",
  },
  {
    id: "tsay-keh-dene-nation-office",
    name: "Tsay Keh Dene Nation Administration",
    type: "first_nation_band_office",
    municipality: "Tsay Keh",
    region: "Fraser-Fort George",
    lat: 57.0167,
    lng: -124.5333,
    phone: "250-562-8882",
    website: "https://www.tsaykeh.com",
    notes: "Sekani nation - remote community",
  },
];
