// NAICS (North American Industry Classification System) codes
// Based on NAICS 2022 - Standard classification for USA, Canada, Mexico
// Structure: 2-digit (Sector) → 3-digit (Subsector) → 6-digit (National Industry)

export interface NAICSCode {
  code: string;       // 6-digit NAICS code
  subsector: string;  // 3-digit subsector
  sector: string;     // 2-digit sector
  title: string;      // Official NAICS title
}

// NAICS Sector labels (20 sectors)
export const naicsSectorLabels: Record<string, string> = {
  "11": "Agriculture, Forestry, Fishing and Hunting",
  "21": "Mining, Quarrying, and Oil and Gas Extraction",
  "22": "Utilities",
  "23": "Construction",
  "31-33": "Manufacturing",
  "42": "Wholesale Trade",
  "44-45": "Retail Trade",
  "48-49": "Transportation and Warehousing",
  "51": "Information",
  "52": "Finance and Insurance",
  "53": "Real Estate and Rental and Leasing",
  "54": "Professional, Scientific, and Technical Services",
  "55": "Management of Companies and Enterprises",
  "56": "Administrative and Support and Waste Management",
  "61": "Educational Services",
  "62": "Health Care and Social Assistance",
  "71": "Arts, Entertainment, and Recreation",
  "72": "Accommodation and Food Services",
  "81": "Other Services (except Public Administration)",
  "92": "Public Administration",
};

// NAICS Subsector labels (3-digit)
export const naicsSubsectorLabels: Record<string, string> = {
  // Sector 11: Agriculture
  "111": "Crop Production",
  "112": "Animal Production and Aquaculture",
  "113": "Forestry and Logging",
  "114": "Fishing, Hunting and Trapping",
  "115": "Support Activities for Agriculture and Forestry",
  // Sector 21: Mining
  "211": "Oil and Gas Extraction",
  "212": "Mining (except Oil and Gas)",
  "213": "Support Activities for Mining",
  // Sector 22: Utilities
  "221": "Utilities",
  // Sector 23: Construction
  "236": "Construction of Buildings",
  "237": "Heavy and Civil Engineering Construction",
  "238": "Specialty Trade Contractors",
  // Sector 31-33: Manufacturing
  "311": "Food Manufacturing",
  "312": "Beverage and Tobacco Product Manufacturing",
  "313": "Textile Mills",
  "314": "Textile Product Mills",
  "315": "Apparel Manufacturing",
  "316": "Leather and Allied Product Manufacturing",
  "321": "Wood Product Manufacturing",
  "322": "Paper Manufacturing",
  "323": "Printing and Related Support Activities",
  "324": "Petroleum and Coal Products Manufacturing",
  "325": "Chemical Manufacturing",
  "326": "Plastics and Rubber Products Manufacturing",
  "327": "Nonmetallic Mineral Product Manufacturing",
  "331": "Primary Metal Manufacturing",
  "332": "Fabricated Metal Product Manufacturing",
  "333": "Machinery Manufacturing",
  "334": "Computer and Electronic Product Manufacturing",
  "335": "Electrical Equipment, Appliance Manufacturing",
  "336": "Transportation Equipment Manufacturing",
  "337": "Furniture and Related Product Manufacturing",
  "339": "Miscellaneous Manufacturing",
  // Sector 42: Wholesale Trade
  "423": "Merchant Wholesalers, Durable Goods",
  "424": "Merchant Wholesalers, Nondurable Goods",
  "425": "Wholesale Electronic Markets and Agents",
  // Sector 44-45: Retail Trade
  "441": "Motor Vehicle and Parts Dealers",
  "442": "Furniture and Home Furnishings Stores",
  "443": "Electronics and Appliance Stores",
  "444": "Building Material and Garden Equipment",
  "445": "Food and Beverage Stores",
  "446": "Health and Personal Care Stores",
  "447": "Gasoline Stations",
  "448": "Clothing and Clothing Accessories Stores",
  "449": "Furniture, Home Furnishings, Appliance Stores",
  "451": "Sporting Goods, Hobby, Musical, Book Stores",
  "452": "General Merchandise Stores",
  "453": "Miscellaneous Store Retailers",
  "454": "Nonstore Retailers",
  "455": "General Merchandise Retailers",
  // Sector 48-49: Transportation
  "481": "Air Transportation",
  "482": "Rail Transportation",
  "483": "Water Transportation",
  "484": "Truck Transportation",
  "485": "Transit and Ground Passenger Transportation",
  "486": "Pipeline Transportation",
  "487": "Scenic and Sightseeing Transportation",
  "488": "Support Activities for Transportation",
  "491": "Postal Service",
  "492": "Couriers and Messengers",
  "493": "Warehousing and Storage",
  // Sector 51: Information
  "511": "Publishing Industries",
  "512": "Motion Picture and Sound Recording",
  "515": "Broadcasting (except Internet)",
  "517": "Telecommunications",
  "518": "Data Processing, Hosting, Related Services",
  "519": "Other Information Services",
  // Sector 52: Finance and Insurance
  "521": "Monetary Authorities-Central Bank",
  "522": "Credit Intermediation and Related Activities",
  "523": "Securities, Commodity Contracts, Investments",
  "524": "Insurance Carriers and Related Activities",
  "525": "Funds, Trusts, Other Financial Vehicles",
  // Sector 53: Real Estate
  "531": "Real Estate",
  "532": "Rental and Leasing Services",
  "533": "Lessors of Nonfinancial Intangible Assets",
  // Sector 54: Professional Services
  "541": "Professional, Scientific, Technical Services",
  // Sector 55: Management
  "551": "Management of Companies and Enterprises",
  // Sector 56: Administrative
  "561": "Administrative and Support Services",
  "562": "Waste Management and Remediation Services",
  // Sector 61: Education
  "611": "Educational Services",
  // Sector 62: Health Care
  "621": "Ambulatory Health Care Services",
  "622": "Hospitals",
  "623": "Nursing and Residential Care Facilities",
  "624": "Social Assistance",
  // Sector 71: Arts, Entertainment
  "711": "Performing Arts, Spectator Sports, Related",
  "712": "Museums, Historical Sites, Similar",
  "713": "Amusement, Gambling, Recreation Industries",
  // Sector 72: Accommodation and Food
  "721": "Accommodation",
  "722": "Food Services and Drinking Places",
  // Sector 81: Other Services
  "811": "Repair and Maintenance",
  "812": "Personal and Laundry Services",
  "813": "Religious, Grantmaking, Civic, Professional",
  "814": "Private Households",
  // Sector 92: Public Administration
  "921": "Executive, Legislative, General Government",
  "922": "Justice, Public Order, Safety Activities",
  "923": "Administration of Human Resource Programs",
  "924": "Administration of Environmental Programs",
  "925": "Community and Housing Program Administration",
  "926": "Administration of Economic Programs",
  "927": "Space Research and Technology",
  "928": "National Security and International Affairs",
};

// Helper to get sector from subsector code
export function getSectorFromSubsector(subsector: string): string {
  const num = parseInt(subsector);
  if (num >= 110 && num <= 115) return "11";
  if (num >= 211 && num <= 213) return "21";
  if (num === 221) return "22";
  if (num >= 236 && num <= 238) return "23";
  if (num >= 311 && num <= 339) return "31-33";
  if (num >= 423 && num <= 425) return "42";
  if (num >= 441 && num <= 455) return "44-45";
  if (num >= 481 && num <= 493) return "48-49";
  if (num >= 511 && num <= 519) return "51";
  if (num >= 521 && num <= 525) return "52";
  if (num >= 531 && num <= 533) return "53";
  if (num === 541) return "54";
  if (num === 551) return "55";
  if (num >= 561 && num <= 562) return "56";
  if (num === 611) return "61";
  if (num >= 621 && num <= 624) return "62";
  if (num >= 711 && num <= 713) return "71";
  if (num >= 721 && num <= 722) return "72";
  if (num >= 811 && num <= 814) return "81";
  if (num >= 921 && num <= 928) return "92";
  return "99"; // Unknown
}

// Master mapping from current messy category values to NAICS codes
// Maps all 694 unique values found in chamber-members.ts
export const categoryToNAICS: Record<string, NAICSCode> = {
  // ============================================================================
  // SECTOR 11: AGRICULTURE, FORESTRY, FISHING AND HUNTING
  // ============================================================================
  "agriculture": { code: "115000", subsector: "115", sector: "11", title: "Support Activities for Agriculture and Forestry" },
  "Farm": { code: "111000", subsector: "111", sector: "11", title: "Crop Production" },
  "Organic Farm": { code: "111998", subsector: "111", sector: "11", title: "All Other Miscellaneous Crop Farming" },
  "Dairy": { code: "112120", subsector: "112", sector: "11", title: "Dairy Cattle and Milk Production" },
  "Ranch": { code: "112111", subsector: "112", sector: "11", title: "Beef Cattle Ranching and Farming" },
  "Guest ranch": { code: "112990", subsector: "112", sector: "11", title: "All Other Animal Production" },
  "Fish Farm": { code: "112511", subsector: "112", sector: "11", title: "Finfish Farming and Fish Hatcheries" },
  "Aquaculture": { code: "112511", subsector: "112", sector: "11", title: "Finfish Farming and Fish Hatcheries" },
  "forestry-logging": { code: "113310", subsector: "113", sector: "11", title: "Logging" },
  "Logging": { code: "113310", subsector: "113", sector: "11", title: "Logging" },
  "Forestry": { code: "113110", subsector: "113", sector: "11", title: "Timber Tract Operations" },
  "fishing-marine": { code: "114111", subsector: "114", sector: "11", title: "Finfish Fishing" },
  "Fishing": { code: "114111", subsector: "114", sector: "11", title: "Finfish Fishing" },
  "Commercial Fishing": { code: "114111", subsector: "114", sector: "11", title: "Finfish Fishing" },
  "Nursery": { code: "111421", subsector: "111", sector: "11", title: "Nursery and Tree Production" },
  "Landscape Nursery": { code: "111421", subsector: "111", sector: "11", title: "Nursery and Tree Production" },
  "Turf & Sod": { code: "111421", subsector: "111", sector: "11", title: "Nursery and Tree Production" },
  "Turf/Sod": { code: "111421", subsector: "111", sector: "11", title: "Nursery and Tree Production" },
  "Turf/Sod Supplier": { code: "111421", subsector: "111", sector: "11", title: "Nursery and Tree Production" },
  "Turf & Soil Supplier": { code: "111421", subsector: "111", sector: "11", title: "Nursery and Tree Production" },

  // ============================================================================
  // SECTOR 21: MINING, QUARRYING, AND OIL AND GAS EXTRACTION
  // ============================================================================
  "mining": { code: "212000", subsector: "212", sector: "21", title: "Mining (except Oil and Gas)" },
  "Coal mining": { code: "212100", subsector: "212", sector: "21", title: "Coal Mining" },
  "Quarry": { code: "212310", subsector: "212", sector: "21", title: "Stone Mining and Quarrying" },
  "Aggregate": { code: "212320", subsector: "212", sector: "21", title: "Sand, Gravel, Clay Mining" },
  "Soil & Aggregates": { code: "212320", subsector: "212", sector: "21", title: "Sand, Gravel, Clay Mining" },
  "Oil & Gas": { code: "211120", subsector: "211", sector: "21", title: "Crude Petroleum Extraction" },
  "Natural Gas": { code: "211130", subsector: "211", sector: "21", title: "Natural Gas Extraction" },

  // ============================================================================
  // SECTOR 22: UTILITIES
  // ============================================================================
  "utilities": { code: "221000", subsector: "221", sector: "22", title: "Utilities" },
  "Electric Utility": { code: "221110", subsector: "221", sector: "22", title: "Electric Power Generation" },
  "Water Utility": { code: "221310", subsector: "221", sector: "22", title: "Water Supply and Irrigation Systems" },
  "Gas Utility": { code: "221210", subsector: "221", sector: "22", title: "Natural Gas Distribution" },

  // ============================================================================
  // SECTOR 23: CONSTRUCTION
  // ============================================================================
  "construction": { code: "236000", subsector: "236", sector: "23", title: "Construction of Buildings" },
  "Construction": { code: "236000", subsector: "236", sector: "23", title: "Construction of Buildings" },
  "Custom Home Builder": { code: "236115", subsector: "236", sector: "23", title: "New Single-Family Housing Construction" },
  "General Contractor": { code: "236220", subsector: "236", sector: "23", title: "Commercial and Institutional Building Construction" },
  "Construction/General Contractor": { code: "236220", subsector: "236", sector: "23", title: "Commercial and Institutional Building Construction" },
  "Commercial Construction": { code: "236220", subsector: "236", sector: "23", title: "Commercial and Institutional Building Construction" },
  "Construction Management": { code: "236220", subsector: "236", sector: "23", title: "Commercial and Institutional Building Construction" },
  "Renovation": { code: "236118", subsector: "236", sector: "23", title: "Residential Remodelers" },
  "Home Renovation": { code: "236118", subsector: "236", sector: "23", title: "Residential Remodelers" },
  "Bathroom Renovation": { code: "236118", subsector: "236", sector: "23", title: "Residential Remodelers" },
  "Bathroom Remodeling": { code: "236118", subsector: "236", sector: "23", title: "Residential Remodelers" },
  "Kitchen & Bath": { code: "236118", subsector: "236", sector: "23", title: "Residential Remodelers" },
  "Modular Construction": { code: "236117", subsector: "236", sector: "23", title: "New Housing For-Sale Builders" },
  "Prefab Homes": { code: "236117", subsector: "236", sector: "23", title: "New Housing For-Sale Builders" },
  "Accessory Dwelling": { code: "236118", subsector: "236", sector: "23", title: "Residential Remodelers" },
  "Paving": { code: "237310", subsector: "237", sector: "23", title: "Highway, Street, and Bridge Construction" },
  "Excavation": { code: "237990", subsector: "237", sector: "23", title: "Other Heavy and Civil Engineering Construction" },
  "Roofing": { code: "238160", subsector: "238", sector: "23", title: "Roofing Contractors" },
  "Roofing Contractor": { code: "238160", subsector: "238", sector: "23", title: "Roofing Contractors" },
  "roofing": { code: "238160", subsector: "238", sector: "23", title: "Roofing Contractors" },
  "Flooring": { code: "238330", subsector: "238", sector: "23", title: "Flooring Contractors" },
  "Flooring Contractor": { code: "238330", subsector: "238", sector: "23", title: "Flooring Contractors" },
  "Painting Contractor": { code: "238320", subsector: "238", sector: "23", title: "Painting and Wall Covering Contractors" },
  "Plumbing": { code: "238220", subsector: "238", sector: "23", title: "Plumbing, Heating, and Air-Conditioning Contractors" },
  "Plumbing Contractor": { code: "238220", subsector: "238", sector: "23", title: "Plumbing, Heating, and Air-Conditioning Contractors" },
  "plumbing": { code: "238220", subsector: "238", sector: "23", title: "Plumbing, Heating, and Air-Conditioning Contractors" },
  "HVAC": { code: "238220", subsector: "238", sector: "23", title: "Plumbing, Heating, and Air-Conditioning Contractors" },
  "HVAC Contractor": { code: "238220", subsector: "238", sector: "23", title: "Plumbing, Heating, and Air-Conditioning Contractors" },
  "heating-cooling": { code: "238220", subsector: "238", sector: "23", title: "Plumbing, Heating, and Air-Conditioning Contractors" },
  "Electrical Contractor": { code: "238210", subsector: "238", sector: "23", title: "Electrical Contractors" },
  "electrical": { code: "238210", subsector: "238", sector: "23", title: "Electrical Contractors" },
  "Solar Installation": { code: "238210", subsector: "238", sector: "23", title: "Electrical Contractors" },
  "Carpentry": { code: "238350", subsector: "238", sector: "23", title: "Finish Carpentry Contractors" },
  "Drywall": { code: "238310", subsector: "238", sector: "23", title: "Drywall and Insulation Contractors" },
  "Insulation": { code: "238310", subsector: "238", sector: "23", title: "Drywall and Insulation Contractors" },
  "Concrete": { code: "238110", subsector: "238", sector: "23", title: "Poured Concrete Foundation and Structure Contractors" },
  "Fencing": { code: "238990", subsector: "238", sector: "23", title: "All Other Specialty Trade Contractors" },
  "Deck Builder": { code: "238350", subsector: "238", sector: "23", title: "Finish Carpentry Contractors" },
  "Pool & Spa": { code: "238990", subsector: "238", sector: "23", title: "All Other Specialty Trade Contractors" },
  "Windows": { code: "238170", subsector: "238", sector: "23", title: "Siding Contractors" },
  "Windows/Doors": { code: "238170", subsector: "238", sector: "23", title: "Siding Contractors" },
  "Building Controls": { code: "238210", subsector: "238", sector: "23", title: "Electrical Contractors" },
  "home-cc_services": { code: "236118", subsector: "236", sector: "23", title: "Residential Remodelers" },

  // ============================================================================
  // SECTOR 31-33: MANUFACTURING
  // ============================================================================
  "manufacturing": { code: "332000", subsector: "332", sector: "31-33", title: "Fabricated Metal Product Manufacturing" },
  "Bakery": { code: "311811", subsector: "311", sector: "31-33", title: "Retail Bakeries" },
  "Bakery/cafe": { code: "311811", subsector: "311", sector: "31-33", title: "Retail Bakeries" },
  "Bakery & Cafe": { code: "311811", subsector: "311", sector: "31-33", title: "Retail Bakeries" },
  "Bakery/Cafe": { code: "311811", subsector: "311", sector: "31-33", title: "Retail Bakeries" },
  "Artisan food producer": { code: "311990", subsector: "311", sector: "31-33", title: "All Other Food Manufacturing" },
  "Food Producer": { code: "311990", subsector: "311", sector: "31-33", title: "All Other Food Manufacturing" },
  "Food Manufacturing": { code: "311990", subsector: "311", sector: "31-33", title: "All Other Food Manufacturing" },
  "Seafood Processing": { code: "311710", subsector: "311", sector: "31-33", title: "Seafood Product Preparation and Packaging" },
  "Meat Processing": { code: "311610", subsector: "311", sector: "31-33", title: "Animal Slaughtering and Processing" },
  "Chocolatier": { code: "311351", subsector: "311", sector: "31-33", title: "Chocolate and Confectionery Manufacturing" },
  "Chocolate/Candy": { code: "311351", subsector: "311", sector: "31-33", title: "Chocolate and Confectionery Manufacturing" },
  "Ice Cream": { code: "311520", subsector: "311", sector: "31-33", title: "Ice Cream and Frozen Dessert Manufacturing" },
  "Coffee Roaster": { code: "311920", subsector: "311", sector: "31-33", title: "Coffee and Tea Manufacturing" },
  "Coffee & Tea": { code: "311920", subsector: "311", sector: "31-33", title: "Coffee and Tea Manufacturing" },
  "Tea": { code: "311920", subsector: "311", sector: "31-33", title: "Coffee and Tea Manufacturing" },
  "winery-brewery": { code: "312120", subsector: "312", sector: "31-33", title: "Breweries" },
  "Brewery": { code: "312120", subsector: "312", sector: "31-33", title: "Breweries" },
  "Brewpub": { code: "312120", subsector: "312", sector: "31-33", title: "Breweries" },
  "Winery": { code: "312130", subsector: "312", sector: "31-33", title: "Wineries" },
  "Cidery": { code: "312130", subsector: "312", sector: "31-33", title: "Wineries" },
  "Distillery": { code: "312140", subsector: "312", sector: "31-33", title: "Distilleries" },
  "Woodworking": { code: "321999", subsector: "321", sector: "31-33", title: "All Other Miscellaneous Wood Product Manufacturing" },
  "Wood carving": { code: "321999", subsector: "321", sector: "31-33", title: "All Other Miscellaneous Wood Product Manufacturing" },
  "Printing": { code: "323111", subsector: "323", sector: "31-33", title: "Commercial Printing" },
  "Printing & Signage": { code: "323111", subsector: "323", sector: "31-33", title: "Commercial Printing" },
  "printing": { code: "323111", subsector: "323", sector: "31-33", title: "Commercial Printing" },
  "Signage Manufacturing": { code: "339950", subsector: "339", sector: "31-33", title: "Sign Manufacturing" },
  "Composites": { code: "326199", subsector: "326", sector: "31-33", title: "All Other Plastics Product Manufacturing" },
  "Bio-based Composites": { code: "326199", subsector: "326", sector: "31-33", title: "All Other Plastics Product Manufacturing" },
  "Aluminum smelter": { code: "331313", subsector: "331", sector: "31-33", title: "Alumina Refining and Primary Aluminum Production" },
  "Steel Manufacturing": { code: "331110", subsector: "331", sector: "31-33", title: "Iron and Steel Mills" },
  "Metal Fabrication": { code: "332310", subsector: "332", sector: "31-33", title: "Plate Work and Fabricated Structural Product Mfg" },
  "CNC Machining": { code: "332710", subsector: "332", sector: "31-33", title: "Machine Shops" },
  "Welding": { code: "332710", subsector: "332", sector: "31-33", title: "Machine Shops" },
  "Machining": { code: "332710", subsector: "332", sector: "31-33", title: "Machine Shops" },
  "Electronics Manufacturing": { code: "334410", subsector: "334", sector: "31-33", title: "Semiconductor and Electronic Component Mfg" },
  "Oceanographic Equipment": { code: "334511", subsector: "334", sector: "31-33", title: "Search, Detection, Navigation Instruments" },
  "Aerospace": { code: "336411", subsector: "336", sector: "31-33", title: "Aircraft Manufacturing" },
  "Marine Manufacturing": { code: "336612", subsector: "336", sector: "31-33", title: "Boat Building" },
  "Boat Building": { code: "336612", subsector: "336", sector: "31-33", title: "Boat Building" },
  "Furniture Manufacturing": { code: "337110", subsector: "337", sector: "31-33", title: "Wood Kitchen Cabinet and Countertop Mfg" },
  "Advanced Materials": { code: "339999", subsector: "339", sector: "31-33", title: "All Other Miscellaneous Manufacturing" },
  "Defence": { code: "332994", subsector: "332", sector: "31-33", title: "Small Arms, Ordnance Mfg" },
  "Windows Manufacturing": { code: "332321", subsector: "332", sector: "31-33", title: "Metal Window and Door Manufacturing" },

  // ============================================================================
  // SECTOR 42: WHOLESALE TRADE
  // ============================================================================
  "Wholesale": { code: "423000", subsector: "423", sector: "42", title: "Merchant Wholesalers, Durable Goods" },
  "Industrial Equipment": { code: "423830", subsector: "423", sector: "42", title: "Industrial Machinery and Equipment Wholesalers" },
  "Wholesale/Optical": { code: "423460", subsector: "423", sector: "42", title: "Ophthalmic Goods Merchant Wholesalers" },
  "Auto & Marine Parts": { code: "423120", subsector: "423", sector: "42", title: "Motor Vehicle Supplies Wholesalers" },
  "Food Distributor": { code: "424410", subsector: "424", sector: "42", title: "General Line Grocery Merchant Wholesalers" },

  // ============================================================================
  // SECTOR 44-45: RETAIL TRADE
  // ============================================================================
  "automotive": { code: "441100", subsector: "441", sector: "44-45", title: "Automobile Dealers" },
  "Car Dealership": { code: "441110", subsector: "441", sector: "44-45", title: "New Car Dealers" },
  "Auto Dealer": { code: "441110", subsector: "441", sector: "44-45", title: "New Car Dealers" },
  "Used Car Dealer": { code: "441120", subsector: "441", sector: "44-45", title: "Used Car Dealers" },
  "Used Car Dealership": { code: "441120", subsector: "441", sector: "44-45", title: "Used Car Dealers" },
  "RV Dealer": { code: "441210", subsector: "441", sector: "44-45", title: "Recreational Vehicle Dealers" },
  "Motorcycle Dealer": { code: "441228", subsector: "441", sector: "44-45", title: "Motorcycle, ATV Dealers" },
  "Auto Parts": { code: "441310", subsector: "441", sector: "44-45", title: "Automotive Parts and Accessories Stores" },
  "Tire Dealer": { code: "441320", subsector: "441", sector: "44-45", title: "Tire Dealers" },
  "Furniture": { code: "442110", subsector: "442", sector: "44-45", title: "Furniture Stores" },
  "Furniture Store": { code: "442110", subsector: "442", sector: "44-45", title: "Furniture Stores" },
  "Home Decor": { code: "442299", subsector: "442", sector: "44-45", title: "All Other Home Furnishings Stores" },
  "Lighting": { code: "442299", subsector: "442", sector: "44-45", title: "All Other Home Furnishings Stores" },
  "Electronics Retail": { code: "443142", subsector: "443", sector: "44-45", title: "Electronics Stores" },
  "Appliances": { code: "443141", subsector: "443", sector: "44-45", title: "Household Appliance Stores" },
  "Hardware Store": { code: "444130", subsector: "444", sector: "44-45", title: "Hardware Stores" },
  "hardware-supplies": { code: "444130", subsector: "444", sector: "44-45", title: "Hardware Stores" },
  "Building supplies": { code: "444110", subsector: "444", sector: "44-45", title: "Home Centers" },
  "Garden Supplies": { code: "444220", subsector: "444", sector: "44-45", title: "Nursery, Garden Center, Farm Supply Stores" },
  "Turf/Garden Supplies": { code: "444220", subsector: "444", sector: "44-45", title: "Nursery, Garden Center, Farm Supply Stores" },
  "grocery": { code: "445110", subsector: "445", sector: "44-45", title: "Supermarkets and Other Grocery Stores" },
  "Grocery Store": { code: "445110", subsector: "445", sector: "44-45", title: "Supermarkets and Other Grocery Stores" },
  "Asian supermarket": { code: "445110", subsector: "445", sector: "44-45", title: "Supermarkets and Other Grocery Stores" },
  "Liquor Store": { code: "445310", subsector: "445", sector: "44-45", title: "Beer, Wine, and Liquor Stores" },
  "Wine Store": { code: "445310", subsector: "445", sector: "44-45", title: "Beer, Wine, and Liquor Stores" },
  "Candy/gifts": { code: "445292", subsector: "445", sector: "44-45", title: "Confectionery and Nut Stores" },
  "Specialty Food": { code: "445299", subsector: "445", sector: "44-45", title: "All Other Specialty Food Stores" },
  "pharmacy": { code: "446110", subsector: "446", sector: "44-45", title: "Pharmacies and Drug Stores" },
  "Pharmacy": { code: "446110", subsector: "446", sector: "44-45", title: "Pharmacies and Drug Stores" },
  "Clothing": { code: "448140", subsector: "448", sector: "44-45", title: "Family Clothing Stores" },
  "Clothing/Gifts": { code: "448140", subsector: "448", sector: "44-45", title: "Family Clothing Stores" },
  "Consignment Clothing": { code: "448190", subsector: "448", sector: "44-45", title: "Other Clothing Stores" },
  "Activewear": { code: "448110", subsector: "448", sector: "44-45", title: "Men's Clothing Stores" },
  "Athletic apparel": { code: "448110", subsector: "448", sector: "44-45", title: "Men's Clothing Stores" },
  "Beach apparel": { code: "448140", subsector: "448", sector: "44-45", title: "Family Clothing Stores" },
  "Jewellery": { code: "448310", subsector: "448", sector: "44-45", title: "Jewelry Stores" },
  "Jeweller": { code: "448310", subsector: "448", sector: "44-45", title: "Jewelry Stores" },
  "Jewellery & Accessories": { code: "448310", subsector: "448", sector: "44-45", title: "Jewelry Stores" },
  "Artisan Jewellery": { code: "448310", subsector: "448", sector: "44-45", title: "Jewelry Stores" },
  "Eyewear": { code: "448320", subsector: "448", sector: "44-45", title: "Luggage and Leather Goods Stores" },
  "Bookstore": { code: "451211", subsector: "451", sector: "44-45", title: "Book Stores" },
  "Sporting Goods": { code: "451110", subsector: "451", sector: "44-45", title: "Sporting Goods Stores" },
  "Outdoor Gear": { code: "451110", subsector: "451", sector: "44-45", title: "Sporting Goods Stores" },
  "Surf shop": { code: "451110", subsector: "451", sector: "44-45", title: "Sporting Goods Stores" },
  "Ski Shop": { code: "451110", subsector: "451", sector: "44-45", title: "Sporting Goods Stores" },
  "Bicycle Shop": { code: "451110", subsector: "451", sector: "44-45", title: "Sporting Goods Stores" },
  "Bicycle Dealer": { code: "451110", subsector: "451", sector: "44-45", title: "Sporting Goods Stores" },
  "Bicycle Dealers": { code: "451110", subsector: "451", sector: "44-45", title: "Sporting Goods Stores" },
  "Bicycle Parts": { code: "451110", subsector: "451", sector: "44-45", title: "Sporting Goods Stores" },
  "Bicycle Tires": { code: "451110", subsector: "451", sector: "44-45", title: "Sporting Goods Stores" },
  "Bike rentals/sales": { code: "451110", subsector: "451", sector: "44-45", title: "Sporting Goods Stores" },
  "Department Store": { code: "452210", subsector: "452", sector: "44-45", title: "Department Stores" },
  "Warehouse Club": { code: "452311", subsector: "452", sector: "44-45", title: "Warehouse Clubs and Supercenters" },
  "Warehouse Retail": { code: "452311", subsector: "452", sector: "44-45", title: "Warehouse Clubs and Supercenters" },
  "retail": { code: "453998", subsector: "453", sector: "44-45", title: "All Other Miscellaneous Store Retailers" },
  "Florist": { code: "453110", subsector: "453", sector: "44-45", title: "Florists" },
  "Florists": { code: "453110", subsector: "453", sector: "44-45", title: "Florists" },
  "Gift Shop": { code: "453220", subsector: "453", sector: "44-45", title: "Gift, Novelty, and Souvenir Stores" },
  "Pet Store": { code: "453910", subsector: "453", sector: "44-45", title: "Pet and Pet Supplies Stores" },
  "Pet Supplies": { code: "453910", subsector: "453", sector: "44-45", title: "Pet and Pet Supplies Stores" },
  "pets": { code: "453910", subsector: "453", sector: "44-45", title: "Pet and Pet Supplies Stores" },
  "cannabis": { code: "453991", subsector: "453", sector: "44-45", title: "Tobacco Stores" },
  "Cannabis Retail": { code: "453991", subsector: "453", sector: "44-45", title: "Tobacco Stores" },
  "Baby Products": { code: "453998", subsector: "453", sector: "44-45", title: "All Other Miscellaneous Store Retailers" },
  "Beauty Subscription": { code: "453998", subsector: "453", sector: "44-45", title: "All Other Miscellaneous Store Retailers" },
  "Cosmetics": { code: "453998", subsector: "453", sector: "44-45", title: "All Other Miscellaneous Store Retailers" },
  "Bullion & Currency": { code: "453998", subsector: "453", sector: "44-45", title: "All Other Miscellaneous Store Retailers" },
  "Shopping centre": { code: "531120", subsector: "531", sector: "53", title: "Lessors of Nonresidential Buildings" },
  "Beverage Retailer": { code: "445310", subsector: "445", sector: "44-45", title: "Beer, Wine, and Liquor Stores" },

  // ============================================================================
  // SECTOR 48-49: TRANSPORTATION AND WAREHOUSING
  // ============================================================================
  "aviation": { code: "481000", subsector: "481", sector: "48-49", title: "Air Transportation" },
  "Airline": { code: "481111", subsector: "481", sector: "48-49", title: "Scheduled Passenger Air Transportation" },
  "Helicopter": { code: "481219", subsector: "481", sector: "48-49", title: "Other Nonscheduled Air Transportation" },
  "Seaplane": { code: "481219", subsector: "481", sector: "48-49", title: "Other Nonscheduled Air Transportation" },
  "Charter Aviation": { code: "481211", subsector: "481", sector: "48-49", title: "Nonscheduled Chartered Passenger Air Transportation" },
  "Aircraft maintenance": { code: "488190", subsector: "488", sector: "48-49", title: "Other Support Activities for Air Transportation" },
  "Airport": { code: "488119", subsector: "488", sector: "48-49", title: "Other Airport Operations" },
  "marine": { code: "483000", subsector: "483", sector: "48-49", title: "Water Transportation" },
  "Ferry": { code: "483212", subsector: "483", sector: "48-49", title: "Inland Water Passenger Transportation" },
  "Ferry terminal": { code: "488310", subsector: "488", sector: "48-49", title: "Port and Harbor Operations" },
  "Ferry Service": { code: "483212", subsector: "483", sector: "48-49", title: "Inland Water Passenger Transportation" },
  "Water taxi": { code: "483212", subsector: "483", sector: "48-49", title: "Inland Water Passenger Transportation" },
  "Cargo Handling": { code: "488320", subsector: "488", sector: "48-49", title: "Marine Cargo Handling" },
  "Port authority": { code: "488310", subsector: "488", sector: "48-49", title: "Port and Harbor Operations" },
  "Harbour authority": { code: "488310", subsector: "488", sector: "48-49", title: "Port and Harbor Operations" },
  "trucking-freight": { code: "484000", subsector: "484", sector: "48-49", title: "Truck Transportation" },
  "Freight": { code: "484121", subsector: "484", sector: "48-49", title: "General Freight Trucking, Long-Distance" },
  "Logistics": { code: "484110", subsector: "484", sector: "48-49", title: "General Freight Trucking, Local" },
  "transit": { code: "485000", subsector: "485", sector: "48-49", title: "Transit and Ground Passenger Transportation" },
  "taxi-rideshare": { code: "485310", subsector: "485", sector: "48-49", title: "Taxi Service" },
  "Bus service": { code: "485210", subsector: "485", sector: "48-49", title: "Interurban and Rural Bus Transportation" },
  "Bus & Limousine": { code: "485320", subsector: "485", sector: "48-49", title: "Limousine Service" },
  "Charter Bus": { code: "485510", subsector: "485", sector: "48-49", title: "Charter Bus Industry" },
  "Limousine": { code: "485320", subsector: "485", sector: "48-49", title: "Limousine Service" },
  "Transportation/Limousine": { code: "485320", subsector: "485", sector: "48-49", title: "Limousine Service" },
  "Rideshare": { code: "485310", subsector: "485", sector: "48-49", title: "Taxi Service" },
  "Commuter rail": { code: "485112", subsector: "485", sector: "48-49", title: "Commuter Rail Systems" },
  "Micromobility": { code: "485999", subsector: "485", sector: "48-49", title: "All Other Transit and Ground Passenger Transportation" },
  "Ground Transportation": { code: "485999", subsector: "485", sector: "48-49", title: "All Other Transit and Ground Passenger Transportation" },
  "transportation": { code: "488000", subsector: "488", sector: "48-49", title: "Support Activities for Transportation" },
  "Towing": { code: "488410", subsector: "488", sector: "48-49", title: "Motor Vehicle Towing" },
  "towing": { code: "488410", subsector: "488", sector: "48-49", title: "Motor Vehicle Towing" },
  "Postal": { code: "491110", subsector: "491", sector: "48-49", title: "Postal Service" },
  "courier-delivery": { code: "492110", subsector: "492", sector: "48-49", title: "Couriers and Express Delivery Services" },
  "Courier Services": { code: "492110", subsector: "492", sector: "48-49", title: "Couriers and Express Delivery Services" },
  "Delivery Services": { code: "492210", subsector: "492", sector: "48-49", title: "Local Messengers and Local Delivery" },
  "Storage": { code: "493110", subsector: "493", sector: "48-49", title: "General Warehousing and Storage" },
  "storage": { code: "493110", subsector: "493", sector: "48-49", title: "General Warehousing and Storage" },
  "Moving Company": { code: "484210", subsector: "484", sector: "48-49", title: "Used Household and Office Goods Moving" },

  // ============================================================================
  // SECTOR 51: INFORMATION
  // ============================================================================
  "cc_media": { code: "511000", subsector: "511", sector: "51", title: "Publishing Industries" },
  "Newspaper": { code: "511110", subsector: "511", sector: "51", title: "Newspaper Publishers" },
  "Community News": { code: "511110", subsector: "511", sector: "51", title: "Newspaper Publishers" },
  "Online Magazine": { code: "511120", subsector: "511", sector: "51", title: "Periodical Publishers" },
  "Business Magazine": { code: "511120", subsector: "511", sector: "51", title: "Periodical Publishers" },
  "Magazine": { code: "511120", subsector: "511", sector: "51", title: "Periodical Publishers" },
  "Publishing": { code: "511130", subsector: "511", sector: "51", title: "Book Publishers" },
  "Software": { code: "511210", subsector: "511", sector: "51", title: "Software Publishers" },
  "Software Development": { code: "511210", subsector: "511", sector: "51", title: "Software Publishers" },
  "SaaS": { code: "511210", subsector: "511", sector: "51", title: "Software Publishers" },
  "Video games": { code: "511210", subsector: "511", sector: "51", title: "Software Publishers" },
  "Visual Effects Software": { code: "511210", subsector: "511", sector: "51", title: "Software Publishers" },
  "Film Production": { code: "512110", subsector: "512", sector: "51", title: "Motion Picture and Video Production" },
  "Video Production": { code: "512110", subsector: "512", sector: "51", title: "Motion Picture and Video Production" },
  "entertainment": { code: "512000", subsector: "512", sector: "51", title: "Motion Picture and Sound Recording Industries" },
  "Podcast": { code: "512290", subsector: "512", sector: "51", title: "Other Sound Recording Industries" },
  "Television": { code: "515120", subsector: "515", sector: "51", title: "Television Broadcasting" },
  "Broadcasting": { code: "515120", subsector: "515", sector: "51", title: "Television Broadcasting" },
  "Radio": { code: "515112", subsector: "515", sector: "51", title: "Radio Stations" },
  "Community radio": { code: "515112", subsector: "515", sector: "51", title: "Radio Stations" },
  "telecommunications": { code: "517000", subsector: "517", sector: "51", title: "Telecommunications" },
  "Telecommunications": { code: "517311", subsector: "517", sector: "51", title: "Wired Telecommunications Carriers" },
  "Wireless Services": { code: "517312", subsector: "517", sector: "51", title: "Wireless Telecommunications Carriers" },
  "Wireless Solutions": { code: "517312", subsector: "517", sector: "51", title: "Wireless Telecommunications Carriers" },
  "Communications": { code: "517311", subsector: "517", sector: "51", title: "Wired Telecommunications Carriers" },
  "Communications Provider": { code: "517311", subsector: "517", sector: "51", title: "Wired Telecommunications Carriers" },
  "Internet Provider": { code: "517311", subsector: "517", sector: "51", title: "Wired Telecommunications Carriers" },
  "Cloud cc_services": { code: "518210", subsector: "518", sector: "51", title: "Data Processing, Hosting, Related Services" },
  "Data Centre": { code: "518210", subsector: "518", sector: "51", title: "Data Processing, Hosting, Related Services" },
  "News Media": { code: "519130", subsector: "519", sector: "51", title: "Internet Publishing and Broadcasting" },
  "Digital Media": { code: "519130", subsector: "519", sector: "51", title: "Internet Publishing and Broadcasting" },
  "Content Production": { code: "519130", subsector: "519", sector: "51", title: "Internet Publishing and Broadcasting" },

  // ============================================================================
  // SECTOR 52: FINANCE AND INSURANCE
  // ============================================================================
  "banking-finance": { code: "522000", subsector: "522", sector: "52", title: "Credit Intermediation and Related Activities" },
  "financial-cc_services": { code: "522000", subsector: "522", sector: "52", title: "Credit Intermediation and Related Activities" },
  "finance": { code: "522000", subsector: "522", sector: "52", title: "Credit Intermediation and Related Activities" },
  "Bank": { code: "522110", subsector: "522", sector: "52", title: "Commercial Banking" },
  "Credit Union": { code: "522130", subsector: "522", sector: "52", title: "Credit Unions" },
  "Credit union": { code: "522130", subsector: "522", sector: "52", title: "Credit Unions" },
  "Mortgage Broker": { code: "522310", subsector: "522", sector: "52", title: "Mortgage and Nonmortgage Loan Brokers" },
  "Mortgage Services": { code: "522310", subsector: "522", sector: "52", title: "Mortgage and Nonmortgage Loan Brokers" },
  "Fintech": { code: "522320", subsector: "522", sector: "52", title: "Financial Transactions Processing" },
  "Payment Processing": { code: "522320", subsector: "522", sector: "52", title: "Financial Transactions Processing" },
  "Currency Exchange": { code: "522390", subsector: "522", sector: "52", title: "Other Activities Related to Credit Intermediation" },
  "Investment Management": { code: "523920", subsector: "523", sector: "52", title: "Portfolio Management" },
  "Wealth Management": { code: "523930", subsector: "523", sector: "52", title: "Investment Advice" },
  "Financial Planning": { code: "523930", subsector: "523", sector: "52", title: "Investment Advice" },
  "Financial Advisor": { code: "523930", subsector: "523", sector: "52", title: "Investment Advice" },
  "Insurance": { code: "524210", subsector: "524", sector: "52", title: "Insurance Agencies and Brokerages" },
  "insurance": { code: "524210", subsector: "524", sector: "52", title: "Insurance Agencies and Brokerages" },
  "Insurance Brokerage": { code: "524210", subsector: "524", sector: "52", title: "Insurance Agencies and Brokerages" },
  "Insurance Broker": { code: "524210", subsector: "524", sector: "52", title: "Insurance Agencies and Brokerages" },
  "Title Insurance": { code: "524127", subsector: "524", sector: "52", title: "Direct Title Insurance Carriers" },

  // ============================================================================
  // SECTOR 53: REAL ESTATE AND RENTAL AND LEASING
  // ============================================================================
  "real-estate": { code: "531000", subsector: "531", sector: "53", title: "Real Estate" },
  "Real Estate Brokerage": { code: "531210", subsector: "531", sector: "53", title: "Offices of Real Estate Agents and Brokers" },
  "Real Estate": { code: "531210", subsector: "531", sector: "53", title: "Offices of Real Estate Agents and Brokers" },
  "Real Estate Development": { code: "531390", subsector: "531", sector: "53", title: "Other Activities Related to Real Estate" },
  "Property Management": { code: "531311", subsector: "531", sector: "53", title: "Residential Property Managers" },
  "property-management": { code: "531311", subsector: "531", sector: "53", title: "Residential Property Managers" },
  "Property Developer": { code: "531390", subsector: "531", sector: "53", title: "Other Activities Related to Real Estate" },
  "Commercial Real Estate": { code: "531120", subsector: "531", sector: "53", title: "Lessors of Nonresidential Buildings" },
  "Residential Real Estate": { code: "531210", subsector: "531", sector: "53", title: "Offices of Real Estate Agents and Brokers" },
  "Land Development": { code: "531390", subsector: "531", sector: "53", title: "Other Activities Related to Real Estate" },
  "Strata Management": { code: "531311", subsector: "531", sector: "53", title: "Residential Property Managers" },
  "Equipment Rental": { code: "532412", subsector: "532", sector: "53", title: "Construction, Mining, Forestry Machinery Rental" },
  "Tool Rental": { code: "532310", subsector: "532", sector: "53", title: "General Rental Centers" },
  "Event Rentals": { code: "532289", subsector: "532", sector: "53", title: "All Other Consumer Goods Rental" },

  // ============================================================================
  // SECTOR 54: PROFESSIONAL, SCIENTIFIC, AND TECHNICAL SERVICES
  // ============================================================================
  "professional-cc_services": { code: "541000", subsector: "541", sector: "54", title: "Professional, Scientific, and Technical Services" },
  "professional": { code: "541000", subsector: "541", sector: "54", title: "Professional, Scientific, and Technical Services" },
  "Professional cc_services": { code: "541000", subsector: "541", sector: "54", title: "Professional, Scientific, and Technical Services" },
  "cc_services": { code: "541000", subsector: "541", sector: "54", title: "Professional, Scientific, and Technical Services" },
  "legal": { code: "541110", subsector: "541", sector: "54", title: "Offices of Lawyers" },
  "Law Firm": { code: "541110", subsector: "541", sector: "54", title: "Offices of Lawyers" },
  "Law firm": { code: "541110", subsector: "541", sector: "54", title: "Offices of Lawyers" },
  "Family Law": { code: "541110", subsector: "541", sector: "54", title: "Offices of Lawyers" },
  "Indigenous Law": { code: "541110", subsector: "541", sector: "54", title: "Offices of Lawyers" },
  "Real Estate Law": { code: "541110", subsector: "541", sector: "54", title: "Offices of Lawyers" },
  "Corporate Law": { code: "541110", subsector: "541", sector: "54", title: "Offices of Lawyers" },
  "Employment Law": { code: "541110", subsector: "541", sector: "54", title: "Offices of Lawyers" },
  "Immigration Law": { code: "541110", subsector: "541", sector: "54", title: "Offices of Lawyers" },
  "Criminal Law": { code: "541110", subsector: "541", sector: "54", title: "Offices of Lawyers" },
  "Personal Injury": { code: "541110", subsector: "541", sector: "54", title: "Offices of Lawyers" },
  "Full Service Law Firm": { code: "541110", subsector: "541", sector: "54", title: "Offices of Lawyers" },
  "Notary Public": { code: "541120", subsector: "541", sector: "54", title: "Offices of Notaries" },
  "Notary": { code: "541120", subsector: "541", sector: "54", title: "Offices of Notaries" },
  "Legal Services": { code: "541199", subsector: "541", sector: "54", title: "All Other Legal Services" },
  "Paralegal": { code: "541199", subsector: "541", sector: "54", title: "All Other Legal Services" },
  "Mediation": { code: "541199", subsector: "541", sector: "54", title: "All Other Legal Services" },
  "accounting": { code: "541211", subsector: "541", sector: "54", title: "Offices of Certified Public Accountants" },
  "Accounting Firm": { code: "541211", subsector: "541", sector: "54", title: "Offices of Certified Public Accountants" },
  "Chartered Professional Accountants": { code: "541211", subsector: "541", sector: "54", title: "Offices of Certified Public Accountants" },
  "CPA Firm": { code: "541211", subsector: "541", sector: "54", title: "Offices of Certified Public Accountants" },
  "Bookkeeping": { code: "541219", subsector: "541", sector: "54", title: "Other Accounting Services" },
  "CFO Services": { code: "541219", subsector: "541", sector: "54", title: "Other Accounting Services" },
  "Tax Services": { code: "541213", subsector: "541", sector: "54", title: "Tax Preparation Services" },
  "Architecture": { code: "541310", subsector: "541", sector: "54", title: "Architectural Services" },
  "Architect": { code: "541310", subsector: "541", sector: "54", title: "Architectural Services" },
  "Engineering": { code: "541330", subsector: "541", sector: "54", title: "Engineering Services" },
  "engineering": { code: "541330", subsector: "541", sector: "54", title: "Engineering Services" },
  "Structural Engineering": { code: "541330", subsector: "541", sector: "54", title: "Engineering Services" },
  "Civil Engineering": { code: "541330", subsector: "541", sector: "54", title: "Engineering Services" },
  "Environmental Engineering": { code: "541330", subsector: "541", sector: "54", title: "Engineering Services" },
  "Mechanical Engineering": { code: "541330", subsector: "541", sector: "54", title: "Engineering Services" },
  "Electrical Engineering": { code: "541330", subsector: "541", sector: "54", title: "Engineering Services" },
  "Landscape Architecture": { code: "541320", subsector: "541", sector: "54", title: "Landscape Architectural Services" },
  "Landscape Design": { code: "541320", subsector: "541", sector: "54", title: "Landscape Architectural Services" },
  "Interior Design": { code: "541410", subsector: "541", sector: "54", title: "Interior Design Services" },
  "Industrial Design": { code: "541420", subsector: "541", sector: "54", title: "Industrial Design Services" },
  "Surveying": { code: "541370", subsector: "541", sector: "54", title: "Surveying and Mapping Services" },
  "GIS": { code: "541370", subsector: "541", sector: "54", title: "Surveying and Mapping Services" },
  "Home Inspection": { code: "541350", subsector: "541", sector: "54", title: "Building Inspection Services" },
  "Appraisal": { code: "541320", subsector: "541", sector: "54", title: "Landscape Architectural Services" },
  "Graphic Design": { code: "541430", subsector: "541", sector: "54", title: "Graphic Design Services" },
  "creative": { code: "541430", subsector: "541", sector: "54", title: "Graphic Design Services" },
  "technology": { code: "541512", subsector: "541", sector: "54", title: "Computer Systems Design Services" },
  "it-technology": { code: "541512", subsector: "541", sector: "54", title: "Computer Systems Design Services" },
  "IT Services": { code: "541512", subsector: "541", sector: "54", title: "Computer Systems Design Services" },
  "IT Solutions": { code: "541512", subsector: "541", sector: "54", title: "Computer Systems Design Services" },
  "IT Consulting": { code: "541512", subsector: "541", sector: "54", title: "Computer Systems Design Services" },
  "Managed IT": { code: "541512", subsector: "541", sector: "54", title: "Computer Systems Design Services" },
  "Computer Services": { code: "541512", subsector: "541", sector: "54", title: "Computer Systems Design Services" },
  "Web Development": { code: "541511", subsector: "541", sector: "54", title: "Custom Computer Programming Services" },
  "Web Design": { code: "541511", subsector: "541", sector: "54", title: "Custom Computer Programming Services" },
  "Web Design & Marketing": { code: "541511", subsector: "541", sector: "54", title: "Custom Computer Programming Services" },
  "Web Design & SEO": { code: "541511", subsector: "541", sector: "54", title: "Custom Computer Programming Services" },
  "Web Development & Marketing": { code: "541511", subsector: "541", sector: "54", title: "Custom Computer Programming Services" },
  "Web Development/SEO": { code: "541511", subsector: "541", sector: "54", title: "Custom Computer Programming Services" },
  "Web Marketing": { code: "541511", subsector: "541", sector: "54", title: "Custom Computer Programming Services" },
  "App Development": { code: "541511", subsector: "541", sector: "54", title: "Custom Computer Programming Services" },
  "Mobile Apps": { code: "541511", subsector: "541", sector: "54", title: "Custom Computer Programming Services" },
  "Cybersecurity": { code: "541512", subsector: "541", sector: "54", title: "Computer Systems Design Services" },
  "AI/Machine Learning": { code: "541512", subsector: "541", sector: "54", title: "Computer Systems Design Services" },
  "Marine Technology": { code: "541512", subsector: "541", sector: "54", title: "Computer Systems Design Services" },
  "consulting": { code: "541611", subsector: "541", sector: "54", title: "Administrative Management Consulting Services" },
  "Management Consulting": { code: "541611", subsector: "541", sector: "54", title: "Administrative Management Consulting Services" },
  "Management Consultant": { code: "541611", subsector: "541", sector: "54", title: "Administrative Management Consulting Services" },
  "Strategic Consulting": { code: "541611", subsector: "541", sector: "54", title: "Administrative Management Consulting Services" },
  "Business Consulting": { code: "541611", subsector: "541", sector: "54", title: "Administrative Management Consulting Services" },
  "Business consulting": { code: "541611", subsector: "541", sector: "54", title: "Administrative Management Consulting Services" },
  "Business Strategy": { code: "541611", subsector: "541", sector: "54", title: "Administrative Management Consulting Services" },
  "Business Coaching": { code: "541611", subsector: "541", sector: "54", title: "Administrative Management Consulting Services" },
  "HR Consulting": { code: "541612", subsector: "541", sector: "54", title: "Human Resources Consulting Services" },
  "Environmental Consulting": { code: "541620", subsector: "541", sector: "54", title: "Environmental Consulting Services" },
  "environmental": { code: "541620", subsector: "541", sector: "54", title: "Environmental Consulting Services" },
  "Safety Consulting": { code: "541690", subsector: "541", sector: "54", title: "Other Scientific and Technical Consulting" },
  "marketing": { code: "541810", subsector: "541", sector: "54", title: "Advertising Agencies" },
  "marketing-advertising": { code: "541810", subsector: "541", sector: "54", title: "Advertising Agencies" },
  "Marketing Agency": { code: "541810", subsector: "541", sector: "54", title: "Advertising Agencies" },
  "Digital Marketing": { code: "541810", subsector: "541", sector: "54", title: "Advertising Agencies" },
  "Growth Marketing": { code: "541810", subsector: "541", sector: "54", title: "Advertising Agencies" },
  "Advertising Agency": { code: "541810", subsector: "541", sector: "54", title: "Advertising Agencies" },
  "Marketing": { code: "541810", subsector: "541", sector: "54", title: "Advertising Agencies" },
  "Public Relations": { code: "541820", subsector: "541", sector: "54", title: "Public Relations Agencies" },
  "Photography": { code: "541921", subsector: "541", sector: "54", title: "Photography Studios, Portrait" },
  "photography": { code: "541921", subsector: "541", sector: "54", title: "Photography Studios, Portrait" },
  "Photography Studio": { code: "541921", subsector: "541", sector: "54", title: "Photography Studios, Portrait" },
  "Wedding Photography": { code: "541921", subsector: "541", sector: "54", title: "Photography Studios, Portrait" },
  "Translation": { code: "541930", subsector: "541", sector: "54", title: "Translation and Interpretation Services" },
  "Immigration Consulting": { code: "541990", subsector: "541", sector: "54", title: "All Other Professional, Scientific, Technical Services" },
  "veterinary": { code: "541940", subsector: "541", sector: "54", title: "Veterinary Services" },
  "Veterinary": { code: "541940", subsector: "541", sector: "54", title: "Veterinary Services" },

  // ============================================================================
  // SECTOR 55: MANAGEMENT OF COMPANIES AND ENTERPRISES
  // ============================================================================
  "Holding Company": { code: "551112", subsector: "551", sector: "55", title: "Offices of Other Holding Companies" },
  "Head Office": { code: "551114", subsector: "551", sector: "55", title: "Corporate, Subsidiary, Regional Managing Offices" },

  // ============================================================================
  // SECTOR 56: ADMINISTRATIVE AND SUPPORT AND WASTE MANAGEMENT
  // ============================================================================
  "Employment Services": { code: "561310", subsector: "561", sector: "56", title: "Employment Placement Agencies" },
  "Recruitment": { code: "561310", subsector: "561", sector: "56", title: "Employment Placement Agencies" },
  "Staffing Agency": { code: "561320", subsector: "561", sector: "56", title: "Temporary Help Services" },
  "Executive Search": { code: "561312", subsector: "561", sector: "56", title: "Executive Search Services" },
  "Security": { code: "561612", subsector: "561", sector: "56", title: "Security Guards and Patrol Services" },
  "Security Services": { code: "561612", subsector: "561", sector: "56", title: "Security Guards and Patrol Services" },
  "security": { code: "561612", subsector: "561", sector: "56", title: "Security Guards and Patrol Services" },
  "Cleaning Services": { code: "561720", subsector: "561", sector: "56", title: "Janitorial Services" },
  "Commercial Cleaning": { code: "561720", subsector: "561", sector: "56", title: "Janitorial Services" },
  "cleaning-janitorial": { code: "561720", subsector: "561", sector: "56", title: "Janitorial Services" },
  "House Cleaning": { code: "561720", subsector: "561", sector: "56", title: "Janitorial Services" },
  "Janitorial": { code: "561720", subsector: "561", sector: "56", title: "Janitorial Services" },
  "Window Cleaning": { code: "561720", subsector: "561", sector: "56", title: "Janitorial Services" },
  "Building Maintenance": { code: "561210", subsector: "561", sector: "56", title: "Facilities Support Services" },
  "Property Maintenance": { code: "561730", subsector: "561", sector: "56", title: "Landscaping Services" },
  "Landscaping": { code: "561730", subsector: "561", sector: "56", title: "Landscaping Services" },
  "landscaping": { code: "561730", subsector: "561", sector: "56", title: "Landscaping Services" },
  "Water Features/Landscape": { code: "561730", subsector: "561", sector: "56", title: "Landscaping Services" },
  "Sign Services": { code: "561920", subsector: "561", sector: "56", title: "Convention and Trade Show Organizers" },
  "Printing Services": { code: "561439", subsector: "561", sector: "56", title: "Other Business Service Centers" },
  "Shredding": { code: "561990", subsector: "561", sector: "56", title: "All Other Support Services" },
  "Locksmith": { code: "561622", subsector: "561", sector: "56", title: "Locksmiths" },
  "Pest Control": { code: "561710", subsector: "561", sector: "56", title: "Exterminating and Pest Control Services" },
  "Waste Management": { code: "562111", subsector: "562", sector: "56", title: "Solid Waste Collection" },
  "Recycling": { code: "562920", subsector: "562", sector: "56", title: "Materials Recovery Facilities" },

  // ============================================================================
  // SECTOR 61: EDUCATIONAL SERVICES
  // ============================================================================
  "education": { code: "611000", subsector: "611", sector: "61", title: "Educational Services" },
  "College": { code: "611310", subsector: "611", sector: "61", title: "Colleges, Universities, Professional Schools" },
  "University": { code: "611310", subsector: "611", sector: "61", title: "Colleges, Universities, Professional Schools" },
  "Business School": { code: "611310", subsector: "611", sector: "61", title: "Colleges, Universities, Professional Schools" },
  "Community school": { code: "611110", subsector: "611", sector: "61", title: "Elementary and Secondary Schools" },
  "Independent school": { code: "611110", subsector: "611", sector: "61", title: "Elementary and Secondary Schools" },
  "Private school": { code: "611110", subsector: "611", sector: "61", title: "Elementary and Secondary Schools" },
  "Flight school": { code: "611512", subsector: "611", sector: "61", title: "Flight Training" },
  "Driving school": { code: "611692", subsector: "611", sector: "61", title: "Automobile Driving Schools" },
  "Language school": { code: "611630", subsector: "611", sector: "61", title: "Language Schools" },
  "Music school": { code: "611610", subsector: "611", sector: "61", title: "Fine Arts Schools" },
  "Training Centre": { code: "611430", subsector: "611", sector: "61", title: "Professional and Management Development Training" },
  "Professional Training": { code: "611430", subsector: "611", sector: "61", title: "Professional and Management Development Training" },
  "Leadership Training": { code: "611430", subsector: "611", sector: "61", title: "Professional and Management Development Training" },
  "Safety Training": { code: "611430", subsector: "611", sector: "61", title: "Professional and Management Development Training" },
  "Tutoring": { code: "611691", subsector: "611", sector: "61", title: "Exam Preparation and Tutoring" },
  "E-Learning": { code: "611710", subsector: "611", sector: "61", title: "Educational Support Services" },
  "Surf school": { code: "611620", subsector: "611", sector: "61", title: "Sports and Recreation Instruction" },

  // ============================================================================
  // SECTOR 62: HEALTH CARE AND SOCIAL ASSISTANCE
  // ============================================================================
  "healthcare": { code: "621000", subsector: "621", sector: "62", title: "Ambulatory Health Care Services" },
  "health": { code: "621000", subsector: "621", sector: "62", title: "Ambulatory Health Care Services" },
  "medical": { code: "621111", subsector: "621", sector: "62", title: "Offices of Physicians" },
  "Medical Clinic": { code: "621111", subsector: "621", sector: "62", title: "Offices of Physicians" },
  "Walk-in Clinic": { code: "621111", subsector: "621", sector: "62", title: "Offices of Physicians" },
  "Urgent Care": { code: "621493", subsector: "621", sector: "62", title: "Freestanding Ambulatory Surgical and Emergency Centers" },
  "Dentist": { code: "621210", subsector: "621", sector: "62", title: "Offices of Dentists" },
  "Dentistry": { code: "621210", subsector: "621", sector: "62", title: "Offices of Dentists" },
  "Dental Clinic": { code: "621210", subsector: "621", sector: "62", title: "Offices of Dentists" },
  "dental": { code: "621210", subsector: "621", sector: "62", title: "Offices of Dentists" },
  "Optometry": { code: "621320", subsector: "621", sector: "62", title: "Offices of Optometrists" },
  "Optometrist": { code: "621320", subsector: "621", sector: "62", title: "Offices of Optometrists" },
  "optometry": { code: "621320", subsector: "621", sector: "62", title: "Offices of Optometrists" },
  "Optical": { code: "621320", subsector: "621", sector: "62", title: "Offices of Optometrists" },
  "Physiotherapy": { code: "621340", subsector: "621", sector: "62", title: "Offices of Physical, Occupational Therapists" },
  "Physical Therapy": { code: "621340", subsector: "621", sector: "62", title: "Offices of Physical, Occupational Therapists" },
  "Chiropractic": { code: "621310", subsector: "621", sector: "62", title: "Offices of Chiropractors" },
  "Massage Therapy": { code: "621399", subsector: "621", sector: "62", title: "Offices of All Other Miscellaneous Health Practitioners" },
  "Acupuncture": { code: "621399", subsector: "621", sector: "62", title: "Offices of All Other Miscellaneous Health Practitioners" },
  "Naturopathic": { code: "621399", subsector: "621", sector: "62", title: "Offices of All Other Miscellaneous Health Practitioners" },
  "Mental Health": { code: "621330", subsector: "621", sector: "62", title: "Offices of Mental Health Practitioners" },
  "Counselling": { code: "621330", subsector: "621", sector: "62", title: "Offices of Mental Health Practitioners" },
  "Psychology": { code: "621330", subsector: "621", sector: "62", title: "Offices of Mental Health Practitioners" },
  "Medical Equipment": { code: "621610", subsector: "621", sector: "62", title: "Home Health Care Services" },
  "Mobility Equipment": { code: "423450", subsector: "423", sector: "42", title: "Medical Equipment Merchant Wholesalers" },
  "Hearing Aids": { code: "621340", subsector: "621", sector: "62", title: "Offices of Physical, Occupational Therapists" },
  "Hospital": { code: "622110", subsector: "622", sector: "62", title: "General Medical and Surgical Hospitals" },
  "Retirement Living": { code: "623311", subsector: "623", sector: "62", title: "Continuing Care Retirement Communities" },
  "seniors": { code: "623311", subsector: "623", sector: "62", title: "Continuing Care Retirement Communities" },
  "Assisted Living": { code: "623312", subsector: "623", sector: "62", title: "Assisted Living Facilities for the Elderly" },
  "Long Term Care": { code: "623110", subsector: "623", sector: "62", title: "Nursing Care Facilities" },
  "Senior Care": { code: "623311", subsector: "623", sector: "62", title: "Continuing Care Retirement Communities" },
  "Home Care": { code: "621610", subsector: "621", sector: "62", title: "Home Health Care Services" },
  "Childcare": { code: "624410", subsector: "624", sector: "62", title: "Child Day Care Services" },
  "childcare": { code: "624410", subsector: "624", sector: "62", title: "Child Day Care Services" },
  "Daycare": { code: "624410", subsector: "624", sector: "62", title: "Child Day Care Services" },
  "Early Learning": { code: "624410", subsector: "624", sector: "62", title: "Child Day Care Services" },
  "Community organization": { code: "624190", subsector: "624", sector: "62", title: "Other Individual and Family Services" },

  // ============================================================================
  // SECTOR 71: ARTS, ENTERTAINMENT, AND RECREATION
  // ============================================================================
  "arts-culture": { code: "711000", subsector: "711", sector: "71", title: "Performing Arts, Spectator Sports, Related" },
  "culture": { code: "711000", subsector: "711", sector: "71", title: "Performing Arts, Spectator Sports, Related" },
  "Theatre": { code: "711110", subsector: "711", sector: "71", title: "Theater Companies and Dinner Theaters" },
  "Performing arts": { code: "711110", subsector: "711", sector: "71", title: "Theater Companies and Dinner Theaters" },
  "Dance studio": { code: "711120", subsector: "711", sector: "71", title: "Dance Companies" },
  "Music Venue": { code: "711310", subsector: "711", sector: "71", title: "Promoters of Performing Arts with Facilities" },
  "Concert Hall": { code: "711310", subsector: "711", sector: "71", title: "Promoters of Performing Arts with Facilities" },
  "Event Centre": { code: "711310", subsector: "711", sector: "71", title: "Promoters of Performing Arts with Facilities" },
  "Event Venue": { code: "711310", subsector: "711", sector: "71", title: "Promoters of Performing Arts with Facilities" },
  "Arena": { code: "711310", subsector: "711", sector: "71", title: "Promoters of Performing Arts with Facilities" },
  "Sports Facility": { code: "711211", subsector: "711", sector: "71", title: "Sports Teams and Clubs" },
  "DJ Services": { code: "711510", subsector: "711", sector: "71", title: "Independent Artists, Writers, Performers" },
  "Artist studio": { code: "711510", subsector: "711", sector: "71", title: "Independent Artists, Writers, Performers" },
  "Airshow": { code: "711190", subsector: "711", sector: "71", title: "Other Performing Arts Companies" },
  "Museum": { code: "712110", subsector: "712", sector: "71", title: "Museums" },
  "Art museum": { code: "712110", subsector: "712", sector: "71", title: "Museums" },
  "Art Gallery": { code: "712110", subsector: "712", sector: "71", title: "Museums" },
  "Art gallery": { code: "712110", subsector: "712", sector: "71", title: "Museums" },
  "Aquarium": { code: "712130", subsector: "712", sector: "71", title: "Zoos and Botanical Gardens" },
  "Heritage site": { code: "712120", subsector: "712", sector: "71", title: "Historical Sites" },
  "Heritage museum": { code: "712120", subsector: "712", sector: "71", title: "Historical Sites" },
  "Heritage railway": { code: "712120", subsector: "712", sector: "71", title: "Historical Sites" },
  "Historical society": { code: "712120", subsector: "712", sector: "71", title: "Historical Sites" },
  "Indigenous cultural centre": { code: "712190", subsector: "712", sector: "71", title: "Nature Parks and Other Similar Institutions" },
  "Cultural centre": { code: "712190", subsector: "712", sector: "71", title: "Nature Parks and Other Similar Institutions" },
  "National park": { code: "712190", subsector: "712", sector: "71", title: "Nature Parks and Other Similar Institutions" },
  "Beach park": { code: "712190", subsector: "712", sector: "71", title: "Nature Parks and Other Similar Institutions" },
  "UNESCO Geopark": { code: "712190", subsector: "712", sector: "71", title: "Nature Parks and Other Similar Institutions" },
  "Wildlife area": { code: "712190", subsector: "712", sector: "71", title: "Nature Parks and Other Similar Institutions" },
  "recreation": { code: "713000", subsector: "713", sector: "71", title: "Amusement, Gambling, and Recreation Industries" },
  "Golf Course": { code: "713910", subsector: "713", sector: "71", title: "Golf Courses and Country Clubs" },
  "Golf Club": { code: "713910", subsector: "713", sector: "71", title: "Golf Courses and Country Clubs" },
  "Ski resort": { code: "713920", subsector: "713", sector: "71", title: "Skiing Facilities" },
  "Ski Resort": { code: "713920", subsector: "713", sector: "71", title: "Skiing Facilities" },
  "Marina": { code: "713930", subsector: "713", sector: "71", title: "Marinas" },
  "Yacht Club": { code: "713930", subsector: "713", sector: "71", title: "Marinas" },
  "Boat rental": { code: "713930", subsector: "713", sector: "71", title: "Marinas" },
  "Kayaking": { code: "713990", subsector: "713", sector: "71", title: "All Other Amusement and Recreation Industries" },
  "Paddleboarding": { code: "713990", subsector: "713", sector: "71", title: "All Other Amusement and Recreation Industries" },
  "Diving": { code: "713990", subsector: "713", sector: "71", title: "All Other Amusement and Recreation Industries" },
  "Casino": { code: "713210", subsector: "713", sector: "71", title: "Casinos (except Casino Hotels)" },
  "fitness-wellness": { code: "713940", subsector: "713", sector: "71", title: "Fitness and Recreational Sports Centers" },
  "Fitness Centre": { code: "713940", subsector: "713", sector: "71", title: "Fitness and Recreational Sports Centers" },
  "Gym": { code: "713940", subsector: "713", sector: "71", title: "Fitness and Recreational Sports Centers" },
  "Personal Training": { code: "713940", subsector: "713", sector: "71", title: "Fitness and Recreational Sports Centers" },
  "Sports Performance": { code: "713940", subsector: "713", sector: "71", title: "Fitness and Recreational Sports Centers" },
  "Athletic Training": { code: "713940", subsector: "713", sector: "71", title: "Fitness and Recreational Sports Centers" },
  "Yoga Studio": { code: "713940", subsector: "713", sector: "71", title: "Fitness and Recreational Sports Centers" },
  "Pilates": { code: "713940", subsector: "713", sector: "71", title: "Fitness and Recreational Sports Centers" },
  "Wellness Centre": { code: "713940", subsector: "713", sector: "71", title: "Fitness and Recreational Sports Centers" },
  "Curling Club": { code: "713940", subsector: "713", sector: "71", title: "Fitness and Recreational Sports Centers" },
  "Tennis Club": { code: "713940", subsector: "713", sector: "71", title: "Fitness and Recreational Sports Centers" },
  "Swimming Pool": { code: "713940", subsector: "713", sector: "71", title: "Fitness and Recreational Sports Centers" },
  "Bowling": { code: "713950", subsector: "713", sector: "71", title: "Bowling Centers" },
  "Skating": { code: "713940", subsector: "713", sector: "71", title: "Fitness and Recreational Sports Centers" },
  "Climbing": { code: "713940", subsector: "713", sector: "71", title: "Fitness and Recreational Sports Centers" },
  "Outdoor Recreation": { code: "713990", subsector: "713", sector: "71", title: "All Other Amusement and Recreation Industries" },
  "Adventure tours": { code: "713990", subsector: "713", sector: "71", title: "All Other Amusement and Recreation Industries" },
  "Adventure tourism": { code: "713990", subsector: "713", sector: "71", title: "All Other Amusement and Recreation Industries" },
  "Adventure outfitter": { code: "713990", subsector: "713", sector: "71", title: "All Other Amusement and Recreation Industries" },
  "Camping": { code: "713990", subsector: "713", sector: "71", title: "All Other Amusement and Recreation Industries" },
  "Hunting & Fishing": { code: "713990", subsector: "713", sector: "71", title: "All Other Amusement and Recreation Industries" },
  "Escape Room": { code: "713990", subsector: "713", sector: "71", title: "All Other Amusement and Recreation Industries" },
  "Party Supplies": { code: "532289", subsector: "532", sector: "53", title: "All Other Consumer Goods Rental" },
  "Fishing charters": { code: "487210", subsector: "487", sector: "48-49", title: "Scenic and Sightseeing Water Transportation" },
  "Whale watching": { code: "487210", subsector: "487", sector: "48-49", title: "Scenic and Sightseeing Water Transportation" },
  "Whale Watching": { code: "487210", subsector: "487", sector: "48-49", title: "Scenic and Sightseeing Water Transportation" },
  "Whale watching/museum": { code: "487210", subsector: "487", sector: "48-49", title: "Scenic and Sightseeing Water Transportation" },
  "Wildlife tours": { code: "487990", subsector: "487", sector: "48-49", title: "Scenic and Sightseeing Transportation, Other" },

  // ============================================================================
  // SECTOR 72: ACCOMMODATION AND FOOD SERVICES
  // ============================================================================
  "accommodation": { code: "721000", subsector: "721", sector: "72", title: "Accommodation" },
  "Hotel": { code: "721110", subsector: "721", sector: "72", title: "Hotels (except Casino Hotels)" },
  "Boutique Hotel": { code: "721110", subsector: "721", sector: "72", title: "Hotels (except Casino Hotels)" },
  "Boutique hotel": { code: "721110", subsector: "721", sector: "72", title: "Hotels (except Casino Hotels)" },
  "Inn": { code: "721110", subsector: "721", sector: "72", title: "Hotels (except Casino Hotels)" },
  "Boutique inn": { code: "721110", subsector: "721", sector: "72", title: "Hotels (except Casino Hotels)" },
  "Lodge": { code: "721110", subsector: "721", sector: "72", title: "Hotels (except Casino Hotels)" },
  "Resort": { code: "721110", subsector: "721", sector: "72", title: "Hotels (except Casino Hotels)" },
  "Beach resort": { code: "721110", subsector: "721", sector: "72", title: "Hotels (except Casino Hotels)" },
  "Luxury resort": { code: "721110", subsector: "721", sector: "72", title: "Hotels (except Casino Hotels)" },
  "Wilderness resort": { code: "721110", subsector: "721", sector: "72", title: "Hotels (except Casino Hotels)" },
  "Wilderness lodge": { code: "721110", subsector: "721", sector: "72", title: "Hotels (except Casino Hotels)" },
  "Fishing lodge": { code: "721110", subsector: "721", sector: "72", title: "Hotels (except Casino Hotels)" },
  "Eco-lodge": { code: "721110", subsector: "721", sector: "72", title: "Hotels (except Casino Hotels)" },
  "Motel": { code: "721110", subsector: "721", sector: "72", title: "Hotels (except Casino Hotels)" },
  "Heritage hotel": { code: "721110", subsector: "721", sector: "72", title: "Hotels (except Casino Hotels)" },
  "Hotel & Restaurant": { code: "721110", subsector: "721", sector: "72", title: "Hotels (except Casino Hotels)" },
  "Conference centre": { code: "721110", subsector: "721", sector: "72", title: "Hotels (except Casino Hotels)" },
  "Convention Centre": { code: "721110", subsector: "721", sector: "72", title: "Hotels (except Casino Hotels)" },
  "Bed & breakfast": { code: "721191", subsector: "721", sector: "72", title: "Bed-and-Breakfast Inns" },
  "B&B": { code: "721191", subsector: "721", sector: "72", title: "Bed-and-Breakfast Inns" },
  "Vacation rentals": { code: "721310", subsector: "721", sector: "72", title: "Rooming and Boarding Houses" },
  "Vacation rental": { code: "721310", subsector: "721", sector: "72", title: "Rooming and Boarding Houses" },
  "Campground": { code: "721211", subsector: "721", sector: "72", title: "RV Parks and Campgrounds" },
  "RV park": { code: "721211", subsector: "721", sector: "72", title: "RV Parks and Campgrounds" },
  "hospitality": { code: "722000", subsector: "722", sector: "72", title: "Food Services and Drinking Places" },
  "food-beverage": { code: "722000", subsector: "722", sector: "72", title: "Food Services and Drinking Places" },
  "food": { code: "722000", subsector: "722", sector: "72", title: "Food Services and Drinking Places" },
  "restaurant": { code: "722511", subsector: "722", sector: "72", title: "Full-Service Restaurants" },
  "Restaurant": { code: "722511", subsector: "722", sector: "72", title: "Full-Service Restaurants" },
  "Fine dining": { code: "722511", subsector: "722", sector: "72", title: "Full-Service Restaurants" },
  "Casual dining": { code: "722511", subsector: "722", sector: "72", title: "Full-Service Restaurants" },
  "Casual Dining": { code: "722511", subsector: "722", sector: "72", title: "Full-Service Restaurants" },
  "Casual dining chain": { code: "722511", subsector: "722", sector: "72", title: "Full-Service Restaurants" },
  "Bistro": { code: "722511", subsector: "722", sector: "72", title: "Full-Service Restaurants" },
  "Steakhouse": { code: "722511", subsector: "722", sector: "72", title: "Full-Service Restaurants" },
  "Seafood Restaurant": { code: "722511", subsector: "722", sector: "72", title: "Full-Service Restaurants" },
  "Sushi": { code: "722511", subsector: "722", sector: "72", title: "Full-Service Restaurants" },
  "Japanese": { code: "722511", subsector: "722", sector: "72", title: "Full-Service Restaurants" },
  "Vietnamese Restaurant": { code: "722511", subsector: "722", sector: "72", title: "Full-Service Restaurants" },
  "Mexican": { code: "722511", subsector: "722", sector: "72", title: "Full-Service Restaurants" },
  "Italian": { code: "722511", subsector: "722", sector: "72", title: "Full-Service Restaurants" },
  "Indian": { code: "722511", subsector: "722", sector: "72", title: "Full-Service Restaurants" },
  "Thai": { code: "722511", subsector: "722", sector: "72", title: "Full-Service Restaurants" },
  "Chinese": { code: "722511", subsector: "722", sector: "72", title: "Full-Service Restaurants" },
  "BBQ": { code: "722511", subsector: "722", sector: "72", title: "Full-Service Restaurants" },
  "Fast Food": { code: "722513", subsector: "722", sector: "72", title: "Limited-Service Restaurants" },
  "Quick Service": { code: "722513", subsector: "722", sector: "72", title: "Limited-Service Restaurants" },
  "Pizza": { code: "722513", subsector: "722", sector: "72", title: "Limited-Service Restaurants" },
  "Food Truck": { code: "722330", subsector: "722", sector: "72", title: "Mobile Food Services" },
  "Pub": { code: "722410", subsector: "722", sector: "72", title: "Drinking Places (Alcoholic Beverages)" },
  "Wings/pub food": { code: "722410", subsector: "722", sector: "72", title: "Drinking Places (Alcoholic Beverages)" },
  "Bar": { code: "722410", subsector: "722", sector: "72", title: "Drinking Places (Alcoholic Beverages)" },
  "Cocktail Bar": { code: "722410", subsector: "722", sector: "72", title: "Drinking Places (Alcoholic Beverages)" },
  "Sports Bar": { code: "722410", subsector: "722", sector: "72", title: "Drinking Places (Alcoholic Beverages)" },
  "Nightclub": { code: "722410", subsector: "722", sector: "72", title: "Drinking Places (Alcoholic Beverages)" },
  "Catering": { code: "722320", subsector: "722", sector: "72", title: "Caterers" },
  "Catering & Events": { code: "722320", subsector: "722", sector: "72", title: "Caterers" },
  "Coffee Shop": { code: "722515", subsector: "722", sector: "72", title: "Snack and Nonalcoholic Beverage Bars" },
  "Coffee shop": { code: "722515", subsector: "722", sector: "72", title: "Snack and Nonalcoholic Beverage Bars" },
  "Coffee": { code: "722515", subsector: "722", sector: "72", title: "Snack and Nonalcoholic Beverage Bars" },
  "Cafe": { code: "722515", subsector: "722", sector: "72", title: "Snack and Nonalcoholic Beverage Bars" },
  "Juice Bar": { code: "722515", subsector: "722", sector: "72", title: "Snack and Nonalcoholic Beverage Bars" },
  "Smoothie Bar": { code: "722515", subsector: "722", sector: "72", title: "Snack and Nonalcoholic Beverage Bars" },
  "Deli": { code: "722514", subsector: "722", sector: "72", title: "Cafeterias, Grill Buffets, and Buffets" },

  // ============================================================================
  // SECTOR 81: OTHER SERVICES (EXCEPT PUBLIC ADMINISTRATION)
  // ============================================================================
  "Auto Repair": { code: "811111", subsector: "811", sector: "81", title: "General Automotive Repair" },
  "Tire & Auto Service": { code: "811111", subsector: "811", sector: "81", title: "General Automotive Repair" },
  "Collision Repair": { code: "811121", subsector: "811", sector: "81", title: "Automotive Body, Paint, Interior Repair" },
  "Auto Glass": { code: "811122", subsector: "811", sector: "81", title: "Automotive Glass Replacement Shops" },
  "Auto Upholstery": { code: "811199", subsector: "811", sector: "81", title: "All Other Automotive Repair and Maintenance" },
  "Car Wash": { code: "811192", subsector: "811", sector: "81", title: "Car Washes" },
  "Bicycle Service": { code: "811490", subsector: "811", sector: "81", title: "Other Personal and Household Goods Repair" },
  "Bicycle Repair": { code: "811490", subsector: "811", sector: "81", title: "Other Personal and Household Goods Repair" },
  "Funeral Services": { code: "812210", subsector: "812", sector: "81", title: "Funeral Homes and Funeral Services" },
  "funeral": { code: "812210", subsector: "812", sector: "81", title: "Funeral Homes and Funeral Services" },
  "Funeral Home": { code: "812210", subsector: "812", sector: "81", title: "Funeral Homes and Funeral Services" },
  "Cemetery & Crematorium": { code: "812220", subsector: "812", sector: "81", title: "Cemeteries and Crematories" },
  "Burial Park": { code: "812220", subsector: "812", sector: "81", title: "Cemeteries and Crematories" },
  "Laundry": { code: "812310", subsector: "812", sector: "81", title: "Coin-Operated Laundries and Drycleaners" },
  "Dry Cleaning": { code: "812320", subsector: "812", sector: "81", title: "Drycleaning and Laundry Services" },
  "Alterations": { code: "811490", subsector: "811", sector: "81", title: "Other Personal and Household Goods Repair" },
  "spa-beauty": { code: "812111", subsector: "812", sector: "81", title: "Barber Shops" },
  "Spa": { code: "812111", subsector: "812", sector: "81", title: "Barber Shops" },
  "charity-nonprofit": { code: "813000", subsector: "813", sector: "81", title: "Religious, Grantmaking, Civic, Professional Orgs" },
  "nonprofit": { code: "813110", subsector: "813", sector: "81", title: "Religious Organizations" },
  "religious": { code: "813110", subsector: "813", sector: "81", title: "Religious Organizations" },
  "associations": { code: "813910", subsector: "813", sector: "81", title: "Business Associations" },
  "Association": { code: "813910", subsector: "813", sector: "81", title: "Business Associations" },
  "Business Association": { code: "813910", subsector: "813", sector: "81", title: "Business Associations" },
  "Industry Association": { code: "813910", subsector: "813", sector: "81", title: "Business Associations" },
  "Construction Industry Association": { code: "813910", subsector: "813", sector: "81", title: "Business Associations" },
  "Chamber of Commerce": { code: "813910", subsector: "813", sector: "81", title: "Business Associations" },
  "Business Network": { code: "813910", subsector: "813", sector: "81", title: "Business Associations" },
  "Business Networking": { code: "813910", subsector: "813", sector: "81", title: "Business Associations" },
  "Arts organization": { code: "813410", subsector: "813", sector: "81", title: "Civic and Social Organizations" },
  "Community centre": { code: "813410", subsector: "813", sector: "81", title: "Civic and Social Organizations" },
  "Community Foundation": { code: "813211", subsector: "813", sector: "81", title: "Grantmaking Foundations" },
  "Environmental organization": { code: "813312", subsector: "813", sector: "81", title: "Environment, Conservation Organizations" },

  // ============================================================================
  // SECTOR 92: PUBLIC ADMINISTRATION
  // ============================================================================
  "government": { code: "921000", subsector: "921", sector: "92", title: "Executive, Legislative, General Government" },
  "Municipal Government": { code: "921110", subsector: "921", sector: "92", title: "Executive Offices" },
  "Provincial Government": { code: "921110", subsector: "921", sector: "92", title: "Executive Offices" },
  "Federal Government": { code: "921110", subsector: "921", sector: "92", title: "Executive Offices" },
  "Regional District": { code: "921110", subsector: "921", sector: "92", title: "Executive Offices" },
  "first-nations": { code: "921150", subsector: "921", sector: "92", title: "American Indian and Alaska Native Tribal Governments" },
  "First Nations government": { code: "921150", subsector: "921", sector: "92", title: "American Indian and Alaska Native Tribal Governments" },
  "Treaty Nation": { code: "921150", subsector: "921", sector: "92", title: "American Indian and Alaska Native Tribal Governments" },
  "Indigenous business": { code: "921150", subsector: "921", sector: "92", title: "American Indian and Alaska Native Tribal Governments" },
  "Indigenous enterprise": { code: "921150", subsector: "921", sector: "92", title: "American Indian and Alaska Native Tribal Governments" },
  "Indigenous tourism": { code: "921150", subsector: "921", sector: "92", title: "American Indian and Alaska Native Tribal Governments" },
  "Indigenous art": { code: "921150", subsector: "921", sector: "92", title: "American Indian and Alaska Native Tribal Governments" },
  "Indigenous Coffee": { code: "921150", subsector: "921", sector: "92", title: "American Indian and Alaska Native Tribal Governments" },
  "Crown Corporation": { code: "926110", subsector: "926", sector: "92", title: "Administration of General Economic Programs" },
  "Economic Development": { code: "926110", subsector: "926", sector: "92", title: "Administration of General Economic Programs" },
  "Tourism Board": { code: "926110", subsector: "926", sector: "92", title: "Administration of General Economic Programs" },
  "Marketing board": { code: "926140", subsector: "926", sector: "92", title: "Regulation of Agricultural Marketing" },
  "Airport Authority": { code: "926120", subsector: "926", sector: "92", title: "Regulation and Administration of Transportation" },
  "Transit Authority": { code: "926120", subsector: "926", sector: "92", title: "Regulation and Administration of Transportation" },
  "Health Authority": { code: "923120", subsector: "923", sector: "92", title: "Administration of Public Health Programs" },

  // ============================================================================
  // TOURISM-SPECIFIC (Cross-sector assignments)
  // ============================================================================
  "tourism": { code: "561510", subsector: "561", sector: "56", title: "Travel Agencies" },
  "Attraction": { code: "712190", subsector: "712", sector: "71", title: "Nature Parks and Other Similar Institutions" },
  "Tourism attraction": { code: "712190", subsector: "712", sector: "71", title: "Nature Parks and Other Similar Institutions" },
  "Tour Operator": { code: "561520", subsector: "561", sector: "56", title: "Tour Operators" },
  "Food Tours": { code: "561520", subsector: "561", sector: "56", title: "Tour Operators" },
  "Wine Tours": { code: "561520", subsector: "561", sector: "56", title: "Tour Operators" },
  "Sightseeing": { code: "487110", subsector: "487", sector: "48-49", title: "Scenic and Sightseeing Transportation, Land" },
  "Eco-tourism": { code: "561520", subsector: "561", sector: "56", title: "Tour Operators" },
  "Marine Tourism": { code: "487210", subsector: "487", sector: "48-49", title: "Scenic and Sightseeing Water Transportation" },
  "Destination Marketing": { code: "561510", subsector: "561", sector: "56", title: "Travel Agencies" },
  "Visitor Centre": { code: "561510", subsector: "561", sector: "56", title: "Travel Agencies" },

  // ============================================================================
  // FALLBACK for unmapped values
  // ============================================================================
  "other": { code: "999999", subsector: "999", sector: "99", title: "Unclassified" },
};

// Default NAICS code for unmapped categories
export const defaultNAICS: NAICSCode = {
  code: "999999",
  subsector: "999", 
  sector: "99",
  title: "Unclassified"
};

// Get NAICS code for a category value
export function getNAICSForCategory(category: string): NAICSCode {
  return categoryToNAICS[category] || defaultNAICS;
}
