export type SchoolType = 
  | "elementary"
  | "middle"
  | "secondary"
  | "k_12"
  | "k_9"
  | "k_7"
  | "grade_8_12"
  | "alternative"
  | "online"
  | "university"
  | "college"
  | "polytechnic"
  | "trades"
  | "private_k_12"
  | "independent"
  | "first_nations";

export type SchoolCategory =
  | "public_k12"
  | "private_k12"
  | "post_secondary"
  | "trades_technical";

export interface School {
  id: string;
  name: string;
  type: SchoolType;
  category: SchoolCategory;
  municipality: string;
  region: string;
  address?: string;
  lat: number;
  lng: number;
  district?: string;
  enrollment?: number;
  grades?: string;
  website?: string;
  phone?: string;
  notes?: string;
}

export const schoolTypeLabels: Record<SchoolType, string> = {
  elementary: "Elementary",
  middle: "Middle School",
  secondary: "Secondary",
  k_12: "K-12",
  k_9: "K-9",
  k_7: "K-7",
  grade_8_12: "Gr 8-12",
  alternative: "Alternative",
  online: "Online",
  university: "University",
  college: "College",
  polytechnic: "Polytechnic",
  trades: "Trades/Technical",
  private_k_12: "Private K-12",
  independent: "Independent",
  first_nations: "First Nations",
};

export const schoolCategoryLabels: Record<SchoolCategory, string> = {
  public_k12: "Public K-12",
  private_k12: "Private/Independent",
  post_secondary: "Post-Secondary",
  trades_technical: "Trades & Technical",
};

export const BC_SCHOOLS: School[] = [
  // ============================================
  // UNIVERSITIES
  // ============================================
  {
    id: "ubc-vancouver",
    name: "University of British Columbia",
    type: "university",
    category: "post_secondary",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    address: "2329 West Mall",
    lat: 49.2606,
    lng: -123.2460,
    enrollment: 55000,
    website: "https://www.ubc.ca",
  },
  {
    id: "ubc-okanagan",
    name: "UBC Okanagan",
    type: "university",
    category: "post_secondary",
    municipality: "Kelowna",
    region: "Central Okanagan",
    address: "3333 University Way",
    lat: 49.9396,
    lng: -119.3948,
    enrollment: 11000,
    website: "https://ok.ubc.ca",
  },
  {
    id: "sfu-burnaby",
    name: "Simon Fraser University - Burnaby",
    type: "university",
    category: "post_secondary",
    municipality: "Burnaby",
    region: "Metro Vancouver",
    address: "8888 University Drive",
    lat: 49.2781,
    lng: -122.9199,
    enrollment: 35000,
    website: "https://www.sfu.ca",
  },
  {
    id: "sfu-surrey",
    name: "Simon Fraser University - Surrey",
    type: "university",
    category: "post_secondary",
    municipality: "Surrey",
    region: "Metro Vancouver",
    address: "13450 102 Avenue",
    lat: 49.1867,
    lng: -122.8490,
    website: "https://www.sfu.ca/surrey",
  },
  {
    id: "sfu-vancouver",
    name: "Simon Fraser University - Vancouver",
    type: "university",
    category: "post_secondary",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    address: "515 West Hastings Street",
    lat: 49.2847,
    lng: -123.1119,
    website: "https://www.sfu.ca/vancouver",
  },
  {
    id: "uvic",
    name: "University of Victoria",
    type: "university",
    category: "post_secondary",
    municipality: "Victoria",
    region: "Capital",
    address: "3800 Finnerty Road",
    lat: 48.4634,
    lng: -123.3117,
    enrollment: 22000,
    website: "https://www.uvic.ca",
  },
  {
    id: "unbc",
    name: "University of Northern British Columbia",
    type: "university",
    category: "post_secondary",
    municipality: "Prince George",
    region: "Fraser-Fort George",
    address: "3333 University Way",
    lat: 53.8925,
    lng: -122.8107,
    enrollment: 4500,
    website: "https://www.unbc.ca",
  },
  {
    id: "tru",
    name: "Thompson Rivers University",
    type: "university",
    category: "post_secondary",
    municipality: "Kamloops",
    region: "Thompson-Nicola",
    address: "805 TRU Way",
    lat: 50.6688,
    lng: -120.3663,
    enrollment: 26000,
    website: "https://www.tru.ca",
  },
  {
    id: "tru-williams-lake",
    name: "TRU Williams Lake",
    type: "university",
    category: "post_secondary",
    municipality: "Williams Lake",
    region: "Cariboo",
    address: "1250 Western Avenue",
    lat: 52.1296,
    lng: -122.1458,
    website: "https://www.tru.ca/williamslake",
  },
  {
    id: "royal-roads",
    name: "Royal Roads University",
    type: "university",
    category: "post_secondary",
    municipality: "Colwood",
    region: "Capital",
    address: "2005 Sooke Road",
    lat: 48.4333,
    lng: -123.4742,
    enrollment: 5000,
    website: "https://www.royalroads.ca",
  },
  {
    id: "kpu-surrey",
    name: "Kwantlen Polytechnic University - Surrey",
    type: "polytechnic",
    category: "post_secondary",
    municipality: "Surrey",
    region: "Metro Vancouver",
    address: "12666 72 Avenue",
    lat: 49.1327,
    lng: -122.8712,
    enrollment: 20000,
    website: "https://www.kpu.ca",
  },
  {
    id: "kpu-richmond",
    name: "Kwantlen Polytechnic University - Richmond",
    type: "polytechnic",
    category: "post_secondary",
    municipality: "Richmond",
    region: "Metro Vancouver",
    address: "8771 Lansdowne Road",
    lat: 49.1710,
    lng: -123.1361,
    website: "https://www.kpu.ca",
  },
  {
    id: "kpu-langley",
    name: "Kwantlen Polytechnic University - Langley",
    type: "polytechnic",
    category: "post_secondary",
    municipality: "Township of Langley",
    region: "Metro Vancouver",
    address: "20901 Langley Bypass",
    lat: 49.1147,
    lng: -122.6659,
    website: "https://www.kpu.ca",
  },
  {
    id: "capilano-nv",
    name: "Capilano University",
    type: "university",
    category: "post_secondary",
    municipality: "North Vancouver",
    region: "Metro Vancouver",
    address: "2055 Purcell Way",
    lat: 49.3530,
    lng: -123.0834,
    enrollment: 13000,
    website: "https://www.capilanou.ca",
  },
  {
    id: "emily-carr",
    name: "Emily Carr University of Art + Design",
    type: "university",
    category: "post_secondary",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    address: "520 East 1st Avenue",
    lat: 49.2690,
    lng: -123.0959,
    enrollment: 2000,
    website: "https://www.ecuad.ca",
  },
  {
    id: "justice-institute",
    name: "Justice Institute of British Columbia",
    type: "polytechnic",
    category: "post_secondary",
    municipality: "New Westminster",
    region: "Metro Vancouver",
    address: "715 McBride Boulevard",
    lat: 49.2318,
    lng: -122.8998,
    website: "https://www.jibc.ca",
  },

  // ============================================
  // COLLEGES
  // ============================================
  {
    id: "bcit-burnaby",
    name: "BCIT - Burnaby Campus",
    type: "polytechnic",
    category: "post_secondary",
    municipality: "Burnaby",
    region: "Metro Vancouver",
    address: "3700 Willingdon Avenue",
    lat: 49.2500,
    lng: -123.0004,
    enrollment: 48000,
    website: "https://www.bcit.ca",
  },
  {
    id: "bcit-downtown",
    name: "BCIT - Downtown Vancouver",
    type: "polytechnic",
    category: "post_secondary",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    address: "555 Seymour Street",
    lat: 49.2830,
    lng: -123.1160,
    website: "https://www.bcit.ca",
  },
  {
    id: "douglas-nwest",
    name: "Douglas College - New Westminster",
    type: "college",
    category: "post_secondary",
    municipality: "New Westminster",
    region: "Metro Vancouver",
    address: "700 Royal Avenue",
    lat: 49.2043,
    lng: -122.9126,
    enrollment: 25000,
    website: "https://www.douglascollege.ca",
  },
  {
    id: "douglas-coquitlam",
    name: "Douglas College - David Lam Campus",
    type: "college",
    category: "post_secondary",
    municipality: "Coquitlam",
    region: "Metro Vancouver",
    address: "1250 Pinetree Way",
    lat: 49.2853,
    lng: -122.7911,
    website: "https://www.douglascollege.ca",
  },
  {
    id: "langara",
    name: "Langara College",
    type: "college",
    category: "post_secondary",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    address: "100 West 49th Avenue",
    lat: 49.2247,
    lng: -123.1088,
    enrollment: 21000,
    website: "https://www.langara.ca",
  },
  {
    id: "vcc-broadway",
    name: "Vancouver Community College - Broadway",
    type: "college",
    category: "post_secondary",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    address: "1155 East Broadway",
    lat: 49.2627,
    lng: -123.0790,
    enrollment: 15000,
    website: "https://www.vcc.ca",
  },
  {
    id: "vcc-downtown",
    name: "Vancouver Community College - Downtown",
    type: "college",
    category: "post_secondary",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    address: "250 West Pender Street",
    lat: 49.2823,
    lng: -123.1098,
    website: "https://www.vcc.ca",
  },
  {
    id: "camosun-lansdowne",
    name: "Camosun College - Lansdowne",
    type: "college",
    category: "post_secondary",
    municipality: "Victoria",
    region: "Capital",
    address: "3100 Foul Bay Road",
    lat: 48.4474,
    lng: -123.3251,
    enrollment: 18000,
    website: "https://www.camosun.ca",
  },
  {
    id: "camosun-interurban",
    name: "Camosun College - Interurban",
    type: "college",
    category: "post_secondary",
    municipality: "Saanich",
    region: "Capital",
    address: "4461 Interurban Road",
    lat: 48.4892,
    lng: -123.4156,
    website: "https://www.camosun.ca",
  },
  {
    id: "okanagan-college-kelowna",
    name: "Okanagan College - Kelowna",
    type: "college",
    category: "post_secondary",
    municipality: "Kelowna",
    region: "Central Okanagan",
    address: "1000 KLO Road",
    lat: 49.8608,
    lng: -119.4769,
    enrollment: 22000,
    website: "https://www.okanagan.bc.ca",
  },
  {
    id: "okanagan-college-vernon",
    name: "Okanagan College - Vernon",
    type: "college",
    category: "post_secondary",
    municipality: "Vernon",
    region: "North Okanagan",
    address: "7000 College Way",
    lat: 50.2418,
    lng: -119.2896,
    website: "https://www.okanagan.bc.ca",
  },
  {
    id: "okanagan-college-penticton",
    name: "Okanagan College - Penticton",
    type: "college",
    category: "post_secondary",
    municipality: "Penticton",
    region: "Okanagan-Similkameen",
    address: "583 Duncan Avenue West",
    lat: 49.4875,
    lng: -119.5923,
    website: "https://www.okanagan.bc.ca",
  },
  {
    id: "okanagan-college-salmon-arm",
    name: "Okanagan College - Salmon Arm",
    type: "college",
    category: "post_secondary",
    municipality: "Salmon Arm",
    region: "Columbia-Shuswap",
    address: "2552 10th Avenue NE",
    lat: 50.6990,
    lng: -119.2627,
    website: "https://www.okanagan.bc.ca",
  },
  {
    id: "college-rockies-cranbrook",
    name: "College of the Rockies - Cranbrook",
    type: "college",
    category: "post_secondary",
    municipality: "Cranbrook",
    region: "East Kootenay",
    address: "2700 College Way",
    lat: 49.4947,
    lng: -115.7554,
    enrollment: 5000,
    website: "https://www.cotr.bc.ca",
  },
  {
    id: "college-rockies-fernie",
    name: "College of the Rockies - Fernie",
    type: "college",
    category: "post_secondary",
    municipality: "Fernie",
    region: "East Kootenay",
    address: "342 3rd Avenue",
    lat: 49.5040,
    lng: -115.0628,
    website: "https://www.cotr.bc.ca",
  },
  {
    id: "college-rockies-golden",
    name: "College of the Rockies - Golden",
    type: "college",
    category: "post_secondary",
    municipality: "Golden",
    region: "Columbia-Shuswap",
    address: "1305 11th Avenue South",
    lat: 51.2965,
    lng: -116.9609,
    website: "https://www.cotr.bc.ca",
  },
  {
    id: "college-rockies-invermere",
    name: "College of the Rockies - Invermere",
    type: "college",
    category: "post_secondary",
    municipality: "Invermere",
    region: "East Kootenay",
    address: "1535 14th Street",
    lat: 50.5065,
    lng: -116.0286,
    website: "https://www.cotr.bc.ca",
  },
  {
    id: "selkirk-castlegar",
    name: "Selkirk College - Castlegar",
    type: "college",
    category: "post_secondary",
    municipality: "Castlegar",
    region: "Central Kootenay",
    address: "301 Frank Beinder Way",
    lat: 49.3156,
    lng: -117.6631,
    enrollment: 6000,
    website: "https://www.selkirk.ca",
  },
  {
    id: "selkirk-nelson",
    name: "Selkirk College - Nelson",
    type: "college",
    category: "post_secondary",
    municipality: "Nelson",
    region: "Central Kootenay",
    address: "820 10th Street",
    lat: 49.4960,
    lng: -117.2878,
    website: "https://www.selkirk.ca",
  },
  {
    id: "selkirk-trail",
    name: "Selkirk College - Trail",
    type: "college",
    category: "post_secondary",
    municipality: "Trail",
    region: "Kootenay Boundary",
    address: "900 Helena Street",
    lat: 49.0963,
    lng: -117.7088,
    website: "https://www.selkirk.ca",
  },
  {
    id: "college-new-cal-pg",
    name: "College of New Caledonia - Prince George",
    type: "college",
    category: "post_secondary",
    municipality: "Prince George",
    region: "Fraser-Fort George",
    address: "3330 22nd Avenue",
    lat: 53.9127,
    lng: -122.7497,
    enrollment: 5500,
    website: "https://www.cnc.bc.ca",
  },
  {
    id: "college-new-cal-quesnel",
    name: "College of New Caledonia - Quesnel",
    type: "college",
    category: "post_secondary",
    municipality: "Quesnel",
    region: "Cariboo",
    address: "100 Campus Way",
    lat: 52.9761,
    lng: -122.4943,
    website: "https://www.cnc.bc.ca",
  },
  {
    id: "college-new-cal-vanderhoof",
    name: "College of New Caledonia - Vanderhoof",
    type: "college",
    category: "post_secondary",
    municipality: "Vanderhoof",
    region: "Bulkley-Nechako",
    address: "3530 Church Avenue",
    lat: 54.0144,
    lng: -124.0031,
    website: "https://www.cnc.bc.ca",
  },
  {
    id: "college-new-cal-mackenzie",
    name: "College of New Caledonia - Mackenzie",
    type: "college",
    category: "post_secondary",
    municipality: "Mackenzie",
    region: "Fraser-Fort George",
    address: "340 Mackenzie Boulevard",
    lat: 55.3363,
    lng: -123.0996,
    website: "https://www.cnc.bc.ca",
  },
  {
    id: "college-new-cal-burns-lake",
    name: "College of New Caledonia - Burns Lake",
    type: "college",
    category: "post_secondary",
    municipality: "Burns Lake",
    region: "Bulkley-Nechako",
    address: "592 Highway 16",
    lat: 54.2307,
    lng: -125.7597,
    website: "https://www.cnc.bc.ca",
  },
  {
    id: "college-new-cal-fort-st-james",
    name: "College of New Caledonia - Fort St. James",
    type: "college",
    category: "post_secondary",
    municipality: "Fort St. James",
    region: "Bulkley-Nechako",
    address: "470 Stuart Drive West",
    lat: 54.4419,
    lng: -124.2571,
    website: "https://www.cnc.bc.ca",
  },
  {
    id: "nwcc-terrace",
    name: "Coast Mountain College - Terrace",
    type: "college",
    category: "post_secondary",
    municipality: "Terrace",
    region: "Kitimat-Stikine",
    address: "5331 McConnell Avenue",
    lat: 54.5172,
    lng: -128.6051,
    enrollment: 3000,
    website: "https://www.coastmountaincollege.ca",
  },
  {
    id: "nwcc-prince-rupert",
    name: "Coast Mountain College - Prince Rupert",
    type: "college",
    category: "post_secondary",
    municipality: "Prince Rupert",
    region: "North Coast",
    address: "353 5th Street",
    lat: 54.3169,
    lng: -130.3248,
    website: "https://www.coastmountaincollege.ca",
  },
  {
    id: "nwcc-smithers",
    name: "Coast Mountain College - Smithers",
    type: "college",
    category: "post_secondary",
    municipality: "Smithers",
    region: "Bulkley-Nechako",
    address: "3966 2nd Avenue",
    lat: 54.3792,
    lng: -126.8416,
    website: "https://www.coastmountaincollege.ca",
  },
  {
    id: "nwcc-kitimat",
    name: "Coast Mountain College - Kitimat",
    type: "college",
    category: "post_secondary",
    municipality: "Kitimat",
    region: "Kitimat-Stikine",
    address: "606 Mountainview Square",
    lat: 54.0529,
    lng: -128.6534,
    website: "https://www.coastmountaincollege.ca",
  },
  {
    id: "nwcc-hazelton",
    name: "Coast Mountain College - Hazelton",
    type: "college",
    category: "post_secondary",
    municipality: "New Hazelton",
    region: "Kitimat-Stikine",
    address: "4815 Swannell Drive",
    lat: 55.2544,
    lng: -127.5859,
    website: "https://www.coastmountaincollege.ca",
  },
  {
    id: "northern-lights-dawson-creek",
    name: "Northern Lights College - Dawson Creek",
    type: "college",
    category: "post_secondary",
    municipality: "Dawson Creek",
    region: "Peace River",
    address: "11401 8th Street",
    lat: 55.7612,
    lng: -120.2245,
    enrollment: 2500,
    website: "https://www.nlc.bc.ca",
  },
  {
    id: "northern-lights-fort-st-john",
    name: "Northern Lights College - Fort St. John",
    type: "college",
    category: "post_secondary",
    municipality: "Fort St. John",
    region: "Peace River",
    address: "9820 120th Avenue",
    lat: 56.2431,
    lng: -120.8533,
    website: "https://www.nlc.bc.ca",
  },
  {
    id: "northern-lights-chetwynd",
    name: "Northern Lights College - Chetwynd",
    type: "college",
    category: "post_secondary",
    municipality: "Chetwynd",
    region: "Peace River",
    address: "5128 50th Street",
    lat: 55.6978,
    lng: -121.6325,
    website: "https://www.nlc.bc.ca",
  },
  {
    id: "northern-lights-fort-nelson",
    name: "Northern Lights College - Fort Nelson",
    type: "college",
    category: "post_secondary",
    municipality: "Fort Nelson",
    region: "Northern Rockies",
    address: "5012 50th Avenue North",
    lat: 58.8050,
    lng: -122.6988,
    website: "https://www.nlc.bc.ca",
  },
  {
    id: "northern-lights-tumbler-ridge",
    name: "Northern Lights College - Tumbler Ridge",
    type: "college",
    category: "post_secondary",
    municipality: "Tumbler Ridge",
    region: "Peace River",
    address: "300 Founders Street",
    lat: 55.1282,
    lng: -120.9958,
    website: "https://www.nlc.bc.ca",
  },
  {
    id: "north-island-courtenay",
    name: "North Island College - Courtenay",
    type: "college",
    category: "post_secondary",
    municipality: "Courtenay",
    region: "Comox Valley",
    address: "2300 Ryan Road",
    lat: 49.6711,
    lng: -124.9796,
    enrollment: 8000,
    website: "https://www.nic.bc.ca",
  },
  {
    id: "north-island-campbell-river",
    name: "North Island College - Campbell River",
    type: "college",
    category: "post_secondary",
    municipality: "Campbell River",
    region: "Strathcona",
    address: "1685 South Dogwood Street",
    lat: 50.0110,
    lng: -125.2450,
    website: "https://www.nic.bc.ca",
  },
  {
    id: "north-island-port-alberni",
    name: "North Island College - Port Alberni",
    type: "college",
    category: "post_secondary",
    municipality: "Port Alberni",
    region: "Alberni-Clayoquot",
    address: "3699 Roger Street",
    lat: 49.2463,
    lng: -124.8066,
    website: "https://www.nic.bc.ca",
  },
  {
    id: "north-island-port-hardy",
    name: "North Island College - Port Hardy",
    type: "college",
    category: "post_secondary",
    municipality: "Port Hardy",
    region: "Mount Waddington",
    address: "8945 Trustee Road",
    lat: 50.7227,
    lng: -127.4963,
    website: "https://www.nic.bc.ca",
  },
  {
    id: "north-island-ucluelet",
    name: "North Island College - Ucluelet",
    type: "college",
    category: "post_secondary",
    municipality: "Ucluelet",
    region: "Alberni-Clayoquot",
    address: "1636 Peninsula Road",
    lat: 48.9402,
    lng: -125.5431,
    website: "https://www.nic.bc.ca",
  },
  {
    id: "ufv-abbotsford",
    name: "University of the Fraser Valley - Abbotsford",
    type: "university",
    category: "post_secondary",
    municipality: "Abbotsford",
    region: "Fraser Valley",
    address: "33844 King Road",
    lat: 49.0306,
    lng: -122.2846,
    enrollment: 15000,
    website: "https://www.ufv.ca",
  },
  {
    id: "ufv-chilliwack",
    name: "University of the Fraser Valley - Chilliwack",
    type: "university",
    category: "post_secondary",
    municipality: "Chilliwack",
    region: "Fraser Valley",
    address: "45190 Caen Avenue",
    lat: 49.1457,
    lng: -121.9560,
    website: "https://www.ufv.ca",
  },
  {
    id: "ufv-mission",
    name: "University of the Fraser Valley - Mission",
    type: "university",
    category: "post_secondary",
    municipality: "Mission",
    region: "Fraser Valley",
    address: "33700 Prentis Avenue",
    lat: 49.1333,
    lng: -122.2967,
    website: "https://www.ufv.ca",
  },
  {
    id: "ufv-hope",
    name: "University of the Fraser Valley - Hope",
    type: "university",
    category: "post_secondary",
    municipality: "Hope",
    region: "Fraser Valley",
    address: "1250 7th Avenue",
    lat: 49.3793,
    lng: -121.4509,
    website: "https://www.ufv.ca",
  },
  {
    id: "viu-nanaimo",
    name: "Vancouver Island University - Nanaimo",
    type: "university",
    category: "post_secondary",
    municipality: "Nanaimo",
    region: "Nanaimo",
    address: "900 Fifth Street",
    lat: 49.1586,
    lng: -123.9658,
    enrollment: 18000,
    website: "https://www.viu.ca",
  },
  {
    id: "viu-cowichan",
    name: "Vancouver Island University - Cowichan",
    type: "university",
    category: "post_secondary",
    municipality: "Duncan",
    region: "Cowichan Valley",
    address: "2011 University Way",
    lat: 48.7791,
    lng: -123.7187,
    website: "https://www.viu.ca",
  },
  {
    id: "viu-powell-river",
    name: "Vancouver Island University - Powell River",
    type: "university",
    category: "post_secondary",
    municipality: "Powell River",
    region: "Powell River",
    address: "3960 Selkirk Avenue",
    lat: 49.8440,
    lng: -124.5202,
    website: "https://www.viu.ca",
  },
  {
    id: "viu-parksville-qualicum",
    name: "Vancouver Island University - Parksville-Qualicum",
    type: "university",
    category: "post_secondary",
    municipality: "Parksville",
    region: "Nanaimo",
    address: "100 Jensen Avenue East",
    lat: 49.3173,
    lng: -124.3146,
    website: "https://www.viu.ca",
  },

  // ============================================
  // TRADES & TECHNICAL
  // ============================================
  {
    id: "ita-bc",
    name: "Industry Training Authority (ITA BC)",
    type: "trades",
    category: "trades_technical",
    municipality: "Richmond",
    region: "Metro Vancouver",
    address: "8100 Granville Avenue",
    lat: 49.1662,
    lng: -123.1364,
    website: "https://www.itabc.ca",
    notes: "Provincial trades training coordination",
  },
  {
    id: "pacific-vocational",
    name: "Pacific Vocational College",
    type: "trades",
    category: "trades_technical",
    municipality: "Surrey",
    region: "Metro Vancouver",
    address: "10362 King George Boulevard",
    lat: 49.1788,
    lng: -122.8447,
    website: "https://www.pvcollege.com",
  },
  {
    id: "sprott-shaw-vancouver",
    name: "Sprott Shaw College - Vancouver",
    type: "trades",
    category: "trades_technical",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    address: "789 West Pender Street",
    lat: 49.2844,
    lng: -123.1168,
    website: "https://www.sprottshaw.com",
  },
  {
    id: "cdi-college-burnaby",
    name: "CDI College - Burnaby",
    type: "trades",
    category: "trades_technical",
    municipality: "Burnaby",
    region: "Metro Vancouver",
    address: "5021 Kingsway",
    lat: 49.2262,
    lng: -122.9995,
    website: "https://www.cdicollege.ca",
  },
  {
    id: "pacific-coast-community",
    name: "Pacific Community Resources Society",
    type: "trades",
    category: "trades_technical",
    municipality: "Surrey",
    region: "Metro Vancouver",
    address: "13483 78th Avenue",
    lat: 49.1287,
    lng: -122.8708,
  },
  {
    id: "bc-firefighter-academy",
    name: "BC Fire Training Academy",
    type: "trades",
    category: "trades_technical",
    municipality: "Maple Ridge",
    region: "Metro Vancouver",
    address: "12251 272nd Street",
    lat: 49.2357,
    lng: -122.4841,
    website: "https://www.bcfiretrainingacademy.ca",
  },
  {
    id: "pacific-marine-training",
    name: "Pacific Marine Training Campus",
    type: "trades",
    category: "trades_technical",
    municipality: "North Vancouver",
    region: "Metro Vancouver",
    address: "265 West Esplanade",
    lat: 49.3110,
    lng: -123.0775,
    website: "https://www.bcit.ca",
    notes: "BCIT Marine Campus",
  },

  // ============================================
  // SELECT PUBLIC SECONDARY SCHOOLS
  // ============================================

  // Vancouver School District
  {
    id: "van-britannia-sec",
    name: "Britannia Secondary School",
    type: "secondary",
    category: "public_k12",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    district: "Vancouver School District",
    address: "1001 Cotton Drive",
    lat: 49.2749,
    lng: -123.0709,
    grades: "8-12",
  },
  {
    id: "van-churchill-sec",
    name: "Sir Winston Churchill Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    district: "Vancouver School District",
    address: "7055 Heather Street",
    lat: 49.2191,
    lng: -123.1240,
    grades: "8-12",
  },
  {
    id: "van-kitsilano-sec",
    name: "Kitsilano Secondary School",
    type: "secondary",
    category: "public_k12",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    district: "Vancouver School District",
    address: "2550 West 10th Avenue",
    lat: 49.2630,
    lng: -123.1623,
    grades: "8-12",
  },
  {
    id: "van-point-grey-sec",
    name: "Point Grey Secondary School",
    type: "secondary",
    category: "public_k12",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    district: "Vancouver School District",
    address: "5350 East Boulevard",
    lat: 49.2416,
    lng: -123.1553,
    grades: "8-12",
  },
  {
    id: "van-magee-sec",
    name: "Magee Secondary School",
    type: "secondary",
    category: "public_k12",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    district: "Vancouver School District",
    address: "6360 Maple Street",
    lat: 49.2285,
    lng: -123.1343,
    grades: "8-12",
  },
  {
    id: "van-university-hill-sec",
    name: "University Hill Secondary School",
    type: "secondary",
    category: "public_k12",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    district: "Vancouver School District",
    address: "5823 Blanca Street",
    lat: 49.2581,
    lng: -123.2336,
    grades: "8-12",
  },
  {
    id: "van-prince-of-wales-sec",
    name: "Prince of Wales Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    district: "Vancouver School District",
    address: "2250 Eddington Drive",
    lat: 49.2415,
    lng: -123.1726,
    grades: "8-12",
  },

  // Burnaby School District
  {
    id: "bby-burnaby-north-sec",
    name: "Burnaby North Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Burnaby",
    region: "Metro Vancouver",
    district: "Burnaby School District",
    address: "751 Hammarskjold Drive",
    lat: 49.2761,
    lng: -122.9540,
    grades: "8-12",
  },
  {
    id: "bby-burnaby-central-sec",
    name: "Burnaby Central Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Burnaby",
    region: "Metro Vancouver",
    district: "Burnaby School District",
    address: "6011 Deer Lake Avenue",
    lat: 49.2393,
    lng: -122.9757,
    grades: "8-12",
  },
  {
    id: "bby-burnaby-south-sec",
    name: "Burnaby South Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Burnaby",
    region: "Metro Vancouver",
    district: "Burnaby School District",
    address: "5455 Rumble Street",
    lat: 49.2163,
    lng: -122.9945,
    grades: "8-12",
  },
  {
    id: "bby-cariboo-hill-sec",
    name: "Cariboo Hill Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Burnaby",
    region: "Metro Vancouver",
    district: "Burnaby School District",
    address: "8560 16th Avenue",
    lat: 49.2255,
    lng: -122.9393,
    grades: "8-12",
  },
  {
    id: "bby-moscrop-sec",
    name: "Moscrop Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Burnaby",
    region: "Metro Vancouver",
    district: "Burnaby School District",
    address: "4433 Moscrop Street",
    lat: 49.2483,
    lng: -123.0013,
    grades: "8-12",
  },
  {
    id: "bby-byrne-creek-sec",
    name: "Byrne Creek Community School",
    type: "secondary",
    category: "public_k12",
    municipality: "Burnaby",
    region: "Metro Vancouver",
    district: "Burnaby School District",
    address: "7777 18th Street",
    lat: 49.2104,
    lng: -122.9519,
    grades: "8-12",
  },

  // Surrey School District
  {
    id: "sur-earl-marriott-sec",
    name: "Earl Marriott Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Surrey",
    region: "Metro Vancouver",
    district: "Surrey School District",
    address: "15751 16th Avenue",
    lat: 49.0312,
    lng: -122.7713,
    grades: "8-12",
  },
  {
    id: "sur-semiahmoo-sec",
    name: "Semiahmoo Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Surrey",
    region: "Metro Vancouver",
    district: "Surrey School District",
    address: "1785 148th Street",
    lat: 49.0283,
    lng: -122.8015,
    grades: "8-12",
  },
  {
    id: "sur-fleetwood-park-sec",
    name: "Fleetwood Park Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Surrey",
    region: "Metro Vancouver",
    district: "Surrey School District",
    address: "7940 156th Street",
    lat: 49.1576,
    lng: -122.7722,
    grades: "8-12",
  },
  {
    id: "sur-fraser-heights-sec",
    name: "Fraser Heights Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Surrey",
    region: "Metro Vancouver",
    district: "Surrey School District",
    address: "16060 108th Avenue",
    lat: 49.2024,
    lng: -122.7632,
    grades: "8-12",
  },
  {
    id: "sur-guildford-park-sec",
    name: "Guildford Park Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Surrey",
    region: "Metro Vancouver",
    district: "Surrey School District",
    address: "10707 146th Street",
    lat: 49.1898,
    lng: -122.8022,
    grades: "8-12",
  },
  {
    id: "sur-lord-tweedsmuir-sec",
    name: "Lord Tweedsmuir Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Surrey",
    region: "Metro Vancouver",
    district: "Surrey School District",
    address: "6151 180th Street",
    lat: 49.1056,
    lng: -122.7243,
    grades: "8-12",
  },
  {
    id: "sur-panorama-ridge-sec",
    name: "Panorama Ridge Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Surrey",
    region: "Metro Vancouver",
    district: "Surrey School District",
    address: "13220 64th Avenue",
    lat: 49.1179,
    lng: -122.8600,
    grades: "8-12",
  },
  {
    id: "sur-sullivan-heights-sec",
    name: "Sullivan Heights Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Surrey",
    region: "Metro Vancouver",
    district: "Surrey School District",
    address: "6248 144th Street",
    lat: 49.1053,
    lng: -122.8148,
    grades: "8-12",
  },

  // Richmond School District
  {
    id: "ric-steveston-london-sec",
    name: "Steveston-London Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Richmond",
    region: "Metro Vancouver",
    district: "Richmond School District",
    address: "6600 Williams Road",
    lat: 49.1389,
    lng: -123.1755,
    grades: "8-12",
  },
  {
    id: "ric-richmond-sec",
    name: "Richmond Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Richmond",
    region: "Metro Vancouver",
    district: "Richmond School District",
    address: "7171 Minoru Boulevard",
    lat: 49.1634,
    lng: -123.1365,
    grades: "8-12",
  },
  {
    id: "ric-mcmath-sec",
    name: "Hugh McRoberts Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Richmond",
    region: "Metro Vancouver",
    district: "Richmond School District",
    address: "8980 Williams Road",
    lat: 49.1387,
    lng: -123.1313,
    grades: "8-12",
  },
  {
    id: "ric-boyd-sec",
    name: "Hugh Boyd Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Richmond",
    region: "Metro Vancouver",
    district: "Richmond School District",
    address: "9200 No. 1 Road",
    lat: 49.1286,
    lng: -123.1460,
    grades: "8-12",
  },
  {
    id: "ric-cambie-sec",
    name: "Cambie Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Richmond",
    region: "Metro Vancouver",
    district: "Richmond School District",
    address: "4151 Jacombs Road",
    lat: 49.1800,
    lng: -123.0925,
    grades: "8-12",
  },

  // Victoria/Capital Region
  {
    id: "vic-oak-bay-high",
    name: "Oak Bay High School",
    type: "secondary",
    category: "public_k12",
    municipality: "Oak Bay",
    region: "Capital",
    district: "Greater Victoria School District",
    address: "2121 Cadboro Bay Road",
    lat: 48.4415,
    lng: -123.2987,
    grades: "9-12",
  },
  {
    id: "vic-victoria-high",
    name: "Victoria High School",
    type: "secondary",
    category: "public_k12",
    municipality: "Victoria",
    region: "Capital",
    district: "Greater Victoria School District",
    address: "1260 Grant Street",
    lat: 48.4328,
    lng: -123.3428,
    grades: "9-12",
  },
  {
    id: "vic-mount-doug-sec",
    name: "Mount Douglas Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Saanich",
    region: "Capital",
    district: "Greater Victoria School District",
    address: "3970 Gordon Head Road",
    lat: 48.4634,
    lng: -123.3202,
    grades: "9-12",
  },
  {
    id: "vic-reynolds-sec",
    name: "Reynolds Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Saanich",
    region: "Capital",
    district: "Greater Victoria School District",
    address: "3963 Borden Street",
    lat: 48.4577,
    lng: -123.3667,
    grades: "9-12",
  },
  {
    id: "vic-spectrum-sec",
    name: "Spectrum Community School",
    type: "secondary",
    category: "public_k12",
    municipality: "Victoria",
    region: "Capital",
    district: "Greater Victoria School District",
    address: "957 Burnside Road West",
    lat: 48.4611,
    lng: -123.3967,
    grades: "9-12",
  },

  // Kelowna
  {
    id: "kel-rutland-sec",
    name: "Rutland Senior Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Kelowna",
    region: "Central Okanagan",
    district: "Central Okanagan School District",
    address: "705 Rutland Road North",
    lat: 49.8986,
    lng: -119.3931,
    grades: "10-12",
  },
  {
    id: "kel-klo-sec",
    name: "KLO Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Kelowna",
    region: "Central Okanagan",
    district: "Central Okanagan School District",
    address: "3130 Gordon Drive",
    lat: 49.8569,
    lng: -119.4868,
    grades: "8-12",
  },
  {
    id: "kel-okanagan-mission-sec",
    name: "Okanagan Mission Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Kelowna",
    region: "Central Okanagan",
    district: "Central Okanagan School District",
    address: "3670 Lakeshore Road",
    lat: 49.8350,
    lng: -119.4786,
    grades: "8-12",
  },
  {
    id: "kel-mount-boucherie-sec",
    name: "Mount Boucherie Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "West Kelowna",
    region: "Central Okanagan",
    district: "Central Okanagan School District",
    address: "2751 Cameron Road",
    lat: 49.8618,
    lng: -119.5847,
    grades: "8-12",
  },

  // Kamloops
  {
    id: "kam-westsyde-sec",
    name: "Westsyde Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Kamloops",
    region: "Thompson-Nicola",
    district: "Kamloops-Thompson School District",
    address: "731 Westsyde Road",
    lat: 50.7128,
    lng: -120.3629,
    grades: "8-12",
  },
  {
    id: "kam-norkam-sec",
    name: "NorKam Senior Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Kamloops",
    region: "Thompson-Nicola",
    district: "Kamloops-Thompson School District",
    address: "730 12th Street",
    lat: 50.6783,
    lng: -120.3392,
    grades: "10-12",
  },
  {
    id: "kam-south-kam-sec",
    name: "South Kamloops Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Kamloops",
    region: "Thompson-Nicola",
    district: "Kamloops-Thompson School District",
    address: "821 Munro Street",
    lat: 50.6620,
    lng: -120.3356,
    grades: "8-12",
  },
  {
    id: "kam-sa-hali-sec",
    name: "Sa-Hali Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Kamloops",
    region: "Thompson-Nicola",
    district: "Kamloops-Thompson School District",
    address: "2100 Tranquille Road",
    lat: 50.6892,
    lng: -120.3580,
    grades: "8-12",
  },

  // Prince George
  {
    id: "pg-duchess-park-sec",
    name: "Duchess Park Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Prince George",
    region: "Fraser-Fort George",
    district: "Prince George School District",
    address: "5750 Domano Boulevard",
    lat: 53.8768,
    lng: -122.8190,
    grades: "8-12",
  },
  {
    id: "pg-prince-george-sec",
    name: "Prince George Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Prince George",
    region: "Fraser-Fort George",
    district: "Prince George School District",
    address: "2901 Griffith Way",
    lat: 53.8941,
    lng: -122.7965,
    grades: "8-12",
  },
  {
    id: "pg-college-heights-sec",
    name: "College Heights Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Prince George",
    region: "Fraser-Fort George",
    district: "Prince George School District",
    address: "5870 Domano Boulevard",
    lat: 53.8768,
    lng: -122.8232,
    grades: "8-12",
  },
  {
    id: "pg-d-p-todd-sec",
    name: "D.P. Todd Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Prince George",
    region: "Fraser-Fort George",
    district: "Prince George School District",
    address: "1551 15th Avenue",
    lat: 53.9070,
    lng: -122.7620,
    grades: "8-12",
  },

  // Fraser Valley
  {
    id: "abb-w-j-mouat-sec",
    name: "W.J. Mouat Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Abbotsford",
    region: "Fraser Valley",
    district: "Abbotsford School District",
    address: "32355 Mouat Drive",
    lat: 49.0524,
    lng: -122.3098,
    grades: "8-12",
  },
  {
    id: "abb-abbotsford-sec",
    name: "Abbotsford Senior Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Abbotsford",
    region: "Fraser Valley",
    district: "Abbotsford School District",
    address: "2329 Crescent Way",
    lat: 49.0484,
    lng: -122.3280,
    grades: "10-12",
  },
  {
    id: "chwk-sardis-sec",
    name: "Sardis Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Chilliwack",
    region: "Fraser Valley",
    district: "Chilliwack School District",
    address: "5780 Vedder Road",
    lat: 49.0955,
    lng: -121.9763,
    grades: "9-12",
  },
  {
    id: "chwk-chilliwack-sec",
    name: "Chilliwack Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Chilliwack",
    region: "Fraser Valley",
    district: "Chilliwack School District",
    address: "46363 Yale Road",
    lat: 49.1591,
    lng: -121.9486,
    grades: "9-12",
  },

  // Nanaimo
  {
    id: "nan-nanaimo-district-sec",
    name: "Nanaimo District Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Nanaimo",
    region: "Nanaimo",
    district: "Nanaimo-Ladysmith School District",
    address: "355 Wakesiah Avenue",
    lat: 49.1684,
    lng: -123.9451,
    grades: "9-12",
  },
  {
    id: "nan-john-barsby-sec",
    name: "John Barsby Community School",
    type: "secondary",
    category: "public_k12",
    municipality: "Nanaimo",
    region: "Nanaimo",
    district: "Nanaimo-Ladysmith School District",
    address: "550 7th Street",
    lat: 49.1781,
    lng: -123.9401,
    grades: "8-12",
  },
  {
    id: "nan-wellington-sec",
    name: "Wellington Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Nanaimo",
    region: "Nanaimo",
    district: "Nanaimo-Ladysmith School District",
    address: "5700 Hammond Bay Road",
    lat: 49.2089,
    lng: -123.9813,
    grades: "8-12",
  },
  {
    id: "nan-dover-bay-sec",
    name: "Dover Bay Secondary",
    type: "secondary",
    category: "public_k12",
    municipality: "Nanaimo",
    region: "Nanaimo",
    district: "Nanaimo-Ladysmith School District",
    address: "6135 McGirr Road",
    lat: 49.2011,
    lng: -123.9728,
    grades: "8-12",
  },

  // ============================================
  // INDEPENDENT/PRIVATE SCHOOLS (SELECT)
  // ============================================
  {
    id: "priv-st-georges",
    name: "St. George's School",
    type: "private_k_12",
    category: "private_k12",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    address: "4175 West 29th Avenue",
    lat: 49.2432,
    lng: -123.1848,
    grades: "1-12",
    website: "https://www.stgeorges.bc.ca",
  },
  {
    id: "priv-crofton-house",
    name: "Crofton House School",
    type: "private_k_12",
    category: "private_k12",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    address: "3200 West 41st Avenue",
    lat: 49.2353,
    lng: -123.1647,
    grades: "JK-12",
    website: "https://www.croftonhouse.ca",
  },
  {
    id: "priv-york-house",
    name: "York House School",
    type: "private_k_12",
    category: "private_k12",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    address: "4176 Alexandra Street",
    lat: 49.2443,
    lng: -123.1855,
    grades: "JK-12",
    website: "https://www.yorkhouse.ca",
  },
  {
    id: "priv-little-flower",
    name: "Little Flower Academy",
    type: "private_k_12",
    category: "private_k12",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    address: "4195 Alexandra Street",
    lat: 49.2440,
    lng: -123.1857,
    grades: "8-12",
    website: "https://www.lfabc.org",
  },
  {
    id: "priv-west-point-grey",
    name: "West Point Grey Academy",
    type: "private_k_12",
    category: "private_k12",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    address: "4125 West 8th Avenue",
    lat: 49.2678,
    lng: -123.1901,
    grades: "JK-12",
    website: "https://www.wpga.ca",
  },
  {
    id: "priv-collingwood",
    name: "Collingwood School",
    type: "private_k_12",
    category: "private_k12",
    municipality: "West Vancouver",
    region: "Metro Vancouver",
    address: "70 Morven Drive",
    lat: 49.3678,
    lng: -123.2454,
    grades: "K-12",
    website: "https://www.collingwood.org",
  },
  {
    id: "priv-mulgrave",
    name: "Mulgrave School",
    type: "private_k_12",
    category: "private_k12",
    municipality: "West Vancouver",
    region: "Metro Vancouver",
    address: "2330 Cypress Bowl Lane",
    lat: 49.3588,
    lng: -123.1963,
    grades: "PK-12",
    website: "https://www.mulgrave.com",
  },
  {
    id: "priv-st-michaels",
    name: "St. Michaels University School",
    type: "private_k_12",
    category: "private_k12",
    municipality: "Victoria",
    region: "Capital",
    address: "3400 Richmond Road",
    lat: 48.4556,
    lng: -123.3196,
    grades: "K-12",
    website: "https://www.smus.ca",
  },
  {
    id: "priv-glenlyon-norfolk",
    name: "Glenlyon Norfolk School",
    type: "private_k_12",
    category: "private_k12",
    municipality: "Victoria",
    region: "Capital",
    address: "801 Bank Street",
    lat: 48.4517,
    lng: -123.3262,
    grades: "JK-12",
    website: "https://www.mygns.ca",
  },
  {
    id: "priv-brentwood",
    name: "Brentwood College School",
    type: "private_k_12",
    category: "private_k12",
    municipality: "Mill Bay",
    region: "Cowichan Valley",
    address: "2735 Mount Baker Road",
    lat: 48.6460,
    lng: -123.5560,
    grades: "9-12",
    website: "https://www.brentwood.bc.ca",
  },
  {
    id: "priv-shawnigan-lake",
    name: "Shawnigan Lake School",
    type: "private_k_12",
    category: "private_k12",
    municipality: "Shawnigan Lake",
    region: "Cowichan Valley",
    address: "1975 Renfrew Road",
    lat: 48.6254,
    lng: -123.6367,
    grades: "8-12",
    website: "https://www.shawnigan.ca",
  },
  {
    id: "priv-meadowridge",
    name: "Meadowridge School",
    type: "private_k_12",
    category: "private_k12",
    municipality: "Maple Ridge",
    region: "Metro Vancouver",
    address: "12224 240th Street",
    lat: 49.1839,
    lng: -122.5020,
    grades: "JK-12",
    website: "https://www.meadowridge.bc.ca",
  },
  {
    id: "priv-southridge",
    name: "Southridge School",
    type: "private_k_12",
    category: "private_k12",
    municipality: "Surrey",
    region: "Metro Vancouver",
    address: "2656 160th Street",
    lat: 49.0430,
    lng: -122.7655,
    grades: "JK-12",
    website: "https://www.southridge.bc.ca",
  },
  {
    id: "priv-pacific-academy",
    name: "Pacific Academy",
    type: "private_k_12",
    category: "private_k12",
    municipality: "Surrey",
    region: "Metro Vancouver",
    address: "10238 168th Street",
    lat: 49.1850,
    lng: -122.7531,
    grades: "PK-12",
    website: "https://www.pacificacademy.net",
  },
  {
    id: "priv-fraser-academy",
    name: "Fraser Academy",
    type: "private_k_12",
    category: "private_k12",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    address: "2294 West 10th Avenue",
    lat: 49.2631,
    lng: -123.1586,
    grades: "1-12",
    website: "https://www.fraseracademy.ca",
    notes: "Specialized school for students with dyslexia",
  },
  {
    id: "priv-vancouver-christian",
    name: "Vancouver Christian School",
    type: "private_k_12",
    category: "private_k12",
    municipality: "Vancouver",
    region: "Metro Vancouver",
    address: "3496 Mons Drive",
    lat: 49.2579,
    lng: -123.0329,
    grades: "K-12",
    website: "https://www.vancouverchristian.org",
  },
  {
    id: "priv-okanagan-mission-sec",
    name: "Aberdeen Hall Preparatory School",
    type: "private_k_12",
    category: "private_k12",
    municipality: "Kelowna",
    region: "Central Okanagan",
    address: "1998 Aberdeen Road",
    lat: 49.8398,
    lng: -119.4637,
    grades: "K-12",
    website: "https://www.aberdeenhall.com",
  },

  // ============================================
  // FIRST NATIONS SCHOOLS (SELECT)
  // ============================================
  {
    id: "fn-seabird-island",
    name: "Seabird Island Community School",
    type: "first_nations",
    category: "public_k12",
    municipality: "Agassiz",
    region: "Fraser Valley",
    address: "2895 Chowat Road",
    lat: 49.2529,
    lng: -121.7696,
    grades: "K-12",
  },
  {
    id: "fn-xetolacw",
    name: "Xet'olacw Community School",
    type: "first_nations",
    category: "public_k12",
    municipality: "Lillooet",
    region: "Squamish-Lillooet",
    address: "1 Band Office Road",
    lat: 50.6876,
    lng: -121.9374,
    grades: "K-12",
  },
  {
    id: "fn-stz-uminus",
    name: "Stz'uminus Community School",
    type: "first_nations",
    category: "public_k12",
    municipality: "Ladysmith",
    region: "Cowichan Valley",
    address: "12611A Trans-Canada Highway",
    lat: 48.9857,
    lng: -123.8167,
    grades: "K-7",
  },
  {
    id: "fn-stein-valley",
    name: "Stein Valley Nlakapamux School",
    type: "first_nations",
    category: "public_k12",
    municipality: "Lytton",
    region: "Thompson-Nicola",
    address: "Box 130",
    lat: 50.2317,
    lng: -121.5706,
    grades: "K-12",
  },
  {
    id: "fn-sk-elep",
    name: "Sk'elep School of Excellence",
    type: "first_nations",
    category: "public_k12",
    municipality: "Kamloops",
    region: "Thompson-Nicola",
    address: "200 Chief Alex Thomas Way",
    lat: 50.7105,
    lng: -120.3893,
    grades: "K-7",
  },
  {
    id: "fn-shuswap-band",
    name: "Shuswap Band Education Centre",
    type: "first_nations",
    category: "public_k12",
    municipality: "Invermere",
    region: "East Kootenay",
    address: "4556 Kinbasket Lake Road",
    lat: 50.5037,
    lng: -116.0298,
    grades: "K-12",
  },
  {
    id: "fn-gitanyow-school",
    name: "Gitanyow Independent School Society",
    type: "first_nations",
    category: "public_k12",
    municipality: "Kitwanga",
    region: "Kitimat-Stikine",
    lat: 55.1088,
    lng: -128.0290,
    grades: "K-7",
  },
  {
    id: "fn-witset-school",
    name: "Witset First Nation School",
    type: "first_nations",
    category: "public_k12",
    municipality: "Witset",
    region: "Bulkley-Nechako",
    lat: 54.4233,
    lng: -127.1543,
    grades: "K-9",
  },

  // ============================================
  // ONLINE/DISTANCE LEARNING
  // ============================================
  {
    id: "online-ssdl",
    name: "South Island Distance Education School",
    type: "online",
    category: "public_k12",
    municipality: "Victoria",
    region: "Capital",
    address: "3107 Tillicum Road",
    lat: 48.4599,
    lng: -123.3910,
    grades: "K-12",
    website: "https://www.sides.ca",
  },
  {
    id: "online-ebus",
    name: "eBus Academy",
    type: "online",
    category: "public_k12",
    municipality: "Kamloops",
    region: "Thompson-Nicola",
    lat: 50.6745,
    lng: -120.3273,
    grades: "K-12",
    website: "https://www.ebus.ca",
    notes: "Online/distance learning",
  },
  {
    id: "online-self-design",
    name: "SelfDesign Learning Community",
    type: "online",
    category: "private_k12",
    municipality: "Nelson",
    region: "Central Kootenay",
    lat: 49.4928,
    lng: -117.2948,
    grades: "K-12",
    website: "https://www.selfdesign.org",
    notes: "Online/distance learning",
  },
  {
    id: "online-connect-charter",
    name: "CONNECT Charter School",
    type: "online",
    category: "public_k12",
    municipality: "Coquitlam",
    region: "Metro Vancouver",
    lat: 49.2838,
    lng: -122.7932,
    grades: "K-12",
    website: "https://www.connectcharter.ca",
    notes: "Online/distance learning",
  },
];
