export type WeatherStationType = 
  | 'metar'        // Airport METAR/AWOS
  | 'synop'        // Surface synoptic station
  | 'marine_buoy'  // Offshore weather buoy
  | 'lightstation' // Coastal light station with weather
  | 'climate'      // Climate reference station
  | 'ship';        // Automated ship station

export interface WeatherStation {
  id: string;
  name: string;
  type: WeatherStationType;
  station_id: string;
  icao?: string;
  wmo_id?: string;
  latitude: number;
  longitude: number;
  elevation_m?: number;
  municipality?: string;
  region_id?: string;
  reports: string[];
  url?: string;
  notes?: string;
}

export const BC_WEATHER_STATIONS: WeatherStation[] = [
  // Major Airport METAR Stations
  {
    id: "metar-cyvr",
    name: "Vancouver International Airport",
    type: "metar",
    station_id: "CYVR",
    icao: "CYVR",
    wmo_id: "71892",
    latitude: 49.1939,
    longitude: -123.1844,
    elevation_m: 4,
    municipality: "Richmond",
    region_id: "metro-vancouver",
    reports: ["METAR", "TAF", "SPECI"],
    url: "https://weather.gc.ca/city/pages/bc-74_metric_e.html",
  },
  {
    id: "metar-cyyj",
    name: "Victoria International Airport",
    type: "metar",
    station_id: "CYYJ",
    icao: "CYYJ",
    wmo_id: "71799",
    latitude: 48.6469,
    longitude: -123.4258,
    elevation_m: 19,
    municipality: "North Saanich",
    region_id: "capital",
    reports: ["METAR", "TAF", "SPECI"],
    url: "https://weather.gc.ca/city/pages/bc-85_metric_e.html",
  },
  {
    id: "metar-cylw",
    name: "Kelowna Airport",
    type: "metar",
    station_id: "CYLW",
    icao: "CYLW",
    wmo_id: "71203",
    latitude: 49.9561,
    longitude: -119.3778,
    elevation_m: 433,
    municipality: "Kelowna",
    region_id: "central-okanagan",
    reports: ["METAR", "TAF", "SPECI"],
  },
  {
    id: "metar-cyxx",
    name: "Abbotsford Airport",
    type: "metar",
    station_id: "CYXX",
    icao: "CYXX",
    wmo_id: "71108",
    latitude: 49.0253,
    longitude: -122.3608,
    elevation_m: 59,
    municipality: "Abbotsford",
    region_id: "fraser-valley",
    reports: ["METAR", "TAF", "SPECI"],
  },
  {
    id: "metar-cyxs",
    name: "Prince George Airport",
    type: "metar",
    station_id: "CYXS",
    icao: "CYXS",
    wmo_id: "71896",
    latitude: 53.8894,
    longitude: -122.6789,
    elevation_m: 691,
    municipality: "Prince George",
    region_id: "fraser-fort-george",
    reports: ["METAR", "TAF", "SPECI"],
  },
  {
    id: "metar-cyka",
    name: "Kamloops Airport",
    type: "metar",
    station_id: "CYKA",
    icao: "CYKA",
    wmo_id: "71887",
    latitude: 50.7022,
    longitude: -120.4444,
    elevation_m: 345,
    municipality: "Kamloops",
    region_id: "thompson-nicola",
    reports: ["METAR", "TAF", "SPECI"],
  },
  {
    id: "metar-cyqq",
    name: "Comox Airport",
    type: "metar",
    station_id: "CYQQ",
    icao: "CYQQ",
    wmo_id: "71893",
    latitude: 49.7108,
    longitude: -124.8867,
    elevation_m: 26,
    municipality: "Comox",
    region_id: "comox-valley",
    reports: ["METAR", "TAF", "SPECI"],
  },
  {
    id: "metar-cycd",
    name: "Nanaimo Airport",
    type: "metar",
    station_id: "CYCD",
    icao: "CYCD",
    wmo_id: "71890",
    latitude: 49.0542,
    longitude: -123.8700,
    elevation_m: 28,
    municipality: "Nanaimo",
    region_id: "nanaimo",
    reports: ["METAR", "TAF", "SPECI"],
  },
  {
    id: "metar-cyaz",
    name: "Tofino Airport",
    type: "metar",
    station_id: "CYAZ",
    icao: "CYAZ",
    wmo_id: "71106",
    latitude: 49.0800,
    longitude: -125.7756,
    elevation_m: 24,
    municipality: "Tofino",
    region_id: "alberni-clayoquot",
    reports: ["METAR", "TAF"],
  },
  {
    id: "metar-cyxc",
    name: "Cranbrook Airport",
    type: "metar",
    station_id: "CYXC",
    icao: "CYXC",
    wmo_id: "71880",
    latitude: 49.6108,
    longitude: -115.7819,
    elevation_m: 940,
    municipality: "Cranbrook",
    region_id: "east-kootenay",
    reports: ["METAR", "TAF", "SPECI"],
  },
  {
    id: "metar-cyxj",
    name: "Fort St. John Airport",
    type: "metar",
    station_id: "CYXJ",
    icao: "CYXJ",
    wmo_id: "71943",
    latitude: 56.2381,
    longitude: -120.7403,
    elevation_m: 695,
    municipality: "Fort St. John",
    region_id: "peace-river",
    reports: ["METAR", "TAF", "SPECI"],
  },
  {
    id: "metar-cyyf",
    name: "Penticton Airport",
    type: "metar",
    station_id: "CYYF",
    icao: "CYYF",
    wmo_id: "71889",
    latitude: 49.4631,
    longitude: -119.6019,
    elevation_m: 344,
    municipality: "Penticton",
    region_id: "okanagan-similkameen",
    reports: ["METAR", "TAF", "SPECI"],
  },
  {
    id: "metar-cypr",
    name: "Prince Rupert Airport",
    type: "metar",
    station_id: "CYPR",
    icao: "CYPR",
    wmo_id: "71022",
    latitude: 54.2861,
    longitude: -130.4450,
    elevation_m: 35,
    municipality: "Prince Rupert",
    region_id: "north-coast",
    reports: ["METAR", "TAF", "SPECI"],
  },
  {
    id: "metar-cyxt",
    name: "Terrace Airport",
    type: "metar",
    station_id: "CYXT",
    icao: "CYXT",
    wmo_id: "71951",
    latitude: 54.4686,
    longitude: -128.5783,
    elevation_m: 217,
    municipality: "Terrace",
    region_id: "kitimat-stikine",
    reports: ["METAR", "TAF", "SPECI"],
  },
  {
    id: "metar-cyyd",
    name: "Smithers Airport",
    type: "metar",
    station_id: "CYYD",
    icao: "CYYD",
    wmo_id: "71950",
    latitude: 54.8247,
    longitude: -127.1828,
    elevation_m: 522,
    municipality: "Smithers",
    region_id: "bulkley-nechako",
    reports: ["METAR", "TAF"],
  },
  {
    id: "metar-cywl",
    name: "Williams Lake Airport",
    type: "metar",
    station_id: "CYWL",
    icao: "CYWL",
    wmo_id: "71104",
    latitude: 52.1831,
    longitude: -122.0539,
    elevation_m: 940,
    municipality: "Williams Lake",
    region_id: "cariboo",
    reports: ["METAR", "TAF"],
  },
  {
    id: "metar-cyqz",
    name: "Quesnel Airport",
    type: "metar",
    station_id: "CYQZ",
    icao: "CYQZ",
    wmo_id: "71028",
    latitude: 53.0261,
    longitude: -122.5100,
    elevation_m: 545,
    municipality: "Quesnel",
    region_id: "cariboo",
    reports: ["METAR", "TAF"],
  },
  {
    id: "metar-cycg",
    name: "Castlegar Airport",
    type: "metar",
    station_id: "CYCG",
    icao: "CYCG",
    wmo_id: "71884",
    latitude: 49.2964,
    longitude: -117.6325,
    elevation_m: 495,
    municipality: "Castlegar",
    region_id: "central-kootenay",
    reports: ["METAR", "TAF", "SPECI"],
  },
  {
    id: "metar-cybd",
    name: "Bella Coola Airport",
    type: "metar",
    station_id: "CYBD",
    icao: "CYBD",
    latitude: 52.3875,
    longitude: -126.5958,
    elevation_m: 36,
    municipality: "Bella Coola",
    region_id: "central-coast",
    reports: ["METAR"],
  },
  {
    id: "metar-cyzt",
    name: "Port Hardy Airport",
    type: "metar",
    station_id: "CYZT",
    icao: "CYZT",
    wmo_id: "71109",
    latitude: 50.6806,
    longitude: -127.3667,
    elevation_m: 22,
    municipality: "Port Hardy",
    region_id: "mount-waddington",
    reports: ["METAR", "TAF"],
  },
  {
    id: "metar-cypw",
    name: "Powell River Airport",
    type: "metar",
    station_id: "CYPW",
    icao: "CYPW",
    latitude: 49.8342,
    longitude: -124.5000,
    elevation_m: 130,
    municipality: "Powell River",
    region_id: "powell-river",
    reports: ["METAR"],
  },
  {
    id: "metar-cyzp",
    name: "Sandspit Airport",
    type: "metar",
    station_id: "CYZP",
    icao: "CYZP",
    wmo_id: "71047",
    latitude: 53.2542,
    longitude: -131.8139,
    elevation_m: 6,
    municipality: "Sandspit",
    region_id: "north-coast",
    reports: ["METAR", "TAF"],
    notes: "Haida Gwaii",
  },
  {
    id: "metar-cybl",
    name: "Campbell River Airport",
    type: "metar",
    station_id: "CYBL",
    icao: "CYBL",
    latitude: 49.9508,
    longitude: -125.2711,
    elevation_m: 105,
    municipality: "Campbell River",
    region_id: "strathcona",
    reports: ["METAR"],
  },
  {
    id: "metar-cybw",
    name: "Boundary Bay Airport",
    type: "metar",
    station_id: "CYBW",
    icao: "CYBW",
    latitude: 49.0742,
    longitude: -123.0117,
    elevation_m: 2,
    municipality: "Delta",
    region_id: "metro-vancouver",
    reports: ["METAR"],
  },
  {
    id: "metar-czbb",
    name: "Langley Airport",
    type: "metar",
    station_id: "CZBB",
    icao: "CZBB",
    latitude: 49.1008,
    longitude: -122.6306,
    elevation_m: 10,
    municipality: "Langley",
    region_id: "metro-vancouver",
    reports: ["METAR"],
  },
  {
    id: "metar-cypk",
    name: "Pitt Meadows Airport",
    type: "metar",
    station_id: "CYPK",
    icao: "CYPK",
    latitude: 49.2161,
    longitude: -122.7108,
    elevation_m: 3,
    municipality: "Pitt Meadows",
    region_id: "metro-vancouver",
    reports: ["METAR"],
  },
  {
    id: "metar-cyge",
    name: "Golden Airport",
    type: "metar",
    station_id: "CYGE",
    icao: "CYGE",
    latitude: 51.2992,
    longitude: -116.9814,
    elevation_m: 785,
    municipality: "Golden",
    region_id: "columbia-shuswap",
    reports: ["METAR"],
  },
  {
    id: "metar-cyye",
    name: "Fort Nelson Airport",
    type: "metar",
    station_id: "CYYE",
    icao: "CYYE",
    wmo_id: "71945",
    latitude: 58.8364,
    longitude: -122.5969,
    elevation_m: 382,
    municipality: "Fort Nelson",
    region_id: "northern-rockies",
    reports: ["METAR", "TAF", "SPECI"],
  },
  {
    id: "metar-cydq",
    name: "Dawson Creek Airport",
    type: "metar",
    station_id: "CYDQ",
    icao: "CYDQ",
    wmo_id: "71946",
    latitude: 55.7422,
    longitude: -120.1831,
    elevation_m: 655,
    municipality: "Dawson Creek",
    region_id: "peace-river",
    reports: ["METAR", "TAF"],
  },
  {
    id: "metar-cyvk",
    name: "Vernon Airport",
    type: "metar",
    station_id: "CYVK",
    icao: "CYVK",
    latitude: 50.2478,
    longitude: -119.3306,
    elevation_m: 347,
    municipality: "Vernon",
    region_id: "north-okanagan",
    reports: ["METAR"],
  },
  {
    id: "metar-cyzz",
    name: "Trail Airport",
    type: "metar",
    station_id: "CYZZ",
    icao: "CYZZ",
    latitude: 49.0556,
    longitude: -117.6092,
    elevation_m: 435,
    municipality: "Trail",
    region_id: "kootenay-boundary",
    reports: ["METAR"],
  },
  
  // Marine Weather Buoys
  {
    id: "buoy-46146",
    name: "Halibut Bank",
    type: "marine_buoy",
    station_id: "46146",
    wmo_id: "46146",
    latitude: 49.340,
    longitude: -123.730,
    region_id: "metro-vancouver",
    reports: ["hourly", "wave", "sst"],
    url: "https://www.ndbc.noaa.gov/station_page.php?station=46146",
    notes: "Strait of Georgia - south of Nanaimo",
  },
  {
    id: "buoy-46131",
    name: "Sentry Shoal",
    type: "marine_buoy",
    station_id: "46131",
    wmo_id: "46131",
    latitude: 49.917,
    longitude: -125.000,
    region_id: "strathcona",
    reports: ["hourly", "wave", "sst"],
    url: "https://www.ndbc.noaa.gov/station_page.php?station=46131",
    notes: "Strait of Georgia - north of Nanaimo",
  },
  {
    id: "buoy-46134",
    name: "South Hecate Strait",
    type: "marine_buoy",
    station_id: "46134",
    wmo_id: "46134",
    latitude: 52.500,
    longitude: -129.800,
    region_id: "north-coast",
    reports: ["hourly", "wave", "sst"],
    notes: "Hecate Strait",
  },
  {
    id: "buoy-46132",
    name: "South Brooks",
    type: "marine_buoy",
    station_id: "46132",
    wmo_id: "46132",
    latitude: 49.740,
    longitude: -127.927,
    region_id: "alberni-clayoquot",
    reports: ["hourly", "wave", "sst"],
    notes: "West Coast Vancouver Island",
  },
  {
    id: "buoy-46147",
    name: "English Bay",
    type: "marine_buoy",
    station_id: "46147",
    latitude: 49.283,
    longitude: -123.450,
    municipality: "Vancouver",
    region_id: "metro-vancouver",
    reports: ["hourly"],
    notes: "Vancouver harbour approach",
  },
  {
    id: "buoy-46206",
    name: "La Perouse Bank",
    type: "marine_buoy",
    station_id: "46206",
    wmo_id: "46206",
    latitude: 48.833,
    longitude: -126.000,
    region_id: "alberni-clayoquot",
    reports: ["hourly", "wave", "sst"],
    notes: "Offshore Tofino/Ucluelet",
  },
  {
    id: "buoy-46207",
    name: "East Dellwood",
    type: "marine_buoy",
    station_id: "46207",
    wmo_id: "46207",
    latitude: 50.867,
    longitude: -129.917,
    region_id: "mount-waddington",
    reports: ["hourly", "wave", "sst"],
    notes: "Offshore North Vancouver Island",
  },
  {
    id: "buoy-46208",
    name: "West Sea Otter",
    type: "marine_buoy",
    station_id: "46208",
    wmo_id: "46208",
    latitude: 51.367,
    longitude: -128.767,
    region_id: "central-coast",
    reports: ["hourly", "wave", "sst"],
    notes: "Queen Charlotte Sound",
  },
  {
    id: "buoy-46185",
    name: "Discovery Island",
    type: "marine_buoy",
    station_id: "46185",
    latitude: 48.417,
    longitude: -123.233,
    region_id: "capital",
    reports: ["hourly"],
    notes: "Juan de Fuca Strait east",
  },
  
  // Light Stations with Weather
  {
    id: "light-cape-scott",
    name: "Cape Scott Lightstation",
    type: "lightstation",
    station_id: "WKM",
    latitude: 50.783,
    longitude: -128.433,
    region_id: "mount-waddington",
    reports: ["hourly", "visibility"],
    notes: "Northwest tip of Vancouver Island",
  },
  {
    id: "light-estevan-point",
    name: "Estevan Point Lightstation",
    type: "lightstation",
    station_id: "WNA",
    latitude: 49.383,
    longitude: -126.550,
    region_id: "alberni-clayoquot",
    reports: ["hourly", "visibility"],
    notes: "West coast Vancouver Island",
  },
  {
    id: "light-cape-beale",
    name: "Cape Beale Lightstation",
    type: "lightstation",
    station_id: "WZV",
    latitude: 48.783,
    longitude: -125.217,
    region_id: "alberni-clayoquot",
    reports: ["hourly", "visibility"],
    notes: "Entrance to Barkley Sound - nearest to Bamfield",
  },
  {
    id: "light-pachena-point",
    name: "Pachena Point Lightstation",
    type: "lightstation",
    station_id: "WAN",
    latitude: 48.717,
    longitude: -125.100,
    region_id: "alberni-clayoquot",
    reports: ["hourly", "visibility"],
    notes: "Near Bamfield - West Coast Trail",
  },
  {
    id: "light-amphitrite-point",
    name: "Amphitrite Point Lightstation",
    type: "lightstation",
    station_id: "WZB",
    latitude: 48.917,
    longitude: -125.533,
    municipality: "Ucluelet",
    region_id: "alberni-clayoquot",
    reports: ["hourly", "visibility"],
    notes: "Ucluelet harbour entrance",
  },
  {
    id: "light-lennard-island",
    name: "Lennard Island Lightstation",
    type: "lightstation",
    station_id: "WLD",
    latitude: 49.117,
    longitude: -125.933,
    municipality: "Tofino",
    region_id: "alberni-clayoquot",
    reports: ["hourly", "visibility"],
    notes: "Tofino area",
  },
  {
    id: "light-nootka",
    name: "Nootka Lightstation",
    type: "lightstation",
    station_id: "WNA",
    latitude: 49.600,
    longitude: -126.617,
    region_id: "strathcona",
    reports: ["hourly", "visibility"],
    notes: "Nootka Sound",
  },
  {
    id: "light-pine-island",
    name: "Pine Island Lightstation",
    type: "lightstation",
    station_id: "WPO",
    latitude: 50.983,
    longitude: -127.733,
    region_id: "mount-waddington",
    reports: ["hourly", "visibility"],
    notes: "Queen Charlotte Strait",
  },
  {
    id: "light-boat-bluff",
    name: "Boat Bluff Lightstation",
    type: "lightstation",
    station_id: "WBU",
    latitude: 52.650,
    longitude: -128.517,
    region_id: "central-coast",
    reports: ["hourly", "visibility"],
    notes: "Inside Passage",
  },
  {
    id: "light-entrance-island",
    name: "Entrance Island Lightstation",
    type: "lightstation",
    station_id: "WEN",
    latitude: 49.217,
    longitude: -123.817,
    municipality: "Nanaimo",
    region_id: "nanaimo",
    reports: ["hourly", "visibility"],
    notes: "Nanaimo harbour entrance",
  },
  {
    id: "light-race-rocks",
    name: "Race Rocks Lightstation",
    type: "lightstation",
    station_id: "WRR",
    latitude: 48.300,
    longitude: -123.533,
    region_id: "capital",
    reports: ["hourly", "visibility", "wave"],
    notes: "Juan de Fuca Strait - extreme tidal currents",
  },
  {
    id: "light-triple-island",
    name: "Triple Island Lightstation",
    type: "lightstation",
    station_id: "WTB",
    latitude: 54.300,
    longitude: -130.883,
    region_id: "north-coast",
    reports: ["hourly", "visibility"],
    notes: "Prince Rupert approach",
  },
  {
    id: "light-bonilla-island",
    name: "Bonilla Island Lightstation",
    type: "lightstation",
    station_id: "WBO",
    latitude: 53.500,
    longitude: -130.633,
    region_id: "north-coast",
    reports: ["hourly", "visibility"],
    notes: "Hecate Strait",
  },
  
  // Climate Stations
  {
    id: "climate-vancouver-intl",
    name: "Vancouver International Airport A",
    type: "climate",
    station_id: "1108395",
    latitude: 49.1939,
    longitude: -123.1844,
    elevation_m: 4,
    municipality: "Richmond",
    region_id: "metro-vancouver",
    reports: ["daily", "monthly", "normals"],
    notes: "Primary climate reference for Metro Vancouver",
  },
  {
    id: "climate-victoria-gonzales",
    name: "Victoria Gonzales HTS",
    type: "climate",
    station_id: "1018611",
    latitude: 48.413,
    longitude: -123.327,
    elevation_m: 61,
    municipality: "Victoria",
    region_id: "capital",
    reports: ["daily", "monthly", "normals"],
    notes: "Long-term climate records since 1898",
  },
  {
    id: "climate-bamfield",
    name: "Bamfield East",
    type: "climate",
    station_id: "1010165",
    latitude: 48.833,
    longitude: -125.133,
    municipality: "Bamfield",
    region_id: "alberni-clayoquot",
    reports: ["daily"],
    notes: "Bamfield Marine Sciences Centre",
  },
  {
    id: "climate-tofino",
    name: "Tofino A",
    type: "climate",
    station_id: "1038205",
    latitude: 49.082,
    longitude: -125.772,
    municipality: "Tofino",
    region_id: "alberni-clayoquot",
    reports: ["daily", "monthly"],
  },
  {
    id: "climate-ucluelet",
    name: "Ucluelet Kennedy Camp",
    type: "climate",
    station_id: "1038332",
    latitude: 48.933,
    longitude: -125.533,
    municipality: "Ucluelet",
    region_id: "alberni-clayoquot",
    reports: ["daily"],
  },
];

export function getWeatherStationsByMunicipality(municipality: string): WeatherStation[] {
  return BC_WEATHER_STATIONS.filter(s => s.municipality === municipality);
}

export function getWeatherStationsByRegion(regionId: string): WeatherStation[] {
  return BC_WEATHER_STATIONS.filter(s => s.region_id === regionId);
}

export function getMETARStations(): WeatherStation[] {
  return BC_WEATHER_STATIONS.filter(s => s.type === 'metar');
}

export function getMarineBuoys(): WeatherStation[] {
  return BC_WEATHER_STATIONS.filter(s => s.type === 'marine_buoy');
}

export function getLightstations(): WeatherStation[] {
  return BC_WEATHER_STATIONS.filter(s => s.type === 'lightstation');
}

export function getNearestWeatherStations(lat: number, lon: number, limit: number = 5): WeatherStation[] {
  const haversineDistance = (lat1: number, lon1: number, lat2: number, lon2: number): number => {
    const R = 6371;
    const dLat = (lat2 - lat1) * Math.PI / 180;
    const dLon = (lon2 - lon1) * Math.PI / 180;
    const a = Math.sin(dLat/2) * Math.sin(dLat/2) +
              Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) *
              Math.sin(dLon/2) * Math.sin(dLon/2);
    const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
    return R * c;
  };

  return BC_WEATHER_STATIONS
    .map(station => ({
      station,
      distance: haversineDistance(lat, lon, station.latitude, station.longitude)
    }))
    .sort((a, b) => a.distance - b.distance)
    .slice(0, limit)
    .map(item => item.station);
}

export interface NearestStationWithDistance {
  station: WeatherStation;
  distance_km: number;
}

export function getNearestWeatherStationsWithDistance(lat: number, lon: number, limit: number = 5): NearestStationWithDistance[] {
  const haversineDistance = (lat1: number, lon1: number, lat2: number, lon2: number): number => {
    const R = 6371;
    const dLat = (lat2 - lat1) * Math.PI / 180;
    const dLon = (lon2 - lon1) * Math.PI / 180;
    const a = Math.sin(dLat/2) * Math.sin(dLat/2) +
              Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) *
              Math.sin(dLon/2) * Math.sin(dLon/2);
    const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
    return R * c;
  };

  return BC_WEATHER_STATIONS
    .map(station => ({
      station,
      distance_km: Math.round(haversineDistance(lat, lon, station.latitude, station.longitude) * 10) / 10
    }))
    .sort((a, b) => a.distance_km - b.distance_km)
    .slice(0, limit);
}
