-- =====================================================
-- BC ROAD TRIPS SEED DATA
-- Migration: 002_road_trips_seed
-- =====================================================

-- Clear existing data (for re-running)
DELETE FROM trip_segments WHERE trip_id IN ('whistler-ski-day', 'tofino-storm-watching', 'okanagan-wine-trail', 'sunshine-coast-loop', 'harrison-hot-springs');
DELETE FROM road_trips WHERE id IN ('whistler-ski-day', 'tofino-storm-watching', 'okanagan-wine-trail', 'sunshine-coast-loop', 'harrison-hot-springs');

-- Insert road trips
INSERT INTO road_trips (id, slug, title, tagline, description, category, difficulty, seasons, tags, duration_min_hours, duration_max_hours, recommended_days, best_start_time, region, start_location_name, start_location_lat, start_location_lng, end_location_name, end_location_lat, end_location_lng, cost_budget, cost_moderate, cost_comfort, rating, rating_count, is_published, is_featured) VALUES
('whistler-ski-day', 'whistler-ski-day', 'Whistler Blackcomb Ski Day', 'North America''s largest ski resort, 2 hours from Vancouver', 'Experience world-class skiing at Whistler Blackcomb with over 8,000 acres of terrain. This day trip takes you along the stunning Sea to Sky Highway with incredible coastal mountain views.', 'ski-snowboard', 'moderate', ARRAY['winter'], ARRAY['skiing', 'snowboarding', 'mountains', 'scenic-drive'], 12, 14, 1, '6:00 AM', 'Sea to Sky', 'Vancouver', 49.2827, -123.1207, 'Vancouver', 49.2827, -123.1207, 185, 329, 450, 4.8, 234, true, true),
('tofino-storm-watching', 'tofino-storm-watching', 'Tofino Storm Watching', 'Wild Pacific waves and cozy beach vibes', 'Experience the raw power of Pacific storms from the comfort of Tofino. Watch massive waves crash on Cox Bay, explore rainforest trails, and warm up in natural hot springs.', 'beach-coastal', 'easy', ARRAY['fall', 'winter'], ARRAY['beach', 'storms', 'hot-springs', 'rainforest'], 48, 72, 3, NULL, 'Vancouver Island', 'Victoria', 48.4284, -123.3656, 'Victoria', 48.4284, -123.3656, 280, 450, 750, 4.9, 189, true, true),
('okanagan-wine-trail', 'okanagan-wine-trail', 'Okanagan Wine Country', 'World-class wines and stunning lake views', 'Tour the famous Okanagan wine region with stops at award-winning wineries, beautiful lake beaches, and farm-to-table dining.', 'wine-culinary', 'easy', ARRAY['spring', 'summer', 'fall'], ARRAY['wine', 'culinary', 'lakes', 'relaxation'], 8, 10, 1, '10:00 AM', 'Okanagan', 'Kelowna', 49.8880, -119.4960, 'Kelowna', 49.8880, -119.4960, 100, 180, 350, 4.7, 156, true, false),
('sunshine-coast-loop', 'sunshine-coast-loop', 'Sunshine Coast Loop', 'Two ferries, beaches, and coastal charm', 'A classic BC road trip featuring two ferry crossings, quaint coastal towns, and stunning ocean views. Perfect for a weekend getaway.', 'scenic-drives', 'easy', ARRAY['spring', 'summer', 'fall'], ARRAY['ferries', 'coastal', 'towns', 'beaches'], 24, 48, 2, NULL, 'Sunshine Coast', 'Vancouver', 49.2827, -123.1207, 'Vancouver', 49.2827, -123.1207, 180, 320, 550, 4.6, 142, true, false),
('harrison-hot-springs', 'harrison-hot-springs', 'Harrison Hot Springs Getaway', 'Natural hot springs and mountain lake views', 'A quick escape from Vancouver to the healing hot springs of Harrison Lake. Perfect for a relaxing day trip or overnight stay.', 'hot-springs', 'easy', ARRAY['spring', 'summer', 'fall', 'winter'], ARRAY['hot-springs', 'relaxation', 'lakes', 'mountains'], 6, 24, 1, NULL, 'Fraser Valley', 'Vancouver', 49.2827, -123.1207, 'Vancouver', 49.2827, -123.1207, 80, 150, 300, 4.5, 198, true, false);

-- Whistler Ski Day segments
INSERT INTO trip_segments (id, trip_id, segment_order, segment_type, title, location_name, location_lat, location_lng, duration_minutes, cost_budget, cost_moderate, cost_comfort, details, pro_tips, webcam_ids) VALUES
('whistler-1', 'whistler-ski-day', 1, 'departure', 'Start from Vancouver', 'HI Vancouver Central', 49.2827, -123.1207, 0, 0, 0, 0, '{"type": "accommodation", "accommodation_type": "hostel", "provider_name": "HI Vancouver Central"}', ARRAY['Pack breakfast from hostel', 'Leave by 6 AM for first chair'], ARRAY[]::INTEGER[]),
('whistler-2', 'whistler-ski-day', 2, 'transport', 'Drive Sea to Sky Highway', 'Highway 99', 49.45, -123.23, 120, 55, 55, 55, '{"type": "transport", "mode": "drive", "route_name": "Sea to Sky Highway (Hwy 99)", "distance_km": 125, "highway_numbers": ["99"], "fuel_estimate": 35, "parking_cost": 20}', ARRAY['Stop at Shannon Falls (5 min walk)', 'Gas up in Squamish - cheaper than Whistler'], ARRAY[1, 2, 3]),
('whistler-3', 'whistler-ski-day', 3, 'activity', 'Ski Whistler Blackcomb', 'Whistler Blackcomb', 50.1163, -122.9574, 480, 89, 189, 289, '{"type": "activity", "activity_type": "skiing", "provider_name": "Whistler Blackcomb", "provider_url": "https://www.whistlerblackcomb.com", "pricing": {"free": false, "adult_price": 189, "rental": 65}, "requirements": ["Ski/snowboard ability", "Warm clothing"]}', ARRAY['Download trail map before going up', 'Roundhouse has best views for lunch'], ARRAY[4, 5]),
('whistler-4', 'whistler-ski-day', 4, 'meal', 'Apres Ski in Village', 'Whistler Village', 50.1150, -122.9540, 90, 25, 50, 100, '{"type": "meal", "meal_type": "drinks", "recommendations": {"budget": "Splitz Grill - great burgers ($15-20)", "moderate": "Longhorn Saloon - classic apres ($25-40)", "comfort": "Bearfoot Bistro - upscale ($60-100)"}}', ARRAY['Happy hour 3-5pm at most spots', 'Longhorn gets packed - arrive early'], ARRAY[]::INTEGER[]),
('whistler-5', 'whistler-ski-day', 5, 'transport', 'Return to Vancouver', 'Highway 99 South', 49.45, -123.23, 120, 35, 35, 35, '{"type": "transport", "mode": "drive", "route_name": "Sea to Sky Highway (Hwy 99)", "distance_km": 125, "fuel_estimate": 35}', ARRAY['Leave by 5:30 PM to avoid traffic', 'Check road conditions before leaving'], ARRAY[1, 2, 3]);

-- Tofino Storm Watching segments
INSERT INTO trip_segments (id, trip_id, segment_order, segment_type, title, location_name, location_lat, location_lng, duration_minutes, cost_budget, cost_moderate, cost_comfort, details, pro_tips, webcam_ids) VALUES
('tofino-1', 'tofino-storm-watching', 1, 'departure', 'Start from Victoria', 'HI Victoria', 48.4284, -123.3656, 0, 0, 0, 0, '{"type": "accommodation", "accommodation_type": "hostel", "provider_name": "HI Victoria"}', ARRAY['Stock up on snacks for the drive'], ARRAY[]::INTEGER[]),
('tofino-2', 'tofino-storm-watching', 2, 'transport', 'Drive to Tofino', 'Pacific Rim Highway', 49.15, -125.90, 270, 60, 60, 60, '{"type": "transport", "mode": "drive", "route_name": "Pacific Rim Highway (Hwy 4)", "distance_km": 316, "highway_numbers": ["1", "4"], "fuel_estimate": 60}', ARRAY['Stop at Cathedral Grove for old-growth trees', 'Windy road after Port Alberni - take your time'], ARRAY[10, 11]),
('tofino-3', 'tofino-storm-watching', 3, 'activity', 'Cox Bay Storm Watching', 'Cox Bay', 49.1033, -125.8769, 180, 0, 0, 0, '{"type": "activity", "activity_type": "beach", "pricing": {"free": true}}', ARRAY['Best waves during incoming storms', 'Bring rain gear!'], ARRAY[12]),
('tofino-4', 'tofino-storm-watching', 4, 'accommodation', 'Stay in Tofino', 'Tofino', 49.1530, -125.9066, 720, 45, 120, 250, '{"type": "accommodation", "accommodation_type": "hostel", "provider_name": "Whalers on the Point Guesthouse", "amenities": ["Kitchen", "Ocean views", "Free parking"]}', ARRAY['Book ahead in storm season'], ARRAY[]::INTEGER[]),
('tofino-5', 'tofino-storm-watching', 5, 'activity', 'Hot Springs Cove', 'Hot Springs Cove', 49.3575, -126.2644, 360, 120, 140, 200, '{"type": "activity", "activity_type": "hot-springs", "provider_name": "Tofino Water Taxi", "provider_url": "https://tofinowatertaxi.com", "pricing": {"free": false, "adult_price": 120}, "reservation_required": true}', ARRAY['Book water taxi in advance', 'Bring towel and swimsuit'], ARRAY[]::INTEGER[]);

-- Okanagan Wine Trail segments
INSERT INTO trip_segments (id, trip_id, segment_order, segment_type, title, location_name, location_lat, location_lng, duration_minutes, cost_budget, cost_moderate, cost_comfort, details, pro_tips, webcam_ids) VALUES
('okanagan-1', 'okanagan-wine-trail', 1, 'departure', 'Start from Kelowna', 'SameSun Kelowna', 49.8880, -119.4960, 0, 0, 0, 0, '{"type": "accommodation", "accommodation_type": "hostel", "provider_name": "SameSun Backpackers"}', ARRAY['Designate a driver or book a wine tour'], ARRAY[]::INTEGER[]),
('okanagan-2', 'okanagan-wine-trail', 2, 'activity', 'Mission Hill Winery', 'Mission Hill', 49.8283, -119.4789, 90, 15, 35, 75, '{"type": "activity", "activity_type": "wine-tasting", "provider_name": "Mission Hill Family Estate", "provider_url": "https://www.missionhillwinery.com", "pricing": {"free": false, "adult_price": 15}, "reservation_required": true}', ARRAY['The architecture is stunning - worth the tour', 'Reserve terrace lunch in summer'], ARRAY[20]),
('okanagan-3', 'okanagan-wine-trail', 3, 'activity', 'Summerhill Pyramid Winery', 'Summerhill', 49.8547, -119.4856, 60, 10, 25, 50, '{"type": "activity", "activity_type": "wine-tasting", "provider_name": "Summerhill Pyramid Winery", "provider_url": "https://www.summerhill.bc.ca", "pricing": {"free": false, "adult_price": 10}}', ARRAY['Unique pyramid aging structure', 'Great organic wines'], ARRAY[]::INTEGER[]),
('okanagan-4', 'okanagan-wine-trail', 4, 'meal', 'Winery Lunch', 'Quails Gate', 49.8167, -119.5000, 90, 35, 60, 120, '{"type": "meal", "meal_type": "lunch", "recommendations": {"budget": "Picnic on winery grounds ($35)", "moderate": "Old Vines Restaurant ($60)", "comfort": "Full tasting menu ($120)"}}', ARRAY['Old Vines has lake views', 'Reservations essential'], ARRAY[]::INTEGER[]),
('okanagan-5', 'okanagan-wine-trail', 5, 'activity', 'Beach at Okanagan Lake', 'Gyro Beach', 49.8650, -119.4875, 120, 0, 0, 0, '{"type": "activity", "activity_type": "beach", "pricing": {"free": true}}', ARRAY['Perfect for sobering up before heading back', 'Warm lake swimming in summer'], ARRAY[21]);

-- Sunshine Coast Loop segments
INSERT INTO trip_segments (id, trip_id, segment_order, segment_type, title, location_name, location_lat, location_lng, duration_minutes, cost_budget, cost_moderate, cost_comfort, details, pro_tips, webcam_ids) VALUES
('sunshine-1', 'sunshine-coast-loop', 1, 'departure', 'Start from Vancouver', 'Vancouver', 49.2827, -123.1207, 0, 0, 0, 0, '{"type": "accommodation", "accommodation_type": "hostel"}', ARRAY[]::TEXT[], ARRAY[]::INTEGER[]),
('sunshine-2', 'sunshine-coast-loop', 2, 'transport', 'Ferry: Horseshoe Bay to Langdale', 'Horseshoe Bay', 49.3742, -123.2733, 40, 65, 65, 65, '{"type": "transport", "mode": "ferry", "operator": "BC Ferries", "fare": 65}', ARRAY['Book ahead in summer', 'Arrive 30 min early'], ARRAY[30, 31]),
('sunshine-3', 'sunshine-coast-loop', 3, 'activity', 'Explore Gibsons', 'Gibsons', 49.3948, -123.5059, 120, 20, 40, 80, '{"type": "activity", "activity_type": "sightseeing", "pricing": {"free": true}}', ARRAY['Famous from The Beachcombers TV show', 'Great fish & chips at Smittys'], ARRAY[]::INTEGER[]),
('sunshine-4', 'sunshine-coast-loop', 4, 'transport', 'Drive to Powell River', 'Highway 101', 49.7, -124.2, 150, 30, 30, 30, '{"type": "transport", "mode": "drive", "distance_km": 85, "fuel_estimate": 30}', ARRAY['Stop at Roberts Creek for coffee', 'Sechelt has great bakeries'], ARRAY[32]),
('sunshine-5', 'sunshine-coast-loop', 5, 'transport', 'Ferry: Earls Cove to Saltery Bay', 'Earls Cove', 49.7500, -124.0167, 50, 55, 55, 55, '{"type": "transport", "mode": "ferry", "operator": "BC Ferries", "fare": 55}', ARRAY['Scenic crossing through Jervis Inlet'], ARRAY[]::INTEGER[]),
('sunshine-6', 'sunshine-coast-loop', 6, 'activity', 'Explore Powell River & Lund', 'Powell River', 49.8353, -124.5247, 180, 0, 30, 60, '{"type": "activity", "activity_type": "sightseeing", "pricing": {"free": true}}', ARRAY['Lund is Mile 0 of the Sunshine Coast', 'Nancys Bakery is legendary'], ARRAY[]::INTEGER[]);

-- Harrison Hot Springs segments
INSERT INTO trip_segments (id, trip_id, segment_order, segment_type, title, location_name, location_lat, location_lng, duration_minutes, cost_budget, cost_moderate, cost_comfort, details, pro_tips, webcam_ids) VALUES
('harrison-1', 'harrison-hot-springs', 1, 'departure', 'Start from Vancouver', 'Vancouver', 49.2827, -123.1207, 0, 0, 0, 0, '{"type": "accommodation", "accommodation_type": "hostel"}', ARRAY[]::TEXT[], ARRAY[]::INTEGER[]),
('harrison-2', 'harrison-hot-springs', 2, 'transport', 'Drive to Harrison', 'Highway 7', 49.25, -121.8, 90, 25, 25, 25, '{"type": "transport", "mode": "drive", "distance_km": 128, "fuel_estimate": 25}', ARRAY['Highway 7 is more scenic than Highway 1'], ARRAY[40, 41]),
('harrison-3', 'harrison-hot-springs', 3, 'activity', 'Harrison Hot Springs Pool', 'Harrison Hot Springs', 49.2992, -121.7853, 180, 18, 18, 80, '{"type": "activity", "activity_type": "hot-springs", "provider_name": "Harrison Hot Springs Public Pool", "pricing": {"free": false, "adult_price": 18}}', ARRAY['Public pool is affordable', 'Resort spa for luxury option'], ARRAY[]::INTEGER[]),
('harrison-4', 'harrison-hot-springs', 4, 'meal', 'Lakeside Dining', 'Harrison Hot Springs', 49.2992, -121.7853, 60, 20, 45, 80, '{"type": "meal", "meal_type": "lunch", "recommendations": {"budget": "Black Forest Steakhouse patio ($20)", "moderate": "Harrison Hot Springs Resort restaurant ($45)", "comfort": "Copper Room fine dining ($80)"}}', ARRAY['Lake views are best at sunset'], ARRAY[]::INTEGER[]);
